import type { PricingPageContent } from '~/types/content'
import type { LocaleCode } from '~/utils/locale'

export const pricingPages: Record<LocaleCode, PricingPageContent> = {
  en: {
    meta: { title: 'Pricing', lead: 'Compare every Postqron plan, limit and included capability.' },
    intro: { title: 'Plans for work at every scale', lead: 'Start with Free. Paid plans are for professionals and organisations; all prices are in euros and exclude VAT.' },
    priceRowLabel: 'Price', comparisonTitle: 'Complete plan comparison', comparisonLead: 'Every difference in the published plan matrix, side by side.',
    includedLabel: 'Included', notIncludedLabel: 'Not included',
    rows: [
      { label: 'Best for', values: ['Side projects', 'Freelancers in production', 'Startups and SMEs', 'Agencies and scale-ups'] },
      { label: 'Cron jobs', values: ['20', '200', 'Unlimited (fair use: 1,000 tasks)', 'Unlimited'] },
      { label: 'Minimum resolution', values: ['1 minute', '10 seconds', '1 second', '1 second'] },
      { label: 'Log retention', values: ['3 days', '15 days', '30 days + CSV/JSON export', '90 days + export'] },
      { label: 'cron.yaml repositories', values: ['1', 'Unlimited', 'Unlimited', 'Unlimited'] },
      { label: 'Members', values: ['1', '1', '5 included', '5+'] },
      { label: 'Environments', values: ['Single', 'Staging + production', 'Staging + production', 'Staging + production'] },
      { label: 'AI debugging (BYOK)', values: ['—', '✓', '✓', '✓'] },
      { label: 'Alerts', values: ['Email', 'Email + webhook (Slack/Discord)', 'Advanced by member and environment', 'Advanced'] },
      { label: 'RBAC', values: ['—', '—', 'Admin / Developer / Viewer', '✓'] },
      { label: 'Metrics and charts', values: ['—', '—', '✓', '✓'] },
      { label: 'Multi-workspace', values: ['—', '—', '—', '✓ Up to 10 isolated, unified billing'] },
      { label: 'Dedicated static outbound IP', values: ['—', '—', '—', '✓'] },
      { label: 'Support', values: ['—', '—', '—', 'Priority'] },
    ],
    downgrade: { question: 'What happens when I downgrade?', answer: 'The criterion that selects which jobs remain active has not been decided yet. We will show the rule and the affected jobs before a downgrade can be confirmed.' },
    checkoutNote: 'Paddle checkout is not connected yet. Free opens the current sign-up path; paid-plan buttons take you to the contact page so we do not promise a purchase flow that is not available.',
  },
  it: {
    meta: { title: 'Prezzi', lead: 'Confronta ogni piano Postqron, limite e funzionalità inclusa.' },
    intro: { title: 'Piani per ogni scala di lavoro', lead: 'Parti da Free. I piani a pagamento sono per professionisti e organizzazioni; tutti i prezzi sono in euro e IVA esclusa.' },
    priceRowLabel: 'Prezzo', comparisonTitle: 'Confronto completo dei piani', comparisonLead: 'Tutte le differenze della matrice pubblicata, una accanto all’altra.',
    includedLabel: 'Incluso', notIncludedLabel: 'Non incluso',
    rows: [
      { label: 'Ideale per', values: ['Side-project', 'Freelance in produzione', 'Startup e PMI', 'Agenzie e scale-up'] },
      { label: 'Cronjob', values: ['20', '200', 'Illimitati (fair use: 1.000 task)', 'Illimitati'] },
      { label: 'Risoluzione minima', values: ['1 minuto', '10 secondi', '1 secondo', '1 secondo'] },
      { label: 'Retention log', values: ['3 giorni', '15 giorni', '30 giorni + export CSV/JSON', '90 giorni + export'] },
      { label: 'Repository cron.yaml', values: ['1', 'Illimitati', 'Illimitati', 'Illimitati'] },
      { label: 'Membri', values: ['1', '1', '5 inclusi', '5+'] },
      { label: 'Ambienti', values: ['Singolo', 'Staging + production', 'Staging + production', 'Staging + production'] },
      { label: 'Debug AI (BYOK)', values: ['—', '✓', '✓', '✓'] },
      { label: 'Alert', values: ['Email', 'Email + webhook (Slack/Discord)', 'Avanzati per membro e ambiente', 'Avanzati'] },
      { label: 'RBAC', values: ['—', '—', 'Admin / Developer / Viewer', '✓'] },
      { label: 'Metriche e grafici', values: ['—', '—', '✓', '✓'] },
      { label: 'Multi-workspace', values: ['—', '—', '—', '✓ Fino a 10 isolati, fatturazione unificata'] },
      { label: 'IP statico dedicato in uscita', values: ['—', '—', '—', '✓'] },
      { label: 'Supporto', values: ['—', '—', '—', 'Prioritario'] },
    ],
    downgrade: { question: 'Cosa succede con un downgrade?', answer: 'Il criterio che sceglie quali job restano attivi non è ancora stato deciso. Mostreremo la regola e i job coinvolti prima che il downgrade possa essere confermato.' },
    checkoutNote: 'Il checkout Paddle non è ancora collegato. Free apre il percorso di registrazione corrente; i pulsanti dei piani a pagamento portano ai contatti, senza promettere un acquisto non disponibile.',
  },
  es: {
    meta: { title: 'Precios', lead: 'Compara todos los planes, límites y funciones incluidas de Postqron.' },
    intro: { title: 'Planes para cada escala de trabajo', lead: 'Empieza con Free. Los planes de pago son para profesionales y organizaciones; todos los precios están en euros y sin IVA.' },
    priceRowLabel: 'Precio', comparisonTitle: 'Comparación completa de planes', comparisonLead: 'Todas las diferencias de la matriz publicada, una al lado de otra.',
    includedLabel: 'Incluido', notIncludedLabel: 'No incluido',
    rows: [
      { label: 'Ideal para', values: ['Proyectos personales', 'Freelance en producción', 'Startups y pymes', 'Agencias y scale-ups'] },
      { label: 'Tareas cron', values: ['20', '200', 'Ilimitadas (uso razonable: 1.000 tareas)', 'Ilimitadas'] },
      { label: 'Resolución mínima', values: ['1 minuto', '10 segundos', '1 segundo', '1 segundo'] },
      { label: 'Retención de logs', values: ['3 días', '15 días', '30 días + exportación CSV/JSON', '90 días + exportación'] },
      { label: 'Repositorios cron.yaml', values: ['1', 'Ilimitados', 'Ilimitados', 'Ilimitados'] },
      { label: 'Miembros', values: ['1', '1', '5 incluidos', '5+'] },
      { label: 'Entornos', values: ['Único', 'Staging + production', 'Staging + production', 'Staging + production'] },
      { label: 'Depuración con IA (BYOK)', values: ['—', '✓', '✓', '✓'] },
      { label: 'Alertas', values: ['Email', 'Email + webhook (Slack/Discord)', 'Avanzadas por miembro y entorno', 'Avanzadas'] },
      { label: 'RBAC', values: ['—', '—', 'Admin / Developer / Viewer', '✓'] },
      { label: 'Métricas y gráficos', values: ['—', '—', '✓', '✓'] },
      { label: 'Multi-workspace', values: ['—', '—', '—', '✓ Hasta 10 aislados, facturación unificada'] },
      { label: 'IP de salida estática dedicada', values: ['—', '—', '—', '✓'] },
      { label: 'Soporte', values: ['—', '—', '—', 'Prioritario'] },
    ],
    downgrade: { question: '¿Qué ocurre al bajar de plan?', answer: 'El criterio que decide qué trabajos siguen activos aún no se ha decidido. Mostraremos la regla y los trabajos afectados antes de confirmar el cambio.' },
    checkoutNote: 'El checkout de Paddle aún no está conectado. Free abre el registro actual; los botones de los planes de pago llevan a contacto para no prometer una compra que todavía no está disponible.',
  },
  de: {
    meta: { title: 'Preise', lead: 'Vergleiche alle Postqron-Tarife, Grenzen und enthaltenen Funktionen.' },
    intro: { title: 'Tarife für jede Arbeitsgröße', lead: 'Starte mit Free. Bezahlte Tarife richten sich an Gewerbetreibende und Organisationen; alle Preise sind in Euro und zuzüglich MwSt.' },
    priceRowLabel: 'Preis', comparisonTitle: 'Vollständiger Tarifvergleich', comparisonLead: 'Alle Unterschiede der veröffentlichten Tarifmatrix nebeneinander.',
    includedLabel: 'Enthalten', notIncludedLabel: 'Nicht enthalten',
    rows: [
      { label: 'Geeignet für', values: ['Nebenprojekte', 'Freelancer in Produktion', 'Start-ups und KMU', 'Agenturen und Scale-ups'] },
      { label: 'Cronjobs', values: ['20', '200', 'Unbegrenzt (Fair Use: 1.000 Aufgaben)', 'Unbegrenzt'] },
      { label: 'Mindestauflösung', values: ['1 Minute', '10 Sekunden', '1 Sekunde', '1 Sekunde'] },
      { label: 'Log-Aufbewahrung', values: ['3 Tage', '15 Tage', '30 Tage + CSV/JSON-Export', '90 Tage + Export'] },
      { label: 'cron.yaml-Repositories', values: ['1', 'Unbegrenzt', 'Unbegrenzt', 'Unbegrenzt'] },
      { label: 'Mitglieder', values: ['1', '1', '5 enthalten', '5+'] },
      { label: 'Umgebungen', values: ['Eine', 'Staging + Production', 'Staging + Production', 'Staging + Production'] },
      { label: 'KI-Debugging (BYOK)', values: ['—', '✓', '✓', '✓'] },
      { label: 'Benachrichtigungen', values: ['E-Mail', 'E-Mail + Webhook (Slack/Discord)', 'Erweitert nach Mitglied und Umgebung', 'Erweitert'] },
      { label: 'RBAC', values: ['—', '—', 'Admin / Developer / Viewer', '✓'] },
      { label: 'Metriken und Diagramme', values: ['—', '—', '✓', '✓'] },
      { label: 'Multi-Workspace', values: ['—', '—', '—', '✓ Bis zu 10 isolierte, einheitliche Abrechnung'] },
      { label: 'Dedizierte statische Ausgangs-IP', values: ['—', '—', '—', '✓'] },
      { label: 'Support', values: ['—', '—', '—', 'Priorität'] },
    ],
    downgrade: { question: 'Was passiert bei einem Downgrade?', answer: 'Das Kriterium dafür, welche Jobs aktiv bleiben, ist noch nicht entschieden. Regel und betroffene Jobs werden vor der Bestätigung angezeigt.' },
    checkoutNote: 'Der Paddle-Checkout ist noch nicht verbunden. Free öffnet die derzeitige Registrierung; Schaltflächen bezahlter Tarife führen zur Kontaktseite und versprechen keinen noch nicht verfügbaren Kauf.',
  },
  fr: {
    meta: { title: 'Tarifs', lead: 'Comparez toutes les offres Postqron, leurs limites et leurs fonctions incluses.' },
    intro: { title: 'Des offres pour chaque échelle', lead: 'Commencez avec Free. Les offres payantes s’adressent aux professionnels et organisations ; tous les prix sont en euros et hors TVA.' },
    priceRowLabel: 'Prix', comparisonTitle: 'Comparaison complète des offres', comparisonLead: 'Toutes les différences de la matrice publiée, côte à côte.',
    includedLabel: 'Inclus', notIncludedLabel: 'Non inclus',
    rows: [
      { label: 'Idéal pour', values: ['Projets personnels', 'Freelances en production', 'Start-up et PME', 'Agences et scale-up'] },
      { label: 'Tâches cron', values: ['20', '200', 'Illimitées (usage raisonnable : 1 000 tâches)', 'Illimitées'] },
      { label: 'Résolution minimale', values: ['1 minute', '10 secondes', '1 seconde', '1 seconde'] },
      { label: 'Rétention des logs', values: ['3 jours', '15 jours', '30 jours + export CSV/JSON', '90 jours + export'] },
      { label: 'Dépôts cron.yaml', values: ['1', 'Illimités', 'Illimités', 'Illimités'] },
      { label: 'Membres', values: ['1', '1', '5 inclus', '5+'] },
      { label: 'Environnements', values: ['Unique', 'Staging + production', 'Staging + production', 'Staging + production'] },
      { label: 'Débogage IA (BYOK)', values: ['—', '✓', '✓', '✓'] },
      { label: 'Alertes', values: ['E-mail', 'E-mail + webhook (Slack/Discord)', 'Avancées par membre et environnement', 'Avancées'] },
      { label: 'RBAC', values: ['—', '—', 'Admin / Developer / Viewer', '✓'] },
      { label: 'Métriques et graphiques', values: ['—', '—', '✓', '✓'] },
      { label: 'Multi-workspace', values: ['—', '—', '—', '✓ Jusqu’à 10 isolés, facturation unifiée'] },
      { label: 'IP sortante statique dédiée', values: ['—', '—', '—', '✓'] },
      { label: 'Support', values: ['—', '—', '—', 'Prioritaire'] },
    ],
    downgrade: { question: 'Que se passe-t-il lors d’un déclassement ?', answer: 'Le critère qui détermine les tâches restant actives n’a pas encore été décidé. La règle et les tâches concernées seront affichées avant confirmation.' },
    checkoutNote: 'Le checkout Paddle n’est pas encore connecté. Free ouvre l’inscription actuelle ; les boutons des offres payantes mènent au contact sans promettre un achat encore indisponible.',
  },
}
