// Code generated by scripts/runtime/bundle-features.sh; DO NOT EDIT.

package main

import (
	"context"

	workspaces "github.com/apdsoftware/postqron/features/f04-workspaces"
	socialconnections "github.com/apdsoftware/postqron/features/f05-social-connections"
	scheduling "github.com/apdsoftware/postqron/features/f07-scheduling"
	entitlements "github.com/apdsoftware/postqron/features/f10-entitlements"
	cookieconsent "github.com/apdsoftware/postqron/features/f26-cookie-consent-api"
	appshell "github.com/apdsoftware/postqron/features/f30-app-shell"
	adminconsole "github.com/apdsoftware/postqron/features/f31-admin-console"
	prelaunch "github.com/apdsoftware/postqron/features/f34-prelaunch/api"
	featureruntime "github.com/apdsoftware/postqron/packages/runtime"
	accountprivacyruntime "github.com/apdsoftware/postqron/services/api/internal/accountprivacyruntime"
	authruntime "github.com/apdsoftware/postqron/services/api/internal/authruntime"
	"github.com/apdsoftware/postqron/services/api/internal/featurehost"
)

func registerFeatureFactories(registry *featurehost.Registry) error {
	factories := map[string]featurehost.Factory{
		"auth": func(_ context.Context, _ featureruntime.Feature, dependencies featurehost.Dependencies) (featurehost.Module, error) {
			return authruntime.NewModule(
				dependencies.PostgreSQL,
				dependencies.Config["billing.app_domain"],
				dependencies.Clock,
			)
		},
		"workspaces": func(_ context.Context, _ featureruntime.Feature, dependencies featurehost.Dependencies) (featurehost.Module, error) {
			return workspaces.NewPostgresModule(dependencies.PostgreSQL, dependencies.Clock)
		},
		"social-connections": func(_ context.Context, _ featureruntime.Feature, dependencies featurehost.Dependencies) (featurehost.Module, error) {
			return socialconnections.NewPostgresModule(dependencies.PostgreSQL, dependencies.Clock)
		},
		"scheduling": func(_ context.Context, _ featureruntime.Feature, dependencies featurehost.Dependencies) (featurehost.Module, error) {
			return scheduling.NewPostgresModule(dependencies.PostgreSQL, dependencies.Clock)
		},
		"f10-entitlements": func(_ context.Context, _ featureruntime.Feature, dependencies featurehost.Dependencies) (featurehost.Module, error) {
			return entitlements.NewPostgresModule(dependencies.PostgreSQL, dependencies.Clock)
		},
		"account-privacy-runtime": func(_ context.Context, _ featureruntime.Feature, dependencies featurehost.Dependencies) (featurehost.Module, error) {
			return accountprivacyruntime.NewModule(dependencies.PostgreSQL, dependencies.Clock)
		},
		"app-shell": func(_ context.Context, _ featureruntime.Feature, dependencies featurehost.Dependencies) (featurehost.Module, error) {
			return appshell.NewPostgresModule(dependencies.PostgreSQL, dependencies.Clock)
		},
		"admin-console": func(_ context.Context, _ featureruntime.Feature, dependencies featurehost.Dependencies) (featurehost.Module, error) {
			return adminconsole.NewPostgresModule(dependencies.PostgreSQL, dependencies.Clock)
		},
		"cookie-consent-api": func(_ context.Context, _ featureruntime.Feature, dependencies featurehost.Dependencies) (featurehost.Module, error) {
			return cookieconsent.NewPostgresModule(dependencies.PostgreSQL, dependencies.Clock)
		},
		"prelaunch-access": func(_ context.Context, _ featureruntime.Feature, dependencies featurehost.Dependencies) (featurehost.Module, error) {
			return prelaunch.NewPostgresModule(dependencies.PostgreSQL, dependencies.Clock)
		},
	}
	for featureID, factory := range factories {
		if err := registry.Register(featureID, factory); err != nil {
			return err
		}
	}
	return nil
}
