// Code generated by scripts/runtime/bundle-features.sh; DO NOT EDIT.

package main

import "github.com/apdsoftware/postqron/services/api/internal/featurehost"

func registerFeatureFactories(*featurehost.Registry) error {
	return nil
}
