import { defineCatalogs } from '../../f36-i18n/src/catalog.ts'

const en = {
  'document.title': 'Admin console — Postqron',
  'shell.skip': 'Skip to admin content',
  'shell.navigation': 'Administration navigation',
  'shell.console': 'Admin console',
  'shell.back': 'Back to Postqron',
  'shell.profile': 'Authenticated administrator',
  'page.eyebrow': 'Protected operations',
  'page.title': 'Postqron administration',
  'page.description': 'Review service health, users, workspaces, entitlements, and immutable audit activity.',
  'login.title': 'Administrator sign-in',
  'login.description': 'Use the administrator email address and password. External providers are not required.',
  'login.email': 'Email address',
  'login.password': 'Password',
  'login.submit': 'Sign in',
  'login.signingIn': 'Signing in…',
  'status.loading': 'Loading protected administration data…',
  'status.empty': 'No matching administration data.',
  'status.forbidden': 'This account is not authorized for administration.',
  'status.unavailable': 'Administration data is temporarily unavailable.',
  'status.retry': 'Try again',
  'health.title': 'Service health',
  'health.healthy': 'Healthy',
  'health.degraded': 'Degraded',
  'search.title': 'Users and workspaces',
  'search.label': 'Search by email, user, or workspace',
  'search.placeholder': 'Enter at least two characters',
  'search.submit': 'Search',
  'search.users': 'Users',
  'search.workspaces': 'Workspaces',
  'search.verified': 'Verified email',
  'search.unverified': 'Unverified email',
  'entitlements.title': 'Plans and entitlements',
  'entitlements.internal': 'Internal plan active',
  'entitlements.public': 'Public plan',
  'entitlements.assign': 'Assign internal plan',
  'entitlements.revoke': 'Revoke internal plan',
  'audit.title': 'Recent audit activity',
  'audit.outcome': 'Outcome',
  'audit.reason': 'Reason',
  'confirm.title.assign': 'Confirm internal plan assignment',
  'confirm.title.revoke': 'Confirm internal plan revocation',
  'confirm.description': 'This sensitive operation is checked again by the server and recorded in immutable audit.',
  'confirm.reason': 'Required reason',
  'confirm.reasonPlaceholder': 'Explain the operational reason',
  'confirm.checkbox': 'I explicitly confirm this operation',
  'confirm.cancel': 'Cancel',
  'confirm.submit': 'Confirm operation',
  'confirm.saving': 'Applying secure change…',
  'confirm.success': 'The operation was accepted and audited.',
  'nav.dashboard': 'Dashboard',
  'nav.users': 'Users',
  'nav.workspaces': 'Workspaces',
  'nav.plans': 'Plans',
  'nav.audit': 'Audit',
  'nav.profile': 'Profile',
  'shell.menu': 'Open navigation menu',
  'shell.closeMenu': 'Close navigation menu',
  'shell.logout': 'Sign out',
  'shell.loggingOut': 'Signing out…',
  'logout.success': 'You signed out securely.',
  'dashboard.title': 'Operations overview',
  'dashboard.description': 'Key indicators across services, workspaces, and immutable audit activity.',
  'dashboard.kpi.services': 'Monitored services',
  'dashboard.kpi.healthy': 'Healthy services',
  'dashboard.kpi.workspaces': 'Workspaces with an entitlement',
  'dashboard.kpi.internalPlans': 'Internal plans active',
  'dashboard.kpi.auditEvents': 'Recent audit events',
  'users.title': 'Users',
  'users.description': 'Search registered users by email or display name.',
  'users.table.name': 'Name',
  'users.table.email': 'Email',
  'users.table.status': 'Email status',
  'workspaces.title': 'Workspaces',
  'workspaces.description': 'Search workspaces by name or owner email.',
  'workspaces.table.name': 'Name',
  'workspaces.table.owner': 'Owner',
  'workspaces.table.members': 'Members',
  'plans.title': 'Plans and entitlements',
  'plans.description': 'Review the entitlement of every workspace and manage the internal plan.',
  'plans.table.workspace': 'Workspace',
  'plans.table.plan': 'Plan',
  'plans.table.type': 'Type',
  'plans.table.actions': 'Actions',
  'audit.description': 'Immutable record of every sensitive administration action.',
  'audit.table.event': 'Event',
  'audit.table.occurredAt': 'Occurred at',
  'audit.table.correlation': 'Correlation',
  'profile.title': 'Administrator profile',
  'profile.description': 'Review the identity and session used for protected operations.',
  'profile.accountId': 'Account identifier',
  'profile.email': 'Email address',
  'profile.authenticatedAt': 'Authenticated since',
  'profile.logoutHint': 'Sign-out is available from this menu and from the top bar identity menu.',
  'profile.password.title': 'Change password',
  'profile.password.policy': 'Use a different password containing at least 12 characters. Changing it revokes every other session and rotates this session.',
  'profile.password.current': 'Current password',
  'profile.password.new': 'New password',
  'profile.password.confirm': 'Confirm new password',
  'profile.password.submit': 'Change password',
  'profile.password.saving': 'Changing password…',
  'profile.password.success': 'Password changed. Other sessions were revoked and this session was rotated.',
  'pagination.previous': 'Previous page',
  'pagination.next': 'Next page',
  'pagination.status': 'Page {page} of {count}',
  'error.ADMIN_UNAUTHENTICATED': 'Your session expired. Sign in again.',
  'error.ADMIN_FORBIDDEN': 'This account is not authorized for administration.',
  'error.ADMIN_CSRF_INVALID': 'The security token is invalid. Reload the page and retry.',
  'error.ADMIN_REAUTH_REQUIRED': 'Sign in again before performing this sensitive operation.',
  'error.ADMIN_IDEMPOTENCY_REQUIRED': 'The operation identifier is invalid. Retry the operation.',
  'error.ADMIN_INVALID_REQUEST': 'Complete the confirmation and provide a useful reason.',
  'error.ADMIN_INVALID_SEARCH': 'Enter between 2 and 120 characters.',
  'error.ADMIN_INVALID_CREDENTIALS': 'The email or password is invalid.',
  'error.ADMIN_CURRENT_PASSWORD_INVALID': 'The current password is invalid.',
  'error.ADMIN_PASSWORD_CONFIRMATION_MISMATCH': 'The new password and confirmation do not match.',
  'error.ADMIN_PASSWORD_WEAK': 'Use a different password containing at least 12 characters.',
  'error.ADMIN_PASSWORD_CHANGE_RATE_LIMITED': 'Too many attempts. Wait before trying again.',
  'error.ADMIN_UNAVAILABLE': 'The protected administration service is unavailable.',
} as const

export type AdminMessageKey = keyof typeof en
type AdminCatalog = Readonly<Record<AdminMessageKey, string>>

const it: AdminCatalog = {
  'document.title': 'Console di amministrazione — Postqron',
  'shell.skip': 'Vai al contenuto amministrativo',
  'shell.navigation': 'Navigazione amministrazione',
  'shell.console': 'Console admin',
  'shell.back': 'Torna a Postqron',
  'shell.profile': 'Amministratore autenticato',
  'page.eyebrow': 'Operazioni protette',
  'page.title': 'Amministrazione Postqron',
  'page.description': 'Controlla salute dei servizi, utenti, workspace, entitlement e attività audit immutabile.',
  'login.title': 'Accesso amministratore',
  'login.description': 'Usa indirizzo email e password dell’amministratore. I provider esterni non sono necessari.',
  'login.email': 'Indirizzo email',
  'login.password': 'Password',
  'login.submit': 'Accedi',
  'login.signingIn': 'Accesso in corso…',
  'status.loading': 'Caricamento dei dati amministrativi protetti…',
  'status.empty': 'Nessun dato amministrativo corrispondente.',
  'status.forbidden': 'Questo account non è autorizzato all’amministrazione.',
  'status.unavailable': 'I dati amministrativi sono temporaneamente indisponibili.',
  'status.retry': 'Riprova',
  'health.title': 'Salute dei servizi',
  'health.healthy': 'Operativo',
  'health.degraded': 'Degradato',
  'search.title': 'Utenti e workspace',
  'search.label': 'Cerca per email, utente o workspace',
  'search.placeholder': 'Inserisci almeno due caratteri',
  'search.submit': 'Cerca',
  'search.users': 'Utenti',
  'search.workspaces': 'Workspace',
  'search.verified': 'Email verificata',
  'search.unverified': 'Email non verificata',
  'entitlements.title': 'Piani ed entitlement',
  'entitlements.internal': 'Piano interno attivo',
  'entitlements.public': 'Piano pubblico',
  'entitlements.assign': 'Assegna piano interno',
  'entitlements.revoke': 'Revoca piano interno',
  'audit.title': 'Attività audit recente',
  'audit.outcome': 'Esito',
  'audit.reason': 'Motivo',
  'confirm.title.assign': 'Conferma assegnazione piano interno',
  'confirm.title.revoke': 'Conferma revoca piano interno',
  'confirm.description': 'Questa operazione sensibile viene verificata nuovamente dal server e registrata nell’audit immutabile.',
  'confirm.reason': 'Motivo obbligatorio',
  'confirm.reasonPlaceholder': 'Descrivi il motivo operativo',
  'confirm.checkbox': 'Confermo esplicitamente questa operazione',
  'confirm.cancel': 'Annulla',
  'confirm.submit': 'Conferma operazione',
  'confirm.saving': 'Applicazione della modifica sicura…',
  'confirm.success': 'L’operazione è stata accettata e auditata.',
  'nav.dashboard': 'Dashboard',
  'nav.users': 'Utenti',
  'nav.workspaces': 'Workspace',
  'nav.plans': 'Piani',
  'nav.audit': 'Audit',
  'nav.profile': 'Profilo',
  'shell.menu': 'Apri il menu di navigazione',
  'shell.closeMenu': 'Chiudi il menu di navigazione',
  'shell.logout': 'Esci',
  'shell.loggingOut': 'Uscita in corso…',
  'logout.success': 'La sessione è stata terminata in sicurezza.',
  'dashboard.title': 'Panoramica operativa',
  'dashboard.description': 'Indicatori chiave su servizi, workspace e attività audit immutabile.',
  'dashboard.kpi.services': 'Servizi monitorati',
  'dashboard.kpi.healthy': 'Servizi operativi',
  'dashboard.kpi.workspaces': 'Workspace con un entitlement',
  'dashboard.kpi.internalPlans': 'Piani interni attivi',
  'dashboard.kpi.auditEvents': 'Eventi audit recenti',
  'users.title': 'Utenti',
  'users.description': 'Cerca gli utenti registrati per email o nome visualizzato.',
  'users.table.name': 'Nome',
  'users.table.email': 'Email',
  'users.table.status': 'Stato email',
  'workspaces.title': 'Workspace',
  'workspaces.description': 'Cerca i workspace per nome o email del proprietario.',
  'workspaces.table.name': 'Nome',
  'workspaces.table.owner': 'Proprietario',
  'workspaces.table.members': 'Membri',
  'plans.title': 'Piani ed entitlement',
  'plans.description': 'Controlla l’entitlement di ogni workspace e gestisci il piano interno.',
  'plans.table.workspace': 'Workspace',
  'plans.table.plan': 'Piano',
  'plans.table.type': 'Tipo',
  'plans.table.actions': 'Azioni',
  'audit.description': 'Registro immutabile di ogni azione amministrativa sensibile.',
  'audit.table.event': 'Evento',
  'audit.table.occurredAt': 'Avvenuto il',
  'audit.table.correlation': 'Correlazione',
  'profile.title': 'Profilo amministratore',
  'profile.description': 'Controlla l’identità e la sessione usate per le operazioni protette.',
  'profile.accountId': 'Identificativo account',
  'profile.email': 'Indirizzo email',
  'profile.authenticatedAt': 'Autenticato dal',
  'profile.logoutHint': 'L’uscita è disponibile da questo menu e dal menu identità nella barra superiore.',
  'profile.password.title': 'Cambia password',
  'profile.password.policy': 'Usa una password diversa di almeno 12 caratteri. La modifica revoca tutte le altre sessioni e ruota quella corrente.',
  'profile.password.current': 'Password attuale',
  'profile.password.new': 'Nuova password',
  'profile.password.confirm': 'Conferma nuova password',
  'profile.password.submit': 'Cambia password',
  'profile.password.saving': 'Modifica password in corso…',
  'profile.password.success': 'Password modificata. Le altre sessioni sono state revocate e quella corrente è stata ruotata.',
  'pagination.previous': 'Pagina precedente',
  'pagination.next': 'Pagina successiva',
  'pagination.status': 'Pagina {page} di {count}',
  'error.ADMIN_UNAUTHENTICATED': 'La sessione è scaduta. Accedi nuovamente.',
  'error.ADMIN_FORBIDDEN': 'Questo account non è autorizzato all’amministrazione.',
  'error.ADMIN_CSRF_INVALID': 'Il token di sicurezza non è valido. Ricarica la pagina e riprova.',
  'error.ADMIN_REAUTH_REQUIRED': 'Accedi nuovamente prima di eseguire questa operazione sensibile.',
  'error.ADMIN_IDEMPOTENCY_REQUIRED': 'L’identificatore dell’operazione non è valido. Riprova.',
  'error.ADMIN_INVALID_REQUEST': 'Completa la conferma e inserisci un motivo utile.',
  'error.ADMIN_INVALID_SEARCH': 'Inserisci da 2 a 120 caratteri.',
  'error.ADMIN_INVALID_CREDENTIALS': 'L’indirizzo email o la password non sono validi.',
  'error.ADMIN_CURRENT_PASSWORD_INVALID': 'La password attuale non è valida.',
  'error.ADMIN_PASSWORD_CONFIRMATION_MISMATCH': 'La nuova password e la conferma non coincidono.',
  'error.ADMIN_PASSWORD_WEAK': 'Usa una password diversa di almeno 12 caratteri.',
  'error.ADMIN_PASSWORD_CHANGE_RATE_LIMITED': 'Troppi tentativi. Attendi prima di riprovare.',
  'error.ADMIN_UNAVAILABLE': 'Il servizio amministrativo protetto non è disponibile.',
}

const es: AdminCatalog = {
  'document.title': 'Consola de administración — Postqron',
  'shell.skip': 'Ir al contenido administrativo',
  'shell.navigation': 'Navegación de administración',
  'shell.console': 'Consola de administración',
  'shell.back': 'Volver a Postqron',
  'shell.profile': 'Administrador autenticado',
  'page.eyebrow': 'Operaciones protegidas',
  'page.title': 'Administración de Postqron',
  'page.description': 'Revisa la salud de los servicios, usuarios, espacios, permisos y la actividad de auditoría inmutable.',
  'login.title': 'Acceso de administración',
  'login.description': 'Usa el correo y la contraseña de administración. Los proveedores externos no son necesarios.',
  'login.email': 'Correo electrónico',
  'login.password': 'Contraseña',
  'login.submit': 'Iniciar sesión',
  'login.signingIn': 'Iniciando sesión…',
  'status.loading': 'Cargando datos administrativos protegidos…',
  'status.empty': 'No hay datos administrativos coincidentes.',
  'status.forbidden': 'Esta cuenta no está autorizada para administrar.',
  'status.unavailable': 'Los datos administrativos no están disponibles temporalmente.',
  'status.retry': 'Reintentar',
  'health.title': 'Salud de los servicios',
  'health.healthy': 'Correcto',
  'health.degraded': 'Degradado',
  'search.title': 'Usuarios y espacios',
  'search.label': 'Buscar por correo, usuario o espacio',
  'search.placeholder': 'Introduce al menos dos caracteres',
  'search.submit': 'Buscar',
  'search.users': 'Usuarios',
  'search.workspaces': 'Espacios',
  'search.verified': 'Correo verificado',
  'search.unverified': 'Correo no verificado',
  'entitlements.title': 'Planes y permisos',
  'entitlements.internal': 'Plan interno activo',
  'entitlements.public': 'Plan público',
  'entitlements.assign': 'Asignar plan interno',
  'entitlements.revoke': 'Revocar plan interno',
  'audit.title': 'Actividad de auditoría reciente',
  'audit.outcome': 'Resultado',
  'audit.reason': 'Motivo',
  'confirm.title.assign': 'Confirmar asignación del plan interno',
  'confirm.title.revoke': 'Confirmar revocación del plan interno',
  'confirm.description': 'El servidor vuelve a comprobar esta operación sensible y la registra en una auditoría inmutable.',
  'confirm.reason': 'Motivo obligatorio',
  'confirm.reasonPlaceholder': 'Explica el motivo operativo',
  'confirm.checkbox': 'Confirmo explícitamente esta operación',
  'confirm.cancel': 'Cancelar',
  'confirm.submit': 'Confirmar operación',
  'confirm.saving': 'Aplicando el cambio seguro…',
  'confirm.success': 'La operación fue aceptada y auditada.',
  'nav.dashboard': 'Panel',
  'nav.users': 'Usuarios',
  'nav.workspaces': 'Espacios',
  'nav.plans': 'Planes',
  'nav.audit': 'Auditoría',
  'nav.profile': 'Perfil',
  'shell.menu': 'Abrir el menú de navegación',
  'shell.closeMenu': 'Cerrar el menú de navegación',
  'shell.logout': 'Cerrar sesión',
  'shell.loggingOut': 'Cerrando sesión…',
  'logout.success': 'La sesión se cerró de forma segura.',
  'dashboard.title': 'Resumen operativo',
  'dashboard.description': 'Indicadores clave de servicios, espacios y actividad de auditoría inmutable.',
  'dashboard.kpi.services': 'Servicios supervisados',
  'dashboard.kpi.healthy': 'Servicios correctos',
  'dashboard.kpi.workspaces': 'Espacios con un permiso',
  'dashboard.kpi.internalPlans': 'Planes internos activos',
  'dashboard.kpi.auditEvents': 'Eventos de auditoría recientes',
  'users.title': 'Usuarios',
  'users.description': 'Busca usuarios registrados por correo o nombre visible.',
  'users.table.name': 'Nombre',
  'users.table.email': 'Correo electrónico',
  'users.table.status': 'Estado del correo',
  'workspaces.title': 'Espacios',
  'workspaces.description': 'Busca espacios por nombre o correo del propietario.',
  'workspaces.table.name': 'Nombre',
  'workspaces.table.owner': 'Propietario',
  'workspaces.table.members': 'Miembros',
  'plans.title': 'Planes y permisos',
  'plans.description': 'Revisa el permiso de cada espacio y gestiona el plan interno.',
  'plans.table.workspace': 'Espacio',
  'plans.table.plan': 'Plan',
  'plans.table.type': 'Tipo',
  'plans.table.actions': 'Acciones',
  'audit.description': 'Registro inmutable de cada acción administrativa sensible.',
  'audit.table.event': 'Evento',
  'audit.table.occurredAt': 'Ocurrido el',
  'audit.table.correlation': 'Correlación',
  'profile.title': 'Perfil de administración',
  'profile.description': 'Revisa la identidad y la sesión usadas para las operaciones protegidas.',
  'profile.accountId': 'Identificador de cuenta',
  'profile.email': 'Correo electrónico',
  'profile.authenticatedAt': 'Autenticado desde',
  'profile.logoutHint': 'Puedes cerrar sesión desde este menú y desde el menú de identidad de la barra superior.',
  'profile.password.title': 'Cambiar contraseña',
  'profile.password.policy': 'Usa una contraseña diferente de al menos 12 caracteres. El cambio revoca las demás sesiones y rota esta sesión.',
  'profile.password.current': 'Contraseña actual',
  'profile.password.new': 'Nueva contraseña',
  'profile.password.confirm': 'Confirmar nueva contraseña',
  'profile.password.submit': 'Cambiar contraseña',
  'profile.password.saving': 'Cambiando contraseña…',
  'profile.password.success': 'Contraseña cambiada. Las demás sesiones se revocaron y esta sesión se rotó.',
  'pagination.previous': 'Página anterior',
  'pagination.next': 'Página siguiente',
  'pagination.status': 'Página {page} de {count}',
  'error.ADMIN_UNAUTHENTICATED': 'Tu sesión caducó. Inicia sesión de nuevo.',
  'error.ADMIN_FORBIDDEN': 'Esta cuenta no está autorizada para administrar.',
  'error.ADMIN_CSRF_INVALID': 'El token de seguridad no es válido. Recarga la página e inténtalo de nuevo.',
  'error.ADMIN_REAUTH_REQUIRED': 'Inicia sesión de nuevo antes de realizar esta operación sensible.',
  'error.ADMIN_IDEMPOTENCY_REQUIRED': 'El identificador de la operación no es válido. Inténtalo de nuevo.',
  'error.ADMIN_INVALID_REQUEST': 'Completa la confirmación e indica un motivo útil.',
  'error.ADMIN_INVALID_SEARCH': 'Introduce entre 2 y 120 caracteres.',
  'error.ADMIN_INVALID_CREDENTIALS': 'El correo o la contraseña no son válidos.',
  'error.ADMIN_CURRENT_PASSWORD_INVALID': 'La contraseña actual no es válida.',
  'error.ADMIN_PASSWORD_CONFIRMATION_MISMATCH': 'La nueva contraseña y la confirmación no coinciden.',
  'error.ADMIN_PASSWORD_WEAK': 'Usa una contraseña diferente de al menos 12 caracteres.',
  'error.ADMIN_PASSWORD_CHANGE_RATE_LIMITED': 'Demasiados intentos. Espera antes de volver a intentarlo.',
  'error.ADMIN_UNAVAILABLE': 'El servicio administrativo protegido no está disponible.',
}

const fr: AdminCatalog = {
  'document.title': 'Console d’administration — Postqron',
  'shell.skip': 'Aller au contenu administratif',
  'shell.navigation': 'Navigation de l’administration',
  'shell.console': 'Console d’administration',
  'shell.back': 'Retour à Postqron',
  'shell.profile': 'Administrateur authentifié',
  'page.eyebrow': 'Opérations protégées',
  'page.title': 'Administration de Postqron',
  'page.description': 'Consultez la santé des services, les utilisateurs, espaces, droits et l’activité d’audit immuable.',
  'login.title': 'Connexion administrateur',
  'login.description': 'Utilisez l’adresse e-mail et le mot de passe administrateur. Aucun fournisseur externe n’est requis.',
  'login.email': 'Adresse e-mail',
  'login.password': 'Mot de passe',
  'login.submit': 'Se connecter',
  'login.signingIn': 'Connexion…',
  'status.loading': 'Chargement des données administratives protégées…',
  'status.empty': 'Aucune donnée administrative correspondante.',
  'status.forbidden': 'Ce compte n’est pas autorisé à administrer.',
  'status.unavailable': 'Les données administratives sont temporairement indisponibles.',
  'status.retry': 'Réessayer',
  'health.title': 'Santé des services',
  'health.healthy': 'Opérationnel',
  'health.degraded': 'Dégradé',
  'search.title': 'Utilisateurs et espaces',
  'search.label': 'Rechercher par e-mail, utilisateur ou espace',
  'search.placeholder': 'Saisissez au moins deux caractères',
  'search.submit': 'Rechercher',
  'search.users': 'Utilisateurs',
  'search.workspaces': 'Espaces',
  'search.verified': 'E-mail vérifié',
  'search.unverified': 'E-mail non vérifié',
  'entitlements.title': 'Forfaits et droits',
  'entitlements.internal': 'Forfait interne actif',
  'entitlements.public': 'Forfait public',
  'entitlements.assign': 'Attribuer le forfait interne',
  'entitlements.revoke': 'Révoquer le forfait interne',
  'audit.title': 'Activité d’audit récente',
  'audit.outcome': 'Résultat',
  'audit.reason': 'Motif',
  'confirm.title.assign': 'Confirmer l’attribution du forfait interne',
  'confirm.title.revoke': 'Confirmer la révocation du forfait interne',
  'confirm.description': 'Cette opération sensible est revérifiée par le serveur et inscrite dans l’audit immuable.',
  'confirm.reason': 'Motif obligatoire',
  'confirm.reasonPlaceholder': 'Expliquez le motif opérationnel',
  'confirm.checkbox': 'Je confirme explicitement cette opération',
  'confirm.cancel': 'Annuler',
  'confirm.submit': 'Confirmer l’opération',
  'confirm.saving': 'Application de la modification sécurisée…',
  'confirm.success': 'L’opération a été acceptée et auditée.',
  'nav.dashboard': 'Tableau de bord',
  'nav.users': 'Utilisateurs',
  'nav.workspaces': 'Espaces',
  'nav.plans': 'Forfaits',
  'nav.audit': 'Audit',
  'nav.profile': 'Profil',
  'shell.menu': 'Ouvrir le menu de navigation',
  'shell.closeMenu': 'Fermer le menu de navigation',
  'shell.logout': 'Se déconnecter',
  'shell.loggingOut': 'Déconnexion…',
  'logout.success': 'Vous vous êtes déconnecté en toute sécurité.',
  'dashboard.title': 'Vue d’ensemble opérationnelle',
  'dashboard.description': 'Indicateurs clés des services, espaces et de l’activité d’audit immuable.',
  'dashboard.kpi.services': 'Services surveillés',
  'dashboard.kpi.healthy': 'Services opérationnels',
  'dashboard.kpi.workspaces': 'Espaces avec un droit',
  'dashboard.kpi.internalPlans': 'Forfaits internes actifs',
  'dashboard.kpi.auditEvents': 'Événements d’audit récents',
  'users.title': 'Utilisateurs',
  'users.description': 'Recherchez les utilisateurs enregistrés par e-mail ou nom affiché.',
  'users.table.name': 'Nom',
  'users.table.email': 'E-mail',
  'users.table.status': 'Statut de l’e-mail',
  'workspaces.title': 'Espaces',
  'workspaces.description': 'Recherchez les espaces par nom ou e-mail du propriétaire.',
  'workspaces.table.name': 'Nom',
  'workspaces.table.owner': 'Propriétaire',
  'workspaces.table.members': 'Membres',
  'plans.title': 'Forfaits et droits',
  'plans.description': 'Consultez le droit de chaque espace et gérez le forfait interne.',
  'plans.table.workspace': 'Espace',
  'plans.table.plan': 'Forfait',
  'plans.table.type': 'Type',
  'plans.table.actions': 'Actions',
  'audit.description': 'Registre immuable de chaque action administrative sensible.',
  'audit.table.event': 'Événement',
  'audit.table.occurredAt': 'Survenu le',
  'audit.table.correlation': 'Corrélation',
  'profile.title': 'Profil administrateur',
  'profile.description': 'Consultez l’identité et la session utilisées pour les opérations protégées.',
  'profile.accountId': 'Identifiant du compte',
  'profile.email': 'Adresse e-mail',
  'profile.authenticatedAt': 'Authentifié depuis',
  'profile.logoutHint': 'La déconnexion est disponible depuis ce menu et depuis le menu d’identité de la barre supérieure.',
  'profile.password.title': 'Modifier le mot de passe',
  'profile.password.policy': 'Utilisez un mot de passe différent d’au moins 12 caractères. La modification révoque les autres sessions et renouvelle celle-ci.',
  'profile.password.current': 'Mot de passe actuel',
  'profile.password.new': 'Nouveau mot de passe',
  'profile.password.confirm': 'Confirmer le nouveau mot de passe',
  'profile.password.submit': 'Modifier le mot de passe',
  'profile.password.saving': 'Modification du mot de passe…',
  'profile.password.success': 'Mot de passe modifié. Les autres sessions ont été révoquées et celle-ci a été renouvelée.',
  'pagination.previous': 'Page précédente',
  'pagination.next': 'Page suivante',
  'pagination.status': 'Page {page} sur {count}',
  'error.ADMIN_UNAUTHENTICATED': 'Votre session a expiré. Reconnectez-vous.',
  'error.ADMIN_FORBIDDEN': 'Ce compte n’est pas autorisé à administrer.',
  'error.ADMIN_CSRF_INVALID': 'Le jeton de sécurité est invalide. Rechargez la page et réessayez.',
  'error.ADMIN_REAUTH_REQUIRED': 'Reconnectez-vous avant cette opération sensible.',
  'error.ADMIN_IDEMPOTENCY_REQUIRED': 'L’identifiant de l’opération est invalide. Réessayez.',
  'error.ADMIN_INVALID_REQUEST': 'Confirmez l’opération et indiquez un motif utile.',
  'error.ADMIN_INVALID_SEARCH': 'Saisissez entre 2 et 120 caractères.',
  'error.ADMIN_INVALID_CREDENTIALS': 'L’adresse e-mail ou le mot de passe est incorrect.',
  'error.ADMIN_CURRENT_PASSWORD_INVALID': 'Le mot de passe actuel est incorrect.',
  'error.ADMIN_PASSWORD_CONFIRMATION_MISMATCH': 'Le nouveau mot de passe et sa confirmation ne correspondent pas.',
  'error.ADMIN_PASSWORD_WEAK': 'Utilisez un mot de passe différent d’au moins 12 caractères.',
  'error.ADMIN_PASSWORD_CHANGE_RATE_LIMITED': 'Trop de tentatives. Attendez avant de réessayer.',
  'error.ADMIN_UNAVAILABLE': 'Le service d’administration protégé est indisponible.',
}

const de: AdminCatalog = {
  'document.title': 'Administrationskonsole — Postqron',
  'shell.skip': 'Zum Administrationsinhalt springen',
  'shell.navigation': 'Administrationsnavigation',
  'shell.console': 'Admin-Konsole',
  'shell.back': 'Zurück zu Postqron',
  'shell.profile': 'Authentifizierte Administration',
  'page.eyebrow': 'Geschützte Vorgänge',
  'page.title': 'Postqron-Administration',
  'page.description': 'Prüfen Sie Dienststatus, Benutzer, Arbeitsbereiche, Berechtigungen und unveränderliche Audit-Aktivitäten.',
  'login.title': 'Administrator-Anmeldung',
  'login.description': 'Verwenden Sie die Administrator-E-Mail-Adresse und das Passwort. Externe Anbieter sind nicht erforderlich.',
  'login.email': 'E-Mail-Adresse',
  'login.password': 'Passwort',
  'login.submit': 'Anmelden',
  'login.signingIn': 'Anmeldung läuft…',
  'status.loading': 'Geschützte Administrationsdaten werden geladen…',
  'status.empty': 'Keine passenden Administrationsdaten.',
  'status.forbidden': 'Dieses Konto ist nicht zur Administration berechtigt.',
  'status.unavailable': 'Administrationsdaten sind vorübergehend nicht verfügbar.',
  'status.retry': 'Erneut versuchen',
  'health.title': 'Dienststatus',
  'health.healthy': 'Betriebsbereit',
  'health.degraded': 'Beeinträchtigt',
  'search.title': 'Benutzer und Arbeitsbereiche',
  'search.label': 'Nach E-Mail, Benutzer oder Arbeitsbereich suchen',
  'search.placeholder': 'Mindestens zwei Zeichen eingeben',
  'search.submit': 'Suchen',
  'search.users': 'Benutzer',
  'search.workspaces': 'Arbeitsbereiche',
  'search.verified': 'Bestätigte E-Mail',
  'search.unverified': 'Unbestätigte E-Mail',
  'entitlements.title': 'Tarife und Berechtigungen',
  'entitlements.internal': 'Interner Tarif aktiv',
  'entitlements.public': 'Öffentlicher Tarif',
  'entitlements.assign': 'Internen Tarif zuweisen',
  'entitlements.revoke': 'Internen Tarif entziehen',
  'audit.title': 'Neueste Audit-Aktivitäten',
  'audit.outcome': 'Ergebnis',
  'audit.reason': 'Begründung',
  'confirm.title.assign': 'Zuweisung des internen Tarifs bestätigen',
  'confirm.title.revoke': 'Entzug des internen Tarifs bestätigen',
  'confirm.description': 'Dieser sensible Vorgang wird serverseitig erneut geprüft und unveränderlich auditiert.',
  'confirm.reason': 'Begründung erforderlich',
  'confirm.reasonPlaceholder': 'Betriebliche Begründung angeben',
  'confirm.checkbox': 'Ich bestätige diesen Vorgang ausdrücklich',
  'confirm.cancel': 'Abbrechen',
  'confirm.submit': 'Vorgang bestätigen',
  'confirm.saving': 'Sichere Änderung wird angewendet…',
  'confirm.success': 'Der Vorgang wurde angenommen und auditiert.',
  'nav.dashboard': 'Übersicht',
  'nav.users': 'Benutzer',
  'nav.workspaces': 'Arbeitsbereiche',
  'nav.plans': 'Tarife',
  'nav.audit': 'Audit',
  'nav.profile': 'Profil',
  'shell.menu': 'Navigationsmenü öffnen',
  'shell.closeMenu': 'Navigationsmenü schließen',
  'shell.logout': 'Abmelden',
  'shell.loggingOut': 'Abmeldung läuft…',
  'logout.success': 'Sie wurden sicher abgemeldet.',
  'dashboard.title': 'Betriebsübersicht',
  'dashboard.description': 'Wichtige Kennzahlen zu Diensten, Arbeitsbereichen und unveränderlicher Audit-Aktivität.',
  'dashboard.kpi.services': 'Überwachte Dienste',
  'dashboard.kpi.healthy': 'Betriebsbereite Dienste',
  'dashboard.kpi.workspaces': 'Arbeitsbereiche mit Berechtigung',
  'dashboard.kpi.internalPlans': 'Aktive interne Tarife',
  'dashboard.kpi.auditEvents': 'Aktuelle Audit-Ereignisse',
  'users.title': 'Benutzer',
  'users.description': 'Registrierte Benutzer nach E-Mail oder Anzeigename suchen.',
  'users.table.name': 'Name',
  'users.table.email': 'E-Mail',
  'users.table.status': 'E-Mail-Status',
  'workspaces.title': 'Arbeitsbereiche',
  'workspaces.description': 'Arbeitsbereiche nach Name oder E-Mail des Inhabers suchen.',
  'workspaces.table.name': 'Name',
  'workspaces.table.owner': 'Inhaber',
  'workspaces.table.members': 'Mitglieder',
  'plans.title': 'Tarife und Berechtigungen',
  'plans.description': 'Prüfen Sie die Berechtigung jedes Arbeitsbereichs und verwalten Sie den internen Tarif.',
  'plans.table.workspace': 'Arbeitsbereich',
  'plans.table.plan': 'Tarif',
  'plans.table.type': 'Typ',
  'plans.table.actions': 'Aktionen',
  'audit.description': 'Unveränderliches Protokoll jeder sensiblen Administrationsaktion.',
  'audit.table.event': 'Ereignis',
  'audit.table.occurredAt': 'Eingetreten am',
  'audit.table.correlation': 'Korrelation',
  'profile.title': 'Administratorprofil',
  'profile.description': 'Prüfen Sie Identität und Sitzung, die für geschützte Vorgänge verwendet werden.',
  'profile.accountId': 'Kontokennung',
  'profile.email': 'E-Mail-Adresse',
  'profile.authenticatedAt': 'Authentifiziert seit',
  'profile.logoutHint': 'Die Abmeldung ist über dieses Menü und über das Identitätsmenü in der oberen Leiste verfügbar.',
  'profile.password.title': 'Passwort ändern',
  'profile.password.policy': 'Verwenden Sie ein anderes Passwort mit mindestens 12 Zeichen. Die Änderung widerruft alle anderen Sitzungen und erneuert diese Sitzung.',
  'profile.password.current': 'Aktuelles Passwort',
  'profile.password.new': 'Neues Passwort',
  'profile.password.confirm': 'Neues Passwort bestätigen',
  'profile.password.submit': 'Passwort ändern',
  'profile.password.saving': 'Passwort wird geändert…',
  'profile.password.success': 'Passwort geändert. Andere Sitzungen wurden widerrufen und diese Sitzung wurde erneuert.',
  'pagination.previous': 'Vorherige Seite',
  'pagination.next': 'Nächste Seite',
  'pagination.status': 'Seite {page} von {count}',
  'error.ADMIN_UNAUTHENTICATED': 'Ihre Sitzung ist abgelaufen. Melden Sie sich erneut an.',
  'error.ADMIN_FORBIDDEN': 'Dieses Konto ist nicht zur Administration berechtigt.',
  'error.ADMIN_CSRF_INVALID': 'Das Sicherheitstoken ist ungültig. Laden Sie die Seite neu.',
  'error.ADMIN_REAUTH_REQUIRED': 'Melden Sie sich vor diesem sensiblen Vorgang erneut an.',
  'error.ADMIN_IDEMPOTENCY_REQUIRED': 'Die Vorgangskennung ist ungültig. Versuchen Sie es erneut.',
  'error.ADMIN_INVALID_REQUEST': 'Bestätigen Sie den Vorgang und geben Sie eine sinnvolle Begründung an.',
  'error.ADMIN_INVALID_SEARCH': 'Geben Sie zwischen 2 und 120 Zeichen ein.',
  'error.ADMIN_INVALID_CREDENTIALS': 'E-Mail-Adresse oder Passwort ist ungültig.',
  'error.ADMIN_CURRENT_PASSWORD_INVALID': 'Das aktuelle Passwort ist ungültig.',
  'error.ADMIN_PASSWORD_CONFIRMATION_MISMATCH': 'Neues Passwort und Bestätigung stimmen nicht überein.',
  'error.ADMIN_PASSWORD_WEAK': 'Verwenden Sie ein anderes Passwort mit mindestens 12 Zeichen.',
  'error.ADMIN_PASSWORD_CHANGE_RATE_LIMITED': 'Zu viele Versuche. Warten Sie vor dem nächsten Versuch.',
  'error.ADMIN_UNAVAILABLE': 'Der geschützte Administrationsdienst ist nicht verfügbar.',
}

export const ADMIN_CATALOGS = defineCatalogs({ en, it, es, fr, de })
