import { defineCatalogs } from '../../f36-i18n/src/catalog.ts'

const en = {
  'document.title': 'Admin console — Postqron',
  'shell.skip': 'Skip to admin content',
  'shell.navigation': 'Administration navigation',
  'shell.console': 'Admin console',
  'shell.back': 'Back to Postqron',
  'shell.profile': 'Authenticated administrator',
  'page.eyebrow': 'Protected operations',
  'page.title': 'Postqron administration',
  'page.description': 'Review service health, users, workspaces, entitlements, and immutable audit activity.',
  'login.title': 'Administrator sign-in',
  'login.description': 'Use the administrator email address and password. External providers are not required.',
  'login.email': 'Email address',
  'login.password': 'Password',
  'login.submit': 'Sign in',
  'login.signingIn': 'Signing in…',
  'status.loading': 'Loading protected administration data…',
  'status.empty': 'No matching administration data.',
  'status.forbidden': 'This account is not authorized for administration.',
  'status.unavailable': 'Administration data is temporarily unavailable.',
  'status.retry': 'Try again',
  'health.title': 'Service health',
  'health.healthy': 'Healthy',
  'health.degraded': 'Degraded',
  'search.title': 'Users and workspaces',
  'search.label': 'Search by email, user, or workspace',
  'search.placeholder': 'Enter at least two characters',
  'search.submit': 'Search',
  'search.users': 'Users',
  'search.workspaces': 'Workspaces',
  'search.verified': 'Verified email',
  'search.unverified': 'Unverified email',
  'entitlements.title': 'Plans and entitlements',
  'entitlements.internal': 'Internal plan active',
  'entitlements.public': 'Public plan',
  'entitlements.assign': 'Assign internal plan',
  'entitlements.revoke': 'Revoke internal plan',
  'audit.title': 'Recent audit activity',
  'audit.outcome': 'Outcome',
  'audit.reason': 'Reason',
  'confirm.title.assign': 'Confirm internal plan assignment',
  'confirm.title.revoke': 'Confirm internal plan revocation',
  'confirm.description': 'This sensitive operation is checked again by the server and recorded in immutable audit.',
  'confirm.reason': 'Required reason',
  'confirm.reasonPlaceholder': 'Explain the operational reason',
  'confirm.checkbox': 'I explicitly confirm this operation',
  'confirm.cancel': 'Cancel',
  'confirm.submit': 'Confirm operation',
  'confirm.saving': 'Applying secure change…',
  'confirm.success': 'The operation was accepted and audited.',
  'error.ADMIN_UNAUTHENTICATED': 'Your session expired. Sign in again.',
  'error.ADMIN_FORBIDDEN': 'This account is not authorized for administration.',
  'error.ADMIN_CSRF_INVALID': 'The security token is invalid. Reload the page and retry.',
  'error.ADMIN_REAUTH_REQUIRED': 'Sign in again before performing this sensitive operation.',
  'error.ADMIN_IDEMPOTENCY_REQUIRED': 'The operation identifier is invalid. Retry the operation.',
  'error.ADMIN_INVALID_REQUEST': 'Complete the confirmation and provide a useful reason.',
  'error.ADMIN_INVALID_SEARCH': 'Enter between 2 and 120 characters.',
  'error.ADMIN_INVALID_CREDENTIALS': 'The email or password is invalid.',
  'error.ADMIN_UNAVAILABLE': 'The protected administration service is unavailable.',
  'nav.dashboard': 'Dashboard',
  'nav.users': 'Users',
  'nav.workspaces': 'Workspaces',
  'nav.plans': 'Plans',
  'nav.audit': 'Audit',
  'nav.profile': 'Profile',
  'shell.menu': 'Open navigation menu',
  'shell.closeMenu': 'Close navigation menu',
  'shell.language': 'Language',
  'shell.logoutPlaceholder': 'Sign-out control',
  'dashboard.kpi.services': 'Service health',
  'dashboard.kpi.servicesHint': 'Healthy checks out of monitored services',
  'dashboard.kpi.entitlements': 'Internal plans active',
  'dashboard.kpi.entitlementsHint': 'Workspaces currently on the internal plan',
  'dashboard.kpi.audit': 'Recent audit events',
  'dashboard.kpi.auditHint': 'Immutable events recorded for this account',
  'dashboard.links.title': 'Jump to a section',
  'users.page.eyebrow': 'Directory',
  'users.page.title': 'Users',
  'users.page.description': 'Search the user directory by name or email address.',
  'users.prompt': 'Search to see matching users.',
  'users.table.name': 'Name',
  'users.table.email': 'Email',
  'users.table.status': 'Email status',
  'workspaces.page.eyebrow': 'Directory',
  'workspaces.page.title': 'Workspaces',
  'workspaces.page.description': 'Search workspaces by name, owner, or identifier.',
  'workspaces.prompt': 'Search to see matching workspaces.',
  'workspaces.table.name': 'Workspace',
  'workspaces.table.owner': 'Owner',
  'workspaces.table.members': 'Members',
  'plans.page.eyebrow': 'Entitlements',
  'plans.page.title': 'Plans',
  'plans.page.description': 'Review workspace entitlements and manage the internal plan.',
  'plans.table.workspace': 'Workspace',
  'plans.table.plan': 'Plan',
  'plans.table.status': 'Status',
  'plans.table.actions': 'Actions',
  'audit.page.eyebrow': 'Compliance',
  'audit.page.title': 'Audit',
  'audit.page.description': 'Review the immutable log of sensitive administration actions.',
  'audit.table.event': 'Event',
  'audit.table.outcome': 'Outcome',
  'audit.table.reason': 'Reason',
  'audit.table.when': 'When',
  'profile.page.eyebrow': 'Account',
  'profile.page.title': 'Profile',
  'profile.page.description': 'Review the identity used for this administration session.',
  'profile.account.id': 'Account identifier',
  'profile.account.email': 'Email address',
  'profile.account.authenticatedAt': 'Signed in since',
  'profile.logout.title': 'Sign out',
  'profile.logout.description': 'A dedicated sign-out control ships in a later release.',
  'pagination.previous': 'Previous page',
  'pagination.next': 'Next page',
  'pagination.status': 'Page {page} of {count}',
} as const

export type AdminMessageKey = keyof typeof en
type AdminCatalog = Readonly<Record<AdminMessageKey, string>>

const it: AdminCatalog = {
  'document.title': 'Console di amministrazione — Postqron',
  'shell.skip': 'Vai al contenuto amministrativo',
  'shell.navigation': 'Navigazione amministrazione',
  'shell.console': 'Console admin',
  'shell.back': 'Torna a Postqron',
  'shell.profile': 'Amministratore autenticato',
  'page.eyebrow': 'Operazioni protette',
  'page.title': 'Amministrazione Postqron',
  'page.description': 'Controlla salute dei servizi, utenti, workspace, entitlement e attività audit immutabile.',
  'login.title': 'Accesso amministratore',
  'login.description': 'Usa indirizzo email e password dell’amministratore. I provider esterni non sono necessari.',
  'login.email': 'Indirizzo email',
  'login.password': 'Password',
  'login.submit': 'Accedi',
  'login.signingIn': 'Accesso in corso…',
  'status.loading': 'Caricamento dei dati amministrativi protetti…',
  'status.empty': 'Nessun dato amministrativo corrispondente.',
  'status.forbidden': 'Questo account non è autorizzato all’amministrazione.',
  'status.unavailable': 'I dati amministrativi sono temporaneamente indisponibili.',
  'status.retry': 'Riprova',
  'health.title': 'Salute dei servizi',
  'health.healthy': 'Operativo',
  'health.degraded': 'Degradato',
  'search.title': 'Utenti e workspace',
  'search.label': 'Cerca per email, utente o workspace',
  'search.placeholder': 'Inserisci almeno due caratteri',
  'search.submit': 'Cerca',
  'search.users': 'Utenti',
  'search.workspaces': 'Workspace',
  'search.verified': 'Email verificata',
  'search.unverified': 'Email non verificata',
  'entitlements.title': 'Piani ed entitlement',
  'entitlements.internal': 'Piano interno attivo',
  'entitlements.public': 'Piano pubblico',
  'entitlements.assign': 'Assegna piano interno',
  'entitlements.revoke': 'Revoca piano interno',
  'audit.title': 'Attività audit recente',
  'audit.outcome': 'Esito',
  'audit.reason': 'Motivo',
  'confirm.title.assign': 'Conferma assegnazione piano interno',
  'confirm.title.revoke': 'Conferma revoca piano interno',
  'confirm.description': 'Questa operazione sensibile viene verificata nuovamente dal server e registrata nell’audit immutabile.',
  'confirm.reason': 'Motivo obbligatorio',
  'confirm.reasonPlaceholder': 'Descrivi il motivo operativo',
  'confirm.checkbox': 'Confermo esplicitamente questa operazione',
  'confirm.cancel': 'Annulla',
  'confirm.submit': 'Conferma operazione',
  'confirm.saving': 'Applicazione della modifica sicura…',
  'confirm.success': 'L’operazione è stata accettata e auditata.',
  'error.ADMIN_UNAUTHENTICATED': 'La sessione è scaduta. Accedi nuovamente.',
  'error.ADMIN_FORBIDDEN': 'Questo account non è autorizzato all’amministrazione.',
  'error.ADMIN_CSRF_INVALID': 'Il token di sicurezza non è valido. Ricarica la pagina e riprova.',
  'error.ADMIN_REAUTH_REQUIRED': 'Accedi nuovamente prima di eseguire questa operazione sensibile.',
  'error.ADMIN_IDEMPOTENCY_REQUIRED': 'L’identificatore dell’operazione non è valido. Riprova.',
  'error.ADMIN_INVALID_REQUEST': 'Completa la conferma e inserisci un motivo utile.',
  'error.ADMIN_INVALID_SEARCH': 'Inserisci da 2 a 120 caratteri.',
  'error.ADMIN_INVALID_CREDENTIALS': 'L’indirizzo email o la password non sono validi.',
  'error.ADMIN_UNAVAILABLE': 'Il servizio amministrativo protetto non è disponibile.',
  'nav.dashboard': 'Dashboard',
  'nav.users': 'Utenti',
  'nav.workspaces': 'Workspace',
  'nav.plans': 'Piani',
  'nav.audit': 'Audit',
  'nav.profile': 'Profilo',
  'shell.menu': 'Apri il menu di navigazione',
  'shell.closeMenu': 'Chiudi il menu di navigazione',
  'shell.language': 'Lingua',
  'shell.logoutPlaceholder': 'Controllo di disconnessione',
  'dashboard.kpi.services': 'Salute dei servizi',
  'dashboard.kpi.servicesHint': 'Controlli operativi sui servizi monitorati',
  'dashboard.kpi.entitlements': 'Piani interni attivi',
  'dashboard.kpi.entitlementsHint': 'Workspace attualmente sul piano interno',
  'dashboard.kpi.audit': 'Eventi audit recenti',
  'dashboard.kpi.auditHint': 'Eventi immutabili registrati per questo account',
  'dashboard.links.title': 'Vai a una sezione',
  'users.page.eyebrow': 'Elenco',
  'users.page.title': 'Utenti',
  'users.page.description': 'Cerca nell’elenco utenti per nome o indirizzo email.',
  'users.prompt': 'Cerca per vedere gli utenti corrispondenti.',
  'users.table.name': 'Nome',
  'users.table.email': 'Email',
  'users.table.status': 'Stato email',
  'workspaces.page.eyebrow': 'Elenco',
  'workspaces.page.title': 'Workspace',
  'workspaces.page.description': 'Cerca i workspace per nome, proprietario o identificativo.',
  'workspaces.prompt': 'Cerca per vedere i workspace corrispondenti.',
  'workspaces.table.name': 'Workspace',
  'workspaces.table.owner': 'Proprietario',
  'workspaces.table.members': 'Membri',
  'plans.page.eyebrow': 'Entitlement',
  'plans.page.title': 'Piani',
  'plans.page.description': 'Controlla gli entitlement dei workspace e gestisci il piano interno.',
  'plans.table.workspace': 'Workspace',
  'plans.table.plan': 'Piano',
  'plans.table.status': 'Stato',
  'plans.table.actions': 'Azioni',
  'audit.page.eyebrow': 'Conformità',
  'audit.page.title': 'Audit',
  'audit.page.description': 'Controlla il registro immutabile delle azioni amministrative sensibili.',
  'audit.table.event': 'Evento',
  'audit.table.outcome': 'Esito',
  'audit.table.reason': 'Motivo',
  'audit.table.when': 'Quando',
  'profile.page.eyebrow': 'Account',
  'profile.page.title': 'Profilo',
  'profile.page.description': 'Controlla l’identità usata per questa sessione amministrativa.',
  'profile.account.id': 'Identificativo account',
  'profile.account.email': 'Indirizzo email',
  'profile.account.authenticatedAt': 'Accesso effettuato dal',
  'profile.logout.title': 'Disconnetti',
  'profile.logout.description': 'Un controllo di disconnessione dedicato arriverà in una release successiva.',
  'pagination.previous': 'Pagina precedente',
  'pagination.next': 'Pagina successiva',
  'pagination.status': 'Pagina {page} di {count}',
}

const es: AdminCatalog = {
  'document.title': 'Consola de administración — Postqron',
  'shell.skip': 'Ir al contenido administrativo',
  'shell.navigation': 'Navegación de administración',
  'shell.console': 'Consola de administración',
  'shell.back': 'Volver a Postqron',
  'shell.profile': 'Administrador autenticado',
  'page.eyebrow': 'Operaciones protegidas',
  'page.title': 'Administración de Postqron',
  'page.description': 'Revisa la salud de los servicios, usuarios, espacios, permisos y la actividad de auditoría inmutable.',
  'login.title': 'Acceso de administración',
  'login.description': 'Usa el correo y la contraseña de administración. Los proveedores externos no son necesarios.',
  'login.email': 'Correo electrónico',
  'login.password': 'Contraseña',
  'login.submit': 'Iniciar sesión',
  'login.signingIn': 'Iniciando sesión…',
  'status.loading': 'Cargando datos administrativos protegidos…',
  'status.empty': 'No hay datos administrativos coincidentes.',
  'status.forbidden': 'Esta cuenta no está autorizada para administrar.',
  'status.unavailable': 'Los datos administrativos no están disponibles temporalmente.',
  'status.retry': 'Reintentar',
  'health.title': 'Salud de los servicios',
  'health.healthy': 'Correcto',
  'health.degraded': 'Degradado',
  'search.title': 'Usuarios y espacios',
  'search.label': 'Buscar por correo, usuario o espacio',
  'search.placeholder': 'Introduce al menos dos caracteres',
  'search.submit': 'Buscar',
  'search.users': 'Usuarios',
  'search.workspaces': 'Espacios',
  'search.verified': 'Correo verificado',
  'search.unverified': 'Correo no verificado',
  'entitlements.title': 'Planes y permisos',
  'entitlements.internal': 'Plan interno activo',
  'entitlements.public': 'Plan público',
  'entitlements.assign': 'Asignar plan interno',
  'entitlements.revoke': 'Revocar plan interno',
  'audit.title': 'Actividad de auditoría reciente',
  'audit.outcome': 'Resultado',
  'audit.reason': 'Motivo',
  'confirm.title.assign': 'Confirmar asignación del plan interno',
  'confirm.title.revoke': 'Confirmar revocación del plan interno',
  'confirm.description': 'El servidor vuelve a comprobar esta operación sensible y la registra en una auditoría inmutable.',
  'confirm.reason': 'Motivo obligatorio',
  'confirm.reasonPlaceholder': 'Explica el motivo operativo',
  'confirm.checkbox': 'Confirmo explícitamente esta operación',
  'confirm.cancel': 'Cancelar',
  'confirm.submit': 'Confirmar operación',
  'confirm.saving': 'Aplicando el cambio seguro…',
  'confirm.success': 'La operación fue aceptada y auditada.',
  'error.ADMIN_UNAUTHENTICATED': 'Tu sesión caducó. Inicia sesión de nuevo.',
  'error.ADMIN_FORBIDDEN': 'Esta cuenta no está autorizada para administrar.',
  'error.ADMIN_CSRF_INVALID': 'El token de seguridad no es válido. Recarga la página e inténtalo de nuevo.',
  'error.ADMIN_REAUTH_REQUIRED': 'Inicia sesión de nuevo antes de realizar esta operación sensible.',
  'error.ADMIN_IDEMPOTENCY_REQUIRED': 'El identificador de la operación no es válido. Inténtalo de nuevo.',
  'error.ADMIN_INVALID_REQUEST': 'Completa la confirmación e indica un motivo útil.',
  'error.ADMIN_INVALID_SEARCH': 'Introduce entre 2 y 120 caracteres.',
  'error.ADMIN_INVALID_CREDENTIALS': 'El correo o la contraseña no son válidos.',
  'error.ADMIN_UNAVAILABLE': 'El servicio administrativo protegido no está disponible.',
  'nav.dashboard': 'Panel',
  'nav.users': 'Usuarios',
  'nav.workspaces': 'Espacios',
  'nav.plans': 'Planes',
  'nav.audit': 'Auditoría',
  'nav.profile': 'Perfil',
  'shell.menu': 'Abrir el menú de navegación',
  'shell.closeMenu': 'Cerrar el menú de navegación',
  'shell.language': 'Idioma',
  'shell.logoutPlaceholder': 'Control de cierre de sesión',
  'dashboard.kpi.services': 'Salud de los servicios',
  'dashboard.kpi.servicesHint': 'Comprobaciones correctas sobre los servicios supervisados',
  'dashboard.kpi.entitlements': 'Planes internos activos',
  'dashboard.kpi.entitlementsHint': 'Espacios actualmente en el plan interno',
  'dashboard.kpi.audit': 'Eventos de auditoría recientes',
  'dashboard.kpi.auditHint': 'Eventos inmutables registrados para esta cuenta',
  'dashboard.links.title': 'Ir a una sección',
  'users.page.eyebrow': 'Directorio',
  'users.page.title': 'Usuarios',
  'users.page.description': 'Busca en el directorio de usuarios por nombre o correo electrónico.',
  'users.prompt': 'Busca para ver usuarios coincidentes.',
  'users.table.name': 'Nombre',
  'users.table.email': 'Correo electrónico',
  'users.table.status': 'Estado del correo',
  'workspaces.page.eyebrow': 'Directorio',
  'workspaces.page.title': 'Espacios',
  'workspaces.page.description': 'Busca espacios por nombre, propietario o identificador.',
  'workspaces.prompt': 'Busca para ver espacios coincidentes.',
  'workspaces.table.name': 'Espacio',
  'workspaces.table.owner': 'Propietario',
  'workspaces.table.members': 'Miembros',
  'plans.page.eyebrow': 'Permisos',
  'plans.page.title': 'Planes',
  'plans.page.description': 'Revisa los permisos de los espacios y gestiona el plan interno.',
  'plans.table.workspace': 'Espacio',
  'plans.table.plan': 'Plan',
  'plans.table.status': 'Estado',
  'plans.table.actions': 'Acciones',
  'audit.page.eyebrow': 'Cumplimiento',
  'audit.page.title': 'Auditoría',
  'audit.page.description': 'Revisa el registro inmutable de acciones administrativas sensibles.',
  'audit.table.event': 'Evento',
  'audit.table.outcome': 'Resultado',
  'audit.table.reason': 'Motivo',
  'audit.table.when': 'Cuándo',
  'profile.page.eyebrow': 'Cuenta',
  'profile.page.title': 'Perfil',
  'profile.page.description': 'Revisa la identidad utilizada para esta sesión administrativa.',
  'profile.account.id': 'Identificador de cuenta',
  'profile.account.email': 'Correo electrónico',
  'profile.account.authenticatedAt': 'Sesión iniciada desde',
  'profile.logout.title': 'Cerrar sesión',
  'profile.logout.description': 'Un control de cierre de sesión dedicado llegará en una versión posterior.',
  'pagination.previous': 'Página anterior',
  'pagination.next': 'Página siguiente',
  'pagination.status': 'Página {page} de {count}',
}

const fr: AdminCatalog = {
  'document.title': 'Console d’administration — Postqron',
  'shell.skip': 'Aller au contenu administratif',
  'shell.navigation': 'Navigation de l’administration',
  'shell.console': 'Console d’administration',
  'shell.back': 'Retour à Postqron',
  'shell.profile': 'Administrateur authentifié',
  'page.eyebrow': 'Opérations protégées',
  'page.title': 'Administration de Postqron',
  'page.description': 'Consultez la santé des services, les utilisateurs, espaces, droits et l’activité d’audit immuable.',
  'login.title': 'Connexion administrateur',
  'login.description': 'Utilisez l’adresse e-mail et le mot de passe administrateur. Aucun fournisseur externe n’est requis.',
  'login.email': 'Adresse e-mail',
  'login.password': 'Mot de passe',
  'login.submit': 'Se connecter',
  'login.signingIn': 'Connexion…',
  'status.loading': 'Chargement des données administratives protégées…',
  'status.empty': 'Aucune donnée administrative correspondante.',
  'status.forbidden': 'Ce compte n’est pas autorisé à administrer.',
  'status.unavailable': 'Les données administratives sont temporairement indisponibles.',
  'status.retry': 'Réessayer',
  'health.title': 'Santé des services',
  'health.healthy': 'Opérationnel',
  'health.degraded': 'Dégradé',
  'search.title': 'Utilisateurs et espaces',
  'search.label': 'Rechercher par e-mail, utilisateur ou espace',
  'search.placeholder': 'Saisissez au moins deux caractères',
  'search.submit': 'Rechercher',
  'search.users': 'Utilisateurs',
  'search.workspaces': 'Espaces',
  'search.verified': 'E-mail vérifié',
  'search.unverified': 'E-mail non vérifié',
  'entitlements.title': 'Forfaits et droits',
  'entitlements.internal': 'Forfait interne actif',
  'entitlements.public': 'Forfait public',
  'entitlements.assign': 'Attribuer le forfait interne',
  'entitlements.revoke': 'Révoquer le forfait interne',
  'audit.title': 'Activité d’audit récente',
  'audit.outcome': 'Résultat',
  'audit.reason': 'Motif',
  'confirm.title.assign': 'Confirmer l’attribution du forfait interne',
  'confirm.title.revoke': 'Confirmer la révocation du forfait interne',
  'confirm.description': 'Cette opération sensible est revérifiée par le serveur et inscrite dans l’audit immuable.',
  'confirm.reason': 'Motif obligatoire',
  'confirm.reasonPlaceholder': 'Expliquez le motif opérationnel',
  'confirm.checkbox': 'Je confirme explicitement cette opération',
  'confirm.cancel': 'Annuler',
  'confirm.submit': 'Confirmer l’opération',
  'confirm.saving': 'Application de la modification sécurisée…',
  'confirm.success': 'L’opération a été acceptée et auditée.',
  'error.ADMIN_UNAUTHENTICATED': 'Votre session a expiré. Reconnectez-vous.',
  'error.ADMIN_FORBIDDEN': 'Ce compte n’est pas autorisé à administrer.',
  'error.ADMIN_CSRF_INVALID': 'Le jeton de sécurité est invalide. Rechargez la page et réessayez.',
  'error.ADMIN_REAUTH_REQUIRED': 'Reconnectez-vous avant cette opération sensible.',
  'error.ADMIN_IDEMPOTENCY_REQUIRED': 'L’identifiant de l’opération est invalide. Réessayez.',
  'error.ADMIN_INVALID_REQUEST': 'Confirmez l’opération et indiquez un motif utile.',
  'error.ADMIN_INVALID_SEARCH': 'Saisissez entre 2 et 120 caractères.',
  'error.ADMIN_INVALID_CREDENTIALS': 'L’adresse e-mail ou le mot de passe est incorrect.',
  'error.ADMIN_UNAVAILABLE': 'Le service d’administration protégé est indisponible.',
  'nav.dashboard': 'Tableau de bord',
  'nav.users': 'Utilisateurs',
  'nav.workspaces': 'Espaces',
  'nav.plans': 'Forfaits',
  'nav.audit': 'Audit',
  'nav.profile': 'Profil',
  'shell.menu': 'Ouvrir le menu de navigation',
  'shell.closeMenu': 'Fermer le menu de navigation',
  'shell.language': 'Langue',
  'shell.logoutPlaceholder': 'Contrôle de déconnexion',
  'dashboard.kpi.services': 'Santé des services',
  'dashboard.kpi.servicesHint': 'Vérifications réussies parmi les services surveillés',
  'dashboard.kpi.entitlements': 'Forfaits internes actifs',
  'dashboard.kpi.entitlementsHint': 'Espaces actuellement sur le forfait interne',
  'dashboard.kpi.audit': 'Événements d’audit récents',
  'dashboard.kpi.auditHint': 'Événements immuables enregistrés pour ce compte',
  'dashboard.links.title': 'Aller à une section',
  'users.page.eyebrow': 'Annuaire',
  'users.page.title': 'Utilisateurs',
  'users.page.description': 'Recherchez dans l’annuaire des utilisateurs par nom ou e-mail.',
  'users.prompt': 'Recherchez pour voir les utilisateurs correspondants.',
  'users.table.name': 'Nom',
  'users.table.email': 'E-mail',
  'users.table.status': 'Statut de l’e-mail',
  'workspaces.page.eyebrow': 'Annuaire',
  'workspaces.page.title': 'Espaces',
  'workspaces.page.description': 'Recherchez les espaces par nom, propriétaire ou identifiant.',
  'workspaces.prompt': 'Recherchez pour voir les espaces correspondants.',
  'workspaces.table.name': 'Espace',
  'workspaces.table.owner': 'Propriétaire',
  'workspaces.table.members': 'Membres',
  'plans.page.eyebrow': 'Droits',
  'plans.page.title': 'Forfaits',
  'plans.page.description': 'Consultez les droits des espaces et gérez le forfait interne.',
  'plans.table.workspace': 'Espace',
  'plans.table.plan': 'Forfait',
  'plans.table.status': 'Statut',
  'plans.table.actions': 'Actions',
  'audit.page.eyebrow': 'Conformité',
  'audit.page.title': 'Audit',
  'audit.page.description': 'Consultez le journal immuable des actions administratives sensibles.',
  'audit.table.event': 'Événement',
  'audit.table.outcome': 'Résultat',
  'audit.table.reason': 'Motif',
  'audit.table.when': 'Quand',
  'profile.page.eyebrow': 'Compte',
  'profile.page.title': 'Profil',
  'profile.page.description': 'Consultez l’identité utilisée pour cette session d’administration.',
  'profile.account.id': 'Identifiant du compte',
  'profile.account.email': 'Adresse e-mail',
  'profile.account.authenticatedAt': 'Connecté depuis',
  'profile.logout.title': 'Se déconnecter',
  'profile.logout.description': 'Un contrôle de déconnexion dédié arrivera dans une prochaine version.',
  'pagination.previous': 'Page précédente',
  'pagination.next': 'Page suivante',
  'pagination.status': 'Page {page} sur {count}',
}

const de: AdminCatalog = {
  'document.title': 'Administrationskonsole — Postqron',
  'shell.skip': 'Zum Administrationsinhalt springen',
  'shell.navigation': 'Administrationsnavigation',
  'shell.console': 'Admin-Konsole',
  'shell.back': 'Zurück zu Postqron',
  'shell.profile': 'Authentifizierte Administration',
  'page.eyebrow': 'Geschützte Vorgänge',
  'page.title': 'Postqron-Administration',
  'page.description': 'Prüfen Sie Dienststatus, Benutzer, Arbeitsbereiche, Berechtigungen und unveränderliche Audit-Aktivitäten.',
  'login.title': 'Administrator-Anmeldung',
  'login.description': 'Verwenden Sie die Administrator-E-Mail-Adresse und das Passwort. Externe Anbieter sind nicht erforderlich.',
  'login.email': 'E-Mail-Adresse',
  'login.password': 'Passwort',
  'login.submit': 'Anmelden',
  'login.signingIn': 'Anmeldung läuft…',
  'status.loading': 'Geschützte Administrationsdaten werden geladen…',
  'status.empty': 'Keine passenden Administrationsdaten.',
  'status.forbidden': 'Dieses Konto ist nicht zur Administration berechtigt.',
  'status.unavailable': 'Administrationsdaten sind vorübergehend nicht verfügbar.',
  'status.retry': 'Erneut versuchen',
  'health.title': 'Dienststatus',
  'health.healthy': 'Betriebsbereit',
  'health.degraded': 'Beeinträchtigt',
  'search.title': 'Benutzer und Arbeitsbereiche',
  'search.label': 'Nach E-Mail, Benutzer oder Arbeitsbereich suchen',
  'search.placeholder': 'Mindestens zwei Zeichen eingeben',
  'search.submit': 'Suchen',
  'search.users': 'Benutzer',
  'search.workspaces': 'Arbeitsbereiche',
  'search.verified': 'Bestätigte E-Mail',
  'search.unverified': 'Unbestätigte E-Mail',
  'entitlements.title': 'Tarife und Berechtigungen',
  'entitlements.internal': 'Interner Tarif aktiv',
  'entitlements.public': 'Öffentlicher Tarif',
  'entitlements.assign': 'Internen Tarif zuweisen',
  'entitlements.revoke': 'Internen Tarif entziehen',
  'audit.title': 'Neueste Audit-Aktivitäten',
  'audit.outcome': 'Ergebnis',
  'audit.reason': 'Begründung',
  'confirm.title.assign': 'Zuweisung des internen Tarifs bestätigen',
  'confirm.title.revoke': 'Entzug des internen Tarifs bestätigen',
  'confirm.description': 'Dieser sensible Vorgang wird serverseitig erneut geprüft und unveränderlich auditiert.',
  'confirm.reason': 'Begründung erforderlich',
  'confirm.reasonPlaceholder': 'Betriebliche Begründung angeben',
  'confirm.checkbox': 'Ich bestätige diesen Vorgang ausdrücklich',
  'confirm.cancel': 'Abbrechen',
  'confirm.submit': 'Vorgang bestätigen',
  'confirm.saving': 'Sichere Änderung wird angewendet…',
  'confirm.success': 'Der Vorgang wurde angenommen und auditiert.',
  'error.ADMIN_UNAUTHENTICATED': 'Ihre Sitzung ist abgelaufen. Melden Sie sich erneut an.',
  'error.ADMIN_FORBIDDEN': 'Dieses Konto ist nicht zur Administration berechtigt.',
  'error.ADMIN_CSRF_INVALID': 'Das Sicherheitstoken ist ungültig. Laden Sie die Seite neu.',
  'error.ADMIN_REAUTH_REQUIRED': 'Melden Sie sich vor diesem sensiblen Vorgang erneut an.',
  'error.ADMIN_IDEMPOTENCY_REQUIRED': 'Die Vorgangskennung ist ungültig. Versuchen Sie es erneut.',
  'error.ADMIN_INVALID_REQUEST': 'Bestätigen Sie den Vorgang und geben Sie eine sinnvolle Begründung an.',
  'error.ADMIN_INVALID_SEARCH': 'Geben Sie zwischen 2 und 120 Zeichen ein.',
  'error.ADMIN_INVALID_CREDENTIALS': 'E-Mail-Adresse oder Passwort ist ungültig.',
  'error.ADMIN_UNAVAILABLE': 'Der geschützte Administrationsdienst ist nicht verfügbar.',
  'nav.dashboard': 'Übersicht',
  'nav.users': 'Benutzer',
  'nav.workspaces': 'Arbeitsbereiche',
  'nav.plans': 'Tarife',
  'nav.audit': 'Audit',
  'nav.profile': 'Profil',
  'shell.menu': 'Navigationsmenü öffnen',
  'shell.closeMenu': 'Navigationsmenü schließen',
  'shell.language': 'Sprache',
  'shell.logoutPlaceholder': 'Abmeldesteuerung',
  'dashboard.kpi.services': 'Dienststatus',
  'dashboard.kpi.servicesHint': 'Erfolgreiche Prüfungen der überwachten Dienste',
  'dashboard.kpi.entitlements': 'Aktive interne Tarife',
  'dashboard.kpi.entitlementsHint': 'Arbeitsbereiche derzeit im internen Tarif',
  'dashboard.kpi.audit': 'Neueste Audit-Ereignisse',
  'dashboard.kpi.auditHint': 'Unveränderliche Ereignisse für dieses Konto',
  'dashboard.links.title': 'Zu einem Bereich wechseln',
  'users.page.eyebrow': 'Verzeichnis',
  'users.page.title': 'Benutzer',
  'users.page.description': 'Durchsuchen Sie das Benutzerverzeichnis nach Name oder E-Mail.',
  'users.prompt': 'Suchen Sie, um passende Benutzer zu sehen.',
  'users.table.name': 'Name',
  'users.table.email': 'E-Mail',
  'users.table.status': 'E-Mail-Status',
  'workspaces.page.eyebrow': 'Verzeichnis',
  'workspaces.page.title': 'Arbeitsbereiche',
  'workspaces.page.description': 'Durchsuchen Sie Arbeitsbereiche nach Name, Inhaber oder Kennung.',
  'workspaces.prompt': 'Suchen Sie, um passende Arbeitsbereiche zu sehen.',
  'workspaces.table.name': 'Arbeitsbereich',
  'workspaces.table.owner': 'Inhaber',
  'workspaces.table.members': 'Mitglieder',
  'plans.page.eyebrow': 'Berechtigungen',
  'plans.page.title': 'Tarife',
  'plans.page.description': 'Prüfen Sie Arbeitsbereichsberechtigungen und verwalten Sie den internen Tarif.',
  'plans.table.workspace': 'Arbeitsbereich',
  'plans.table.plan': 'Tarif',
  'plans.table.status': 'Status',
  'plans.table.actions': 'Aktionen',
  'audit.page.eyebrow': 'Compliance',
  'audit.page.title': 'Audit',
  'audit.page.description': 'Prüfen Sie das unveränderliche Protokoll sensibler Administrationsaktionen.',
  'audit.table.event': 'Ereignis',
  'audit.table.outcome': 'Ergebnis',
  'audit.table.reason': 'Begründung',
  'audit.table.when': 'Wann',
  'profile.page.eyebrow': 'Konto',
  'profile.page.title': 'Profil',
  'profile.page.description': 'Prüfen Sie die für diese Administrationssitzung verwendete Identität.',
  'profile.account.id': 'Kontokennung',
  'profile.account.email': 'E-Mail-Adresse',
  'profile.account.authenticatedAt': 'Angemeldet seit',
  'profile.logout.title': 'Abmelden',
  'profile.logout.description': 'Eine eigene Abmeldesteuerung folgt in einer späteren Version.',
  'pagination.previous': 'Vorherige Seite',
  'pagination.next': 'Nächste Seite',
  'pagination.status': 'Seite {page} von {count}',
}

export const ADMIN_CATALOGS = defineCatalogs({ en, it, es, fr, de })
