// Regenerates the F13 compliance-ledger seed migration for the approved
// `cookies_it` release straight from the canonical F25 bundle
// (`src/bundle.ts`), which was produced under the external legal approval
// recorded under reference LEGAL-APPROVAL-2026-07-25-F25
// (https://github.com/apdsoftware/postqron/issues/134#issuecomment-5080412206).
//
// This keeps the runtime ledger row and the approved corpus mechanically in
// sync: content, digest, version, dates, and approval reference are read
// from the bundle, never retyped by hand. Run with:
//   node --experimental-strip-types scripts/build-cookie-consent-seed.ts
//
// Do not hand-edit the generated migration file — change the source corpus
// (via build-bundle.ts) or this script and regenerate instead.

import { writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { BUNDLED_LEGAL_RELEASE } from '../src/bundle.ts'

const featureRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
export const COOKIE_CONSENT_SEED_MIGRATION_PATH = resolve(
  featureRoot,
  '../f13-compliance/migrations/000002_seed_cookies_it_release.sql',
)

const DOLLAR_TAG = '$cookies_it_v0_1_content$'

export function renderCookieConsentSeedMigration(): string {
  const artifact = BUNDLED_LEGAL_RELEASE.artifacts.find(
    item => item.document === 'cookies' && item.locale === 'it',
  )
  if (!artifact) {
    throw new Error('the canonical F25 bundle has no approved cookies/it artifact')
  }
  if (artifact.status !== 'approved') {
    throw new Error('the canonical cookies/it artifact is not approved')
  }
  if (artifact.content.includes(DOLLAR_TAG)) {
    throw new Error('dollar-quote tag collides with the approved cookies/it content')
  }

  const permanentUrl = `/api/v1/legal-documents/cookies_it/versions/${artifact.version}`
  const currentUrl = '/api/v1/legal-documents/cookies_it/current'

  return `-- Materializes the F25-approved \`cookies_it\` release into the F13
-- compliance ledger (\`compliance_legal_documents\`). Generated by
-- \`node --experimental-strip-types features/f25-legal-documents/scripts/build-cookie-consent-seed.ts\`
-- from the canonical bundle in \`features/f25-legal-documents/src/bundle.ts\`
-- (ref. ${artifact.approvalReference}). Do not hand-edit this file — change
-- the source corpus or the generation script and regenerate instead.
--
-- Fixes the production defect where F26's cookie-preferences API returned
-- \`503 cookie_policy_unavailable\` because no approved \`cookies_it\` row
-- existed in the runtime ledger, even though the corpus was approved.
--
-- \`ON CONFLICT DO NOTHING\` makes a re-run idempotent, but it must never
-- silently mask a pre-existing row that diverges from the approved bundle
-- (hand edit, corruption, a stale release, ...). So after the insert
-- no-ops or succeeds, this block re-reads the row and fails the migration
-- explicitly if any field does not match the bundle exactly.
DO $$
DECLARE
  expected_content bytea := convert_to(${DOLLAR_TAG}${artifact.content}${DOLLAR_TAG}, 'UTF8');
  actual compliance_legal_documents%ROWTYPE;
BEGIN
  INSERT INTO compliance_legal_documents (
      document_key,
      jurisdiction,
      locale,
      version,
      content_bytes,
      digest_sha256,
      content_status,
      legal_approval_id,
      approved_at,
      published_at,
      effective_at,
      permanent_url,
      current_url,
      change_type
  ) VALUES (
      'cookies_it',
      '${artifact.jurisdiction}',
      'it-IT',
      '${artifact.version}',
      expected_content,
      '${artifact.digestSha256}',
      'approved',
      '${artifact.approvalReference}',
      '${artifact.approvedAt}'::timestamptz,
      '${artifact.publishedAt}'::timestamptz,
      '${artifact.effectiveAt}'::timestamptz,
      '${permanentUrl}',
      '${currentUrl}',
      '${artifact.changeType}'
  )
  ON CONFLICT (document_key, jurisdiction, locale, version) DO NOTHING;

  SELECT * INTO actual
  FROM compliance_legal_documents
  WHERE document_key = 'cookies_it'
    AND jurisdiction = '${artifact.jurisdiction}'
    AND locale = 'it-IT'
    AND version = '${artifact.version}';

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'cookies_it % seed migration: expected row is missing after insert',
      '${artifact.version}';
  END IF;

  IF actual.content_bytes IS DISTINCT FROM expected_content
    OR actual.digest_sha256 IS DISTINCT FROM '${artifact.digestSha256}'
    OR actual.content_status IS DISTINCT FROM 'approved'
    OR actual.legal_approval_id IS DISTINCT FROM '${artifact.approvalReference}'
    OR actual.approved_at IS DISTINCT FROM '${artifact.approvedAt}'::timestamptz
    OR actual.published_at IS DISTINCT FROM '${artifact.publishedAt}'::timestamptz
    OR actual.effective_at IS DISTINCT FROM '${artifact.effectiveAt}'::timestamptz
    OR actual.superseded_at IS NOT NULL
    OR actual.permanent_url IS DISTINCT FROM '${permanentUrl}'
    OR actual.current_url IS DISTINCT FROM '${currentUrl}'
    OR actual.change_type IS DISTINCT FROM '${artifact.changeType}'
  THEN
    RAISE EXCEPTION
      'cookies_it % seed migration: an existing compliance_legal_documents row for cookies_it/${artifact.jurisdiction}/it-IT/% diverges from the F25-approved bundle (ref %); refusing to mask the conflict',
      '${artifact.version}', '${artifact.version}', '${artifact.approvalReference}';
  END IF;
END;
$$;
`
}

const isMainModule = process.argv[1] === fileURLToPath(import.meta.url)
if (isMainModule) {
  const output = renderCookieConsentSeedMigration()
  await writeFile(COOKIE_CONSENT_SEED_MIGRATION_PATH, output, 'utf8')
  console.warn(`wrote ${COOKIE_CONSENT_SEED_MIGRATION_PATH}`)
}
