// Regenerates the F13 compliance-ledger seed migration for the approved
// `cookies_it` release straight from the canonical F25 bundle
// (`src/bundle.ts`), which was produced under the external legal approval
// recorded under reference LEGAL-APPROVAL-2026-07-25-F25
// (https://github.com/apdsoftware/postqron/issues/134#issuecomment-5080412206).
//
// This keeps the runtime ledger row and the approved corpus mechanically in
// sync: content, digest, version, dates, and approval reference are read
// from the bundle, never retyped by hand. Run with:
//   node --experimental-strip-types scripts/build-cookie-consent-seed.ts
//
// Do not hand-edit the generated migration file — change the source corpus
// (via build-bundle.ts) or this script and regenerate instead.

import { writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { BUNDLED_LEGAL_RELEASE } from '../src/bundle.ts'

const featureRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
export const COOKIE_CONSENT_SEED_MIGRATION_PATH = resolve(
  featureRoot,
  '../f13-compliance/migrations/000002_seed_cookies_it_release.sql',
)

const DOLLAR_TAG = '$cookies_it_v0_1_content$'

export function renderCookieConsentSeedMigration(): string {
  const artifact = BUNDLED_LEGAL_RELEASE.artifacts.find(
    item => item.document === 'cookies' && item.locale === 'it',
  )
  if (!artifact) {
    throw new Error('the canonical F25 bundle has no approved cookies/it artifact')
  }
  if (artifact.status !== 'approved') {
    throw new Error('the canonical cookies/it artifact is not approved')
  }
  if (artifact.content.includes(DOLLAR_TAG)) {
    throw new Error('dollar-quote tag collides with the approved cookies/it content')
  }

  return `-- Materializes the F25-approved \`cookies_it\` release into the F13
-- compliance ledger (\`compliance_legal_documents\`). Generated by
-- \`node --experimental-strip-types features/f25-legal-documents/scripts/build-cookie-consent-seed.ts\`
-- from the canonical bundle in \`features/f25-legal-documents/src/bundle.ts\`
-- (ref. ${artifact.approvalReference}). Do not hand-edit this file — change
-- the source corpus or the generation script and regenerate instead.
--
-- Fixes the production defect where F26's cookie-preferences API returned
-- \`503 cookie_policy_unavailable\` because no approved \`cookies_it\` row
-- existed in the runtime ledger, even though the corpus was approved.
INSERT INTO compliance_legal_documents (
    document_key,
    jurisdiction,
    locale,
    version,
    content_bytes,
    digest_sha256,
    content_status,
    legal_approval_id,
    approved_at,
    published_at,
    effective_at,
    permanent_url,
    current_url,
    change_type
) VALUES (
    'cookies_it',
    '${artifact.jurisdiction}',
    'it-IT',
    '${artifact.version}',
    convert_to(${DOLLAR_TAG}${artifact.content}${DOLLAR_TAG}, 'UTF8'),
    '${artifact.digestSha256}',
    'approved',
    '${artifact.approvalReference}',
    '${artifact.approvedAt}',
    '${artifact.publishedAt}',
    '${artifact.effectiveAt}',
    '/api/v1/legal-documents/cookies_it/versions/${artifact.version}',
    '/api/v1/legal-documents/cookies_it/current',
    '${artifact.changeType}'
)
ON CONFLICT (document_key, jurisdiction, locale, version) DO NOTHING;
`
}

const isMainModule = process.argv[1] === fileURLToPath(import.meta.url)
if (isMainModule) {
  const output = renderCookieConsentSeedMigration()
  await writeFile(COOKIE_CONSENT_SEED_MIGRATION_PATH, output, 'utf8')
  console.warn(`wrote ${COOKIE_CONSENT_SEED_MIGRATION_PATH}`)
}
