import { defineCatalogs } from '../../f36-i18n/src/catalog.ts'

export const BILLING_UI_CATALOGS = defineCatalogs({
  en: {
    'nav.title': 'Plan and billing',
    'overview.eyebrow': 'Billing',
    'overview.title': 'Your plan at a glance',
    'overview.description': 'Usage and remaining capacity come from the server-side entitlement.',
    'overview.currentPlan': 'Current plan',
    'overview.interval': 'Billing interval',
    'overview.period': 'Current period: {start} – {end}',
    'overview.used': '{used} of {limit} used · {remaining} remaining',
    'overview.portal': 'Open secure Paddle portal',
    'overview.portalOpening': 'Opening portal…',
    'overview.portalError': 'The secure portal could not be opened. Try again.',
    'overview.noPortal': 'Start has no subscription to manage.',
    'overview.pricing': 'Compare all plans',
    'resource.members': 'Users',
    'resource.channels': 'Social channels',
    'resource.scheduled_publications': 'Scheduled posts',
    'interval.monthly': 'Monthly',
    'interval.annual': 'Annual',
    'state.trialing': 'Trial',
    'state.active': 'Active',
    'state.past_due': 'Payment recovery',
    'state.trial_expired': 'Trial expired',
    'state.payment_restricted': 'Payment restricted',
    'state.canceled': 'Canceled',
    'checkout.eyebrow': 'Secure checkout',
    'checkout.title': 'Complete your {plan} purchase',
    'checkout.description': 'Paddle shows localized subtotal, taxes, total, renewal, and cancellation terms before you consent.',
    'checkout.channels': '{count} social channels',
    'checkout.baseTotal': 'Base recurring total: {total}',
    'checkout.taxes': 'Taxes are calculated by Paddle for your location. Paddle is the Merchant of Record.',
    'checkout.opening': 'Preparing secure checkout…',
    'checkout.open': 'Open secure checkout',
    'checkout.fallback': 'Continue in Paddle’s secure hosted checkout',
    'checkout.invalid': 'This plan selection is invalid or expired. Return to pricing and choose again.',
    'checkout.closed': 'Checkout was closed. No purchase was created.',
    'checkout.paymentFailed': 'Payment was not completed. Check the details in Paddle and retry safely.',
    'checkout.processing': 'Payment received. We are waiting for the verified Paddle webhook before enabling the plan.',
    'checkout.confirmed': 'Your entitlement is confirmed and the plan is active.',
    'checkout.error': 'Checkout could not be opened. No duplicate purchase was created.',
    'checkout.retry': 'Retry',
    'checkout.back': 'Back to pricing',
    'checkout.free': 'Start is free and does not use Paddle checkout.',
    'checkout.loading': 'Loading secure billing details…',
  },
  it: {
    'nav.title': 'Piano e fatturazione',
    'overview.eyebrow': 'Fatturazione',
    'overview.title': 'Il tuo piano in sintesi',
    'overview.description': 'Utilizzo e capacità residua provengono dall’entitlement lato server.',
    'overview.currentPlan': 'Piano corrente',
    'overview.interval': 'Intervallo di fatturazione',
    'overview.period': 'Periodo corrente: {start} – {end}',
    'overview.used': '{used} di {limit} usati · {remaining} disponibili',
    'overview.portal': 'Apri il portale Paddle sicuro',
    'overview.portalOpening': 'Apertura del portale…',
    'overview.portalError': 'Impossibile aprire il portale sicuro. Riprova.',
    'overview.noPortal': 'Start non ha un abbonamento da gestire.',
    'overview.pricing': 'Confronta tutti i piani',
    'resource.members': 'Utenti',
    'resource.channels': 'Canali social',
    'resource.scheduled_publications': 'Post programmati',
    'interval.monthly': 'Mensile',
    'interval.annual': 'Annuale',
    'state.trialing': 'Prova',
    'state.active': 'Attivo',
    'state.past_due': 'Recupero pagamento',
    'state.trial_expired': 'Prova scaduta',
    'state.payment_restricted': 'Limitato per pagamento',
    'state.canceled': 'Annullato',
    'checkout.eyebrow': 'Checkout sicuro',
    'checkout.title': 'Completa l’acquisto di {plan}',
    'checkout.description': 'Paddle mostra subtotale, imposte, totale, rinnovo e condizioni di cancellazione localizzati prima del consenso.',
    'checkout.channels': '{count} canali social',
    'checkout.baseTotal': 'Totale ricorrente base: {total}',
    'checkout.taxes': 'Paddle calcola le imposte per la tua località. Paddle è il Merchant of Record.',
    'checkout.opening': 'Preparazione del checkout sicuro…',
    'checkout.open': 'Apri il checkout sicuro',
    'checkout.fallback': 'Continua nel checkout sicuro ospitato da Paddle',
    'checkout.invalid': 'La selezione del piano non è valida o è scaduta. Torna ai prezzi e scegli di nuovo.',
    'checkout.closed': 'Il checkout è stato chiuso. Non è stato creato alcun acquisto.',
    'checkout.paymentFailed': 'Il pagamento non è stato completato. Controlla i dettagli in Paddle e riprova in sicurezza.',
    'checkout.processing': 'Pagamento ricevuto. Attendiamo il webhook Paddle verificato prima di abilitare il piano.',
    'checkout.confirmed': 'Il tuo entitlement è confermato e il piano è attivo.',
    'checkout.error': 'Impossibile aprire il checkout. Non è stato creato un acquisto duplicato.',
    'checkout.retry': 'Riprova',
    'checkout.back': 'Torna ai prezzi',
    'checkout.free': 'Start è gratuito e non usa il checkout Paddle.',
    'checkout.loading': 'Caricamento dei dati di fatturazione sicuri…',
  },
  es: {
    'nav.title': 'Plan y facturación',
    'overview.eyebrow': 'Facturación',
    'overview.title': 'Tu plan de un vistazo',
    'overview.description': 'El uso y la capacidad restante provienen del entitlement del servidor.',
    'overview.currentPlan': 'Plan actual',
    'overview.interval': 'Intervalo de facturación',
    'overview.period': 'Período actual: {start} – {end}',
    'overview.used': '{used} de {limit} usados · {remaining} disponibles',
    'overview.portal': 'Abrir el portal seguro de Paddle',
    'overview.portalOpening': 'Abriendo el portal…',
    'overview.portalError': 'No se pudo abrir el portal seguro. Inténtalo de nuevo.',
    'overview.noPortal': 'Start no tiene una suscripción que gestionar.',
    'overview.pricing': 'Comparar todos los planes',
    'resource.members': 'Usuarios',
    'resource.channels': 'Canales sociales',
    'resource.scheduled_publications': 'Publicaciones programadas',
    'interval.monthly': 'Mensual',
    'interval.annual': 'Anual',
    'state.trialing': 'Prueba',
    'state.active': 'Activo',
    'state.past_due': 'Recuperación de pago',
    'state.trial_expired': 'Prueba vencida',
    'state.payment_restricted': 'Restringido por pago',
    'state.canceled': 'Cancelado',
    'checkout.eyebrow': 'Pago seguro',
    'checkout.title': 'Completa la compra de {plan}',
    'checkout.description': 'Paddle muestra subtotal, impuestos, total, renovación y cancelación localizados antes de tu consentimiento.',
    'checkout.channels': '{count} canales sociales',
    'checkout.baseTotal': 'Total recurrente base: {total}',
    'checkout.taxes': 'Paddle calcula los impuestos para tu ubicación. Paddle es el Merchant of Record.',
    'checkout.opening': 'Preparando el pago seguro…',
    'checkout.open': 'Abrir el pago seguro',
    'checkout.fallback': 'Continuar en el pago seguro alojado por Paddle',
    'checkout.invalid': 'La selección del plan no es válida o ha vencido. Vuelve a precios y elige de nuevo.',
    'checkout.closed': 'Se cerró el pago. No se creó ninguna compra.',
    'checkout.paymentFailed': 'El pago no se completó. Revisa los detalles en Paddle y vuelve a intentarlo.',
    'checkout.processing': 'Pago recibido. Esperamos el webhook verificado de Paddle antes de habilitar el plan.',
    'checkout.confirmed': 'Tu entitlement está confirmado y el plan está activo.',
    'checkout.error': 'No se pudo abrir el pago. No se creó una compra duplicada.',
    'checkout.retry': 'Reintentar',
    'checkout.back': 'Volver a precios',
    'checkout.free': 'Start es gratuito y no usa el checkout de Paddle.',
    'checkout.loading': 'Cargando los datos seguros de facturación…',
  },
  fr: {
    'nav.title': 'Abonnement et facturation',
    'overview.eyebrow': 'Facturation',
    'overview.title': 'Votre abonnement en un coup d’œil',
    'overview.description': 'L’utilisation et la capacité restante proviennent de l’entitlement côté serveur.',
    'overview.currentPlan': 'Abonnement actuel',
    'overview.interval': 'Période de facturation',
    'overview.period': 'Période actuelle : {start} – {end}',
    'overview.used': '{used} sur {limit} utilisés · {remaining} disponibles',
    'overview.portal': 'Ouvrir le portail Paddle sécurisé',
    'overview.portalOpening': 'Ouverture du portail…',
    'overview.portalError': 'Impossible d’ouvrir le portail sécurisé. Réessayez.',
    'overview.noPortal': 'Start n’a aucun abonnement à gérer.',
    'overview.pricing': 'Comparer tous les abonnements',
    'resource.members': 'Utilisateurs',
    'resource.channels': 'Canaux sociaux',
    'resource.scheduled_publications': 'Publications programmées',
    'interval.monthly': 'Mensuel',
    'interval.annual': 'Annuel',
    'state.trialing': 'Essai',
    'state.active': 'Actif',
    'state.past_due': 'Récupération du paiement',
    'state.trial_expired': 'Essai expiré',
    'state.payment_restricted': 'Restreint pour paiement',
    'state.canceled': 'Annulé',
    'checkout.eyebrow': 'Paiement sécurisé',
    'checkout.title': 'Finalisez l’achat de {plan}',
    'checkout.description': 'Paddle affiche le sous-total, les taxes, le total, le renouvellement et l’annulation localisés avant votre consentement.',
    'checkout.channels': '{count} canaux sociaux',
    'checkout.baseTotal': 'Total récurrent de base : {total}',
    'checkout.taxes': 'Paddle calcule les taxes selon votre localisation. Paddle est le Merchant of Record.',
    'checkout.opening': 'Préparation du paiement sécurisé…',
    'checkout.open': 'Ouvrir le paiement sécurisé',
    'checkout.fallback': 'Continuer sur le paiement sécurisé hébergé par Paddle',
    'checkout.invalid': 'Ce choix d’abonnement est invalide ou expiré. Revenez aux tarifs et choisissez à nouveau.',
    'checkout.closed': 'Le paiement a été fermé. Aucun achat n’a été créé.',
    'checkout.paymentFailed': 'Le paiement n’a pas abouti. Vérifiez les détails dans Paddle et réessayez.',
    'checkout.processing': 'Paiement reçu. Nous attendons le webhook Paddle vérifié avant d’activer l’abonnement.',
    'checkout.confirmed': 'Votre entitlement est confirmé et l’abonnement est actif.',
    'checkout.error': 'Impossible d’ouvrir le paiement. Aucun achat en double n’a été créé.',
    'checkout.retry': 'Réessayer',
    'checkout.back': 'Retour aux tarifs',
    'checkout.free': 'Start est gratuit et n’utilise pas le paiement Paddle.',
    'checkout.loading': 'Chargement des informations de facturation sécurisées…',
  },
  de: {
    'nav.title': 'Tarif und Abrechnung',
    'overview.eyebrow': 'Abrechnung',
    'overview.title': 'Dein Tarif im Überblick',
    'overview.description': 'Nutzung und Restkapazität stammen aus dem serverseitigen Entitlement.',
    'overview.currentPlan': 'Aktueller Tarif',
    'overview.interval': 'Abrechnungszeitraum',
    'overview.period': 'Aktueller Zeitraum: {start} – {end}',
    'overview.used': '{used} von {limit} genutzt · {remaining} verfügbar',
    'overview.portal': 'Sicheres Paddle-Portal öffnen',
    'overview.portalOpening': 'Portal wird geöffnet…',
    'overview.portalError': 'Das sichere Portal konnte nicht geöffnet werden. Versuche es erneut.',
    'overview.noPortal': 'Für Start gibt es kein Abonnement zu verwalten.',
    'overview.pricing': 'Alle Tarife vergleichen',
    'resource.members': 'Benutzer',
    'resource.channels': 'Social-Media-Kanäle',
    'resource.scheduled_publications': 'Geplante Beiträge',
    'interval.monthly': 'Monatlich',
    'interval.annual': 'Jährlich',
    'state.trialing': 'Testphase',
    'state.active': 'Aktiv',
    'state.past_due': 'Zahlungswiederherstellung',
    'state.trial_expired': 'Testphase abgelaufen',
    'state.payment_restricted': 'Wegen Zahlung eingeschränkt',
    'state.canceled': 'Gekündigt',
    'checkout.eyebrow': 'Sicherer Checkout',
    'checkout.title': 'Schließe den Kauf von {plan} ab',
    'checkout.description': 'Paddle zeigt vor deiner Zustimmung lokalisierte Zwischensumme, Steuern, Gesamtpreis, Verlängerung und Kündigungsbedingungen.',
    'checkout.channels': '{count} Social-Media-Kanäle',
    'checkout.baseTotal': 'Wiederkehrender Basispreis: {total}',
    'checkout.taxes': 'Paddle berechnet die Steuern für deinen Standort. Paddle ist der Merchant of Record.',
    'checkout.opening': 'Sicherer Checkout wird vorbereitet…',
    'checkout.open': 'Sicheren Checkout öffnen',
    'checkout.fallback': 'Im sicheren, von Paddle gehosteten Checkout fortfahren',
    'checkout.invalid': 'Diese Tarifauswahl ist ungültig oder abgelaufen. Kehre zur Preisseite zurück und wähle erneut.',
    'checkout.closed': 'Der Checkout wurde geschlossen. Es wurde kein Kauf erstellt.',
    'checkout.paymentFailed': 'Die Zahlung wurde nicht abgeschlossen. Prüfe die Angaben in Paddle und versuche es erneut.',
    'checkout.processing': 'Zahlung eingegangen. Wir warten auf den verifizierten Paddle-Webhook, bevor der Tarif aktiviert wird.',
    'checkout.confirmed': 'Dein Entitlement ist bestätigt und der Tarif ist aktiv.',
    'checkout.error': 'Der Checkout konnte nicht geöffnet werden. Es wurde kein doppelter Kauf erstellt.',
    'checkout.retry': 'Erneut versuchen',
    'checkout.back': 'Zurück zu den Preisen',
    'checkout.free': 'Start ist kostenlos und verwendet keinen Paddle-Checkout.',
    'checkout.loading': 'Sichere Abrechnungsdaten werden geladen…',
  },
})

export type BillingUIMessageKey = keyof typeof BILLING_UI_CATALOGS.en
