import { defineCatalogs } from '../../f36-i18n/src/catalog.ts'

export const BILLING_PLAN_CATALOGS = defineCatalogs({
  en: {
    'document.title': 'Plan and usage',
    'overview.eyebrow': 'Plan',
    'overview.title': 'Plan and usage',
    'overview.description': 'Check your current plan, usage, and available capacity.',
    'overview.current': 'Current plan',
    'overview.interval': 'Billing',
    'overview.channels': 'Channel quantity',
    'overview.price': 'Current base price',
    'overview.free': 'Free',
    'overview.renews': 'Renews on {date}',
    'overview.trialEnds': 'Trial ends on {date}',
    'overview.periodEnds': 'Current period ends on {date}',
    'overview.manage': 'Manage billing',
    'overview.managing': 'Opening Paddle…',
    'overview.manageError': 'The secure billing portal could not be opened. Try again.',
    'overview.noSubscription': 'There is no paid subscription to manage.',
    'overview.change': 'Change plan',
    'overview.readOnly': 'Only a workspace Owner can change the plan or manage billing.',
    'usage.title': 'Usage and limits',
    'usage.description': 'Limits are enforced by the server. Nothing is removed automatically.',
    'usage.value': '{used} used',
    'usage.limit': 'Limit {limit}',
    'usage.remaining': '{remaining} remaining',
    'usage.unlimited': 'Unlimited',
    'usage.percent': '{percent}% used',
    'resource.members': 'Users',
    'resource.channels': 'Social channels',
    'resource.scheduled_publications': 'Scheduled posts',
    'interval.monthly': 'Monthly',
    'interval.annual': 'Annual',
    'state.trialing': 'Trial',
    'state.active': 'Active',
    'state.past_due': 'Payment recovery',
    'state.trial_expired': 'Trial expired',
    'state.payment_restricted': 'Payment restricted',
    'state.canceled': 'Canceled',
    'common.loading': 'Loading plan details…',
    'common.error': 'Plan details are temporarily unavailable.',
    'common.retry': 'Try again',
    'change.dialog': 'Change workspace plan',
    'change.title': 'Compare plans',
    'change.description': 'Choose billing frequency and a plan. Prices and limits come from the current server catalog.',
    'change.close': 'Close plan comparison',
    'change.interval': 'Billing frequency',
    'change.annualNote': 'Annual billing costs ten monthly payments and covers twelve months.',
    'change.recommended': 'Minimum compatible',
    'change.current': 'Current',
    'change.select': 'Select {plan}',
    'change.selected': '{plan} selected',
    'change.incompatible': 'Does not fit current usage',
    'change.members': '{count} users',
    'change.channels': '{count} social channels',
    'change.posts': '{count} scheduled posts per channel',
    'change.unlimitedMembers': 'Unlimited users',
    'change.unlimitedChannels': 'Unlimited social channels',
    'change.unlimitedPosts': 'Unlimited scheduled posts',
    'change.quantity': 'Channels to include',
    'change.basePrice': '{price} base price',
    'change.taxNotice': 'Paddle calculates applicable taxes and shows the authoritative total in the preview.',
    'change.preview': 'Review change',
    'change.previewing': 'Preparing preview…',
    'change.previewError': 'The change preview is unavailable. No change was requested.',
    'change.upgrade': 'Upgrade',
    'change.downgrade': 'Downgrade',
    'change.immediate': 'Takes effect after payment and the verified Paddle webhook.',
    'change.periodEnd': 'Takes effect at the end of the current paid period.',
    'change.cancelAtPeriodEnd': 'The paid subscription will end at period close. Your data stays in the workspace.',
    'change.chargeNow': 'Due now: {amount}',
    'change.recurring': 'Recurring total: {amount}',
    'change.confirm': 'Confirm plan change',
    'change.requesting': 'Requesting change…',
    'change.pending': 'Change pending. Your current entitlement stays active until the matching Paddle webhook is verified.',
    'change.success': 'Plan change confirmed.',
    'change.checkout': 'Continue to secure checkout',
    'change.checkoutRequired': 'A first paid subscription is created through secure Paddle checkout.',
    'change.samePlan': 'This plan and billing setup are already active.',
    'change.inProgress': 'Another plan change is already pending. Wait for it to complete before trying again.',
    'change.conflict': 'The subscription changed while you were reviewing it. Reload and review the latest details.',
    'change.failure': 'The plan change could not be requested. Your current plan is unchanged.',
    'blocked.title': 'Reduce usage before downgrading',
    'blocked.description': 'This downgrade is blocked. Bring each resource within the new limit, then retry.',
    'blocked.values': '{resource}: {used} used, limit {limit}, {excess} over.',
    'blocked.members': 'Remove access for {excess} users before retrying.',
    'blocked.channels': 'Disconnect {excess} social channels before retrying.',
    'blocked.scheduled_publications': 'Remove or reschedule {excess} scheduled posts before retrying.',
    'blocked.noDeletion': 'Postqron has not deleted, disconnected, or changed any resource.',
  },
  it: {
    'document.title': 'Piano e utilizzo',
    'overview.eyebrow': 'Piano',
    'overview.title': 'Piano e utilizzo',
    'overview.description': 'Controlla il piano corrente, l’utilizzo e la capacità disponibile.',
    'overview.current': 'Piano corrente',
    'overview.interval': 'Fatturazione',
    'overview.channels': 'Quantità di canali',
    'overview.price': 'Prezzo base corrente',
    'overview.free': 'Gratis',
    'overview.renews': 'Rinnovo il {date}',
    'overview.trialEnds': 'La prova termina il {date}',
    'overview.periodEnds': 'Il periodo corrente termina il {date}',
    'overview.manage': 'Gestisci fatturazione',
    'overview.managing': 'Apertura di Paddle…',
    'overview.manageError': 'Impossibile aprire il portale di fatturazione sicuro. Riprova.',
    'overview.noSubscription': 'Non è presente un abbonamento a pagamento da gestire.',
    'overview.change': 'Cambia piano',
    'overview.readOnly': 'Solo un Owner del workspace può cambiare piano o gestire la fatturazione.',
    'usage.title': 'Utilizzo e limiti',
    'usage.description': 'I limiti sono applicati dal server. Nulla viene rimosso automaticamente.',
    'usage.value': '{used} usati',
    'usage.limit': 'Limite {limit}',
    'usage.remaining': '{remaining} disponibili',
    'usage.unlimited': 'Illimitato',
    'usage.percent': '{percent}% utilizzato',
    'resource.members': 'Utenti',
    'resource.channels': 'Canali social',
    'resource.scheduled_publications': 'Post programmati',
    'interval.monthly': 'Mensile',
    'interval.annual': 'Annuale',
    'state.trialing': 'Prova',
    'state.active': 'Attivo',
    'state.past_due': 'Recupero pagamento',
    'state.trial_expired': 'Prova scaduta',
    'state.payment_restricted': 'Limitato per pagamento',
    'state.canceled': 'Annullato',
    'common.loading': 'Caricamento dei dettagli del piano…',
    'common.error': 'I dettagli del piano non sono momentaneamente disponibili.',
    'common.retry': 'Riprova',
    'change.dialog': 'Cambia il piano del workspace',
    'change.title': 'Confronta i piani',
    'change.description': 'Scegli la frequenza di fatturazione e un piano. Prezzi e limiti provengono dal catalogo corrente del server.',
    'change.close': 'Chiudi il confronto dei piani',
    'change.interval': 'Frequenza di fatturazione',
    'change.annualNote': 'L’annuale costa dieci mensilità e copre dodici mesi.',
    'change.recommended': 'Minimo compatibile',
    'change.current': 'Corrente',
    'change.select': 'Scegli {plan}',
    'change.selected': '{plan} selezionato',
    'change.incompatible': 'Non compatibile con l’utilizzo corrente',
    'change.members': '{count} utenti',
    'change.channels': '{count} canali social',
    'change.posts': '{count} post programmati per canale',
    'change.unlimitedMembers': 'Utenti illimitati',
    'change.unlimitedChannels': 'Canali social illimitati',
    'change.unlimitedPosts': 'Post programmati illimitati',
    'change.quantity': 'Canali da includere',
    'change.basePrice': 'Prezzo base {price}',
    'change.taxNotice': 'Paddle calcola le imposte applicabili e mostra il totale autorevole nella preview.',
    'change.preview': 'Rivedi la modifica',
    'change.previewing': 'Preparazione della preview…',
    'change.previewError': 'La preview non è disponibile. Non è stata richiesta alcuna modifica.',
    'change.upgrade': 'Upgrade',
    'change.downgrade': 'Downgrade',
    'change.immediate': 'Diventa effettivo dopo il pagamento e il webhook Paddle verificato.',
    'change.periodEnd': 'Diventa effettivo alla fine del periodo già pagato.',
    'change.cancelAtPeriodEnd': 'L’abbonamento pagante terminerà a fine periodo. I dati restano nel workspace.',
    'change.chargeNow': 'Da pagare ora: {amount}',
    'change.recurring': 'Totale ricorrente: {amount}',
    'change.confirm': 'Conferma cambio piano',
    'change.requesting': 'Richiesta della modifica…',
    'change.pending': 'Modifica in attesa. L’entitlement corrente resta attivo fino alla verifica del webhook Paddle corrispondente.',
    'change.success': 'Cambio piano confermato.',
    'change.checkout': 'Continua al checkout sicuro',
    'change.checkoutRequired': 'Il primo abbonamento pagante viene creato tramite il checkout sicuro Paddle.',
    'change.samePlan': 'Questo piano e questa configurazione di fatturazione sono già attivi.',
    'change.inProgress': 'Un altro cambio piano è già in attesa. Attendi che termini prima di riprovare.',
    'change.conflict': 'L’abbonamento è cambiato durante la verifica. Ricarica e controlla i dati aggiornati.',
    'change.failure': 'Impossibile richiedere il cambio piano. Il piano corrente è invariato.',
    'blocked.title': 'Riduci l’utilizzo prima del downgrade',
    'blocked.description': 'Il downgrade è bloccato. Riporta ogni risorsa entro il nuovo limite, poi riprova.',
    'blocked.values': '{resource}: usato {used}, limite {limit}, eccedenza {excess}.',
    'blocked.members': 'Rimuovi l’accesso a {excess} utenti prima di riprovare.',
    'blocked.channels': 'Scollega {excess} canali social prima di riprovare.',
    'blocked.scheduled_publications': 'Elimina o riprogramma {excess} post programmati prima di riprovare.',
    'blocked.noDeletion': 'Postqron non ha eliminato, scollegato o modificato alcuna risorsa.',
  },
  es: {
    'document.title': 'Plan y uso',
    'overview.eyebrow': 'Plan',
    'overview.title': 'Plan y uso',
    'overview.description': 'Consulta el plan actual, el uso y la capacidad disponible.',
    'overview.current': 'Plan actual',
    'overview.interval': 'Facturación',
    'overview.channels': 'Cantidad de canales',
    'overview.price': 'Precio base actual',
    'overview.free': 'Gratis',
    'overview.renews': 'Se renueva el {date}',
    'overview.trialEnds': 'La prueba termina el {date}',
    'overview.periodEnds': 'El período actual termina el {date}',
    'overview.manage': 'Gestionar facturación',
    'overview.managing': 'Abriendo Paddle…',
    'overview.manageError': 'No se pudo abrir el portal de facturación seguro. Inténtalo de nuevo.',
    'overview.noSubscription': 'No hay una suscripción de pago que gestionar.',
    'overview.change': 'Cambiar plan',
    'overview.readOnly': 'Solo un Owner del workspace puede cambiar el plan o gestionar la facturación.',
    'usage.title': 'Uso y límites',
    'usage.description': 'El servidor aplica los límites. Nada se elimina automáticamente.',
    'usage.value': '{used} usados',
    'usage.limit': 'Límite {limit}',
    'usage.remaining': '{remaining} disponibles',
    'usage.unlimited': 'Ilimitado',
    'usage.percent': '{percent}% usado',
    'resource.members': 'Usuarios',
    'resource.channels': 'Canales sociales',
    'resource.scheduled_publications': 'Publicaciones programadas',
    'interval.monthly': 'Mensual',
    'interval.annual': 'Anual',
    'state.trialing': 'Prueba',
    'state.active': 'Activo',
    'state.past_due': 'Recuperación de pago',
    'state.trial_expired': 'Prueba vencida',
    'state.payment_restricted': 'Restringido por pago',
    'state.canceled': 'Cancelado',
    'common.loading': 'Cargando los detalles del plan…',
    'common.error': 'Los detalles del plan no están disponibles temporalmente.',
    'common.retry': 'Reintentar',
    'change.dialog': 'Cambiar el plan del workspace',
    'change.title': 'Comparar planes',
    'change.description': 'Elige la frecuencia de facturación y un plan. Los precios y límites proceden del catálogo actual del servidor.',
    'change.close': 'Cerrar la comparación de planes',
    'change.interval': 'Frecuencia de facturación',
    'change.annualNote': 'La facturación anual cuesta diez mensualidades y cubre doce meses.',
    'change.recommended': 'Mínimo compatible',
    'change.current': 'Actual',
    'change.select': 'Elegir {plan}',
    'change.selected': '{plan} seleccionado',
    'change.incompatible': 'No admite el uso actual',
    'change.members': '{count} usuarios',
    'change.channels': '{count} canales sociales',
    'change.posts': '{count} publicaciones programadas por canal',
    'change.unlimitedMembers': 'Usuarios ilimitados',
    'change.unlimitedChannels': 'Canales sociales ilimitados',
    'change.unlimitedPosts': 'Publicaciones programadas ilimitadas',
    'change.quantity': 'Canales incluidos',
    'change.basePrice': 'Precio base {price}',
    'change.taxNotice': 'Paddle calcula los impuestos aplicables y muestra el total oficial en la vista previa.',
    'change.preview': 'Revisar cambio',
    'change.previewing': 'Preparando vista previa…',
    'change.previewError': 'La vista previa no está disponible. No se solicitó ningún cambio.',
    'change.upgrade': 'Mejora',
    'change.downgrade': 'Reducción',
    'change.immediate': 'Entra en vigor tras el pago y el webhook verificado de Paddle.',
    'change.periodEnd': 'Entra en vigor al final del período ya pagado.',
    'change.cancelAtPeriodEnd': 'La suscripción de pago finalizará al cierre del período. Tus datos permanecen en el workspace.',
    'change.chargeNow': 'A pagar ahora: {amount}',
    'change.recurring': 'Total recurrente: {amount}',
    'change.confirm': 'Confirmar cambio de plan',
    'change.requesting': 'Solicitando cambio…',
    'change.pending': 'Cambio pendiente. El entitlement actual sigue activo hasta verificar el webhook de Paddle correspondiente.',
    'change.success': 'Cambio de plan confirmado.',
    'change.checkout': 'Continuar al pago seguro',
    'change.checkoutRequired': 'La primera suscripción de pago se crea mediante el pago seguro de Paddle.',
    'change.samePlan': 'Este plan y esta configuración de facturación ya están activos.',
    'change.inProgress': 'Ya hay otro cambio de plan pendiente. Espera a que termine antes de reintentarlo.',
    'change.conflict': 'La suscripción cambió durante la revisión. Recarga y revisa los datos más recientes.',
    'change.failure': 'No se pudo solicitar el cambio. El plan actual no ha cambiado.',
    'blocked.title': 'Reduce el uso antes de bajar de plan',
    'blocked.description': 'La reducción está bloqueada. Ajusta cada recurso al nuevo límite y vuelve a intentarlo.',
    'blocked.values': '{resource}: {used} usados, límite {limit}, excedente {excess}.',
    'blocked.members': 'Retira el acceso a {excess} usuarios antes de reintentarlo.',
    'blocked.channels': 'Desconecta {excess} canales sociales antes de reintentarlo.',
    'blocked.scheduled_publications': 'Elimina o reprograma {excess} publicaciones antes de reintentarlo.',
    'blocked.noDeletion': 'Postqron no ha eliminado, desconectado ni modificado ningún recurso.',
  },
  fr: {
    'document.title': 'Abonnement et utilisation',
    'overview.eyebrow': 'Abonnement',
    'overview.title': 'Abonnement et utilisation',
    'overview.description': 'Consultez votre abonnement, l’utilisation et la capacité disponible.',
    'overview.current': 'Abonnement actuel',
    'overview.interval': 'Facturation',
    'overview.channels': 'Nombre de canaux',
    'overview.price': 'Prix de base actuel',
    'overview.free': 'Gratuit',
    'overview.renews': 'Renouvellement le {date}',
    'overview.trialEnds': 'L’essai se termine le {date}',
    'overview.periodEnds': 'La période actuelle se termine le {date}',
    'overview.manage': 'Gérer la facturation',
    'overview.managing': 'Ouverture de Paddle…',
    'overview.manageError': 'Impossible d’ouvrir le portail de facturation sécurisé. Réessayez.',
    'overview.noSubscription': 'Aucun abonnement payant à gérer.',
    'overview.change': 'Changer d’abonnement',
    'overview.readOnly': 'Seul un Owner du workspace peut changer d’abonnement ou gérer la facturation.',
    'usage.title': 'Utilisation et limites',
    'usage.description': 'Les limites sont appliquées par le serveur. Rien n’est supprimé automatiquement.',
    'usage.value': '{used} utilisés',
    'usage.limit': 'Limite {limit}',
    'usage.remaining': '{remaining} disponibles',
    'usage.unlimited': 'Illimité',
    'usage.percent': '{percent}% utilisé',
    'resource.members': 'Utilisateurs',
    'resource.channels': 'Canaux sociaux',
    'resource.scheduled_publications': 'Publications programmées',
    'interval.monthly': 'Mensuel',
    'interval.annual': 'Annuel',
    'state.trialing': 'Essai',
    'state.active': 'Actif',
    'state.past_due': 'Récupération du paiement',
    'state.trial_expired': 'Essai expiré',
    'state.payment_restricted': 'Paiement restreint',
    'state.canceled': 'Annulé',
    'common.loading': 'Chargement des détails de l’abonnement…',
    'common.error': 'Les détails de l’abonnement sont temporairement indisponibles.',
    'common.retry': 'Réessayer',
    'change.dialog': 'Changer l’abonnement du workspace',
    'change.title': 'Comparer les abonnements',
    'change.description': 'Choisissez la fréquence de facturation et un abonnement. Les prix et limites proviennent du catalogue actuel du serveur.',
    'change.close': 'Fermer la comparaison des abonnements',
    'change.interval': 'Fréquence de facturation',
    'change.annualNote': 'La facturation annuelle coûte dix mensualités et couvre douze mois.',
    'change.recommended': 'Minimum compatible',
    'change.current': 'Actuel',
    'change.select': 'Choisir {plan}',
    'change.selected': '{plan} sélectionné',
    'change.incompatible': 'Incompatible avec l’utilisation actuelle',
    'change.members': '{count} utilisateurs',
    'change.channels': '{count} canaux sociaux',
    'change.posts': '{count} publications programmées par canal',
    'change.unlimitedMembers': 'Utilisateurs illimités',
    'change.unlimitedChannels': 'Canaux sociaux illimités',
    'change.unlimitedPosts': 'Publications programmées illimitées',
    'change.quantity': 'Canaux inclus',
    'change.basePrice': 'Prix de base {price}',
    'change.taxNotice': 'Paddle calcule les taxes applicables et affiche le total officiel dans l’aperçu.',
    'change.preview': 'Vérifier la modification',
    'change.previewing': 'Préparation de l’aperçu…',
    'change.previewError': 'L’aperçu est indisponible. Aucune modification n’a été demandée.',
    'change.upgrade': 'Mise à niveau',
    'change.downgrade': 'Rétrogradation',
    'change.immediate': 'Prend effet après paiement et vérification du webhook Paddle.',
    'change.periodEnd': 'Prend effet à la fin de la période déjà payée.',
    'change.cancelAtPeriodEnd': 'L’abonnement payant prendra fin à la clôture de la période. Vos données restent dans le workspace.',
    'change.chargeNow': 'À payer maintenant : {amount}',
    'change.recurring': 'Total récurrent : {amount}',
    'change.confirm': 'Confirmer le changement',
    'change.requesting': 'Demande en cours…',
    'change.pending': 'Modification en attente. L’entitlement actuel reste actif jusqu’à la vérification du webhook Paddle correspondant.',
    'change.success': 'Changement d’abonnement confirmé.',
    'change.checkout': 'Continuer vers le paiement sécurisé',
    'change.checkoutRequired': 'Le premier abonnement payant est créé via le paiement sécurisé Paddle.',
    'change.samePlan': 'Cet abonnement et cette configuration de facturation sont déjà actifs.',
    'change.inProgress': 'Un autre changement est déjà en attente. Attendez sa fin avant de réessayer.',
    'change.conflict': 'L’abonnement a changé pendant la vérification. Rechargez et vérifiez les dernières informations.',
    'change.failure': 'Le changement n’a pas pu être demandé. L’abonnement actuel est inchangé.',
    'blocked.title': 'Réduisez l’utilisation avant la rétrogradation',
    'blocked.description': 'La rétrogradation est bloquée. Respectez chaque nouvelle limite, puis réessayez.',
    'blocked.values': '{resource} : {used} utilisés, limite {limit}, dépassement {excess}.',
    'blocked.members': 'Retirez l’accès à {excess} utilisateurs avant de réessayer.',
    'blocked.channels': 'Déconnectez {excess} canaux sociaux avant de réessayer.',
    'blocked.scheduled_publications': 'Supprimez ou reprogrammez {excess} publications avant de réessayer.',
    'blocked.noDeletion': 'Postqron n’a supprimé, déconnecté ni modifié aucune ressource.',
  },
  de: {
    'document.title': 'Tarif und Nutzung',
    'overview.eyebrow': 'Tarif',
    'overview.title': 'Tarif und Nutzung',
    'overview.description': 'Prüfe deinen aktuellen Tarif, die Nutzung und die verfügbare Kapazität.',
    'overview.current': 'Aktueller Tarif',
    'overview.interval': 'Abrechnung',
    'overview.channels': 'Kanalanzahl',
    'overview.price': 'Aktueller Basispreis',
    'overview.free': 'Kostenlos',
    'overview.renews': 'Verlängerung am {date}',
    'overview.trialEnds': 'Testphase endet am {date}',
    'overview.periodEnds': 'Aktueller Zeitraum endet am {date}',
    'overview.manage': 'Abrechnung verwalten',
    'overview.managing': 'Paddle wird geöffnet…',
    'overview.manageError': 'Das sichere Abrechnungsportal konnte nicht geöffnet werden. Versuche es erneut.',
    'overview.noSubscription': 'Es gibt kein kostenpflichtiges Abonnement zu verwalten.',
    'overview.change': 'Tarif wechseln',
    'overview.readOnly': 'Nur ein Workspace-Owner kann den Tarif wechseln oder die Abrechnung verwalten.',
    'usage.title': 'Nutzung und Limits',
    'usage.description': 'Limits werden vom Server durchgesetzt. Nichts wird automatisch entfernt.',
    'usage.value': '{used} genutzt',
    'usage.limit': 'Limit {limit}',
    'usage.remaining': '{remaining} verfügbar',
    'usage.unlimited': 'Unbegrenzt',
    'usage.percent': '{percent}% genutzt',
    'resource.members': 'Benutzer',
    'resource.channels': 'Social-Media-Kanäle',
    'resource.scheduled_publications': 'Geplante Beiträge',
    'interval.monthly': 'Monatlich',
    'interval.annual': 'Jährlich',
    'state.trialing': 'Testphase',
    'state.active': 'Aktiv',
    'state.past_due': 'Zahlungswiederherstellung',
    'state.trial_expired': 'Testphase abgelaufen',
    'state.payment_restricted': 'Wegen Zahlung eingeschränkt',
    'state.canceled': 'Gekündigt',
    'common.loading': 'Tarifdetails werden geladen…',
    'common.error': 'Tarifdetails sind vorübergehend nicht verfügbar.',
    'common.retry': 'Erneut versuchen',
    'change.dialog': 'Workspace-Tarif wechseln',
    'change.title': 'Tarife vergleichen',
    'change.description': 'Wähle Abrechnung und Tarif. Preise und Limits stammen aus dem aktuellen Serverkatalog.',
    'change.close': 'Tarifvergleich schließen',
    'change.interval': 'Abrechnungszeitraum',
    'change.annualNote': 'Jährliche Abrechnung kostet zehn Monatsraten und deckt zwölf Monate ab.',
    'change.recommended': 'Kleinster passender Tarif',
    'change.current': 'Aktuell',
    'change.select': '{plan} wählen',
    'change.selected': '{plan} ausgewählt',
    'change.incompatible': 'Passt nicht zur aktuellen Nutzung',
    'change.members': '{count} Benutzer',
    'change.channels': '{count} Social-Media-Kanäle',
    'change.posts': '{count} geplante Beiträge pro Kanal',
    'change.unlimitedMembers': 'Unbegrenzte Benutzer',
    'change.unlimitedChannels': 'Unbegrenzte Social-Media-Kanäle',
    'change.unlimitedPosts': 'Unbegrenzte geplante Beiträge',
    'change.quantity': 'Enthaltene Kanäle',
    'change.basePrice': 'Basispreis {price}',
    'change.taxNotice': 'Paddle berechnet anfallende Steuern und zeigt die verbindliche Summe in der Vorschau.',
    'change.preview': 'Änderung prüfen',
    'change.previewing': 'Vorschau wird vorbereitet…',
    'change.previewError': 'Die Vorschau ist nicht verfügbar. Es wurde keine Änderung angefordert.',
    'change.upgrade': 'Upgrade',
    'change.downgrade': 'Downgrade',
    'change.immediate': 'Wird nach Zahlung und verifiziertem Paddle-Webhook wirksam.',
    'change.periodEnd': 'Wird am Ende des bereits bezahlten Zeitraums wirksam.',
    'change.cancelAtPeriodEnd': 'Das bezahlte Abonnement endet zum Periodenende. Deine Daten bleiben im Workspace.',
    'change.chargeNow': 'Jetzt fällig: {amount}',
    'change.recurring': 'Wiederkehrende Summe: {amount}',
    'change.confirm': 'Tarifwechsel bestätigen',
    'change.requesting': 'Änderung wird angefordert…',
    'change.pending': 'Änderung ausstehend. Das aktuelle Entitlement bleibt bis zum verifizierten Paddle-Webhook aktiv.',
    'change.success': 'Tarifwechsel bestätigt.',
    'change.checkout': 'Zum sicheren Checkout',
    'change.checkoutRequired': 'Das erste bezahlte Abonnement wird über den sicheren Paddle-Checkout erstellt.',
    'change.samePlan': 'Dieser Tarif und diese Abrechnung sind bereits aktiv.',
    'change.inProgress': 'Ein anderer Tarifwechsel ist bereits ausstehend. Warte vor einem neuen Versuch.',
    'change.conflict': 'Das Abonnement wurde während der Prüfung geändert. Lade neu und prüfe die aktuellen Angaben.',
    'change.failure': 'Der Tarifwechsel konnte nicht angefordert werden. Der aktuelle Tarif bleibt unverändert.',
    'blocked.title': 'Nutzung vor dem Downgrade reduzieren',
    'blocked.description': 'Das Downgrade ist blockiert. Halte jedes neue Limit ein und versuche es erneut.',
    'blocked.values': '{resource}: {used} genutzt, Limit {limit}, {excess} zu viel.',
    'blocked.members': 'Entziehe {excess} Benutzern den Zugriff, bevor du es erneut versuchst.',
    'blocked.channels': 'Trenne {excess} Social-Media-Kanäle, bevor du es erneut versuchst.',
    'blocked.scheduled_publications': 'Entferne oder verschiebe {excess} geplante Beiträge, bevor du es erneut versuchst.',
    'blocked.noDeletion': 'Postqron hat keine Ressource gelöscht, getrennt oder verändert.',
  },
})

export type BillingPlanMessageKey = keyof typeof BILLING_PLAN_CATALOGS.en
