import type { DashboardContent } from '~/types/content'

/** Testi della dashboard in tedesco, tradotti da `content/en.ts`. */
export const de: DashboardContent = {
  shell: {
    languageLabel: 'Sprache',
    skipToContent: 'Zum Inhalt springen',
    navigationLabel: 'Hauptnavigation',
    openNavigation: 'Navigation öffnen',
    closeNavigation: 'Navigation schließen',
    nav: {
      jobs: 'Cronjobs',
      overview: 'Übersicht',
    },
    toLightTheme: 'Zum hellen Design wechseln',
    toDarkTheme: 'Zum dunklen Design wechseln',
    account: {
      open: 'Kontomenü',
      signedInAs: 'Angemeldet als',
      signOut: 'Abmelden',
    },
  },

  status: {
    loading: 'Wird geladen…',
    errorTitle: 'Etwas ist schiefgelaufen',
    retry: 'Erneut versuchen',
    errors: {
      network: 'Das Backend hat nicht geantwortet. Prüfe die Verbindung und versuche es erneut.',
      unauthorized: 'Deine Sitzung ist abgelaufen. Melde dich erneut an, um fortzufahren.',
      forbidden: 'Du hast keinen Zugriff darauf.',
      notFound: 'Das ist nicht mehr vorhanden.',
      invalid: 'Die Anfrage wurde abgelehnt. Prüfe deine Eingaben.',
      server: 'Im Backend ist ein Problem aufgetreten. Versuche es gleich noch einmal.',
    },
  },

  home: {
    title: 'Übersicht',
    intro: 'Der Postqron-Dienst, der deine Cronjobs ausführt — und ob er antwortet.',
    backendTitle: 'Zustand des Dienstes',
    apiBaseLabel: 'Basisadresse der API',
    statusLabel: 'Status',
    environmentLabel: 'Umgebung',
    versionLabel: 'Version',
    check: 'Erneut prüfen',
  },

  notFound: {
    title: 'Seite nicht gefunden',
    intro: 'Diese Adresse gehört zu keiner Ansicht des Dashboards. Sie hat sich vielleicht geändert, oder der Link ist falsch.',
    back: 'Zurück zur Übersicht',
  },

  auth: {
    signIn: {
      title: 'Anmelden',
      submit: 'Anmelden',
      submitting: 'Anmeldung läuft…',
      noAccount: 'Noch kein Konto?',
      noAccountLink: 'Jetzt erstellen',
      interrupted: 'Deine Sitzung ist beendet. Melde dich erneut an, um dort weiterzumachen, wo du warst.',
      returningTo: 'Du kommst zurück auf die Seite, die du aufgerufen hattest.',
    },
    signUp: {
      title: 'Konto erstellen',
      submit: 'Konto erstellen',
      submitting: 'Wird erstellt…',
      haveAccount: 'Du hast schon ein Konto?',
      haveAccountLink: 'Anmelden',
      acceptedTitle: 'Sieh in deinem Postfach nach',
      acceptedBody: 'Falls die Adresse verwendbar ist, haben wir eine E-Mail mit den nächsten Schritten geschickt.',
      acceptedSignIn: 'Zur Anmeldung',
    },
    fields: {
      email: 'E-Mail',
      password: 'Passwort',
      fullName: 'Vor- und Nachname',
      passwordHint: 'Mindestens 12 Zeichen.',
    },
    errors: {
      credentials: 'E-Mail oder Passwort sind nicht korrekt.',
      tooManyAttempts: 'Zu viele Versuche. Warte ein paar Minuten und versuche es erneut.',
      suspended: 'Dieses Konto ist gesperrt. Wende dich an den Support.',
      invalidEmail: 'Diese E-Mail-Adresse ist ungültig.',
      weakPassword: 'Dieses Passwort erfüllt die Anforderung oben nicht.',
      unexpected: 'Die Anfrage konnte nicht abgeschlossen werden. Versuche es gleich noch einmal.',
      required: 'Fülle dieses Feld aus.',
    },
  },

  jobs: {
    list: {
      title: 'Cronjobs',
      intro: 'Alles, was Postqron für dich ausführt — und wann es das nächste Mal läuft.',
      create: 'Neuer Cronjob',
      empty: 'Noch keine Cronjobs.',
      emptyHint: 'Lege einen an, und er läuft in dem Takt, den du wählst.',

      columnName: 'Name',
      columnSchedule: 'Zeitplan',
      columnNextRun: 'Nächster Lauf',
      columnState: 'Zustand',
      columnActions: 'Aktionen',

      nextRunPending: 'Wartet auf den Planer',
      nextRunNone: 'Keiner',

      edit: 'Bearbeiten',
      runNow: 'Jetzt ausführen',
      running: 'Wird gestartet…',
      runQueued: 'Lauf vorgemerkt. Die Engine ruft das Ziel gleich auf.',
      pause: 'Pausieren',
      resume: 'Fortsetzen',
      delete: 'Löschen',
      deleteTitle: 'Diesen Cronjob löschen?',
      deleteBody: 'Der Job und seine Ausführungshistorie verschwinden. Das lässt sich nicht rückgängig machen.',
      deleteConfirm: 'Löschen',
      deleteCancel: 'Behalten',
    },

    form: {
      createTitle: 'Neuer Cronjob',
      editTitle: 'Cronjob bearbeiten',
      save: 'Speichern',
      saving: 'Wird gespeichert…',
      saved: 'Gespeichert',
      cancel: 'Abbrechen',
      back: 'Zurück zu den Cronjobs',

      sectionIdentity: 'Identität',
      sectionSchedule: 'Zeitplan',
      sectionTarget: 'Ziel',
      sectionExecution: 'Ausführung',
      sectionAlerts: 'Benachrichtigungen',

      managedTitle: 'Dieser Job ist in deinem Repository definiert',
      managedBody: 'Bearbeite ihn in der cron.yaml, aus der er stammt. Eine Änderung hier würde beim nächsten Push zurückgenommen, ohne Fehlermeldung. Pausieren kannst du ihn trotzdem.',

      invalidTitle: 'Einige Felder brauchen noch einen Blick, bevor gespeichert werden kann.',
      nameTaken: 'Du hast bereits einen Job mit diesem Namen. Der Name ist die feste Identität des Jobs.',
      unexpected: 'Der Job konnte nicht gespeichert werden. Versuche es gleich noch einmal.',
    },

    fields: {
      name: 'Name',
      nameHint: 'Buchstaben, Ziffern, Punkt, Bindestrich und Unterstrich. Er ist die feste Identität des Jobs: ihn umzubenennen heißt, ihn zu löschen und einen anderen anzulegen.',
      description: 'Beschreibung',
      optional: 'Optional',

      mode: 'Wie oft',
      modeCron: 'Cron-Ausdruck',
      modeInterval: 'Fester Abstand',
      schedule: 'Cron-Ausdruck',
      scheduleHint: 'Fünf Felder: Minute, Stunde, Tag des Monats, Monat, Wochentag.',
      every: 'Alle',
      everyUnit: 'Einheit',
      timezone: 'Zeitzone',
      timezoneHint: 'Die Zeitzone des Jobs, nicht die deines Browsers. Die Sommerzeitwechsel werden in ihr aufgelöst.',

      environments: 'Umgebungen',
      url: 'URL',
      method: 'Methode',
      headers: 'Header',
      headerName: 'Header-Name',
      headerValue: 'Header-Wert',
      addHeader: 'Header hinzufügen',
      removeHeader: 'Diesen Header entfernen',
      body: 'Anfrage-Body',

      timeout: 'Zeitlimit (Sekunden)',
      timeoutHint: 'Wie lange auf das Ziel gewartet wird, bevor aufgegeben wird.',
      retries: 'Wiederholungen',
      backoff: 'Wartezeit zwischen Versuchen',
      overlap: 'Wenn der vorige Lauf noch läuft',
      overlapHint: 'Bei Zeitplänen unterhalb einer Minute ist das kein Sonderfall, sondern der Normalfall.',
      alerts: 'Bescheid geben, wenn er fehlschlägt',
      enabled: 'Aktiv',
      enabledHint: 'Ein pausierter Job behält seine Historie und läuft nicht mehr.',
    },

    options: {
      backoff: {
        exponential: 'Exponentiell',
        linear: 'Linear',
        fixed: 'Fest',
      },
      overlap: {
        skip: 'Neuen Lauf überspringen',
        queue: 'In die Warteschlange stellen',
        allow: 'Beide laufen lassen',
      },
      overlapHint: {
        skip: 'Der Termin wird als übersprungen verbucht, mit Grund. Nichts läuft doppelt.',
        queue: 'Die Läufe bleiben in Reihe. Ein Job, der langsamer ist als sein eigener Abstand, baut Rückstand auf.',
        allow: 'Beide Aufrufe gehen gemeinsam raus. Ein Ziel, das pro Aufruf abrechnet, würde doppelt abrechnen.',
      },
      alerts: {
        email: 'E-Mail',
        slack: 'Slack',
        discord: 'Discord',
        webhook: 'Webhook',
      },
      environments: {
        staging: 'Staging',
        production: 'Produktion',
      },
      everyUnits: {
        s: 'Sekunden',
        m: 'Minuten',
        h: 'Stunden',
      },
    },

    preview: {
      title: 'Nächste Läufe',
      inTimezone: 'Zeiten in {zone}, der Zeitzone des Jobs.',
      epochAnchored: 'Abstände hängen an der Unix-Epoche, nicht am Zeitpunkt des Speicherns: alle 1h heißt zur vollen UTC-Stunde.',
      never: 'Dieser Ausdruck tritt nie ein. Prüfe den Tag und den Monat, die du angegeben hast.',
      invalid: 'Korrigiere den Zeitplan, um zu sehen, wann der Job liefe.',
      shifted: 'Diese Uhrzeit gibt es an dem Tag nicht — die Uhr springt darüber hinweg. Der Job läuft im ersten Augenblick, den es gibt.',
      ambiguous: 'Diese Uhrzeit gibt es an dem Tag zweimal. Der Job läuft nur beim ersten Mal.',
      scheduled: 'Vom Planer berechnet',
    },

    plan: {
      title: 'Dein Tarif',
      jobsUsed: 'Cronjobs: {used} von {limit}',
      jobsUnlimited: 'Cronjobs: {used}, ohne harte Obergrenze',
      jobsFull: 'Der Tarif ist voll. Lösche einen Job oder wechsle in einen größeren Tarif, bevor du einen weiteren anlegst.',
      minInterval: 'Kürzester Abstand: {value}',
      retention: 'Ausführungsprotokolle {days} Tage aufbewahrt',

      suspendedTitle: 'Ein Tarifwechsel hat einige Jobs angehalten',
      suspendedByJobLimit: 'Angehalten, weil der Tarif voll war: {count}. Schalte so viele wieder ein, wie der Tarif erlaubt — welche, entscheidest du, und niemand sonst kann das.',
      suspendedByResolution: 'Angehalten, weil sie öfter laufen als {value}: {count}. Ändere ihren Zeitplan, um sie zurückzuholen.',
      resolutionBlocked: 'Dieser Job läuft öfter als {value}, und so viel erlaubt dein Tarif. Ändere zuerst seinen Zeitplan: einen Platz woanders freizumachen holt ihn nicht zurück.',

      limitJobs: 'Der Tarif ist voll. Lösche einen Job oder wechsle in einen größeren Tarif.',
      limitResolution: 'Der Tarif {plan} führt Jobs höchstens alle {value} aus. Vergrößere den Abstand, oder wechsle in einen größeren Tarif.',
      limitEnvironments: 'Dein Tarif hat eine einzige Umgebung. Staging braucht einen größeren Tarif.',
      upgrade: 'Tarife ansehen',
    },

    state: {
      active: 'Aktiv',
      paused: 'Pausiert',
      suspendedByJobLimit: 'Durch Tarifwechsel angehalten',
      suspendedByResolution: 'Zu häufig für den Tarif',
      archived: 'Archiviert',
      managed: 'Aus einem Repository',
    },

    errors: {
      required: 'Dieses Feld ist erforderlich.',
      tooLong: 'Höchstens {limit} Zeichen.',
      invalidName: 'Nur Buchstaben, Ziffern, Punkt, Bindestrich und Unterstrich, am Anfang und am Ende ein Buchstabe oder eine Ziffer.',
      invalidUrl: 'Das ist keine lesbare Adresse.',
      unsupportedScheme: 'Aufgerufen werden können nur http- und https-Adressen.',
      invalidHeaderName: 'Das ist kein gültiger Header-Name.',
      reservedHeader: '{value} bestimmt der Ausführer; der Job kann ihn nicht setzen.',
      duplicateHeader: '{value} kommt zweimal vor. Nur einer der beiden würde gesendet.',
      headerNewline: 'Ein Header-Wert darf keinen Zeilenumbruch enthalten.',
      tooManyHeaders: 'Höchstens {limit} Header.',
      headerTooLong: '{value} überschreitet die erlaubten {limit} Zeichen.',
      bodyTooLong: 'Der Body überschreitet {limit} Byte.',
      timeoutRange: 'Das Zeitlimit reicht von {min} bis {max} Sekunden.',
      timeoutWhole: 'Das Zeitlimit muss eine ganze Zahl von Sekunden sein.',
      retriesRange: 'Wiederholungen reichen von 0 bis {limit}.',
      environmentsRequired: 'Wähle mindestens eine Umgebung.',
      scheduleRequired: 'Schreibe einen Cron-Ausdruck, oder wechsle zum festen Abstand.',
      scheduleConflict: 'Ein Cron-Ausdruck und ein Abstand schließen einander aus.',
      scheduleMacro: 'Kurzformen wie @daily werden nicht angenommen. Schreibe die fünf Felder.',
      scheduleFieldCount: 'Ein Cron-Ausdruck hat fünf Felder: Minute, Stunde, Tag des Monats, Monat, Wochentag.',
      scheduleField: '{value} ist kein Wert, den dieses Feld annimmt.',
      unknownTimezone: '{value} ist kein bekannter Zeitzonenname.',
      localTimezone: 'Ein Job braucht eine ausdrückliche Zeitzone, nicht die der Maschine, die ihn ausführt.',
      invalidInterval: 'Der Abstand muss eine ganze Zahl von Sekunden sein, mindestens eine.',
      targetNotAllowed: 'Diese Adresse kann von Postqron nicht aufgerufen werden.',
      nameTaken: 'Du hast bereits einen Job mit diesem Namen.',
      rejected: 'Der Server hat dieses Feld abgelehnt.',
    },
  },
}
