import type { DashboardContent } from '~/types/content'

/** Testi della dashboard in spagnolo, tradotti da `content/en.ts`. */
export const es: DashboardContent = {
  shell: {
    languageLabel: 'Idioma',
    skipToContent: 'Ir al contenido',
    navigationLabel: 'Navegación principal',
    openNavigation: 'Abrir la navegación',
    closeNavigation: 'Cerrar la navegación',
    nav: {
      jobs: 'Cron jobs',
      overview: 'Resumen',
    },
    toLightTheme: 'Cambiar al tema claro',
    toDarkTheme: 'Cambiar al tema oscuro',
    account: {
      open: 'Menú de la cuenta',
      signedInAs: 'Sesión iniciada como',
      signOut: 'Cerrar sesión',
    },
  },

  status: {
    loading: 'Cargando…',
    errorTitle: 'Algo ha fallado',
    retry: 'Reintentar',
    errors: {
      network: 'El backend no ha respondido. Comprueba la conexión y vuelve a intentarlo.',
      unauthorized: 'Tu sesión ha caducado. Vuelve a iniciar sesión para continuar.',
      forbidden: 'No tienes acceso a este recurso.',
      notFound: 'Este recurso ya no existe.',
      invalid: 'La solicitud ha sido rechazada. Revisa los datos introducidos.',
      server: 'El backend ha tenido un problema. Inténtalo de nuevo en un momento.',
    },
  },

  home: {
    title: 'Resumen',
    intro: 'El servicio Postqron que ejecuta tus tareas programadas, y si está respondiendo.',
    backendTitle: 'Estado del servicio',
    apiBaseLabel: 'Dirección base de la API',
    statusLabel: 'Estado',
    environmentLabel: 'Entorno',
    versionLabel: 'Versión',
    check: 'Comprobar de nuevo',
  },

  notFound: {
    title: 'Página no encontrada',
    intro: 'Esta dirección no corresponde a ninguna pantalla del panel. Puede que haya cambiado, o que el enlace sea incorrecto.',
    back: 'Volver al resumen',
  },

  auth: {
    signIn: {
      title: 'Iniciar sesión',
      submit: 'Iniciar sesión',
      submitting: 'Iniciando sesión…',
      noAccount: '¿Todavía no tienes cuenta?',
      noAccountLink: 'Crea una',
      interrupted: 'Tu sesión ha terminado. Vuelve a iniciar sesión para retomar donde lo dejaste.',
      returningTo: 'Volverás a la página que habías pedido.',
    },
    signUp: {
      title: 'Crear una cuenta',
      submit: 'Crear cuenta',
      submitting: 'Creando…',
      haveAccount: '¿Ya tienes una cuenta?',
      haveAccountLink: 'Inicia sesión',
      acceptedTitle: 'Revisa tu correo',
      acceptedBody: 'Si la dirección se puede utilizar, hemos enviado un correo con las instrucciones.',
      acceptedSignIn: 'Ir al inicio de sesión',
    },
    fields: {
      email: 'Correo electrónico',
      password: 'Contraseña',
      fullName: 'Nombre y apellidos',
      passwordHint: 'Al menos 12 caracteres.',
    },
    errors: {
      credentials: 'El correo o la contraseña no son correctos.',
      tooManyAttempts: 'Demasiados intentos. Espera unos minutos y vuelve a intentarlo.',
      suspended: 'Esta cuenta está suspendida. Contacta con soporte.',
      invalidEmail: 'Esta dirección de correo no es válida.',
      weakPassword: 'Esta contraseña no cumple el requisito de arriba.',
      unexpected: 'No se ha podido completar la solicitud. Inténtalo de nuevo en un momento.',
      required: 'Rellena este campo.',
    },
  },

  jobs: {
    list: {
      title: 'Cron jobs',
      intro: 'Todo lo que Postqron ejecuta por ti, y cuándo lo ejecuta la próxima vez.',
      create: 'Nuevo cron job',
      empty: 'Todavía no hay ningún cron job.',
      emptyHint: 'Crea uno y empezará a ejecutarse con la frecuencia que elijas.',

      columnName: 'Nombre',
      columnSchedule: 'Programación',
      columnNextRun: 'Próxima ejecución',
      columnState: 'Estado',
      columnActions: 'Acciones',

      nextRunPending: 'Pendiente del planificador',
      nextRunNone: 'Ninguna',

      edit: 'Editar',
      runNow: 'Ejecutar ahora',
      running: 'Iniciando…',
      runQueued: 'Ejecución registrada. El motor llamará al destino en un momento.',
      pause: 'Pausar',
      resume: 'Reanudar',
      delete: 'Eliminar',
      deleteTitle: '¿Eliminar este cron job?',
      deleteBody: 'Desaparecen el job y su historial de ejecuciones. No se puede deshacer.',
      deleteConfirm: 'Eliminar',
      deleteCancel: 'Conservarlo',
    },

    form: {
      createTitle: 'Nuevo cron job',
      editTitle: 'Editar cron job',
      save: 'Guardar',
      saving: 'Guardando…',
      saved: 'Guardado',
      cancel: 'Cancelar',
      back: 'Volver a los cron jobs',

      sectionIdentity: 'Identidad',
      sectionSchedule: 'Programación',
      sectionTarget: 'Destino',
      sectionExecution: 'Ejecución',
      sectionAlerts: 'Avisos',

      managedTitle: 'Este job está definido en tu repositorio',
      managedBody: 'Edítalo en el cron.yaml del que procede. Un cambio hecho aquí se revertiría en el siguiente push, sin ningún error. Aun así puedes pausarlo.',

      invalidTitle: 'Hay campos que revisar antes de poder guardar.',
      nameTaken: 'Ya tienes un job con este nombre. El nombre es la identidad estable del job.',
      unexpected: 'No se ha podido guardar el job. Inténtalo de nuevo en un momento.',
    },

    fields: {
      name: 'Nombre',
      nameHint: 'Letras, dígitos, punto, guion y guion bajo. Es la identidad estable del job: renombrarlo equivale a borrarlo y crear otro.',
      description: 'Descripción',
      optional: 'Opcional',

      mode: 'Cada cuánto',
      modeCron: 'Expresión cron',
      modeInterval: 'Intervalo fijo',
      schedule: 'Expresión cron',
      scheduleHint: 'Cinco campos: minuto, hora, día del mes, mes, día de la semana.',
      every: 'Cada',
      everyUnit: 'Unidad',
      timezone: 'Zona horaria',
      timezoneHint: 'La zona del job, no la de tu navegador. Los cambios de horario de verano se resuelven en ella.',

      environments: 'Entornos',
      url: 'URL',
      method: 'Método',
      headers: 'Cabeceras',
      headerName: 'Nombre de la cabecera',
      headerValue: 'Valor de la cabecera',
      addHeader: 'Añadir una cabecera',
      removeHeader: 'Quitar esta cabecera',
      body: 'Cuerpo de la petición',

      timeout: 'Tiempo de espera (segundos)',
      timeoutHint: 'Cuánto esperar al destino antes de rendirse.',
      retries: 'Reintentos',
      backoff: 'Espera entre reintentos',
      overlap: 'Si la ejecución anterior sigue en curso',
      overlapHint: 'Con programaciones por debajo del minuto no es un caso raro, es la norma.',
      alerts: 'Avísame cuando falle',
      enabled: 'Activo',
      enabledHint: 'Un job pausado conserva su historial y deja de ejecutarse.',
    },

    options: {
      backoff: {
        exponential: 'Exponencial',
        linear: 'Lineal',
        fixed: 'Fija',
      },
      overlap: {
        skip: 'Saltar la nueva ejecución',
        queue: 'Ponerla en cola',
        allow: 'Ejecutar ambas',
      },
      overlapHint: {
        skip: 'La ocurrencia se registra como saltada, con el motivo. Nada se ejecuta dos veces.',
        queue: 'Las ejecuciones quedan en fila. Un job más lento que su propio intervalo acumula atrasos.',
        allow: 'Las dos llamadas salen a la vez. Un destino que factura por llamada facturaría dos veces.',
      },
      alerts: {
        email: 'Correo',
        slack: 'Slack',
        discord: 'Discord',
        webhook: 'Webhook',
      },
      environments: {
        staging: 'Staging',
        production: 'Producción',
      },
      everyUnits: {
        s: 'segundos',
        m: 'minutos',
        h: 'horas',
      },
    },

    preview: {
      title: 'Próximas ejecuciones',
      inTimezone: 'Horas en {zone}, la zona horaria del job.',
      epochAnchored: 'Los intervalos se anclan al epoch de Unix, no al momento en que guardas: cada 1h salta en la hora en punto UTC.',
      never: 'Esta expresión no llega nunca. Revisa el día y el mes que has pedido.',
      invalid: 'Corrige la programación para ver cuándo se ejecutaría el job.',
      shifted: 'Esa hora de reloj no existe ese día: el reloj la salta. El job se ejecuta en el primer instante que sí existe.',
      ambiguous: 'Esa hora de reloj ocurre dos veces ese día. El job se ejecuta solo en la primera.',
      scheduled: 'Calculada por el planificador',
    },

    plan: {
      title: 'Tu plan',
      jobsUsed: 'Cron jobs: {used} de {limit}',
      jobsUnlimited: 'Cron jobs: {used}, sin tope rígido',
      jobsFull: 'El plan está lleno. Elimina un job, o pasa a un plan mayor, antes de crear otro.',
      minInterval: 'Intervalo mínimo: {value}',
      retention: 'Registros de ejecución conservados {days} días',

      suspendedTitle: 'Un cambio de plan ha detenido algunos jobs',
      suspendedByJobLimit: 'Detenidos porque el plan estaba lleno: {count}. Reactiva tantos como permita el plan — cuáles, lo decides tú, y nadie más puede hacerlo.',
      suspendedByResolution: 'Detenidos porque se ejecutan más a menudo de {value}: {count}. Cambia su programación para recuperarlos.',
      resolutionBlocked: 'Este job se ejecuta más a menudo de {value}, que es lo que permite tu plan. Cambia antes su programación: liberar un hueco en otro sitio no lo reactiva.',

      limitJobs: 'El plan está lleno. Elimina un job, o pasa a un plan mayor.',
      limitResolution: 'El plan {plan} ejecuta los jobs no más a menudo de {value}. Amplía el intervalo, o pasa a un plan mayor.',
      limitEnvironments: 'Tu plan tiene un único entorno. Staging necesita un plan mayor.',
      upgrade: 'Ver los planes',
    },

    state: {
      active: 'Activo',
      paused: 'En pausa',
      suspendedByJobLimit: 'Detenido por un cambio de plan',
      suspendedByResolution: 'Demasiado frecuente para el plan',
      archived: 'Archivado',
      managed: 'De un repositorio',
    },

    errors: {
      required: 'Este campo es obligatorio.',
      tooLong: 'Como mucho {limit} caracteres.',
      invalidName: 'Solo letras, dígitos, punto, guion y guion bajo, empezando y terminando por una letra o un dígito.',
      invalidUrl: 'Esto no es una dirección legible.',
      unsupportedScheme: 'Solo se pueden llamar direcciones http y https.',
      invalidHeaderName: 'Esto no es un nombre de cabecera válido.',
      reservedHeader: '{value} lo decide el ejecutor y el job no puede declararlo.',
      duplicateHeader: '{value} aparece dos veces. Solo se enviaría una de las dos.',
      headerNewline: 'El valor de una cabecera no puede contener un salto de línea.',
      tooManyHeaders: 'Como mucho {limit} cabeceras.',
      headerTooLong: '{value} supera los {limit} caracteres permitidos.',
      bodyTooLong: 'El cuerpo supera {limit} bytes.',
      timeoutRange: 'El tiempo de espera va de {min} a {max} segundos.',
      timeoutWhole: 'El tiempo de espera debe ser un número entero de segundos.',
      retriesRange: 'Los reintentos van de 0 a {limit}.',
      environmentsRequired: 'Elige al menos un entorno.',
      scheduleRequired: 'Escribe una expresión cron, o cambia al intervalo fijo.',
      scheduleConflict: 'Una expresión cron y un intervalo no pueden convivir.',
      scheduleMacro: 'Las abreviaturas como @daily no se aceptan. Escribe los cinco campos.',
      scheduleFieldCount: 'Una expresión cron tiene cinco campos: minuto, hora, día del mes, mes, día de la semana.',
      scheduleField: '{value} no es un valor que este campo acepte.',
      unknownTimezone: '{value} no es el nombre de una zona horaria conocida.',
      localTimezone: 'Un job necesita una zona horaria explícita, no la de la máquina que lo ejecuta.',
      invalidInterval: 'El intervalo debe ser un número entero de segundos, al menos uno.',
      targetNotAllowed: 'Esta dirección no puede llamarse desde Postqron.',
      nameTaken: 'Ya tienes un job con este nombre.',
      rejected: 'El servidor ha rechazado este campo.',
    },
  },
}
