import type { DashboardContent } from '~/types/content'

/** Testi della dashboard in francese, tradotti da `content/en.ts`. */
export const fr: DashboardContent = {
  shell: {
    languageLabel: 'Langue',
    skipToContent: 'Aller au contenu',
    navigationLabel: 'Navigation principale',
    openNavigation: 'Ouvrir la navigation',
    closeNavigation: 'Fermer la navigation',
    nav: {
      jobs: 'Tâches cron',
      overview: 'Aperçu',
    },
    toLightTheme: 'Passer au thème clair',
    toDarkTheme: 'Passer au thème sombre',
    account: {
      open: 'Menu du compte',
      signedInAs: 'Connecté en tant que',
      signOut: 'Se déconnecter',
    },
  },

  status: {
    loading: 'Chargement…',
    errorTitle: 'Quelque chose n\'a pas fonctionné',
    retry: 'Réessayer',
    errors: {
      network: 'Le backend n\'a pas répondu. Vérifiez la connexion, puis réessayez.',
      unauthorized: 'Votre session a expiré. Reconnectez-vous pour continuer.',
      forbidden: 'Vous n\'avez pas accès à cette ressource.',
      notFound: 'Cette ressource n\'existe plus.',
      invalid: 'La requête a été refusée. Vérifiez les données saisies.',
      server: 'Le backend a rencontré un problème. Réessayez dans un instant.',
    },
  },

  home: {
    title: 'Aperçu',
    intro: 'Le service Postqron qui exécute vos tâches planifiées, et s\'il répond.',
    backendTitle: 'État du service',
    apiBaseLabel: 'Adresse de base de l\'API',
    statusLabel: 'État',
    environmentLabel: 'Environnement',
    versionLabel: 'Version',
    check: 'Vérifier à nouveau',
  },

  notFound: {
    title: 'Page introuvable',
    intro: 'Cette adresse ne correspond à aucun écran du tableau de bord. Elle a peut-être changé, ou le lien est erroné.',
    back: 'Retour à l\'aperçu',
  },

  auth: {
    signIn: {
      title: 'Se connecter',
      submit: 'Se connecter',
      submitting: 'Connexion en cours…',
      noAccount: 'Pas encore de compte ?',
      noAccountLink: 'Créez-en un',
      interrupted: 'Votre session a pris fin. Reconnectez-vous pour reprendre où vous en étiez.',
      returningTo: 'Vous reviendrez à la page que vous aviez demandée.',
    },
    signUp: {
      title: 'Créer un compte',
      submit: 'Créer le compte',
      submitting: 'Création en cours…',
      haveAccount: 'Vous avez déjà un compte ?',
      haveAccountLink: 'Connectez-vous',
      acceptedTitle: 'Consultez votre boîte mail',
      acceptedBody: 'Si l\'adresse est utilisable, nous avons envoyé un e-mail avec la marche à suivre.',
      acceptedSignIn: 'Aller à la connexion',
    },
    fields: {
      email: 'E-mail',
      password: 'Mot de passe',
      fullName: 'Nom et prénom',
      passwordHint: 'Au moins 12 caractères.',
    },
    errors: {
      credentials: 'L\'e-mail ou le mot de passe est incorrect.',
      tooManyAttempts: 'Trop de tentatives. Patientez quelques minutes, puis réessayez.',
      suspended: 'Ce compte est suspendu. Contactez l\'assistance.',
      invalidEmail: 'Cette adresse e-mail n\'est pas valide.',
      weakPassword: 'Ce mot de passe ne respecte pas l\'exigence ci-dessus.',
      unexpected: 'La requête n\'a pas pu aboutir. Réessayez dans un instant.',
      required: 'Remplissez ce champ.',
    },
  },

  jobs: {
    list: {
      title: 'Tâches cron',
      intro: 'Tout ce que Postqron exécute pour vous, et quand la prochaine exécution aura lieu.',
      create: 'Nouvelle tâche cron',
      empty: 'Aucune tâche cron pour l\'instant.',
      emptyHint: 'Créez-en une : elle se lancera au rythme que vous choisirez.',

      columnName: 'Nom',
      columnSchedule: 'Planification',
      columnNextRun: 'Prochaine exécution',
      columnState: 'État',
      columnActions: 'Actions',

      nextRunPending: 'En attente du planificateur',
      nextRunNone: 'Aucune',

      edit: 'Modifier',
      runNow: 'Exécuter maintenant',
      running: 'Démarrage…',
      runQueued: 'Exécution enregistrée. Le moteur appellera la cible dans un instant.',
      pause: 'Mettre en pause',
      resume: 'Réactiver',
      delete: 'Supprimer',
      deleteTitle: 'Supprimer cette tâche cron ?',
      deleteBody: 'La tâche et son historique d\'exécutions disparaissent. C\'est irréversible.',
      deleteConfirm: 'Supprimer',
      deleteCancel: 'La garder',
    },

    form: {
      createTitle: 'Nouvelle tâche cron',
      editTitle: 'Modifier la tâche cron',
      save: 'Enregistrer',
      saving: 'Enregistrement…',
      saved: 'Enregistré',
      cancel: 'Annuler',
      back: 'Retour aux tâches cron',

      sectionIdentity: 'Identité',
      sectionSchedule: 'Planification',
      sectionTarget: 'Cible',
      sectionExecution: 'Exécution',
      sectionAlerts: 'Alertes',

      managedTitle: 'Cette tâche est définie dans votre dépôt',
      managedBody: 'Modifiez-la dans le cron.yaml dont elle provient. Une modification faite ici serait annulée au prochain push, sans erreur. Vous pouvez tout de même la mettre en pause.',

      invalidTitle: 'Quelques champs sont à revoir avant de pouvoir enregistrer.',
      nameTaken: 'Vous avez déjà une tâche portant ce nom. Le nom est l\'identité stable de la tâche.',
      unexpected: 'La tâche n\'a pas pu être enregistrée. Réessayez dans un instant.',
    },

    fields: {
      name: 'Nom',
      nameHint: 'Lettres, chiffres, point, tiret et tiret bas. C\'est l\'identité stable de la tâche : la renommer revient à la supprimer et à en créer une autre.',
      description: 'Description',
      optional: 'Facultatif',

      mode: 'À quelle fréquence',
      modeCron: 'Expression cron',
      modeInterval: 'Intervalle fixe',
      schedule: 'Expression cron',
      scheduleHint: 'Cinq champs : minute, heure, jour du mois, mois, jour de la semaine.',
      every: 'Toutes les',
      everyUnit: 'Unité',
      timezone: 'Fuseau horaire',
      timezoneHint: 'Le fuseau de la tâche, pas celui de votre navigateur. Les changements d\'heure y sont résolus.',

      environments: 'Environnements',
      url: 'URL',
      method: 'Méthode',
      headers: 'En-têtes',
      headerName: 'Nom de l\'en-tête',
      headerValue: 'Valeur de l\'en-tête',
      addHeader: 'Ajouter un en-tête',
      removeHeader: 'Retirer cet en-tête',
      body: 'Corps de la requête',

      timeout: 'Délai d\'attente (secondes)',
      timeoutHint: 'Combien de temps attendre la cible avant d\'abandonner.',
      retries: 'Nouvelles tentatives',
      backoff: 'Attente entre les tentatives',
      overlap: 'Si l\'exécution précédente est encore en cours',
      overlapHint: 'Avec une planification inférieure à la minute, ce n\'est pas un cas rare : c\'est la norme.',
      alerts: 'Me prévenir en cas d\'échec',
      enabled: 'Active',
      enabledHint: 'Une tâche en pause conserve son historique et cesse de se lancer.',
    },

    options: {
      backoff: {
        exponential: 'Exponentielle',
        linear: 'Linéaire',
        fixed: 'Fixe',
      },
      overlap: {
        skip: 'Sauter la nouvelle exécution',
        queue: 'La mettre en file',
        allow: 'Lancer les deux',
      },
      overlapHint: {
        skip: 'L\'occurrence est enregistrée comme sautée, avec le motif. Rien ne s\'exécute deux fois.',
        queue: 'Les exécutions restent en file. Une tâche plus lente que son propre intervalle accumule du retard.',
        allow: 'Les deux appels partent ensemble. Une cible facturée à l\'appel facturerait deux fois.',
      },
      alerts: {
        email: 'E-mail',
        slack: 'Slack',
        discord: 'Discord',
        webhook: 'Webhook',
      },
      environments: {
        staging: 'Préproduction',
        production: 'Production',
      },
      everyUnits: {
        s: 'secondes',
        m: 'minutes',
        h: 'heures',
      },
    },

    preview: {
      title: 'Prochaines exécutions',
      inTimezone: 'Horaires en {zone}, le fuseau de la tâche.',
      epochAnchored: 'Les intervalles sont ancrés à l\'epoch Unix, pas au moment où vous enregistrez : toutes les 1h veut dire à l\'heure pile UTC.',
      never: 'Cette expression ne se présente jamais. Vérifiez le jour et le mois demandés.',
      invalid: 'Corrigez la planification pour voir quand la tâche se lancerait.',
      shifted: 'Cette heure d\'horloge n\'existe pas ce jour-là : l\'horloge l\'enjambe. La tâche part au premier instant qui existe.',
      ambiguous: 'Cette heure d\'horloge a lieu deux fois ce jour-là. La tâche ne part qu\'à la première.',
      scheduled: 'Calculée par le planificateur',
    },

    plan: {
      title: 'Votre offre',
      jobsUsed: 'Tâches cron : {used} sur {limit}',
      jobsUnlimited: 'Tâches cron : {used}, sans plafond strict',
      jobsFull: 'L\'offre est pleine. Supprimez une tâche, ou passez à une offre plus large, avant d\'en créer une autre.',
      minInterval: 'Intervalle minimal : {value}',
      retention: 'Journaux d\'exécution conservés {days} jours',

      suspendedTitle: 'Un changement d\'offre a arrêté certaines tâches',
      suspendedByJobLimit: 'Arrêtées parce que l\'offre était pleine : {count}. Réactivez-en autant que l\'offre le permet — lesquelles, c\'est à vous de le décider, et personne d\'autre ne le peut.',
      suspendedByResolution: 'Arrêtées parce qu\'elles partent plus souvent que {value} : {count}. Changez leur planification pour les récupérer.',
      resolutionBlocked: 'Cette tâche part plus souvent que {value}, ce qui est la limite de votre offre. Changez d\'abord sa planification : libérer une place ailleurs ne la réactivera pas.',

      limitJobs: 'L\'offre est pleine. Supprimez une tâche, ou passez à une offre plus large.',
      limitResolution: 'L\'offre {plan} n\'exécute pas les tâches plus souvent que {value}. Élargissez l\'intervalle, ou passez à une offre plus large.',
      limitEnvironments: 'Votre offre n\'a qu\'un seul environnement. La préproduction demande une offre plus large.',
      upgrade: 'Voir les offres',
    },

    state: {
      active: 'Active',
      paused: 'En pause',
      suspendedByJobLimit: 'Arrêtée par un changement d\'offre',
      suspendedByResolution: 'Trop fréquente pour l\'offre',
      archived: 'Archivée',
      managed: 'Issue d\'un dépôt',
    },

    errors: {
      required: 'Ce champ est obligatoire.',
      tooLong: 'Au plus {limit} caractères.',
      invalidName: 'Uniquement lettres, chiffres, point, tiret et tiret bas, en commençant et en finissant par une lettre ou un chiffre.',
      invalidUrl: 'Ceci n\'est pas une adresse lisible.',
      unsupportedScheme: 'Seules les adresses http et https peuvent être appelées.',
      invalidHeaderName: 'Ceci n\'est pas un nom d\'en-tête valide.',
      reservedHeader: '{value} est décidé par l\'exécuteur et ne peut pas être déclaré par la tâche.',
      duplicateHeader: '{value} apparaît deux fois. Un seul des deux serait envoyé.',
      headerNewline: 'La valeur d\'un en-tête ne peut pas contenir de saut de ligne.',
      tooManyHeaders: 'Au plus {limit} en-têtes.',
      headerTooLong: '{value} dépasse les {limit} caractères autorisés.',
      bodyTooLong: 'Le corps dépasse {limit} octets.',
      timeoutRange: 'Le délai d\'attente va de {min} à {max} secondes.',
      timeoutWhole: 'Le délai d\'attente doit être un nombre entier de secondes.',
      retriesRange: 'Les tentatives vont de 0 à {limit}.',
      environmentsRequired: 'Choisissez au moins un environnement.',
      scheduleRequired: 'Écrivez une expression cron, ou passez à l\'intervalle fixe.',
      scheduleConflict: 'Une expression cron et un intervalle s\'excluent mutuellement.',
      scheduleMacro: 'Les abréviations comme @daily ne sont pas acceptées. Écrivez les cinq champs.',
      scheduleFieldCount: 'Une expression cron a cinq champs : minute, heure, jour du mois, mois, jour de la semaine.',
      scheduleField: '{value} n\'est pas une valeur que ce champ accepte.',
      unknownTimezone: '{value} n\'est pas un nom de fuseau horaire connu.',
      localTimezone: 'Une tâche a besoin d\'un fuseau explicite, pas de celui de la machine qui l\'exécute.',
      invalidInterval: 'L\'intervalle doit être un nombre entier de secondes, au moins une.',
      targetNotAllowed: 'Cette adresse ne peut pas être appelée depuis Postqron.',
      nameTaken: 'Vous avez déjà une tâche portant ce nom.',
      rejected: 'Le serveur a rejeté ce champ.',
    },
  },
}
