import type { DashboardContent } from '~/types/content'

/** Testi della dashboard in italiano, tradotti da `content/en.ts`. */
export const it: DashboardContent = {
  shell: {
    languageLabel: 'Lingua',
    skipToContent: 'Vai al contenuto',
    navigationLabel: 'Navigazione principale',
    openNavigation: 'Apri la navigazione',
    closeNavigation: 'Chiudi la navigazione',
    nav: {
      jobs: 'Cronjob',
      overview: 'Panoramica',
    },
    toLightTheme: 'Passa al tema chiaro',
    toDarkTheme: 'Passa al tema scuro',
    account: {
      open: 'Menu dell\'account',
      signedInAs: 'Collegato come',
      signOut: 'Esci',
    },
  },

  status: {
    loading: 'Caricamento…',
    errorTitle: 'Qualcosa non ha funzionato',
    retry: 'Riprova',
    errors: {
      network: 'Il backend non ha risposto. Controlla la connessione e riprova.',
      unauthorized: 'La sessione è scaduta. Accedi di nuovo per continuare.',
      forbidden: 'Non hai accesso a questa risorsa.',
      notFound: 'Questa risorsa non c\'è più.',
      invalid: 'La richiesta è stata rifiutata. Controlla i dati inseriti.',
      server: 'Il backend ha avuto un problema. Riprova fra un momento.',
    },
  },

  home: {
    title: 'Panoramica',
    intro: 'Il servizio Postqron che esegue i tuoi cronjob, e se sta rispondendo.',
    backendTitle: 'Stato del servizio',
    apiBaseLabel: 'Indirizzo base dell\'API',
    statusLabel: 'Stato',
    environmentLabel: 'Ambiente',
    versionLabel: 'Versione',
    check: 'Controlla di nuovo',
  },

  notFound: {
    title: 'Pagina non trovata',
    intro: 'Questo indirizzo non corrisponde a nessuna schermata della dashboard. Potrebbe essere cambiato, o il collegamento potrebbe essere sbagliato.',
    back: 'Torna alla panoramica',
  },

  auth: {
    signIn: {
      title: 'Accedi',
      submit: 'Accedi',
      submitting: 'Accesso in corso…',
      noAccount: 'Non hai ancora un account?',
      noAccountLink: 'Creane uno',
      interrupted: 'La sessione è terminata. Accedi di nuovo per riprendere da dove eri.',
      returningTo: 'Tornerai alla pagina che avevi chiesto.',
    },
    signUp: {
      title: 'Crea un account',
      submit: 'Crea account',
      submitting: 'Creazione in corso…',
      haveAccount: 'Hai già un account?',
      haveAccountLink: 'Accedi',
      acceptedTitle: 'Controlla la posta',
      acceptedBody: 'Se l\'indirizzo è utilizzabile, abbiamo inviato un\'email con le istruzioni.',
      acceptedSignIn: 'Vai all\'accesso',
    },
    fields: {
      email: 'Email',
      password: 'Password',
      fullName: 'Nome e cognome',
      passwordHint: 'Almeno 12 caratteri.',
    },
    errors: {
      credentials: 'Email o password non corretti.',
      tooManyAttempts: 'Troppi tentativi. Aspetta qualche minuto e riprova.',
      suspended: 'Questo account è sospeso. Contatta l\'assistenza.',
      invalidEmail: 'Questo indirizzo email non è valido.',
      weakPassword: 'Questa password non rispetta il requisito qui sopra.',
      unexpected: 'Non è stato possibile completare la richiesta. Riprova fra un momento.',
      required: 'Compila questo campo.',
    },
  },

  jobs: {
    list: {
      title: 'Cronjob',
      intro: 'Tutto ciò che Postqron esegue per te, e quando lo esegue la prossima volta.',
      create: 'Nuovo cronjob',
      empty: 'Nessun cronjob, per ora.',
      emptyHint: 'Creane uno: comincerà a partire con la cadenza che scegli.',

      columnName: 'Nome',
      columnSchedule: 'Schedulazione',
      columnNextRun: 'Prossima esecuzione',
      columnState: 'Stato',
      columnActions: 'Azioni',

      nextRunPending: 'In attesa dello scheduler',
      nextRunNone: 'Nessuna',

      edit: 'Modifica',
      runNow: 'Esegui adesso',
      running: 'Avvio…',
      runQueued: 'Esecuzione registrata. Il motore chiamerà il bersaglio fra un momento.',
      pause: 'Metti in pausa',
      resume: 'Riattiva',
      delete: 'Elimina',
      deleteTitle: 'Eliminare questo cronjob?',
      deleteBody: 'Spariscono il job e il suo storico di esecuzioni. Non si può annullare.',
      deleteConfirm: 'Elimina',
      deleteCancel: 'Tienilo',
    },

    form: {
      createTitle: 'Nuovo cronjob',
      editTitle: 'Modifica cronjob',
      save: 'Salva',
      saving: 'Salvataggio…',
      saved: 'Salvato',
      cancel: 'Annulla',
      back: 'Torna ai cronjob',

      sectionIdentity: 'Identità',
      sectionSchedule: 'Schedulazione',
      sectionTarget: 'Bersaglio',
      sectionExecution: 'Esecuzione',
      sectionAlerts: 'Avvisi',

      managedTitle: 'Questo job è definito nel tuo repository',
      managedBody: 'Modificalo nel cron.yaml da cui proviene. Una modifica fatta qui verrebbe riportata indietro al primo push, senza un errore. Puoi comunque metterlo in pausa.',

      invalidTitle: 'Qualche campo va rivisto prima di poter salvare.',
      nameTaken: 'Hai già un job con questo nome. Il nome è l\'identità stabile del job.',
      unexpected: 'Non è stato possibile salvare il job. Riprova fra un momento.',
    },

    fields: {
      name: 'Nome',
      nameHint: 'Lettere, cifre, punto, trattino e trattino basso. È l\'identità stabile del job: rinominarlo equivale a cancellarlo e crearne un altro.',
      description: 'Descrizione',
      optional: 'Facoltativo',

      mode: 'Ogni quanto',
      modeCron: 'Espressione cron',
      modeInterval: 'Intervallo fisso',
      schedule: 'Espressione cron',
      scheduleHint: 'Cinque campi: minuti, ore, giorno del mese, mese, giorno della settimana.',
      every: 'Ogni',
      everyUnit: 'Unità',
      timezone: 'Fuso orario',
      timezoneHint: 'Il fuso del job, non quello del tuo browser. I cambi di ora legale sono gestiti in quel fuso.',

      environments: 'Ambienti',
      url: 'URL',
      method: 'Metodo',
      headers: 'Header',
      headerName: 'Nome dell\'header',
      headerValue: 'Valore dell\'header',
      addHeader: 'Aggiungi un header',
      removeHeader: 'Togli questo header',
      body: 'Corpo della richiesta',

      timeout: 'Timeout (secondi)',
      timeoutHint: 'Quanto aspettare il bersaglio prima di rinunciare.',
      retries: 'Tentativi',
      backoff: 'Attesa fra i tentativi',
      overlap: 'Se l\'esecuzione precedente è ancora in corso',
      overlapHint: 'Con le schedulazioni sotto il minuto non è un caso raro, è la norma.',
      alerts: 'Avvisami quando fallisce',
      enabled: 'Attivo',
      enabledHint: 'Un job in pausa conserva il proprio storico e smette di partire.',
    },

    options: {
      backoff: {
        exponential: 'Esponenziale',
        linear: 'Lineare',
        fixed: 'Fissa',
      },
      overlap: {
        skip: 'Salta la nuova esecuzione',
        queue: 'Mettila in coda',
        allow: 'Eseguile insieme',
      },
      overlapHint: {
        skip: 'L\'occorrenza viene registrata come saltata, con il motivo. Niente parte due volte.',
        queue: 'Le esecuzioni restano in fila. Un job più lento del proprio intervallo accumula arretrato.',
        allow: 'Le due chiamate partono insieme. Un bersaglio che fattura per chiamata fatturerebbe due volte.',
      },
      alerts: {
        email: 'Email',
        slack: 'Slack',
        discord: 'Discord',
        webhook: 'Webhook',
      },
      environments: {
        staging: 'Staging',
        production: 'Produzione',
      },
      everyUnits: {
        s: 'secondi',
        m: 'minuti',
        h: 'ore',
      },
    },

    preview: {
      title: 'Prossime esecuzioni',
      inTimezone: 'Orari in {zone}, il fuso del job.',
      epochAnchored: 'Gli intervalli sono ancorati all\'epoch Unix, non al momento in cui salvi: ogni 1h scocca all\'ora piena UTC.',
      never: 'Questa espressione non arriva mai. Controlla il giorno e il mese che hai chiesto.',
      invalid: 'Correggi la schedulazione per vedere quando partirebbe il job.',
      shifted: 'Questo orario da parete quel giorno non esiste: l\'orologio ci salta sopra. Il job parte al primo istante che esiste.',
      ambiguous: 'Questo orario da parete quel giorno accade due volte. Il job parte solo alla prima.',
      scheduled: 'Calcolata dallo scheduler',
    },

    plan: {
      title: 'Il tuo piano',
      jobsUsed: 'Cronjob: {used} di {limit}',
      jobsUnlimited: 'Cronjob: {used}, senza tetto rigido',
      jobsFull: 'Il piano è pieno. Elimina un job, o passa a un piano più capiente, prima di crearne un altro.',
      minInterval: 'Intervallo minimo: {value}',
      retention: 'Log delle esecuzioni conservati {days} giorni',

      suspendedTitle: 'Un cambio di piano ha fermato alcuni job',
      suspendedByJobLimit: 'Fermi perché il piano era pieno: {count}. Riaccendine quanti il piano ne consente — quali, lo decidi tu, e nessun altro può farlo.',
      suspendedByResolution: 'Fermi perché partono più spesso di {value}: {count}. Cambia la loro schedulazione per riaverli.',
      resolutionBlocked: 'Questo job parte più spesso di {value}, che è quanto il tuo piano consente. Cambia prima la sua schedulazione: liberare un posto altrove non lo riaccende.',

      limitJobs: 'Il piano è pieno. Elimina un job, o passa a un piano più capiente.',
      limitResolution: 'Il piano {plan} esegue i job non più spesso di {value}. Allarga l\'intervallo, oppure passa a un piano superiore.',
      limitEnvironments: 'Il tuo piano ha un solo ambiente. Lo staging richiede un piano superiore.',
      upgrade: 'Guarda i piani',
    },

    state: {
      active: 'Attivo',
      paused: 'In pausa',
      suspendedByJobLimit: 'Fermato da un cambio di piano',
      suspendedByResolution: 'Troppo frequente per il piano',
      archived: 'Archiviato',
      managed: 'Da un repository',
    },

    errors: {
      required: 'Questo campo è obbligatorio.',
      tooLong: 'Al massimo {limit} caratteri.',
      invalidName: 'Solo lettere, cifre, punto, trattino e trattino basso, con una lettera o una cifra all\'inizio e alla fine.',
      invalidUrl: 'Questo non è un indirizzo leggibile.',
      unsupportedScheme: 'Si possono chiamare solo indirizzi http e https.',
      invalidHeaderName: 'Questo non è un nome di header valido.',
      reservedHeader: '{value} lo decide l\'esecutore e non può essere dichiarato dal job.',
      duplicateHeader: '{value} compare due volte. Ne verrebbe mandato uno solo dei due.',
      headerNewline: 'Il valore di un header non può contenere un a capo.',
      tooManyHeaders: 'Al massimo {limit} header.',
      headerTooLong: '{value} supera i {limit} caratteri ammessi.',
      bodyTooLong: 'Il corpo supera {limit} byte.',
      timeoutRange: 'Il timeout va da {min} a {max} secondi.',
      timeoutWhole: 'Il timeout dev\'essere un numero intero di secondi.',
      retriesRange: 'I tentativi vanno da 0 a {limit}.',
      environmentsRequired: 'Scegli almeno un ambiente.',
      scheduleRequired: 'Scrivi un\'espressione cron, oppure passa all\'intervallo fisso.',
      scheduleConflict: 'Un\'espressione cron e un intervallo non possono coesistere.',
      scheduleMacro: 'Le abbreviazioni come @daily non sono ammesse. Scrivi i cinque campi.',
      scheduleFieldCount: 'Un\'espressione cron ha cinque campi: minuti, ore, giorno del mese, mese, giorno della settimana.',
      scheduleField: '{value} non è un valore che questo campo accetta.',
      unknownTimezone: '{value} non è il nome di un fuso orario conosciuto.',
      localTimezone: 'Un job ha bisogno di un fuso esplicito, non di quello della macchina che lo esegue.',
      invalidInterval: 'L\'intervallo dev\'essere un numero intero di secondi, almeno uno.',
      targetNotAllowed: 'Questo indirizzo non può essere chiamato da Postqron.',
      nameTaken: 'Hai già un job con questo nome.',
      rejected: 'Il server ha rifiutato questo campo.',
    },
  },
}
