-- Materializes the current F25-approved Italian Terms and Privacy
-- artifacts into the F13 compliance ledger (`compliance_legal_documents`).
-- Generated by
-- `node --experimental-strip-types features/f25-legal-documents/scripts/build-legal-bootstrap-seed.ts`
-- from the canonical bundle in `features/f25-legal-documents/src/bundle.ts`
-- (refs. terms_it 0.2: https://github.com/apdsoftware/postqron/issues/179#issuecomment-5090088911; privacy_it 0.1: LEGAL-APPROVAL-2026-07-25-F25). Do not hand-edit this file.
--
-- `ON CONFLICT DO NOTHING` makes re-runs idempotent. The post-insert
-- comparisons remain fail-closed: every bundle-derived field is checked and
-- any pre-existing divergent row aborts this atomic block rather than masking
-- legal-ledger drift.
DO $$
DECLARE
  expected_terms_it_content bytea := convert_to($terms_it_v0_2_content$# Termini di Servizio di Postqron

## 1. Identità del fornitore

I presenti Termini di Servizio sono emessi da Apdsoftware di Carlo Zuffetti (Via C. Colombo 15, 24047 Treviglio (BG), Italia, P.IVA 03835250162, REA BG 431224), operante con il marchio APDSoftware quale gestore del servizio di programmazione di contenuti sui social media Postqron ("Postqron", il "Servizio"). Dati anagrafici verificati tramite fonte pubblica: https://mailronix.com/terms (consultata il 2026-07-25). L'entità è contattabile all'indirizzo help@postqron.com e all'indirizzo https://apdsoftware.it.

## 2. Ambito e accettazione

I presenti Termini disciplinano l'accesso e l'utilizzo del Servizio, compresi il sito pubblico, l'applicazione e qualsiasi integrazione connessa. Utilizzando il Servizio, oppure accettando espressamente i presenti Termini durante la registrazione dell'account, l'utente accetta di essere vincolato dalla versione e dal digest di contenuto esatti dei Termini presentati in quel momento. Postqron conserva una registrazione interna di quale versione e digest ciascun utente ha accettato, e quando. In caso di mancata accettazione, l'utente non può utilizzare il Servizio.

## 3. Clienti B2C e B2B

Durante questa fase MVP, Postqron è offerto esclusivamente a consumatori e imprese residenti o stabiliti in Italia. Le pagine pubbliche del sito possono essere consultate da qualsiasi luogo, ma la registrazione dell'account e l'acquisto di qualsiasi piano a pagamento richiedono un paese contraente italiano e un indirizzo di fatturazione italiano. La distinzione tra consumatori (B2C) e imprese (B2B) è rilevante in tutti i presenti Termini poiché determina gli obblighi informativi precontrattuali applicabili, la disponibilità e la portata del diritto di recesso previsto dalla legge, nonché i rimedi e le procedure disponibili in caso di controversia. Ove una disposizione si applichi solo ai consumatori o solo alle imprese, ciò è espressamente indicato.

## 4. Account e workspace

Al primo accesso al Servizio viene automaticamente creato un workspace personale. All'interno di un workspace esistono due ruoli: il Proprietario (Owner), che può gestire i membri del workspace, i canali social connessi, il piano di abbonamento e l'eliminazione del workspace; e il Membro (Member), che dispone di un accesso operativo più limitato, configurato dal Proprietario. Ciascun utente è responsabile della riservatezza delle proprie credenziali di accesso e di tutte le attività svolte tramite il proprio account, compreso qualsiasi contenuto pubblicato attraverso gli account social connessi al proprio workspace.

## 5. Uso consentito

Gli utenti non devono utilizzare il Servizio per pubblicare, programmare o distribuire contenuti illeciti, lesivi di diritti di terzi o abusivi. Postqron pubblica sulle piattaforme social connesse esclusivamente tramite le API ufficialmente supportate da tali piattaforme. Gli utenti non devono tentare di eludere i limiti di frequenza (rate limit), i diritti previsti dal piano sottoscritto, né accedere al piano interno illimitato non pubblico descritto alla Sezione 6. La violazione della presente Sezione può comportare la sospensione o la risoluzione dell'account, in aggiunta a ogni altro rimedio previsto dai presenti Termini o dalla legge applicabile.

## 6. Piani e prezzi

Postqron offre quattro piani di abbonamento pubblici, con prezzi espressi esclusivamente in euro (EUR):

- **Start** — gratuito in modo permanente, non richiede una carta di pagamento, include fino a 3 canali connessi, 1 utente e fino a 10 post programmati contemporaneamente per canale.
- **Pro** — 1 utente, fino a 6 canali connessi, fino a 500 post programmati contemporaneamente per canale, fatturato a 4,50 € per canale/mese (fino a 27,00 €/mese con 6 canali). Il prezzo annuale equivale a dieci volte il totale mensile (l'equivalente di due mesi gratuiti).
- **Team** — fino a 9 utenti, fino a 9 canali connessi, fino a 500 post programmati contemporaneamente per canale, fatturato a 9,00 € per canale/mese (fino a 81,00 €/mese con 9 canali). Il prezzo annuale equivale a dieci volte il totale mensile (l'equivalente di due mesi gratuiti).
- **Unlimited** — piano a prezzo fisso di 129,00 €/mese o 1.290,00 €/anno (pari a dieci mensilità), senza alcuna quota commerciale sul numero di canali connessi, di utenti o di post programmabili contemporaneamente per canale. Le protezioni di sicurezza tecniche e i rate limit (ad esempio i limiti di frequenza delle API delle piattaforme social collegate, le protezioni anti-abuso e i limiti di throughput dell'infrastruttura) restano in vigore indipendentemente dal piano e non vengono mai presentati come un limite di piano.

Postqron mantiene inoltre un piano non pubblico "Internal Unlimited" (interno illimitato), non acquistabile né richiedibile dai clienti. Può essere assegnato esclusivamente da un amministratore Postqron autorizzato ad account specificamente indicati, e il suo utilizzo è interamente tracciato. Il piano pubblico Unlimited sopra descritto è un'offerta distinta e separatamente acquistabile, diversa da Internal Unlimited per visibilità, acquistabilità, assegnazione, fatturazione e controllo; nessun cliente può richiedere o ottenere Internal Unlimited, e il suo meccanismo di assegnazione interno non è divulgato in questa sede.

Ogni nuovo workspace idoneo può attivare una prova gratuita di 14 giorni, senza carta di pagamento, del piano Team. Se la prova scade senza un acquisto a pagamento, il workspace torna automaticamente al piano Start secondo regole prudenziali di conservazione delle risorse: i canali, i membri e i contenuti esistenti vengono conservati, ma le risorse eccedenti i limiti del piano Start vengono sospese anziché eliminate.

## 7. Paddle quale fornitore di pagamenti e Merchant of Record

Gli abbonamenti sono venduti tramite Paddle.com Market Ltd (o la società del gruppo Paddle competente), che agisce come rivenditore autorizzato (Merchant of Record). Ne consegue che: (i) la transazione di acquisto — addebiti, emissione della fattura, applicazione dell'IVA, eventuali rimborsi — intercorre tra il Cliente e Paddle ed è regolata dai termini e dalla refund policy di Paddle; (ii) il rapporto di servizio, regolato dai presenti Termini, intercorre tra il Cliente e il Fornitore. In caso di conflitto, per la parte transazionale prevalgono i termini di Paddle, per l'erogazione del Servizio prevalgono i presenti Termini.

## 8. Rinnovo

Gli abbonamenti si rinnovano automaticamente alla scadenza di ciascun periodo (mensile o annuale), salvo disdetta effettuata prima del rinnovo dal pannello del Servizio o tramite Paddle.

## 9. Upgrade e downgrade

Un upgrade — un aumento del livello di piano, un passaggio alla periodicità annuale o un aumento del numero di canali connessi — ha effetto immediato al pagamento dell'importo proporzionale (prorata) calcolato da Paddle per il periodo residuo del ciclo di fatturazione in corso. Un downgrade ha effetto alla fine del periodo già pagato, senza credito o rimborso automatico per la parte non utilizzata del piano superiore. Qualora un downgrade determini per il workspace risorse eccedenti i limiti del nuovo piano, tali risorse eccedenti vengono sospese, non eliminate, fino a quando non rientrino nuovamente nei limiti applicabili.

## 10. Disdetta

Il Proprietario del workspace può disdire un abbonamento a pagamento direttamente all'interno del Servizio oppure tramite il portale clienti di Paddle. Salvo diversa indicazione, la disdetta ha effetto al termine del periodo già pagato, e il piano rimane attivo fino a tale data. La disdetta con effetto immediato, prima della fine del periodo pagato, è riservata ai casi di rimborso, sospetta frode, obbligo di legge o intervento documentato dell'assistenza clienti. La disdetta di un abbonamento non comporta l'eliminazione dell'account né dei dati associati, ed è un processo distinto dalla procedura di eliminazione dell'account descritta nell'Informativa sulla Privacy di Postqron.

## 11. Diritto di recesso

Nulla nei presenti Termini limita il diritto di recesso previsto dalla normativa applicabile dell'Unione Europea e italiana a tutela dei consumatori, incluso il quadro normativo della Direttiva 2011/83/UE sui diritti dei consumatori. Tali diritti di legge restano pienamente disponibili secondo le proprie condizioni e i propri termini temporali.

Separatamente, e in aggiunta a qualsiasi diritto di legge, Postqron offre volontariamente a ciascun cliente un rimborso integrale su richiesta, formulata entro 14 giorni di calendario dal primo addebito a pagamento del workspace. Questo rimborso volontario può essere utilizzato una sola volta per workspace e, una volta concesso, pone immediatamente fine al piano a pagamento per quel workspace. Questa offerta di rimborso volontario è distinta e non sostituisce, né limita, alcun diritto di recesso di legge del consumatore. I consumatori residenti nell'Unione Europea possono inoltre rivolgere reclami all'organismo nazionale di risoluzione delle controversie dei consumatori competente, elencato nel registro della Commissione Europea all'indirizzo https://consumer-redress.ec.europa.eu/dispute-resolution-bodies (la piattaforma di Risoluzione delle Controversie Online dell'UE è stata dismessa dalla Commissione Europea il 20 luglio 2025 ai sensi del Regolamento (UE) 2024/3228 e non accetta più reclami; fonte consultata il 2026-07-25).

## 12. Mancati pagamenti

In caso di mancato pagamento, il Fornitore può sospendere le funzioni del Servizio dopo un ragionevole preavviso e, persistendo l'inadempimento per oltre 30 giorni, risolvere il contratto.

## 13. Disponibilità del servizio

Postqron persegue un livello elevato, ma non assoluto, di disponibilità della propria applicazione e delle API sottostanti, e adotta sforzi ragionevoli dal punto di vista commerciale per mantenere l'affidabilità del Servizio. Possono verificarsi periodicamente finestre di manutenzione programmata. I presenti Termini non garantiscono contrattualmente ai clienti alcuna percentuale specifica di uptime. Postqron può mantenere obiettivi interni di disponibilità operativa per propri fini interni; questi non costituiscono un accordo sul livello di servizio (SLA) rivolto ai clienti e non generano diritti contrattuali.

## 14. Responsabilità

Nella misura massima consentita dalla legge inderogabile applicabile, la responsabilità di Postqron derivante dai presenti Termini o dall'utilizzo del Servizio è limitata ai danni diretti effettivamente subiti, ed esclude i danni indiretti, incidentali o consequenziali, comprese perdite di profitto, di ricavi, di dati o di opportunità commerciali. Nulla nei presenti Termini limita o esclude la responsabilità che non può essere legalmente limitata o esclusa ai sensi della legge inderogabile applicabile, compresa la responsabilità per colpa grave, dolo, morte o lesioni personali, e i diritti di legge dei consumatori che non possono essere derogati per contratto.

## 15. Legge applicabile e foro competente

I presenti Termini sono disciplinati dalla legge italiana. Per i consumatori, tale scelta di legge non li priva della protezione garantita dalle disposizioni inderogabili della legge del paese di residenza abituale, ove le norme applicabili dell'Unione Europea sui contratti transfrontalieri con i consumatori (in particolare il Regolamento Roma I) lo prevedano. Per le controversie che coinvolgono un consumatore, il foro competente è quello del luogo di residenza del consumatore, come determinato dalla legge applicabile. Per le controversie tra Postqron e un cliente impresa (B2B), è competente il Tribunale di Bergamo, foro della sede legale dell'entità contraente Apdsoftware di Carlo Zuffetti (Via C. Colombo 15, 24047 Treviglio (BG), Italia).

## 16. Reclami e controversie

I reclami relativi al Servizio possono essere indirizzati a help@postqron.com, oppure a legal@postqron.com per le comunicazioni legali. I consumatori residenti nell'Unione Europea possono inoltre sottoporre controversie transfrontaliere all'organismo nazionale di risoluzione delle controversie dei consumatori competente, elencato nel registro della Commissione Europea all'indirizzo https://consumer-redress.ec.europa.eu/dispute-resolution-bodies (la piattaforma di Risoluzione delle Controversie Online dell'UE è stata dismessa dalla Commissione Europea il 20 luglio 2025 ai sensi del Regolamento (UE) 2024/3228 e non accetta più reclami; fonte consultata il 2026-07-25), fermo restando il diritto di adire il tribunale competente.

## 17. Modifiche ai presenti Termini

Postqron può modificare periodicamente i presenti Termini. Una modifica sostanziale richiede la nuova accettazione attiva della versione aggiornata da parte dell'utente prima di poter continuare a utilizzare le funzionalità autenticate del Servizio. Una modifica non sostanziale viene pubblicata come nuova versione dei presenti Termini senza richiedere una nuova accettazione. Ogni versione pubblicata dei presenti Termini è immutabile una volta emessa ed è identificata da un digest di contenuto univoco, registrato insieme alla corrispondente registrazione di accettazione descritta alla Sezione 2.$terms_it_v0_2_content$, 'UTF8');
  expected_privacy_it_content bytea := convert_to($privacy_it_v0_1_content$# Informativa sulla privacy di Postqron

*Versione 0.1 — approvata in seguito a revisione legale esterna (rif. LEGAL-APPROVAL-2026-07-25-F25). Questo documento descrive come Postqron tratta i dati personali.*

## 1. Titolare del trattamento e contatti

La presente informativa è emessa da Apdsoftware di Carlo Zuffetti (Via C. Colombo 15, 24047 Treviglio (BG), Italia, P.IVA 03835250162, REA BG 431224), operante con il marchio APDSoftware quale titolare del trattamento per il servizio Postqron (dati anagrafici verificati tramite fonte pubblica: https://mailronix.com/terms, consultata il 2026-07-25), raggiungibile all'indirizzo privacy@postqron.com e tramite https://apdsoftware.it. Non è stato nominato un Responsabile della protezione dei dati (DPO). Per qualsiasi domanda, richiesta o reclamo in materia di privacy è possibile scrivere a privacy@postqron.com.

## 2. Categorie di dati personali trattati

Postqron tratta le seguenti categorie di dati personali in relazione al servizio:

- **Dati di account e profilo**: nome, indirizzo email e credenziali di autenticazione o identificatori OAuth utilizzati per l'accesso.
- **Dati di workspace**: appartenenza al workspace, ruoli e permessi assegnati all'interno del workspace.
- **Dati di contenuto**: bozze, media caricati, metadati di pianificazione, destinazioni di pubblicazione ed esiti di pubblicazione creati o caricati dall'utente tramite il servizio.
- **Dati identificativi OAuth**: quando l'utente accede tramite Google, Apple, Facebook o LinkedIn, Postqron riceve l'indirizzo email, il nome visualizzato, l'immagine avatar e l'identificativo dell'account fornito da tale provider, utilizzati esclusivamente per creare e autenticare l'account.
- **Metadati di fatturazione**: piano tariffario, quantità di posti o di utilizzo e stato di fatturazione a livello di workspace visibili a Postqron. I dati completi dello strumento di pagamento (numeri di carta, coordinate bancarie e simili) sono conservati esclusivamente da Paddle, che agisce come Merchant of Record, e non sono detenuti da Postqron.
- **Log di utilizzo e di sicurezza**: registrazioni delle azioni svolte all'interno del servizio, generate a fini di sicurezza, accountability e risoluzione dei problemi.
- **Cookie e tecnologie simili**: possono essere utilizzate le categorie necessari, preferenze, analitici e marketing. L'inventario completo e aggiornato dei cookie è mantenuto nella separata Cookie Policy di Postqron e non è duplicato qui. Alla data della presente versione, sono attivi solo i cookie "necessari".

## 3. Finalità e basi giuridiche

| Finalità | Base giuridica |
|---|---|
| Fornitura dell'account, del workspace e del servizio di pianificazione e pubblicazione | Art. 6, par. 1, lett. b) GDPR — esecuzione di un contratto |
| Fatturazione, contabilità e riscontro a richieste legittime delle autorità competenti | Art. 6, par. 1, lett. c) GDPR — obbligo legale |
| Sicurezza, prevenzione degli abusi e accertamento, esercizio o difesa di diritti in sede giudiziaria | Art. 6, par. 1, lett. f) GDPR — legittimo interesse, documentato internamente tramite una valutazione del legittimo interesse |
| Pubblicazione di contenuti sulle piattaforme social scelte dal cliente | Art. 6, par. 1, lett. b) GDPR per i dati a livello di account; istruzioni contrattuali e termini di trattamento dati laddove Postqron agisca come responsabile del trattamento per i dati di contenuto trattati su istruzione documentata del cliente, a seconda dell'esatto flusso di dati e dei termini propri della piattaforma ricevente |
| Email strettamente transazionali e di sicurezza (es. avvisi di accesso, reimpostazione password, comunicazioni di fatturazione) | Art. 6, par. 1, lett. b), c) o f) GDPR a seconda del fattore scatenante; inviate da infrastruttura separata dalle comunicazioni di marketing |
| Comunicazioni di marketing facoltative da parte di Postqron | Art. 6, par. 1, lett. a) GDPR — consenso, unitamente al regime speciale applicabile alle comunicazioni di marketing elettronico; solo su base opt-in, mai preselezionato, con meccanismo di disiscrizione in ogni messaggio |
| Cookie e tracciatori non essenziali | Consenso, ai sensi della normativa ePrivacy applicabile; come indicato sopra, nessun cookie non essenziale è attualmente attivo |
| Gestione di richieste di esportazione, cancellazione, opposizione e altri diritti in materia di privacy | Art. 6, par. 1, lett. c) GDPR — obbligo legale; tipicamente eseguita tramite un flusso autenticato all'interno dell'account |

## 4. Destinatari

Postqron condivide i dati personali, nella misura necessaria per le finalità sopra indicate, con le seguenti categorie di destinatari:

- **Mailronix** — invio di email transazionali.
- **Paddle** — elaborazione dei pagamenti, in qualità di Merchant of Record.
- **Hetzner** — infrastruttura di hosting cloud.
- **Cloudflare** — servizi di DNS, distribuzione dei contenuti, rete edge e terminazione TLS.
- **Provider di identità OAuth** (Google, Apple, Facebook, LinkedIn) — ciascuno agisce come titolare autonomo del trattamento per la fase di accesso e verifica dell'identità; tale fase è disciplinata dall'informativa privacy propria di ciascun provider, e questi provider non sono responsabili del trattamento (subprocessor) di Postqron.
- **Piattaforme social di pubblicazione** scelte dal cliente (ad esempio, Pagine Facebook o account Instagram Professionale) — si tratta di account e integrazioni collegati direttamente dal cliente, utilizzati per pianificare e pubblicare contenuti su istruzione del cliente stesso.

Un registro pubblico e regolarmente aggiornato dei responsabili del trattamento (il documento "Subprocessors" di Postqron) fornisce il dettaglio completo e aggiornato per singolo fornitore delle parti che trattano dati personali per conto di Postqron ed è la fonte autorevole per tali informazioni; è richiamato dalla presente informativa anziché essere duplicato qui.

## 5. Trasferimenti internazionali

Postqron e i suoi fornitori di infrastruttura sono selezionati con una preferenza per l'hosting basato nell'UE/SEE. Qualora i dati personali siano comunque trasferiti al di fuori dello Spazio Economico Europeo, tale trasferimento si basa su una decisione di adeguatezza applicabile o su garanzie appropriate quali le Clausole Contrattuali Standard della Commissione Europea, verificate per singolo fornitore. Il registro dei responsabili del trattamento richiamato alla Sezione 4 è la fonte autorevole e aggiornata per il meccanismo di trasferimento specifico applicabile a ciascun fornitore; la presente informativa non duplica tale dettaglio per singolo fornitore.

## 6. Conservazione

I dati personali sono conservati secondo il seguente schema:

| Dati | Conservazione |
|---|---|
| Dati di account, profilo e appartenenza al workspace | Per tutta la durata dell'account |
| Account inattivi | Dopo 24 mesi di inattività si avvia un processo di chiusura per inattività, con preavviso a 30 e 7 giorni prima della chiusura |
| Richieste di cancellazione confermate | Segue un periodo di grazia di 28 giorni, durante il quale i dati sono congelati e utilizzabili solo per annullare la richiesta, adempiere a un obbligo legale o gestire un incidente di sicurezza, prima della cancellazione o anonimizzazione |
| Contenuti eliminati | Recuperabili per 7 giorni, poi definitivamente cancellati entro 24 ore |
| Media mai associati ad alcun contenuto | Cancellati dopo 24 ore |
| Media scollegati da tutti i contenuti | Cancellati dopo 7 giorni |
| Token OAuth | Revocati e cancellati localmente entro circa 15 minuti dalla disconnessione, revoca o avvio di un processo di cancellazione |
| Sessioni | Invalidate entro circa 5 minuti |
| Log di audit | 12 mesi |
| Log operativi | 30 giorni, prorogabili fino a 90 giorni se collegati a un incidente di sicurezza aperto |
| Backup crittografati | Massimo 35 giorni |
| Pacchetti di esportazione dati | 7 giorni, con link di download in scadenza dopo 24 ore |

## 7. Sicurezza

Postqron applica, tra le altre, le seguenti misure tecniche e organizzative: cifratura in transito (TLS) per tutto il traffico da e verso il servizio; cifratura a riposo per campi sensibili come i token OAuth, conservati separatamente dai dati che proteggono; controllo degli accessi basato sui ruoli per l'accesso interno a sistemi e dati; registrazione strutturata (audit log) delle azioni sensibili; backup crittografati regolari con test di ripristino periodici.

## 8. Diritti dell'interessato

Alle condizioni previste dal GDPR, gli interessati hanno diritto di accedere, rettificare, cancellare, limitare il trattamento, ottenere la portabilità e opporsi al trattamento dei propri dati personali (artt. 15–21 GDPR). La maggior parte di questi diritti può essere esercitata direttamente tramite un flusso autenticato di esportazione o cancellazione all'interno dell'account; altri possono essere esercitati contattando privacy@postqron.com.

Gli interessati hanno inoltre il diritto di proporre reclamo a un'autorità di controllo. In Italia, l'autorità competente è il Garante per la protezione dei dati personali (https://www.garanteprivacy.it). Ai sensi dell'art. 77 GDPR, l'interessato può altresì proporre reclamo all'autorità di controllo del proprio Stato membro dell'UE di residenza abituale o di lavoro, se diverso dall'Italia.

## 9. Minori

Il Servizio è riservato a utenti che abbiano compiuto 18 anni di età e non è offerto a persone minori di 18 anni, in linea con il requisito di età minima adottato da Buffer, il servizio comparabile usato come riferimento commerciale (fonte: Buffer, Termini di Servizio, Sezione 2 "Eligibility" — "You must be at least 18-years old to use the Service", https://buffer.com/legal/terms-of-use/year/2023, consultata il 2026-07-25).

## 10. Reclami e governance del DPO

Le richieste e i reclami in materia di privacy devono essere indirizzati a privacy@postqron.com. Non è stato nominato un Responsabile della protezione dei dati (DPO).

## 11. Modifiche alla presente informativa

Le nuove versioni della presente informativa sulla privacy sono pubblicate con un digest di contenuto immutabile e un numero di versione. Le modifiche sostanziali sono notificate agli utenti. La presente informativa descrive il trattamento dei dati personali da parte di Postqron e non costituisce di per sé un meccanismo generale di consenso.$privacy_it_v0_1_content$, 'UTF8');
  actual compliance_legal_documents%ROWTYPE;
BEGIN
  INSERT INTO compliance_legal_documents (
      document_key,
      jurisdiction,
      locale,
      version,
      content_bytes,
      digest_sha256,
      content_status,
      legal_approval_id,
      approved_at,
      published_at,
      effective_at,
      permanent_url,
      current_url,
      change_type
  ) VALUES (
      'terms_it',
      'IT',
      'it-IT',
      '0.2',
      expected_terms_it_content,
      '2630d35d50853a781453dcad5b067725df2bcd0469e8bf37e9e109c660533f9b',
      'approved',
      'https://github.com/apdsoftware/postqron/issues/179#issuecomment-5090088911',
      '2026-07-27T10:15:46.000Z'::timestamptz,
      '2026-07-27T10:15:46.000Z'::timestamptz,
      '2026-07-27T10:15:46.000Z'::timestamptz,
      '/api/v1/legal-documents/terms_it/versions/0.2',
      '/api/v1/legal-documents/terms_it/current',
      'material'
  )
  ON CONFLICT (document_key, jurisdiction, locale, version) DO NOTHING;

  SELECT * INTO actual
  FROM compliance_legal_documents
  WHERE document_key = 'terms_it'
    AND jurisdiction = 'IT'
    AND locale = 'it-IT'
    AND version = '0.2';

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'terms_it % bootstrap migration: expected row is missing after insert',
      '0.2';
  END IF;

  IF actual.content_bytes IS DISTINCT FROM expected_terms_it_content
    OR actual.digest_sha256 IS DISTINCT FROM '2630d35d50853a781453dcad5b067725df2bcd0469e8bf37e9e109c660533f9b'
    OR actual.content_status IS DISTINCT FROM 'approved'
    OR actual.legal_approval_id IS DISTINCT FROM 'https://github.com/apdsoftware/postqron/issues/179#issuecomment-5090088911'
    OR actual.approved_at IS DISTINCT FROM '2026-07-27T10:15:46.000Z'::timestamptz
    OR actual.published_at IS DISTINCT FROM '2026-07-27T10:15:46.000Z'::timestamptz
    OR actual.effective_at IS DISTINCT FROM '2026-07-27T10:15:46.000Z'::timestamptz
    OR actual.superseded_at IS NOT NULL
    OR actual.permanent_url IS DISTINCT FROM '/api/v1/legal-documents/terms_it/versions/0.2'
    OR actual.current_url IS DISTINCT FROM '/api/v1/legal-documents/terms_it/current'
    OR actual.change_type IS DISTINCT FROM 'material'
  THEN
    RAISE EXCEPTION
      'terms_it % bootstrap migration: an existing compliance_legal_documents row for terms_it/IT/it-IT/% diverges from the F25-approved bundle (ref %); refusing to mask the conflict',
      '0.2', '0.2', 'https://github.com/apdsoftware/postqron/issues/179#issuecomment-5090088911';
  END IF;

  INSERT INTO compliance_legal_documents (
      document_key,
      jurisdiction,
      locale,
      version,
      content_bytes,
      digest_sha256,
      content_status,
      legal_approval_id,
      approved_at,
      published_at,
      effective_at,
      permanent_url,
      current_url,
      change_type
  ) VALUES (
      'privacy_it',
      'IT',
      'it-IT',
      '0.1',
      expected_privacy_it_content,
      'e9bd3260ec45259f92e84592f988be9886423d69f3c8ddb84ab8f03a39b1a660',
      'approved',
      'LEGAL-APPROVAL-2026-07-25-F25',
      '2026-07-25T20:16:56.000Z'::timestamptz,
      '2026-07-25T20:16:56.000Z'::timestamptz,
      '2026-07-25T20:16:56.000Z'::timestamptz,
      '/api/v1/legal-documents/privacy_it/versions/0.1',
      '/api/v1/legal-documents/privacy_it/current',
      'material'
  )
  ON CONFLICT (document_key, jurisdiction, locale, version) DO NOTHING;

  SELECT * INTO actual
  FROM compliance_legal_documents
  WHERE document_key = 'privacy_it'
    AND jurisdiction = 'IT'
    AND locale = 'it-IT'
    AND version = '0.1';

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'privacy_it % bootstrap migration: expected row is missing after insert',
      '0.1';
  END IF;

  IF actual.content_bytes IS DISTINCT FROM expected_privacy_it_content
    OR actual.digest_sha256 IS DISTINCT FROM 'e9bd3260ec45259f92e84592f988be9886423d69f3c8ddb84ab8f03a39b1a660'
    OR actual.content_status IS DISTINCT FROM 'approved'
    OR actual.legal_approval_id IS DISTINCT FROM 'LEGAL-APPROVAL-2026-07-25-F25'
    OR actual.approved_at IS DISTINCT FROM '2026-07-25T20:16:56.000Z'::timestamptz
    OR actual.published_at IS DISTINCT FROM '2026-07-25T20:16:56.000Z'::timestamptz
    OR actual.effective_at IS DISTINCT FROM '2026-07-25T20:16:56.000Z'::timestamptz
    OR actual.superseded_at IS NOT NULL
    OR actual.permanent_url IS DISTINCT FROM '/api/v1/legal-documents/privacy_it/versions/0.1'
    OR actual.current_url IS DISTINCT FROM '/api/v1/legal-documents/privacy_it/current'
    OR actual.change_type IS DISTINCT FROM 'material'
  THEN
    RAISE EXCEPTION
      'privacy_it % bootstrap migration: an existing compliance_legal_documents row for privacy_it/IT/it-IT/% diverges from the F25-approved bundle (ref %); refusing to mask the conflict',
      '0.1', '0.1', 'LEGAL-APPROVAL-2026-07-25-F25';
  END IF;
END;
$$;
