-- Materializes the F25-approved `cookies_it` release into the F13
-- compliance ledger (`compliance_legal_documents`). Generated by
-- `node --experimental-strip-types features/f25-legal-documents/scripts/build-cookie-consent-seed.ts`
-- from the canonical bundle in `features/f25-legal-documents/src/bundle.ts`
-- (ref. LEGAL-APPROVAL-2026-07-25-F25). Do not hand-edit this file — change
-- the source corpus or the generation script and regenerate instead.
--
-- Fixes the production defect where F26's cookie-preferences API returned
-- `503 cookie_policy_unavailable` because no approved `cookies_it` row
-- existed in the runtime ledger, even though the corpus was approved.
--
-- `ON CONFLICT DO NOTHING` makes a re-run idempotent, but it must never
-- silently mask a pre-existing row that diverges from the approved bundle
-- (hand edit, corruption, a stale release, ...). So after the insert
-- no-ops or succeeds, this block re-reads the row and fails the migration
-- explicitly if any field does not match the bundle exactly.
DO $$
DECLARE
  expected_content bytea := convert_to($cookies_it_v0_1_content$# Informativa sui Cookie di Postqron

## 1. Chi emette questa informativa

La presente Informativa sui Cookie è emessa da Apdsoftware di Carlo Zuffetti (Via C. Colombo 15, 24047 Treviglio (BG), Italia, P.IVA 03835250162, REA BG 431224), operante con il marchio APDSoftware quale gestore del servizio di pianificazione per i social media Postqron ("Postqron", "noi"; dati anagrafici verificati tramite fonte pubblica: https://mailronix.com/terms, consultata il 2026-07-25), contattabile all'indirizzo privacy@postqron.com e all'indirizzo https://apdsoftware.it.

## 2. Cosa copre questa informativa

Questa informativa spiega come vengono utilizzati cookie, l'archiviazione locale del browser (local storage) e tecnologie simili sul sito postqron.com e all'interno dell'applicazione Postqron. Le tue scelte relative alle tecnologie non essenziali vengono raccolte tramite un meccanismo di consenso che organizza le tecnologie in quattro categorie: **necessari**, **preferenze**, **analitici** e **marketing**. Solo la categoria **necessari** è attiva prima di effettuare qualsiasi scelta. Le altre tre categorie richiedono il tuo consenso esplicito (opt-in) e nulla di classificato al loro interno viene caricato o eseguito prima che tu abbia espresso il consenso.

## 3. Inventario dei cookie

La tabella seguente elenca ogni cookie, elemento di local storage e script di terze parti attualmente in uso da Postqron. Questo inventario è esaustivo alla versione indicata sopra.

| Nome | Impostato da | Categoria | Finalità | Durata | Prima/terza parte |
|---|---|---|---|---|---|
| `__Host-postqron_session` | Backend Postqron (autenticazione) | necessari | Autentica la sessione con accesso effettuato | Durata della sessione, legata alla scadenza della sessione | Prima parte |
| `__Host-postqron_cookie_subject` | Backend Postqron (servizio di consenso cookie) | necessari | Identificatore pseudonimo anonimo usato per registrare e applicare la tua scelta sui cookie prima dell'accesso | 183 giorni (6 mesi) | Prima parte |
| `postqron_locale` | Frontend Postqron | necessari (funzionali) | Ricorda la lingua dell'interfaccia selezionata; non contiene dati personali | 365 giorni | Prima parte |
| `postqron.cookie-choice` (local storage del browser, non un cookie) | Frontend Postqron | necessari (funzionali) | Cache lato client della scelta sui cookie già confermata con il nostro server | Fino alla cancellazione o all'aggiornamento con una nuova scelta | Prima parte, solo local storage, non inviato ad alcun server |
| Script di checkout Paddle (`https://cdn.paddle.com/paddle/v2/paddle.js`) ed eventuali cookie da esso impostati | Paddle | Non classificato da Postqron — interamente disciplinato da Paddle | Caricato solo nella pagina di fatturazione/checkout per elaborare il pagamento | Disciplinato da Paddle, non impostato né controllato da Postqron | Terza parte, limitato rigorosamente al flusso di checkout |

## 4. Nessun tracciante di analitica, preferenze o marketing ad oggi

Alla data di questa versione, Postqron non imposta né carica alcun cookie, pixel, SDK o script nelle categorie **preferenze**, **analitici** o **marketing**. Queste categorie esistono all'interno del meccanismo di consenso per un possibile uso futuro, sono strettamente opt-in e attualmente presentano zero traccianti registrati. Nulla viene tracciato, misurato o utilizzato per finalità di targeting al loro interno oggi. Qualora ciò cambiasse, l'inventario della Sezione 3 sarà aggiornato e agli utenti verrà richiesta una nuova scelta di consenso prima che venga caricata qualsiasi nuova tecnologia non essenziale.

## 5. Le tue scelte

Alla tua prima visita, nessuna tecnologia opzionale viene caricata prima che tu effettui una scelta. Il banner di consenso presenta "Accetta tutti", "Rifiuta tutti" e "Personalizza" con pari evidenza visiva, senza opzioni preselezionate a nostro favore. Una scelta registrata viene conservata per un massimo di 6 mesi. Puoi rivedere o modificare la tua scelta in qualsiasi momento tramite il link "Rivedi le tue scelte sui cookie" disponibile nel piè di pagina del sito o nell'area account; revocare il consenso non richiede più passaggi rispetto a concederlo. La revoca del consenso interrompe immediatamente qualsiasi nuova lettura o scrittura delle tecnologie non necessarie e rimuove gli eventuali cookie a cui puoi accedere in tali categorie.

## 6. Contatti

Per domande su questa Informativa sui Cookie, contattaci all'indirizzo privacy@postqron.com.$cookies_it_v0_1_content$, 'UTF8');
  actual compliance_legal_documents%ROWTYPE;
BEGIN
  INSERT INTO compliance_legal_documents (
      document_key,
      jurisdiction,
      locale,
      version,
      content_bytes,
      digest_sha256,
      content_status,
      legal_approval_id,
      approved_at,
      published_at,
      effective_at,
      permanent_url,
      current_url,
      change_type
  ) VALUES (
      'cookies_it',
      'IT',
      'it-IT',
      '0.1',
      expected_content,
      '9f6e657791afa9c0f54a448ffcdaf031cc244e218f2bbea27ed1d1563cf8bd33',
      'approved',
      'LEGAL-APPROVAL-2026-07-25-F25',
      '2026-07-25T20:16:56.000Z'::timestamptz,
      '2026-07-25T20:16:56.000Z'::timestamptz,
      '2026-07-25T20:16:56.000Z'::timestamptz,
      '/api/v1/legal-documents/cookies_it/versions/0.1',
      '/api/v1/legal-documents/cookies_it/current',
      'material'
  )
  ON CONFLICT (document_key, jurisdiction, locale, version) DO NOTHING;

  SELECT * INTO actual
  FROM compliance_legal_documents
  WHERE document_key = 'cookies_it'
    AND jurisdiction = 'IT'
    AND locale = 'it-IT'
    AND version = '0.1';

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'cookies_it % seed migration: expected row is missing after insert',
      '0.1';
  END IF;

  IF actual.content_bytes IS DISTINCT FROM expected_content
    OR actual.digest_sha256 IS DISTINCT FROM '9f6e657791afa9c0f54a448ffcdaf031cc244e218f2bbea27ed1d1563cf8bd33'
    OR actual.content_status IS DISTINCT FROM 'approved'
    OR actual.legal_approval_id IS DISTINCT FROM 'LEGAL-APPROVAL-2026-07-25-F25'
    OR actual.approved_at IS DISTINCT FROM '2026-07-25T20:16:56.000Z'::timestamptz
    OR actual.published_at IS DISTINCT FROM '2026-07-25T20:16:56.000Z'::timestamptz
    OR actual.effective_at IS DISTINCT FROM '2026-07-25T20:16:56.000Z'::timestamptz
    OR actual.superseded_at IS NOT NULL
    OR actual.permanent_url IS DISTINCT FROM '/api/v1/legal-documents/cookies_it/versions/0.1'
    OR actual.current_url IS DISTINCT FROM '/api/v1/legal-documents/cookies_it/current'
    OR actual.change_type IS DISTINCT FROM 'material'
  THEN
    RAISE EXCEPTION
      'cookies_it % seed migration: an existing compliance_legal_documents row for cookies_it/IT/it-IT/% diverges from the F25-approved bundle (ref %); refusing to mask the conflict',
      '0.1', '0.1', 'LEGAL-APPROVAL-2026-07-25-F25';
  END IF;
END;
$$;
