import { defineCatalogs } from '../../f36-i18n/src/catalog.ts'

const en = {
  'nav.home': 'Pre-launch home',
  'nav.language': 'Language',
  'status.label': 'Private preview',
  'landing.eyebrow': 'Postqron is getting ready',
  'landing.title': 'Your social content, finally in order.',
  'landing.description': 'We are building a clear workspace to plan, schedule and track social content without scattered drafts and reminders.',
  'landing.valuePlan': 'Plan with confidence',
  'landing.valuePlanCopy': 'See what will be published, where and when in one editorial calendar.',
  'landing.valueAdapt': 'Adapt every channel',
  'landing.valueAdaptCopy': 'Prepare content once and catch channel-specific constraints before publishing.',
  'landing.valueKnow': 'Know what happened',
  'landing.valueKnowCopy': 'Follow every publication status and act quickly when something needs attention.',
  'landing.cta': 'Request early access',
  'landing.note': 'No purchase is available during pre-launch.',
  'landing.metaTitle': 'Postqron — Social publishing, in order',
  'landing.metaDescription': 'Postqron is preparing a simpler way to plan, schedule and track social content. Request early access.',
  'access.eyebrow': 'Early access',
  'access.title': 'Be among the first to try Postqron.',
  'access.description': 'Leave your email only to register this access request and receive its transactional confirmation.',
  'access.emailLabel': 'Email address',
  'access.emailHelp': 'We use this address for your access request. It does not subscribe you to marketing.',
  'access.consent': 'I consent to Postqron processing my email to handle this early-access request and send its confirmation.',
  'access.submit': 'Request access',
  'access.submitting': 'Sending request…',
  'access.successTitle': 'Request received',
  'access.success': 'If the address is valid, your access request has been recorded. Check your inbox for the transactional confirmation.',
  'access.error': 'We could not record the request. Please try again later or contact help@postqron.com.',
  'access.rateLimited': 'Too many attempts. Please wait a few minutes and try again.',
  'access.back': 'Back to the pre-launch page',
  'access.metaTitle': 'Request early access — Postqron',
  'access.metaDescription': 'Request early access to Postqron without joining a marketing list.',
  'footer.support': 'Support',
  'footer.privacy': 'Privacy',
  'footer.cookies': 'Cookies',
  'footer.terms': 'Terms',
  'footer.supportLabel': 'Email support at help@postqron.com',
} as const

const it = {
  'nav.home': 'Home pre-lancio',
  'nav.language': 'Lingua',
  'status.label': 'Anteprima privata',
  'landing.eyebrow': 'Postqron si sta preparando',
  'landing.title': 'I tuoi contenuti social, finalmente in ordine.',
  'landing.description': 'Stiamo costruendo uno spazio chiaro per pianificare, programmare e controllare i contenuti social senza bozze e promemoria sparsi.',
  'landing.valuePlan': 'Pianifica con sicurezza',
  'landing.valuePlanCopy': 'Vedi cosa verrà pubblicato, dove e quando in un unico calendario editoriale.',
  'landing.valueAdapt': 'Adatta ogni canale',
  'landing.valueAdaptCopy': 'Prepara il contenuto una volta e intercetta i vincoli specifici prima della pubblicazione.',
  'landing.valueKnow': 'Conosci sempre l’esito',
  'landing.valueKnowCopy': 'Segui lo stato di ogni pubblicazione e intervieni rapidamente quando serve.',
  'landing.cta': 'Richiedi accesso anticipato',
  'landing.note': 'Durante il pre-lancio non è disponibile alcun acquisto.',
  'landing.metaTitle': 'Postqron — La pubblicazione social, in ordine',
  'landing.metaDescription': 'Postqron sta preparando un modo più semplice per pianificare, programmare e controllare i contenuti social. Richiedi accesso anticipato.',
  'access.eyebrow': 'Accesso anticipato',
  'access.title': 'Prova Postqron tra i primi.',
  'access.description': 'Lascia la tua email solo per registrare questa richiesta di accesso e ricevere la conferma transazionale.',
  'access.emailLabel': 'Indirizzo email',
  'access.emailHelp': 'Usiamo questo indirizzo per la richiesta di accesso. Non ti iscrive al marketing.',
  'access.consent': 'Acconsento al trattamento della mia email da parte di Postqron per gestire questa richiesta di accesso anticipato e inviare la relativa conferma.',
  'access.submit': 'Richiedi accesso',
  'access.submitting': 'Invio richiesta…',
  'access.successTitle': 'Richiesta ricevuta',
  'access.success': 'Se l’indirizzo è valido, la richiesta di accesso è stata registrata. Controlla la posta per la conferma transazionale.',
  'access.error': 'Non è stato possibile registrare la richiesta. Riprova più tardi o contatta help@postqron.com.',
  'access.rateLimited': 'Troppi tentativi. Attendi qualche minuto e riprova.',
  'access.back': 'Torna alla pagina di pre-lancio',
  'access.metaTitle': 'Richiedi accesso anticipato — Postqron',
  'access.metaDescription': 'Richiedi accesso anticipato a Postqron senza iscriverti a una lista marketing.',
  'footer.support': 'Supporto',
  'footer.privacy': 'Privacy',
  'footer.cookies': 'Cookie',
  'footer.terms': 'Termini',
  'footer.supportLabel': 'Scrivi al supporto a help@postqron.com',
} as const

const es = {
  'nav.home': 'Inicio de prelanzamiento',
  'nav.language': 'Idioma',
  'status.label': 'Vista previa privada',
  'landing.eyebrow': 'Postqron se está preparando',
  'landing.title': 'Tu contenido social, por fin en orden.',
  'landing.description': 'Estamos creando un espacio claro para planificar, programar y controlar el contenido social sin borradores ni recordatorios dispersos.',
  'landing.valuePlan': 'Planifica con confianza',
  'landing.valuePlanCopy': 'Consulta qué se publicará, dónde y cuándo en un único calendario editorial.',
  'landing.valueAdapt': 'Adapta cada canal',
  'landing.valueAdaptCopy': 'Prepara el contenido una vez y detecta las restricciones de cada canal antes de publicar.',
  'landing.valueKnow': 'Conoce siempre el resultado',
  'landing.valueKnowCopy': 'Sigue el estado de cada publicación y actúa rápido cuando sea necesario.',
  'landing.cta': 'Solicitar acceso anticipado',
  'landing.note': 'No se pueden realizar compras durante el prelanzamiento.',
  'landing.metaTitle': 'Postqron — Publicación social en orden',
  'landing.metaDescription': 'Postqron prepara una forma más sencilla de planificar, programar y controlar contenido social. Solicita acceso anticipado.',
  'access.eyebrow': 'Acceso anticipado',
  'access.title': 'Sé de los primeros en probar Postqron.',
  'access.description': 'Deja tu correo solo para registrar esta solicitud de acceso y recibir su confirmación transaccional.',
  'access.emailLabel': 'Correo electrónico',
  'access.emailHelp': 'Usamos esta dirección para tu solicitud. No te suscribe a comunicaciones de marketing.',
  'access.consent': 'Consiento que Postqron trate mi correo para gestionar esta solicitud de acceso anticipado y enviar su confirmación.',
  'access.submit': 'Solicitar acceso',
  'access.submitting': 'Enviando solicitud…',
  'access.successTitle': 'Solicitud recibida',
  'access.success': 'Si la dirección es válida, se ha registrado tu solicitud. Revisa tu bandeja de entrada para ver la confirmación transaccional.',
  'access.error': 'No pudimos registrar la solicitud. Inténtalo más tarde o contacta con help@postqron.com.',
  'access.rateLimited': 'Demasiados intentos. Espera unos minutos y vuelve a intentarlo.',
  'access.back': 'Volver a la página de prelanzamiento',
  'access.metaTitle': 'Solicita acceso anticipado — Postqron',
  'access.metaDescription': 'Solicita acceso anticipado a Postqron sin unirte a una lista de marketing.',
  'footer.support': 'Soporte',
  'footer.privacy': 'Privacidad',
  'footer.cookies': 'Cookies',
  'footer.terms': 'Términos',
  'footer.supportLabel': 'Escribe a soporte en help@postqron.com',
} as const

const fr = {
  'nav.home': 'Accueil du prélancement',
  'nav.language': 'Langue',
  'status.label': 'Aperçu privé',
  'landing.eyebrow': 'Postqron se prépare',
  'landing.title': 'Vos contenus sociaux, enfin en ordre.',
  'landing.description': 'Nous créons un espace clair pour planifier, programmer et suivre les contenus sociaux sans brouillons ni rappels dispersés.',
  'landing.valuePlan': 'Planifiez sereinement',
  'landing.valuePlanCopy': 'Visualisez quoi publier, où et quand dans un seul calendrier éditorial.',
  'landing.valueAdapt': 'Adaptez chaque canal',
  'landing.valueAdaptCopy': 'Préparez le contenu une fois et détectez les contraintes propres à chaque canal avant publication.',
  'landing.valueKnow': 'Connaissez toujours le résultat',
  'landing.valueKnowCopy': 'Suivez le statut de chaque publication et intervenez rapidement si nécessaire.',
  'landing.cta': 'Demander un accès anticipé',
  'landing.note': 'Aucun achat n’est proposé pendant le prélancement.',
  'landing.metaTitle': 'Postqron — La publication sociale, en ordre',
  'landing.metaDescription': 'Postqron prépare une manière plus simple de planifier, programmer et suivre les contenus sociaux. Demandez un accès anticipé.',
  'access.eyebrow': 'Accès anticipé',
  'access.title': 'Essayez Postqron parmi les premiers.',
  'access.description': 'Laissez votre e-mail uniquement pour enregistrer cette demande et recevoir sa confirmation transactionnelle.',
  'access.emailLabel': 'Adresse e-mail',
  'access.emailHelp': 'Cette adresse sert à votre demande d’accès. Elle ne vous inscrit pas au marketing.',
  'access.consent': 'J’accepte que Postqron traite mon e-mail pour gérer cette demande d’accès anticipé et envoyer sa confirmation.',
  'access.submit': 'Demander l’accès',
  'access.submitting': 'Envoi de la demande…',
  'access.successTitle': 'Demande reçue',
  'access.success': 'Si l’adresse est valide, votre demande a été enregistrée. Consultez votre boîte de réception pour la confirmation transactionnelle.',
  'access.error': 'La demande n’a pas pu être enregistrée. Réessayez plus tard ou contactez help@postqron.com.',
  'access.rateLimited': 'Trop de tentatives. Patientez quelques minutes avant de réessayer.',
  'access.back': 'Retour à la page de prélancement',
  'access.metaTitle': 'Demander un accès anticipé — Postqron',
  'access.metaDescription': 'Demandez un accès anticipé à Postqron sans rejoindre de liste marketing.',
  'footer.support': 'Assistance',
  'footer.privacy': 'Confidentialité',
  'footer.cookies': 'Cookies',
  'footer.terms': 'Conditions',
  'footer.supportLabel': 'Écrire à l’assistance à help@postqron.com',
} as const

const de = {
  'nav.home': 'Prelaunch-Startseite',
  'nav.language': 'Sprache',
  'status.label': 'Private Vorschau',
  'landing.eyebrow': 'Postqron macht sich bereit',
  'landing.title': 'Deine Social-Media-Inhalte, endlich geordnet.',
  'landing.description': 'Wir entwickeln einen übersichtlichen Ort zum Planen, Terminieren und Verfolgen von Social-Media-Inhalten – ohne verstreute Entwürfe und Erinnerungen.',
  'landing.valuePlan': 'Sicher planen',
  'landing.valuePlanCopy': 'Sieh in einem Redaktionskalender, was wann und wo veröffentlicht wird.',
  'landing.valueAdapt': 'Jeden Kanal anpassen',
  'landing.valueAdaptCopy': 'Bereite Inhalte einmal vor und erkenne kanalspezifische Vorgaben vor der Veröffentlichung.',
  'landing.valueKnow': 'Das Ergebnis immer kennen',
  'landing.valueKnowCopy': 'Verfolge jeden Veröffentlichungsstatus und reagiere schnell, wenn etwas Aufmerksamkeit braucht.',
  'landing.cta': 'Frühzugang anfragen',
  'landing.note': 'Während des Prelaunch ist kein Kauf möglich.',
  'landing.metaTitle': 'Postqron — Social Publishing, geordnet',
  'landing.metaDescription': 'Postqron bereitet eine einfachere Art vor, Social-Media-Inhalte zu planen, zu terminieren und zu verfolgen. Frage Frühzugang an.',
  'access.eyebrow': 'Frühzugang',
  'access.title': 'Teste Postqron als eine der ersten Personen.',
  'access.description': 'Hinterlasse deine E-Mail nur, um diese Zugangsanfrage zu registrieren und die transaktionale Bestätigung zu erhalten.',
  'access.emailLabel': 'E-Mail-Adresse',
  'access.emailHelp': 'Wir verwenden diese Adresse für deine Anfrage. Sie meldet dich nicht für Marketing an.',
  'access.consent': 'Ich stimme zu, dass Postqron meine E-Mail zur Bearbeitung dieser Frühzugangsanfrage und für deren Bestätigung verarbeitet.',
  'access.submit': 'Zugang anfragen',
  'access.submitting': 'Anfrage wird gesendet…',
  'access.successTitle': 'Anfrage erhalten',
  'access.success': 'Wenn die Adresse gültig ist, wurde deine Anfrage registriert. Prüfe deinen Posteingang auf die transaktionale Bestätigung.',
  'access.error': 'Die Anfrage konnte nicht registriert werden. Versuche es später erneut oder kontaktiere help@postqron.com.',
  'access.rateLimited': 'Zu viele Versuche. Warte einige Minuten und versuche es erneut.',
  'access.back': 'Zurück zur Prelaunch-Seite',
  'access.metaTitle': 'Frühzugang anfragen — Postqron',
  'access.metaDescription': 'Frage Frühzugang zu Postqron an, ohne dich für eine Marketingliste anzumelden.',
  'footer.support': 'Support',
  'footer.privacy': 'Datenschutz',
  'footer.cookies': 'Cookies',
  'footer.terms': 'Bedingungen',
  'footer.supportLabel': 'Support unter help@postqron.com kontaktieren',
} as const

export const PRELAUNCH_CATALOGS = defineCatalogs({ en, it, es, fr, de })
export type PrelaunchMessageKey = keyof typeof en
