import { defineCatalogs } from '../../f36-i18n/src/catalog.ts'

const en = {
  'footer.description': 'Plan and manage your social content from one place.',
  'footer.productNavLabel': 'Product information',
  'footer.productHeading': 'Product',
  'footer.features': 'Features',
  'footer.pricing': 'Pricing',
  'footer.faq': 'FAQ',
  'footer.contact': 'Contact',
  'footer.supportHeading': 'Support',
  'footer.supportLinkLabel': 'Email support at {email}',
  'footer.legalNavLabel': 'Legal documents',
  'footer.legalHeading': 'Legal',
  'footer.terms': 'Terms and conditions',
  'footer.privacy': 'Privacy Policy',
  'footer.cookies': 'Cookie Policy',
  'footer.manageCookies': 'Manage cookies',
  'footer.developedBy': 'Developed by',
  'page.eyebrow': 'Contact',
  'page.title': 'How can we help?',
  'page.description': 'Write to our support team for help with your account, publishing, billing, privacy, or product use.',
  'page.emailHeading': 'Email support',
  'page.emailDescription': 'Your message goes directly to the Postqron support channel.',
  'page.emailLinkLabel': 'Write to {email}',
  'page.responseHeading': 'Response time',
  'page.responseTiming': {
    one: 'We normally acknowledge requests within {count} business day.',
    other: 'We normally acknowledge requests within {count} business days.',
  },
  'page.responseNote': 'Urgent security or service incidents are triaged according to their severity.',
  'page.includeHeading': 'What to include',
  'page.includeIntro': 'A few details help us understand and resolve your request more quickly:',
  'page.includeAccount': 'The email address associated with your Postqron account.',
  'page.includeSummary': 'A concise description of what you expected and what happened.',
  'page.includeSteps': 'The steps to reproduce the issue, including date, time, and time zone when relevant.',
  'page.includeEvidence': 'Screenshots or error references with passwords, access tokens, and other secrets removed.',
  'page.safetyHeading': 'Protect sensitive information',
  'page.safetyDescription': 'Never send passwords, access tokens, recovery codes, payment card details, or unnecessary personal data by email.',
  'page.metaTitle': 'Contact Postqron support',
  'page.metaDescription': 'Contact Postqron support by email and learn what information to include and when to expect a response.',
} as const

const it = {
  'footer.description': 'Programma e gestisci i tuoi contenuti social da un unico spazio.',
  'footer.productNavLabel': 'Informazioni sul prodotto',
  'footer.productHeading': 'Prodotto',
  'footer.features': 'Funzionalità',
  'footer.pricing': 'Prezzi',
  'footer.faq': 'FAQ',
  'footer.contact': 'Contatti',
  'footer.supportHeading': 'Supporto',
  'footer.supportLinkLabel': 'Scrivi al supporto a {email}',
  'footer.legalNavLabel': 'Documenti legali',
  'footer.legalHeading': 'Legale',
  'footer.terms': 'Termini e condizioni',
  'footer.privacy': 'Privacy Policy',
  'footer.cookies': 'Cookie Policy',
  'footer.manageCookies': 'Gestisci cookie',
  'footer.developedBy': 'Sviluppato da',
  'page.eyebrow': 'Contatti',
  'page.title': 'Come possiamo aiutarti?',
  'page.description': 'Scrivi al nostro team di supporto per ricevere assistenza su account, pubblicazione, fatturazione, privacy o utilizzo del prodotto.',
  'page.emailHeading': 'Supporto via email',
  'page.emailDescription': 'Il tuo messaggio arriva direttamente al canale di supporto Postqron.',
  'page.emailLinkLabel': 'Scrivi a {email}',
  'page.responseHeading': 'Tempi di risposta',
  'page.responseTiming': {
    one: 'Normalmente confermiamo la presa in carico entro {count} giorno lavorativo.',
    other: 'Normalmente confermiamo la presa in carico entro {count} giorni lavorativi.',
  },
  'page.responseNote': 'Gli incidenti urgenti di sicurezza o servizio vengono classificati in base alla gravità.',
  'page.includeHeading': 'Cosa includere',
  'page.includeIntro': 'Alcuni dettagli ci aiutano a comprendere e risolvere più rapidamente la richiesta:',
  'page.includeAccount': 'L’indirizzo email associato al tuo account Postqron.',
  'page.includeSummary': 'Una descrizione concisa di ciò che ti aspettavi e di cosa è accaduto.',
  'page.includeSteps': 'I passaggi per riprodurre il problema, inclusi data, ora e fuso orario quando rilevanti.',
  'page.includeEvidence': 'Screenshot o riferimenti di errore da cui siano stati rimossi password, token di accesso e altri segreti.',
  'page.safetyHeading': 'Proteggi le informazioni sensibili',
  'page.safetyDescription': 'Non inviare mai via email password, token di accesso, codici di recupero, dati di carte di pagamento o dati personali non necessari.',
  'page.metaTitle': 'Contatta il supporto Postqron',
  'page.metaDescription': 'Contatta via email il supporto Postqron e scopri quali informazioni includere e quando aspettarti una risposta.',
} as const

const es = {
  'footer.description': 'Programa y gestiona tu contenido social desde un único lugar.',
  'footer.productNavLabel': 'Información del producto',
  'footer.productHeading': 'Producto',
  'footer.features': 'Funciones',
  'footer.pricing': 'Precios',
  'footer.faq': 'Preguntas frecuentes',
  'footer.contact': 'Contacto',
  'footer.supportHeading': 'Soporte',
  'footer.supportLinkLabel': 'Escribe al soporte en {email}',
  'footer.legalNavLabel': 'Documentos legales',
  'footer.legalHeading': 'Legal',
  'footer.terms': 'Términos y condiciones',
  'footer.privacy': 'Política de privacidad',
  'footer.cookies': 'Política de cookies',
  'footer.manageCookies': 'Gestionar cookies',
  'footer.developedBy': 'Desarrollado por',
  'page.eyebrow': 'Contacto',
  'page.title': '¿Cómo podemos ayudarte?',
  'page.description': 'Escribe a nuestro equipo de soporte para obtener ayuda con tu cuenta, publicaciones, facturación, privacidad o uso del producto.',
  'page.emailHeading': 'Soporte por correo',
  'page.emailDescription': 'Tu mensaje llega directamente al canal de soporte de Postqron.',
  'page.emailLinkLabel': 'Escribe a {email}',
  'page.responseHeading': 'Tiempo de respuesta',
  'page.responseTiming': {
    one: 'Normalmente confirmamos la recepción en un plazo de {count} día laborable.',
    other: 'Normalmente confirmamos la recepción en un plazo de {count} días laborables.',
  },
  'page.responseNote': 'Los incidentes urgentes de seguridad o servicio se clasifican según su gravedad.',
  'page.includeHeading': 'Qué debes incluir',
  'page.includeIntro': 'Algunos detalles nos ayudan a comprender y resolver tu solicitud más rápidamente:',
  'page.includeAccount': 'La dirección de correo asociada a tu cuenta de Postqron.',
  'page.includeSummary': 'Una descripción concisa de lo que esperabas y lo que ocurrió.',
  'page.includeSteps': 'Los pasos para reproducir el problema, con fecha, hora y zona horaria cuando corresponda.',
  'page.includeEvidence': 'Capturas o referencias de error sin contraseñas, tokens de acceso ni otros secretos.',
  'page.safetyHeading': 'Protege la información sensible',
  'page.safetyDescription': 'Nunca envíes por correo contraseñas, tokens de acceso, códigos de recuperación, datos de tarjetas de pago ni datos personales innecesarios.',
  'page.metaTitle': 'Contacta con el soporte de Postqron',
  'page.metaDescription': 'Contacta por correo con el soporte de Postqron y consulta qué información incluir y cuándo esperar una respuesta.',
} as const

const fr = {
  'footer.description': 'Planifiez et gérez vos contenus sociaux depuis un espace unique.',
  'footer.productNavLabel': 'Informations sur le produit',
  'footer.productHeading': 'Produit',
  'footer.features': 'Fonctionnalités',
  'footer.pricing': 'Tarifs',
  'footer.faq': 'FAQ',
  'footer.contact': 'Contact',
  'footer.supportHeading': 'Assistance',
  'footer.supportLinkLabel': 'Écrire à l’assistance à {email}',
  'footer.legalNavLabel': 'Documents juridiques',
  'footer.legalHeading': 'Juridique',
  'footer.terms': 'Conditions générales',
  'footer.privacy': 'Politique de confidentialité',
  'footer.cookies': 'Politique relative aux cookies',
  'footer.manageCookies': 'Gérer les cookies',
  'footer.developedBy': 'Développé par',
  'page.eyebrow': 'Contact',
  'page.title': 'Comment pouvons-nous vous aider ?',
  'page.description': 'Écrivez à notre équipe d’assistance pour toute question concernant votre compte, la publication, la facturation, la confidentialité ou l’utilisation du produit.',
  'page.emailHeading': 'Assistance par e-mail',
  'page.emailDescription': 'Votre message est envoyé directement au canal d’assistance de Postqron.',
  'page.emailLinkLabel': 'Écrire à {email}',
  'page.responseHeading': 'Délai de réponse',
  'page.responseTiming': {
    one: 'Nous accusons normalement réception sous {count} jour ouvré.',
    other: 'Nous accusons normalement réception sous {count} jours ouvrés.',
  },
  'page.responseNote': 'Les incidents urgents de sécurité ou de service sont traités selon leur gravité.',
  'page.includeHeading': 'Informations à inclure',
  'page.includeIntro': 'Quelques détails nous aident à comprendre et résoudre votre demande plus rapidement :',
  'page.includeAccount': 'L’adresse e-mail associée à votre compte Postqron.',
  'page.includeSummary': 'Une description concise du résultat attendu et de ce qui s’est produit.',
  'page.includeSteps': 'Les étapes permettant de reproduire le problème, avec la date, l’heure et le fuseau horaire si nécessaire.',
  'page.includeEvidence': 'Des captures d’écran ou références d’erreur sans mots de passe, jetons d’accès ni autres secrets.',
  'page.safetyHeading': 'Protégez les informations sensibles',
  'page.safetyDescription': 'N’envoyez jamais par e-mail de mots de passe, jetons d’accès, codes de récupération, données de carte de paiement ou données personnelles inutiles.',
  'page.metaTitle': 'Contacter l’assistance Postqron',
  'page.metaDescription': 'Contactez l’assistance Postqron par e-mail et découvrez les informations à inclure ainsi que le délai de réponse.',
} as const

const de = {
  'footer.description': 'Plane und verwalte deine Social-Media-Inhalte an einem Ort.',
  'footer.productNavLabel': 'Produktinformationen',
  'footer.productHeading': 'Produkt',
  'footer.features': 'Funktionen',
  'footer.pricing': 'Preise',
  'footer.faq': 'FAQ',
  'footer.contact': 'Kontakt',
  'footer.supportHeading': 'Support',
  'footer.supportLinkLabel': 'Support unter {email} kontaktieren',
  'footer.legalNavLabel': 'Rechtliche Dokumente',
  'footer.legalHeading': 'Rechtliches',
  'footer.terms': 'Allgemeine Geschäftsbedingungen',
  'footer.privacy': 'Datenschutzerklärung',
  'footer.cookies': 'Cookie-Richtlinie',
  'footer.manageCookies': 'Cookies verwalten',
  'footer.developedBy': 'Entwickelt von',
  'page.eyebrow': 'Kontakt',
  'page.title': 'Wie können wir helfen?',
  'page.description': 'Schreibe unserem Support-Team, wenn du Hilfe mit deinem Konto, Veröffentlichungen, Abrechnung, Datenschutz oder der Produktnutzung brauchst.',
  'page.emailHeading': 'E-Mail-Support',
  'page.emailDescription': 'Deine Nachricht erreicht direkt den Support-Kanal von Postqron.',
  'page.emailLinkLabel': 'E-Mail an {email}',
  'page.responseHeading': 'Antwortzeit',
  'page.responseTiming': {
    one: 'Wir bestätigen Anfragen normalerweise innerhalb von {count} Werktag.',
    other: 'Wir bestätigen Anfragen normalerweise innerhalb von {count} Werktagen.',
  },
  'page.responseNote': 'Dringende Sicherheits- oder Servicevorfälle werden entsprechend ihrem Schweregrad eingestuft.',
  'page.includeHeading': 'Was du angeben solltest',
  'page.includeIntro': 'Einige Angaben helfen uns, deine Anfrage schneller zu verstehen und zu lösen:',
  'page.includeAccount': 'Die E-Mail-Adresse, die mit deinem Postqron-Konto verknüpft ist.',
  'page.includeSummary': 'Eine kurze Beschreibung des erwarteten und des tatsächlichen Verhaltens.',
  'page.includeSteps': 'Schritte zum Nachvollziehen des Problems, gegebenenfalls mit Datum, Uhrzeit und Zeitzone.',
  'page.includeEvidence': 'Screenshots oder Fehlerreferenzen ohne Passwörter, Zugriffstoken oder andere Geheimnisse.',
  'page.safetyHeading': 'Schütze vertrauliche Informationen',
  'page.safetyDescription': 'Sende niemals Passwörter, Zugriffstoken, Wiederherstellungscodes, Zahlungskartendaten oder unnötige personenbezogene Daten per E-Mail.',
  'page.metaTitle': 'Postqron-Support kontaktieren',
  'page.metaDescription': 'Kontaktiere den Postqron-Support per E-Mail und erfahre, welche Angaben hilfreich sind und wann du eine Antwort erwarten kannst.',
} as const

export const SUPPORT_CONTACT_CATALOGS = defineCatalogs({
  en,
  it,
  es,
  fr,
  de,
})

export type SupportContactMessageKey = keyof typeof en
