export const APP_SHELL_LOCALES = ['en', 'it', 'es', 'fr', 'de'] as const
export type AppShellLocale = typeof APP_SHELL_LOCALES[number]

const en = {
  'documentTitle.app': 'Sign in or create an account — Postqron',
  'documentTitle.callback': 'Completing sign-in — Postqron',
  'documentTitle.onboarding': 'Set up your workspace — Postqron',
  'documentTitle.home': 'Workspace overview — Postqron',
  'documentTitle.feature': 'Feature workspace — Postqron',
  'auth.eyebrow': 'Postqron workspace',
  'auth.title': 'Plan, publish, and keep every channel in view.',
  'auth.description': 'Sign in with your email and password. Configured external providers remain optional.',
  'auth.newAccount': 'Create an account',
  'auth.existingAccount': 'Sign in',
  'auth.email': 'Email address',
  'auth.password': 'Password',
  'auth.passwordSubmit': 'Sign in with email',
  'auth.signingIn': 'Signing in…',
  'auth.orProvider': 'or use an optional provider',
  'auth.consentBefore': 'I accept the',
  'auth.terms': 'Terms and Conditions',
  'auth.consentAnd': 'and the',
  'auth.privacy': 'Privacy Policy',
  'auth.consentAfter': '.',
  'auth.provider.google': 'Continue with Google',
  'auth.provider.apple': 'Continue with Apple',
  'auth.provider.facebook': 'Continue with Facebook',
  'auth.provider.linkedin': 'Continue with LinkedIn',
  'auth.providerUnavailable': 'This sign-in method is not configured.',
  'auth.requiredConsent': 'Accept the required documents before continuing.',
  'auth.configurationError': 'Sign-in is temporarily unavailable because configuration is incomplete.',
  'auth.invalidParameters': 'The selected plan details are not valid. Return to pricing and try again.',
  'auth.offline': 'Postqron cannot reach the sign-in service. Check your connection and try again.',
  'auth.retry': 'Try again',
  'callback.loading': 'Completing secure sign-in…',
  'callback.title': 'We could not complete sign-in',
  'callback.description': 'The provider response was declined, expired, or incomplete. No session was created.',
  'callback.retry': 'Return to sign-in',
  'onboarding.eyebrow': 'One last step',
  'onboarding.title': 'Set up your workspace',
  'onboarding.description': 'Confirm the required documents and choose where you want to work.',
  'onboarding.create': 'Create a new workspace',
  'onboarding.select': 'Use an existing workspace',
  'onboarding.workspaceName': 'Workspace name',
  'onboarding.workspacePlaceholder': 'My workspace',
  'onboarding.workspaceChoice': 'Workspace',
  'onboarding.submit': 'Open Postqron',
  'onboarding.saving': 'Setting up your workspace…',
  'onboarding.error': 'We could not finish setup. Your choices were not lost; try again.',
  'shell.skip': 'Skip to main content',
  'shell.navigation': 'Product navigation',
  'shell.home': 'Home',
  'shell.workspace': 'Current workspace',
  'shell.profile': 'Profile',
  'shell.logout': 'Sign out',
  'shell.menu': 'Open navigation',
  'shell.closeMenu': 'Close navigation',
  'home.eyebrow': 'Workspace overview',
  'home.welcome': 'Welcome, {name}',
  'home.description': 'Your product shell is ready. Connected features appear here without changing this navigation.',
  'home.getStarted': 'Start by connecting a social channel or creating a draft.',
  'state.loading.title': 'Loading your workspace',
  'state.loading.description': 'Checking your secure session and workspace access.',
  'state.empty.title': 'Nothing here yet',
  'state.empty.description': 'This feature has an empty workspace slot ready for its first item.',
  'state.offline.title': 'You appear to be offline',
  'state.offline.description': 'Reconnect and retry. Postqron has not discarded your work.',
  'state.denied.title': 'Access denied',
  'state.denied.description': 'Your account does not have access to this workspace or feature.',
  'state.retry': 'Retry',
  'feature.title': 'Feature workspace',
  'feature.description': 'This route is reserved for its owning feature slice.',
  'documentTitle.profile': 'Your profile — Postqron',
  'documentTitle.security': 'Security settings — Postqron',
  'documentTitle.providers': 'Connected providers — Postqron',
  'documentTitle.plan': 'Plan and usage — Postqron',
  'documentTitle.workspace': 'Workspace settings — Postqron',
  'documentTitle.privacy': 'Privacy and exports — Postqron',
  'documentTitle.verifyEmail': 'Verify your email — Postqron',
  'auth.confirmation': 'Confirm password',
  'auth.registerSubmit': 'Create account',
  'auth.registering': 'Creating account…',
  'auth.registerError': 'We could not create your account. Review the details and try again.',
  'auth.signInError': 'We could not sign you in. Check your credentials and try again.',
  'auth.resend': 'Resend verification email',
  'auth.resending': 'Resending…',
  'auth.resendError': 'We could not resend the verification email. Try again in a moment.',
  'auth.verificationTitle': 'Check your inbox',
  'auth.verificationDescription': 'We sent a verification link to {email}. Confirm the address to continue.',
  'auth.verificationOpen': 'Open email verification page',
  'shell.nav.home': 'Home',
  'shell.nav.profile': 'Profile',
  'shell.nav.security': 'Security',
  'shell.nav.providers': 'Providers',
  'shell.nav.plan': 'Plan',
  'shell.nav.workspace': 'Workspace',
  'shell.nav.privacy': 'Privacy',
  'home.currentWorkspace': 'Current workspace',
  'home.currentRole': 'Role: {role}',
  'home.noWorkspace': 'No workspace selected',
  'home.currentPlanLabel': 'Current plan',
  'home.planUnknown': 'Plan unavailable',
  'home.providerCountLabel': 'Connected providers',
  'home.providerCountDescription': 'Review which sign-in and social connections protect this account.',
  'home.card.profile.eyebrow': 'Account details',
  'home.card.profile.title': 'Update your profile',
  'home.card.profile.description': 'Keep your name, language, and timezone aligned with your work.',
  'home.card.security.eyebrow': 'Access protection',
  'home.card.security.title': 'Review security',
  'home.card.security.description': 'Change your password, inspect access methods, and revoke sessions.',
  'home.card.providers.eyebrow': 'Connected identities',
  'home.card.providers.title': 'Manage providers',
  'home.card.providers.description': 'Link or disconnect available OAuth providers without leaving the app.',
  'home.card.plan.eyebrow': 'Commercial status',
  'home.card.plan.title': 'View plan usage',
  'home.card.plan.description': 'Check your active plan, limits, and current usage from authoritative data.',
  'home.card.workspace.eyebrow': 'Workspace access',
  'home.card.workspace.title': 'Manage workspace',
  'home.card.workspace.description': 'Switch workspaces, inspect members, and confirm your current role.',
  'home.card.privacy.eyebrow': 'Privacy controls',
  'home.card.privacy.title': 'Export or delete data',
  'home.card.privacy.description': 'Request exports, track deletion state, and manage the grace period.',
  'profile.eyebrow': 'Account profile',
  'profile.title': 'Profile',
  'profile.description': 'Keep your display name and regional preferences up to date.',
  'profile.displayName': 'Display name',
  'profile.email': 'Email address',
  'profile.locale': 'Preferred locale',
  'profile.timezone': 'Timezone',
  'profile.updatedAt': 'Last updated',
  'profile.emailStatus': 'Email verification',
  'profile.verified': 'Verified',
  'profile.unverified': 'Verification pending',
  'profile.saved': 'Your profile was updated.',
  'profile.error': 'We could not save your profile. Try again.',
  'profile.saving': 'Saving profile…',
  'profile.submit': 'Save profile',
  'security.eyebrow': 'Security',
  'security.title': 'Security settings',
  'security.description': 'Manage your password, sessions, and connected access methods.',
  'security.emailStatus': 'Primary email',
  'security.emailMissing': 'No email on file',
  'security.verified': 'Verified',
  'security.unverified': 'Verification pending',
  'security.methods': 'Access methods',
  'security.onlyMethod': 'required to keep account access',
  'security.changePassword': 'Change password',
  'security.currentPassword': 'Current password',
  'security.newPassword': 'New password',
  'security.confirmPassword': 'Confirm new password',
  'security.changeSubmit': 'Update password',
  'security.changing': 'Updating password…',
  'security.changed': 'Your password was updated.',
  'security.error': 'We could not complete the security action. Try again.',
  'security.sessions': 'Active sessions',
  'security.sessionsDescription': 'Revoke other active sessions if you suspect unwanted access.',
  'security.revokeSubmit': 'Revoke other sessions',
  'security.revoking': 'Revoking sessions…',
  'security.revoked': 'Other sessions were revoked.',
  'providers.eyebrow': 'Connected providers',
  'providers.title': 'Providers',
  'providers.description': 'Link supported sign-in providers and disconnect the ones you no longer use.',
  'providers.linkNew': 'Link a new provider',
  'providers.noAvailable': 'No additional configured providers are currently available.',
  'providers.connected': 'Connected methods',
  'providers.required': 'Required',
  'providers.disconnect': 'Disconnect',
  'providers.disconnecting': 'Disconnecting…',
  'providers.linked': 'Provider hand-off started in a new secure flow.',
  'providers.removed': 'Provider disconnected.',
  'providers.error': 'We could not update your providers. Try again.',
  'plan.eyebrow': 'Plan',
  'plan.title': 'Plan and usage',
  'plan.description': 'Review the current workspace plan, limits, and consumption.',
  'plan.current': 'Current subscription',
  'plan.unknown': 'Unavailable',
  'plan.usage': 'Usage',
  'plan.limits': 'Limits',
  'workspace.eyebrow': 'Workspace',
  'workspace.title': 'Workspace settings',
  'workspace.description': 'Inspect the selected workspace, the workspaces available to you, and current members.',
  'workspace.current': 'Selected workspace',
  'workspace.all': 'Available workspaces',
  'workspace.members': 'Members',
  'workspace.none': 'Unavailable',
  'privacy.eyebrow': 'Privacy',
  'privacy.title': 'Privacy and data controls',
  'privacy.description': 'Request exports, monitor deletion status, and manage grace-period actions.',
  'privacy.exportAccount': 'Account export',
  'privacy.exportWorkspace': 'Workspace export',
  'privacy.exportDescription': 'Prepare a privacy export with the currently available account data.',
  'privacy.requestExport': 'Request export',
  'privacy.requesting': 'Submitting request…',
  'privacy.deleteAccount': 'Delete account',
  'privacy.deleteWorkspace': 'Delete workspace',
  'privacy.deleteDescription': 'Deletion starts a protected grace period before final removal.',
  'privacy.requestDelete': 'Request deletion',
  'privacy.exportStatus': 'Export status',
  'privacy.download': 'Fetch secure download',
  'privacy.downloading': 'Loading export…',
  'privacy.deletionStatus': 'Deletion status',
  'privacy.cancelDeletion': 'Cancel deletion request',
  'privacy.cancelling': 'Cancelling request…',
  'privacy.statusNote': 'Deletion and export requests remain subject to retention and ownership rules.',
  'privacy.saved': 'Your privacy request was saved.',
  'privacy.error': 'We could not complete the privacy request. Try again.',
  'privacy.workspaceUnavailable': 'No owner workspace is currently available for this action.',
  'privacy.confirmAccountDeletion': 'Request account deletion? This starts the configured grace period.',
  'privacy.confirmWorkspaceDeletion': 'Request deletion for workspace "{workspace}"? This starts the configured grace period.',
  'verify.eyebrow': 'Email verification',
  'verify.title': 'Verify your email',
  'verify.description': 'Paste the same email address to request a fresh verification link.',
  'verify.success': 'If the address is valid, a verification action was completed or re-sent.',
  'verify.error': 'We could not verify or resend the email. Check the details and try again.',
  'verify.email': 'Email address',
  'verify.resend': 'Resend verification',
  'verify.resending': 'Resending…',
  'verify.return': 'Return to sign-in',
} as const

export type AppShellMessageKey = keyof typeof en
export type AppShellCatalog = Readonly<Record<AppShellMessageKey, string>>

const it: AppShellCatalog = {
  'documentTitle.app': 'Accedi o registrati — Postqron',
  'documentTitle.callback': 'Completamento dell’accesso — Postqron',
  'documentTitle.onboarding': 'Configura il workspace — Postqron',
  'documentTitle.home': 'Panoramica workspace — Postqron',
  'documentTitle.feature': 'Funzionalità — Postqron',
  'auth.eyebrow': 'Workspace Postqron',
  'auth.title': 'Pianifica, pubblica e tieni ogni canale sotto controllo.',
  'auth.description': 'Accedi con email e password. I provider esterni configurati restano opzionali.',
  'auth.newAccount': 'Crea un account',
  'auth.existingAccount': 'Accedi',
  'auth.email': 'Indirizzo email',
  'auth.password': 'Password',
  'auth.passwordSubmit': 'Accedi con email',
  'auth.signingIn': 'Accesso in corso…',
  'auth.orProvider': 'oppure usa un provider opzionale',
  'auth.consentBefore': 'Accetto i',
  'auth.terms': 'Termini e condizioni',
  'auth.consentAnd': 'e la',
  'auth.privacy': 'Privacy Policy',
  'auth.consentAfter': '.',
  'auth.provider.google': 'Continua con Google',
  'auth.provider.apple': 'Continua con Apple',
  'auth.provider.facebook': 'Continua con Facebook',
  'auth.provider.linkedin': 'Continua con LinkedIn',
  'auth.providerUnavailable': 'Questo metodo di accesso non è configurato.',
  'auth.requiredConsent': 'Accetta i documenti obbligatori prima di continuare.',
  'auth.configurationError': 'L’accesso è temporaneamente indisponibile perché la configurazione è incompleta.',
  'auth.invalidParameters': 'I dettagli del piano selezionato non sono validi. Torna ai prezzi e riprova.',
  'auth.offline': 'Postqron non riesce a raggiungere il servizio di accesso. Controlla la connessione e riprova.',
  'auth.retry': 'Riprova',
  'callback.loading': 'Completamento dell’accesso sicuro…',
  'callback.title': 'Non è stato possibile completare l’accesso',
  'callback.description': 'La risposta del provider è stata negata, è scaduta o è incompleta. Non è stata creata alcuna sessione.',
  'callback.retry': 'Torna all’accesso',
  'onboarding.eyebrow': 'Un ultimo passaggio',
  'onboarding.title': 'Configura il tuo workspace',
  'onboarding.description': 'Conferma i documenti obbligatori e scegli dove vuoi lavorare.',
  'onboarding.create': 'Crea un nuovo workspace',
  'onboarding.select': 'Usa un workspace esistente',
  'onboarding.workspaceName': 'Nome del workspace',
  'onboarding.workspacePlaceholder': 'Il mio workspace',
  'onboarding.workspaceChoice': 'Workspace',
  'onboarding.submit': 'Apri Postqron',
  'onboarding.saving': 'Configurazione del workspace…',
  'onboarding.error': 'Non è stato possibile terminare la configurazione. Le tue scelte non sono andate perse; riprova.',
  'shell.skip': 'Vai al contenuto principale',
  'shell.navigation': 'Navigazione prodotto',
  'shell.home': 'Home',
  'shell.workspace': 'Workspace corrente',
  'shell.profile': 'Profilo',
  'shell.logout': 'Esci',
  'shell.menu': 'Apri la navigazione',
  'shell.closeMenu': 'Chiudi la navigazione',
  'home.eyebrow': 'Panoramica workspace',
  'home.welcome': 'Bentornato, {name}',
  'home.description': 'La shell prodotto è pronta. Le funzionalità collegate appariranno qui senza modificare questa navigazione.',
  'home.getStarted': 'Inizia collegando un canale social o creando una bozza.',
  'state.loading.title': 'Caricamento del workspace',
  'state.loading.description': 'Verifica della sessione sicura e dell’accesso al workspace.',
  'state.empty.title': 'Ancora nessun contenuto',
  'state.empty.description': 'Questa funzionalità ha uno spazio vuoto pronto per il primo elemento.',
  'state.offline.title': 'Sembra che tu sia offline',
  'state.offline.description': 'Riconnettiti e riprova. Postqron non ha eliminato il tuo lavoro.',
  'state.denied.title': 'Accesso negato',
  'state.denied.description': 'Il tuo account non può accedere a questo workspace o funzionalità.',
  'state.retry': 'Riprova',
  'feature.title': 'Spazio funzionalità',
  'feature.description': 'Questa route è riservata alla feature che ne è proprietaria.',
  'documentTitle.profile': 'Il tuo profilo — Postqron',
  'documentTitle.security': 'Impostazioni di sicurezza — Postqron',
  'documentTitle.providers': 'Provider collegati — Postqron',
  'documentTitle.plan': 'Piano e utilizzo — Postqron',
  'documentTitle.workspace': 'Impostazioni workspace — Postqron',
  'documentTitle.privacy': 'Privacy ed export — Postqron',
  'documentTitle.verifyEmail': 'Verifica la tua email — Postqron',
  'auth.confirmation': 'Conferma password',
  'auth.registerSubmit': 'Crea account',
  'auth.registering': 'Creazione account…',
  'auth.registerError': 'Non è stato possibile creare l’account. Controlla i dati e riprova.',
  'auth.signInError': 'Non è stato possibile accedere. Controlla le credenziali e riprova.',
  'auth.resend': 'Invia di nuovo la verifica',
  'auth.resending': 'Invio in corso…',
  'auth.resendError': 'Non è stato possibile reinviare la verifica. Riprova tra poco.',
  'auth.verificationTitle': 'Controlla la tua casella email',
  'auth.verificationDescription': 'Abbiamo inviato un link di verifica a {email}. Conferma l’indirizzo per continuare.',
  'auth.verificationOpen': 'Apri la pagina di verifica email',
  'shell.nav.home': 'Home',
  'shell.nav.profile': 'Profilo',
  'shell.nav.security': 'Sicurezza',
  'shell.nav.providers': 'Provider',
  'shell.nav.plan': 'Piano',
  'shell.nav.workspace': 'Workspace',
  'shell.nav.privacy': 'Privacy',
  'home.currentWorkspace': 'Workspace corrente',
  'home.currentRole': 'Ruolo: {role}',
  'home.noWorkspace': 'Nessun workspace selezionato',
  'home.currentPlanLabel': 'Piano attuale',
  'home.planUnknown': 'Piano non disponibile',
  'home.providerCountLabel': 'Provider collegati',
  'home.providerCountDescription': 'Controlla quali accessi e collegamenti proteggono questo account.',
  'home.card.profile.eyebrow': 'Dettagli account',
  'home.card.profile.title': 'Aggiorna il profilo',
  'home.card.profile.description': 'Mantieni nome, lingua e fuso orario allineati al tuo lavoro.',
  'home.card.security.eyebrow': 'Protezione accesso',
  'home.card.security.title': 'Rivedi la sicurezza',
  'home.card.security.description': 'Cambia password, controlla i metodi di accesso e revoca le sessioni.',
  'home.card.providers.eyebrow': 'Identità collegate',
  'home.card.providers.title': 'Gestisci i provider',
  'home.card.providers.description': 'Collega o scollega i provider OAuth disponibili senza uscire dall’app.',
  'home.card.plan.eyebrow': 'Stato commerciale',
  'home.card.plan.title': 'Vedi utilizzo del piano',
  'home.card.plan.description': 'Controlla piano attivo, limiti e utilizzo corrente dai dati autorevoli.',
  'home.card.workspace.eyebrow': 'Accesso al workspace',
  'home.card.workspace.title': 'Gestisci il workspace',
  'home.card.workspace.description': 'Cambia workspace, controlla i membri e conferma il tuo ruolo attuale.',
  'home.card.privacy.eyebrow': 'Controlli privacy',
  'home.card.privacy.title': 'Esporta o elimina dati',
  'home.card.privacy.description': 'Richiedi export, controlla lo stato della cancellazione e gestisci il grace period.',
  'profile.eyebrow': 'Profilo account',
  'profile.title': 'Profilo',
  'profile.description': 'Mantieni aggiornati il nome mostrato e le preferenze regionali.',
  'profile.displayName': 'Nome visualizzato',
  'profile.email': 'Indirizzo email',
  'profile.locale': 'Lingua preferita',
  'profile.timezone': 'Fuso orario',
  'profile.updatedAt': 'Ultimo aggiornamento',
  'profile.emailStatus': 'Verifica email',
  'profile.verified': 'Verificata',
  'profile.unverified': 'Verifica in sospeso',
  'profile.saved': 'Il profilo è stato aggiornato.',
  'profile.error': 'Non è stato possibile salvare il profilo. Riprova.',
  'profile.saving': 'Salvataggio profilo…',
  'profile.submit': 'Salva profilo',
  'security.eyebrow': 'Sicurezza',
  'security.title': 'Impostazioni di sicurezza',
  'security.description': 'Gestisci password, sessioni e metodi di accesso collegati.',
  'security.emailStatus': 'Email principale',
  'security.emailMissing': 'Nessuna email disponibile',
  'security.verified': 'Verificata',
  'security.unverified': 'Verifica in sospeso',
  'security.methods': 'Metodi di accesso',
  'security.onlyMethod': 'necessario per mantenere l’accesso all’account',
  'security.changePassword': 'Cambia password',
  'security.currentPassword': 'Password attuale',
  'security.newPassword': 'Nuova password',
  'security.confirmPassword': 'Conferma nuova password',
  'security.changeSubmit': 'Aggiorna password',
  'security.changing': 'Aggiornamento password…',
  'security.changed': 'La password è stata aggiornata.',
  'security.error': 'Non è stato possibile completare l’azione di sicurezza. Riprova.',
  'security.sessions': 'Sessioni attive',
  'security.sessionsDescription': 'Revoca le altre sessioni attive se sospetti un accesso indesiderato.',
  'security.revokeSubmit': 'Revoca altre sessioni',
  'security.revoking': 'Revoca sessioni…',
  'security.revoked': 'Le altre sessioni sono state revocate.',
  'providers.eyebrow': 'Provider collegati',
  'providers.title': 'Provider',
  'providers.description': 'Collega i provider di accesso supportati e scollega quelli che non usi più.',
  'providers.linkNew': 'Collega un nuovo provider',
  'providers.noAvailable': 'Al momento non ci sono altri provider configurati disponibili.',
  'providers.connected': 'Metodi collegati',
  'providers.required': 'Obbligatorio',
  'providers.disconnect': 'Scollega',
  'providers.disconnecting': 'Scollegamento…',
  'providers.linked': 'Il collegamento del provider è stato avviato in un nuovo flusso sicuro.',
  'providers.removed': 'Provider scollegato.',
  'providers.error': 'Non è stato possibile aggiornare i provider. Riprova.',
  'plan.eyebrow': 'Piano',
  'plan.title': 'Piano e utilizzo',
  'plan.description': 'Controlla il piano del workspace corrente, i limiti e il consumo.',
  'plan.current': 'Sottoscrizione corrente',
  'plan.unknown': 'Non disponibile',
  'plan.usage': 'Utilizzo',
  'plan.limits': 'Limiti',
  'workspace.eyebrow': 'Workspace',
  'workspace.title': 'Impostazioni workspace',
  'workspace.description': 'Controlla il workspace selezionato, quelli disponibili e i membri correnti.',
  'workspace.current': 'Workspace selezionato',
  'workspace.all': 'Workspace disponibili',
  'workspace.members': 'Membri',
  'workspace.none': 'Non disponibile',
  'privacy.eyebrow': 'Privacy',
  'privacy.title': 'Privacy e controlli sui dati',
  'privacy.description': 'Richiedi export, monitora lo stato della cancellazione e gestisci le azioni nel grace period.',
  'privacy.exportAccount': 'Export account',
  'privacy.exportWorkspace': 'Export workspace',
  'privacy.exportDescription': 'Prepara un export privacy con i dati account attualmente disponibili.',
  'privacy.requestExport': 'Richiedi export',
  'privacy.requesting': 'Invio richiesta…',
  'privacy.deleteAccount': 'Elimina account',
  'privacy.deleteWorkspace': 'Elimina workspace',
  'privacy.deleteDescription': 'La cancellazione avvia un grace period protetto prima della rimozione finale.',
  'privacy.requestDelete': 'Richiedi cancellazione',
  'privacy.exportStatus': 'Stato export',
  'privacy.download': 'Recupera download sicuro',
  'privacy.downloading': 'Caricamento export…',
  'privacy.deletionStatus': 'Stato cancellazione',
  'privacy.cancelDeletion': 'Annulla richiesta di cancellazione',
  'privacy.cancelling': 'Annullamento richiesta…',
  'privacy.statusNote': 'Le richieste di export e cancellazione restano soggette a retention e regole di ownership.',
  'privacy.saved': 'La richiesta privacy è stata salvata.',
  'privacy.error': 'Non è stato possibile completare la richiesta privacy. Riprova.',
  'privacy.workspaceUnavailable': 'Nessun workspace owner disponibile per questa azione.',
  'privacy.confirmAccountDeletion': 'Richiedere la cancellazione dell’account? Verrà avviato il grace period configurato.',
  'privacy.confirmWorkspaceDeletion': 'Richiedere la cancellazione del workspace "{workspace}"? Verrà avviato il grace period configurato.',
  'verify.eyebrow': 'Verifica email',
  'verify.title': 'Verifica la tua email',
  'verify.description': 'Inserisci lo stesso indirizzo email per richiedere un nuovo link di verifica.',
  'verify.success': 'Se l’indirizzo è valido, la verifica è stata completata o reinviata.',
  'verify.error': 'Non è stato possibile verificare o reinviare l’email. Controlla i dati e riprova.',
  'verify.email': 'Indirizzo email',
  'verify.resend': 'Reinvia verifica',
  'verify.resending': 'Invio in corso…',
  'verify.return': 'Torna all’accesso',
}

const es: AppShellCatalog = {
  'documentTitle.app': 'Iniciar sesión o registrarse — Postqron',
  'documentTitle.callback': 'Completando el acceso — Postqron',
  'documentTitle.onboarding': 'Configura tu espacio de trabajo — Postqron',
  'documentTitle.home': 'Resumen del espacio de trabajo — Postqron',
  'documentTitle.feature': 'Función — Postqron',
  'auth.eyebrow': 'Espacio de trabajo Postqron',
  'auth.title': 'Planifica, publica y controla todos tus canales.',
  'auth.description': 'Inicia sesión con correo y contraseña. Los proveedores externos configurados son opcionales.',
  'auth.newAccount': 'Crear una cuenta',
  'auth.existingAccount': 'Iniciar sesión',
  'auth.email': 'Correo electrónico',
  'auth.password': 'Contraseña',
  'auth.passwordSubmit': 'Entrar con correo',
  'auth.signingIn': 'Iniciando sesión…',
  'auth.orProvider': 'o usa un proveedor opcional',
  'auth.consentBefore': 'Acepto los',
  'auth.terms': 'Términos y condiciones',
  'auth.consentAnd': 'y la',
  'auth.privacy': 'Política de privacidad',
  'auth.consentAfter': '.',
  'auth.provider.google': 'Continuar con Google',
  'auth.provider.apple': 'Continuar con Apple',
  'auth.provider.facebook': 'Continuar con Facebook',
  'auth.provider.linkedin': 'Continuar con LinkedIn',
  'auth.providerUnavailable': 'Este método de acceso no está configurado.',
  'auth.requiredConsent': 'Acepta los documentos obligatorios antes de continuar.',
  'auth.configurationError': 'El acceso no está disponible temporalmente porque falta configuración.',
  'auth.invalidParameters': 'Los datos del plan seleccionado no son válidos. Vuelve a precios e inténtalo de nuevo.',
  'auth.offline': 'Postqron no puede conectar con el servicio de acceso. Comprueba tu conexión e inténtalo de nuevo.',
  'auth.retry': 'Reintentar',
  'callback.loading': 'Completando el acceso seguro…',
  'callback.title': 'No pudimos completar el acceso',
  'callback.description': 'La respuesta del proveedor fue rechazada, caducó o está incompleta. No se creó ninguna sesión.',
  'callback.retry': 'Volver al acceso',
  'onboarding.eyebrow': 'Un último paso',
  'onboarding.title': 'Configura tu espacio de trabajo',
  'onboarding.description': 'Confirma los documentos obligatorios y elige dónde quieres trabajar.',
  'onboarding.create': 'Crear un espacio nuevo',
  'onboarding.select': 'Usar un espacio existente',
  'onboarding.workspaceName': 'Nombre del espacio',
  'onboarding.workspacePlaceholder': 'Mi espacio de trabajo',
  'onboarding.workspaceChoice': 'Espacio de trabajo',
  'onboarding.submit': 'Abrir Postqron',
  'onboarding.saving': 'Configurando tu espacio…',
  'onboarding.error': 'No pudimos terminar la configuración. Tus elecciones no se han perdido; inténtalo de nuevo.',
  'shell.skip': 'Ir al contenido principal',
  'shell.navigation': 'Navegación del producto',
  'shell.home': 'Inicio',
  'shell.workspace': 'Espacio actual',
  'shell.profile': 'Perfil',
  'shell.logout': 'Cerrar sesión',
  'shell.menu': 'Abrir navegación',
  'shell.closeMenu': 'Cerrar navegación',
  'home.eyebrow': 'Resumen del espacio',
  'home.welcome': 'Te damos la bienvenida, {name}',
  'home.description': 'La estructura del producto está lista. Las funciones conectadas aparecerán aquí sin cambiar esta navegación.',
  'home.getStarted': 'Empieza conectando un canal social o creando un borrador.',
  'state.loading.title': 'Cargando tu espacio',
  'state.loading.description': 'Comprobando tu sesión segura y el acceso al espacio.',
  'state.empty.title': 'Todavía no hay nada',
  'state.empty.description': 'Esta función tiene un espacio vacío preparado para su primer elemento.',
  'state.offline.title': 'Parece que no tienes conexión',
  'state.offline.description': 'Vuelve a conectarte e inténtalo de nuevo. Postqron no ha descartado tu trabajo.',
  'state.denied.title': 'Acceso denegado',
  'state.denied.description': 'Tu cuenta no tiene acceso a este espacio o función.',
  'state.retry': 'Reintentar',
  'feature.title': 'Espacio de la función',
  'feature.description': 'Esta ruta está reservada para la feature propietaria.',
  'documentTitle.profile': 'Tu perfil — Postqron',
  'documentTitle.security': 'Configuración de seguridad — Postqron',
  'documentTitle.providers': 'Proveedores conectados — Postqron',
  'documentTitle.plan': 'Plan y uso — Postqron',
  'documentTitle.workspace': 'Configuración del espacio — Postqron',
  'documentTitle.privacy': 'Privacidad y exportaciones — Postqron',
  'documentTitle.verifyEmail': 'Verifica tu correo — Postqron',
  'auth.confirmation': 'Confirmar contraseña',
  'auth.registerSubmit': 'Crear cuenta',
  'auth.registering': 'Creando cuenta…',
  'auth.registerError': 'No pudimos crear tu cuenta. Revisa los datos e inténtalo de nuevo.',
  'auth.signInError': 'No pudimos iniciar tu sesión. Comprueba tus credenciales e inténtalo de nuevo.',
  'auth.resend': 'Reenviar verificación',
  'auth.resending': 'Reenviando…',
  'auth.resendError': 'No pudimos reenviar el correo de verificación. Inténtalo de nuevo dentro de unos minutos.',
  'auth.verificationTitle': 'Revisa tu bandeja de entrada',
  'auth.verificationDescription': 'Hemos enviado un enlace de verificación a {email}. Confirma la dirección para continuar.',
  'auth.verificationOpen': 'Abrir la página de verificación de correo',
  'shell.nav.home': 'Inicio',
  'shell.nav.profile': 'Perfil',
  'shell.nav.security': 'Seguridad',
  'shell.nav.providers': 'Proveedores',
  'shell.nav.plan': 'Plan',
  'shell.nav.workspace': 'Espacio',
  'shell.nav.privacy': 'Privacidad',
  'home.currentWorkspace': 'Espacio actual',
  'home.currentRole': 'Rol: {role}',
  'home.noWorkspace': 'No hay espacio seleccionado',
  'home.currentPlanLabel': 'Plan actual',
  'home.planUnknown': 'Plan no disponible',
  'home.providerCountLabel': 'Proveedores conectados',
  'home.providerCountDescription': 'Revisa qué accesos y conexiones protegen esta cuenta.',
  'home.card.profile.eyebrow': 'Datos de la cuenta',
  'home.card.profile.title': 'Actualiza tu perfil',
  'home.card.profile.description': 'Mantén tu nombre, idioma y zona horaria alineados con tu trabajo.',
  'home.card.security.eyebrow': 'Protección de acceso',
  'home.card.security.title': 'Revisar seguridad',
  'home.card.security.description': 'Cambia tu contraseña, revisa los métodos de acceso y revoca sesiones.',
  'home.card.providers.eyebrow': 'Identidades conectadas',
  'home.card.providers.title': 'Gestionar proveedores',
  'home.card.providers.description': 'Vincula o desconecta proveedores OAuth disponibles sin salir de la app.',
  'home.card.plan.eyebrow': 'Estado comercial',
  'home.card.plan.title': 'Ver uso del plan',
  'home.card.plan.description': 'Consulta el plan activo, los límites y el uso actual desde datos autorizados.',
  'home.card.workspace.eyebrow': 'Acceso al espacio',
  'home.card.workspace.title': 'Gestionar espacio',
  'home.card.workspace.description': 'Cambia de espacio, revisa miembros y confirma tu rol actual.',
  'home.card.privacy.eyebrow': 'Controles de privacidad',
  'home.card.privacy.title': 'Exportar o eliminar datos',
  'home.card.privacy.description': 'Solicita exportaciones, consulta el estado de borrado y gestiona el periodo de gracia.',
  'profile.eyebrow': 'Perfil de la cuenta',
  'profile.title': 'Perfil',
  'profile.description': 'Mantén actualizado tu nombre visible y tus preferencias regionales.',
  'profile.displayName': 'Nombre visible',
  'profile.email': 'Correo electrónico',
  'profile.locale': 'Idioma preferido',
  'profile.timezone': 'Zona horaria',
  'profile.updatedAt': 'Última actualización',
  'profile.emailStatus': 'Verificación del correo',
  'profile.verified': 'Verificado',
  'profile.unverified': 'Verificación pendiente',
  'profile.saved': 'Tu perfil se ha actualizado.',
  'profile.error': 'No pudimos guardar tu perfil. Inténtalo de nuevo.',
  'profile.saving': 'Guardando perfil…',
  'profile.submit': 'Guardar perfil',
  'security.eyebrow': 'Seguridad',
  'security.title': 'Configuración de seguridad',
  'security.description': 'Gestiona tu contraseña, sesiones y métodos de acceso conectados.',
  'security.emailStatus': 'Correo principal',
  'security.emailMissing': 'No hay correo registrado',
  'security.verified': 'Verificado',
  'security.unverified': 'Verificación pendiente',
  'security.methods': 'Métodos de acceso',
  'security.onlyMethod': 'necesario para conservar el acceso a la cuenta',
  'security.changePassword': 'Cambiar contraseña',
  'security.currentPassword': 'Contraseña actual',
  'security.newPassword': 'Nueva contraseña',
  'security.confirmPassword': 'Confirmar nueva contraseña',
  'security.changeSubmit': 'Actualizar contraseña',
  'security.changing': 'Actualizando contraseña…',
  'security.changed': 'Tu contraseña se ha actualizado.',
  'security.error': 'No pudimos completar la acción de seguridad. Inténtalo de nuevo.',
  'security.sessions': 'Sesiones activas',
  'security.sessionsDescription': 'Revoca las demás sesiones activas si sospechas un acceso no deseado.',
  'security.revokeSubmit': 'Revocar otras sesiones',
  'security.revoking': 'Revocando sesiones…',
  'security.revoked': 'Las demás sesiones han sido revocadas.',
  'providers.eyebrow': 'Proveedores conectados',
  'providers.title': 'Proveedores',
  'providers.description': 'Vincula los proveedores de acceso admitidos y desconecta los que ya no uses.',
  'providers.linkNew': 'Vincular un proveedor nuevo',
  'providers.noAvailable': 'No hay más proveedores configurados disponibles en este momento.',
  'providers.connected': 'Métodos conectados',
  'providers.required': 'Obligatorio',
  'providers.disconnect': 'Desconectar',
  'providers.disconnecting': 'Desconectando…',
  'providers.linked': 'La vinculación del proveedor se ha iniciado en un flujo seguro nuevo.',
  'providers.removed': 'Proveedor desconectado.',
  'providers.error': 'No pudimos actualizar tus proveedores. Inténtalo de nuevo.',
  'plan.eyebrow': 'Plan',
  'plan.title': 'Plan y uso',
  'plan.description': 'Consulta el plan del espacio actual, sus límites y el consumo.',
  'plan.current': 'Suscripción actual',
  'plan.unknown': 'No disponible',
  'plan.usage': 'Uso',
  'plan.limits': 'Límites',
  'workspace.eyebrow': 'Espacio',
  'workspace.title': 'Configuración del espacio',
  'workspace.description': 'Revisa el espacio seleccionado, los espacios disponibles y los miembros actuales.',
  'workspace.current': 'Espacio seleccionado',
  'workspace.all': 'Espacios disponibles',
  'workspace.members': 'Miembros',
  'workspace.none': 'No disponible',
  'privacy.eyebrow': 'Privacidad',
  'privacy.title': 'Privacidad y controles de datos',
  'privacy.description': 'Solicita exportaciones, supervisa el estado de borrado y gestiona las acciones del periodo de gracia.',
  'privacy.exportAccount': 'Exportación de cuenta',
  'privacy.exportWorkspace': 'Exportación del espacio',
  'privacy.exportDescription': 'Prepara una exportación de privacidad con los datos de cuenta disponibles en este momento.',
  'privacy.requestExport': 'Solicitar exportación',
  'privacy.requesting': 'Enviando solicitud…',
  'privacy.deleteAccount': 'Eliminar cuenta',
  'privacy.deleteWorkspace': 'Eliminar espacio',
  'privacy.deleteDescription': 'La eliminación inicia un periodo de gracia protegido antes del borrado final.',
  'privacy.requestDelete': 'Solicitar eliminación',
  'privacy.exportStatus': 'Estado de la exportación',
  'privacy.download': 'Obtener descarga segura',
  'privacy.downloading': 'Cargando exportación…',
  'privacy.deletionStatus': 'Estado de la eliminación',
  'privacy.cancelDeletion': 'Cancelar solicitud de eliminación',
  'privacy.cancelling': 'Cancelando solicitud…',
  'privacy.statusNote': 'Las solicitudes de exportación y eliminación siguen sujetas a retención y reglas de propiedad.',
  'privacy.saved': 'Tu solicitud de privacidad se ha guardado.',
  'privacy.error': 'No pudimos completar la solicitud de privacidad. Inténtalo de nuevo.',
  'privacy.workspaceUnavailable': 'No hay un espacio de owner disponible para esta acción.',
  'privacy.confirmAccountDeletion': '¿Solicitar la eliminación de la cuenta? Esto iniciará el periodo de gracia configurado.',
  'privacy.confirmWorkspaceDeletion': '¿Solicitar la eliminación del espacio "{workspace}"? Esto iniciará el periodo de gracia configurado.',
  'verify.eyebrow': 'Verificación de correo',
  'verify.title': 'Verifica tu correo electrónico',
  'verify.description': 'Escribe la misma dirección de correo para solicitar un enlace de verificación nuevo.',
  'verify.success': 'Si la dirección es válida, la verificación se completó o se volvió a enviar.',
  'verify.error': 'No pudimos verificar o reenviar el correo. Revisa los datos e inténtalo de nuevo.',
  'verify.email': 'Correo electrónico',
  'verify.resend': 'Reenviar verificación',
  'verify.resending': 'Reenviando…',
  'verify.return': 'Volver al acceso',
}

const fr: AppShellCatalog = {
  'documentTitle.app': 'Connexion ou inscription — Postqron',
  'documentTitle.callback': 'Finalisation de la connexion — Postqron',
  'documentTitle.onboarding': 'Configurez votre espace de travail — Postqron',
  'documentTitle.home': 'Vue d’ensemble de l’espace — Postqron',
  'documentTitle.feature': 'Fonctionnalité — Postqron',
  'auth.eyebrow': 'Espace de travail Postqron',
  'auth.title': 'Planifiez, publiez et gardez chaque canal sous contrôle.',
  'auth.description': 'Connectez-vous avec votre e-mail et mot de passe. Les fournisseurs externes configurés restent facultatifs.',
  'auth.newAccount': 'Créer un compte',
  'auth.existingAccount': 'Se connecter',
  'auth.email': 'Adresse e-mail',
  'auth.password': 'Mot de passe',
  'auth.passwordSubmit': 'Se connecter par e-mail',
  'auth.signingIn': 'Connexion…',
  'auth.orProvider': 'ou utilisez un fournisseur facultatif',
  'auth.consentBefore': 'J’accepte les',
  'auth.terms': 'Conditions générales',
  'auth.consentAnd': 'et la',
  'auth.privacy': 'Politique de confidentialité',
  'auth.consentAfter': '.',
  'auth.provider.google': 'Continuer avec Google',
  'auth.provider.apple': 'Continuer avec Apple',
  'auth.provider.facebook': 'Continuer avec Facebook',
  'auth.provider.linkedin': 'Continuer avec LinkedIn',
  'auth.providerUnavailable': 'Cette méthode de connexion n’est pas configurée.',
  'auth.requiredConsent': 'Acceptez les documents obligatoires avant de continuer.',
  'auth.configurationError': 'La connexion est temporairement indisponible car la configuration est incomplète.',
  'auth.invalidParameters': 'Les informations du forfait sélectionné ne sont pas valides. Revenez aux tarifs et réessayez.',
  'auth.offline': 'Postqron ne peut pas joindre le service de connexion. Vérifiez votre connexion et réessayez.',
  'auth.retry': 'Réessayer',
  'callback.loading': 'Finalisation de la connexion sécurisée…',
  'callback.title': 'Impossible de finaliser la connexion',
  'callback.description': 'La réponse du fournisseur a été refusée, a expiré ou est incomplète. Aucune session n’a été créée.',
  'callback.retry': 'Revenir à la connexion',
  'onboarding.eyebrow': 'Une dernière étape',
  'onboarding.title': 'Configurez votre espace de travail',
  'onboarding.description': 'Confirmez les documents obligatoires et choisissez où travailler.',
  'onboarding.create': 'Créer un nouvel espace',
  'onboarding.select': 'Utiliser un espace existant',
  'onboarding.workspaceName': 'Nom de l’espace',
  'onboarding.workspacePlaceholder': 'Mon espace de travail',
  'onboarding.workspaceChoice': 'Espace de travail',
  'onboarding.submit': 'Ouvrir Postqron',
  'onboarding.saving': 'Configuration de votre espace…',
  'onboarding.error': 'La configuration n’a pas pu être terminée. Vos choix sont conservés ; réessayez.',
  'shell.skip': 'Aller au contenu principal',
  'shell.navigation': 'Navigation du produit',
  'shell.home': 'Accueil',
  'shell.workspace': 'Espace actuel',
  'shell.profile': 'Profil',
  'shell.logout': 'Se déconnecter',
  'shell.menu': 'Ouvrir la navigation',
  'shell.closeMenu': 'Fermer la navigation',
  'home.eyebrow': 'Vue d’ensemble de l’espace',
  'home.welcome': 'Bienvenue, {name}',
  'home.description': 'La structure du produit est prête. Les fonctionnalités connectées apparaîtront ici sans modifier cette navigation.',
  'home.getStarted': 'Commencez par connecter un canal social ou créer un brouillon.',
  'state.loading.title': 'Chargement de votre espace',
  'state.loading.description': 'Vérification de votre session sécurisée et de l’accès à l’espace.',
  'state.empty.title': 'Rien pour le moment',
  'state.empty.description': 'Cette fonctionnalité dispose d’un espace vide prêt pour son premier élément.',
  'state.offline.title': 'Vous semblez hors ligne',
  'state.offline.description': 'Reconnectez-vous et réessayez. Postqron n’a pas supprimé votre travail.',
  'state.denied.title': 'Accès refusé',
  'state.denied.description': 'Votre compte n’a pas accès à cet espace ou à cette fonctionnalité.',
  'state.retry': 'Réessayer',
  'feature.title': 'Espace de fonctionnalité',
  'feature.description': 'Cette route est réservée à la feature qui en est propriétaire.',
  'documentTitle.profile': 'Votre profil — Postqron',
  'documentTitle.security': 'Paramètres de sécurité — Postqron',
  'documentTitle.providers': 'Fournisseurs connectés — Postqron',
  'documentTitle.plan': 'Forfait et usage — Postqron',
  'documentTitle.workspace': 'Paramètres de l’espace — Postqron',
  'documentTitle.privacy': 'Confidentialité et exports — Postqron',
  'documentTitle.verifyEmail': 'Vérifiez votre e-mail — Postqron',
  'auth.confirmation': 'Confirmer le mot de passe',
  'auth.registerSubmit': 'Créer un compte',
  'auth.registering': 'Création du compte…',
  'auth.registerError': 'Nous n’avons pas pu créer votre compte. Vérifiez les informations puis réessayez.',
  'auth.signInError': 'Nous n’avons pas pu vous connecter. Vérifiez vos identifiants puis réessayez.',
  'auth.resend': 'Renvoyer la vérification',
  'auth.resending': 'Renvoi…',
  'auth.resendError': 'Nous n’avons pas pu renvoyer l’e-mail de vérification. Réessayez dans un instant.',
  'auth.verificationTitle': 'Consultez votre boîte de réception',
  'auth.verificationDescription': 'Nous avons envoyé un lien de vérification à {email}. Confirmez cette adresse pour continuer.',
  'auth.verificationOpen': 'Ouvrir la page de vérification de l’e-mail',
  'shell.nav.home': 'Accueil',
  'shell.nav.profile': 'Profil',
  'shell.nav.security': 'Sécurité',
  'shell.nav.providers': 'Fournisseurs',
  'shell.nav.plan': 'Forfait',
  'shell.nav.workspace': 'Espace',
  'shell.nav.privacy': 'Confidentialité',
  'home.currentWorkspace': 'Espace actuel',
  'home.currentRole': 'Rôle : {role}',
  'home.noWorkspace': 'Aucun espace sélectionné',
  'home.currentPlanLabel': 'Forfait actuel',
  'home.planUnknown': 'Forfait indisponible',
  'home.providerCountLabel': 'Fournisseurs connectés',
  'home.providerCountDescription': 'Vérifiez quels accès et connexions protègent ce compte.',
  'home.card.profile.eyebrow': 'Détails du compte',
  'home.card.profile.title': 'Mettre à jour votre profil',
  'home.card.profile.description': 'Gardez votre nom, votre langue et votre fuseau horaire cohérents avec votre travail.',
  'home.card.security.eyebrow': 'Protection de l’accès',
  'home.card.security.title': 'Revoir la sécurité',
  'home.card.security.description': 'Changez votre mot de passe, consultez les méthodes d’accès et révoquez des sessions.',
  'home.card.providers.eyebrow': 'Identités connectées',
  'home.card.providers.title': 'Gérer les fournisseurs',
  'home.card.providers.description': 'Liez ou déconnectez les fournisseurs OAuth disponibles sans quitter l’application.',
  'home.card.plan.eyebrow': 'Statut commercial',
  'home.card.plan.title': 'Voir l’usage du forfait',
  'home.card.plan.description': 'Consultez le forfait actif, les limites et l’utilisation actuelle depuis les données autorisées.',
  'home.card.workspace.eyebrow': 'Accès à l’espace',
  'home.card.workspace.title': 'Gérer l’espace',
  'home.card.workspace.description': 'Changez d’espace, consultez les membres et confirmez votre rôle actuel.',
  'home.card.privacy.eyebrow': 'Contrôles de confidentialité',
  'home.card.privacy.title': 'Exporter ou supprimer des données',
  'home.card.privacy.description': 'Demandez des exports, suivez l’état de suppression et gérez la période de grâce.',
  'profile.eyebrow': 'Profil du compte',
  'profile.title': 'Profil',
  'profile.description': 'Gardez à jour votre nom affiché et vos préférences régionales.',
  'profile.displayName': 'Nom affiché',
  'profile.email': 'Adresse e-mail',
  'profile.locale': 'Langue préférée',
  'profile.timezone': 'Fuseau horaire',
  'profile.updatedAt': 'Dernière mise à jour',
  'profile.emailStatus': 'Vérification de l’e-mail',
  'profile.verified': 'Vérifié',
  'profile.unverified': 'Vérification en attente',
  'profile.saved': 'Votre profil a été mis à jour.',
  'profile.error': 'Nous n’avons pas pu enregistrer votre profil. Réessayez.',
  'profile.saving': 'Enregistrement du profil…',
  'profile.submit': 'Enregistrer le profil',
  'security.eyebrow': 'Sécurité',
  'security.title': 'Paramètres de sécurité',
  'security.description': 'Gérez votre mot de passe, vos sessions et vos méthodes d’accès connectées.',
  'security.emailStatus': 'E-mail principal',
  'security.emailMissing': 'Aucun e-mail enregistré',
  'security.verified': 'Vérifié',
  'security.unverified': 'Vérification en attente',
  'security.methods': 'Méthodes d’accès',
  'security.onlyMethod': 'nécessaire pour conserver l’accès au compte',
  'security.changePassword': 'Changer le mot de passe',
  'security.currentPassword': 'Mot de passe actuel',
  'security.newPassword': 'Nouveau mot de passe',
  'security.confirmPassword': 'Confirmer le nouveau mot de passe',
  'security.changeSubmit': 'Mettre à jour le mot de passe',
  'security.changing': 'Mise à jour du mot de passe…',
  'security.changed': 'Votre mot de passe a été mis à jour.',
  'security.error': 'Nous n’avons pas pu terminer l’action de sécurité. Réessayez.',
  'security.sessions': 'Sessions actives',
  'security.sessionsDescription': 'Révoquez les autres sessions actives si vous soupçonnez un accès non souhaité.',
  'security.revokeSubmit': 'Révoquer les autres sessions',
  'security.revoking': 'Révocation des sessions…',
  'security.revoked': 'Les autres sessions ont été révoquées.',
  'providers.eyebrow': 'Fournisseurs connectés',
  'providers.title': 'Fournisseurs',
  'providers.description': 'Liez les fournisseurs de connexion pris en charge et déconnectez ceux que vous n’utilisez plus.',
  'providers.linkNew': 'Lier un nouveau fournisseur',
  'providers.noAvailable': 'Aucun autre fournisseur configuré n’est disponible pour le moment.',
  'providers.connected': 'Méthodes connectées',
  'providers.required': 'Obligatoire',
  'providers.disconnect': 'Déconnecter',
  'providers.disconnecting': 'Déconnexion…',
  'providers.linked': 'La liaison du fournisseur a démarré dans un nouveau flux sécurisé.',
  'providers.removed': 'Fournisseur déconnecté.',
  'providers.error': 'Nous n’avons pas pu mettre à jour vos fournisseurs. Réessayez.',
  'plan.eyebrow': 'Forfait',
  'plan.title': 'Forfait et usage',
  'plan.description': 'Consultez le forfait de l’espace actuel, ses limites et sa consommation.',
  'plan.current': 'Abonnement actuel',
  'plan.unknown': 'Indisponible',
  'plan.usage': 'Utilisation',
  'plan.limits': 'Limites',
  'workspace.eyebrow': 'Espace',
  'workspace.title': 'Paramètres de l’espace',
  'workspace.description': 'Inspectez l’espace sélectionné, les espaces disponibles et les membres actuels.',
  'workspace.current': 'Espace sélectionné',
  'workspace.all': 'Espaces disponibles',
  'workspace.members': 'Membres',
  'workspace.none': 'Indisponible',
  'privacy.eyebrow': 'Confidentialité',
  'privacy.title': 'Confidentialité et contrôles des données',
  'privacy.description': 'Demandez des exports, suivez l’état de suppression et gérez les actions pendant la période de grâce.',
  'privacy.exportAccount': 'Export du compte',
  'privacy.exportWorkspace': 'Export de l’espace',
  'privacy.exportDescription': 'Préparez un export de confidentialité avec les données de compte disponibles actuellement.',
  'privacy.requestExport': 'Demander un export',
  'privacy.requesting': 'Envoi de la demande…',
  'privacy.deleteAccount': 'Supprimer le compte',
  'privacy.deleteWorkspace': 'Supprimer l’espace',
  'privacy.deleteDescription': 'La suppression lance une période de grâce protégée avant la suppression finale.',
  'privacy.requestDelete': 'Demander la suppression',
  'privacy.exportStatus': 'État de l’export',
  'privacy.download': 'Obtenir le téléchargement sécurisé',
  'privacy.downloading': 'Chargement de l’export…',
  'privacy.deletionStatus': 'État de la suppression',
  'privacy.cancelDeletion': 'Annuler la demande de suppression',
  'privacy.cancelling': 'Annulation de la demande…',
  'privacy.statusNote': 'Les demandes d’export et de suppression restent soumises aux règles de rétention et de propriété.',
  'privacy.saved': 'Votre demande de confidentialité a été enregistrée.',
  'privacy.error': 'Nous n’avons pas pu traiter la demande de confidentialité. Réessayez.',
  'privacy.workspaceUnavailable': 'Aucun espace owner n’est disponible pour cette action.',
  'privacy.confirmAccountDeletion': 'Demander la suppression du compte ? Cela lancera la période de grâce configurée.',
  'privacy.confirmWorkspaceDeletion': 'Demander la suppression de l’espace "{workspace}" ? Cela lancera la période de grâce configurée.',
  'verify.eyebrow': 'Vérification de l’e-mail',
  'verify.title': 'Vérifiez votre e-mail',
  'verify.description': 'Saisissez la même adresse e-mail pour demander un nouveau lien de vérification.',
  'verify.success': 'Si l’adresse est valide, la vérification a été effectuée ou renvoyée.',
  'verify.error': 'Nous n’avons pas pu vérifier ou renvoyer l’e-mail. Vérifiez les informations puis réessayez.',
  'verify.email': 'Adresse e-mail',
  'verify.resend': 'Renvoyer la vérification',
  'verify.resending': 'Renvoi…',
  'verify.return': 'Retour à la connexion',
}

const de: AppShellCatalog = {
  'documentTitle.app': 'Anmelden oder registrieren — Postqron',
  'documentTitle.callback': 'Anmeldung wird abgeschlossen — Postqron',
  'documentTitle.onboarding': 'Arbeitsbereich einrichten — Postqron',
  'documentTitle.home': 'Arbeitsbereich im Überblick — Postqron',
  'documentTitle.feature': 'Funktion — Postqron',
  'auth.eyebrow': 'Postqron-Arbeitsbereich',
  'auth.title': 'Plane, veröffentliche und behalte jeden Kanal im Blick.',
  'auth.description': 'Melde dich mit E-Mail und Passwort an. Konfigurierte externe Anbieter bleiben optional.',
  'auth.newAccount': 'Konto erstellen',
  'auth.existingAccount': 'Anmelden',
  'auth.email': 'E-Mail-Adresse',
  'auth.password': 'Passwort',
  'auth.passwordSubmit': 'Mit E-Mail anmelden',
  'auth.signingIn': 'Anmeldung läuft…',
  'auth.orProvider': 'oder optionalen Anbieter verwenden',
  'auth.consentBefore': 'Ich akzeptiere die',
  'auth.terms': 'Allgemeinen Geschäftsbedingungen',
  'auth.consentAnd': 'und die',
  'auth.privacy': 'Datenschutzerklärung',
  'auth.consentAfter': '.',
  'auth.provider.google': 'Mit Google fortfahren',
  'auth.provider.apple': 'Mit Apple fortfahren',
  'auth.provider.facebook': 'Mit Facebook fortfahren',
  'auth.provider.linkedin': 'Mit LinkedIn fortfahren',
  'auth.providerUnavailable': 'Diese Anmeldemethode ist nicht konfiguriert.',
  'auth.requiredConsent': 'Akzeptiere die erforderlichen Dokumente, bevor du fortfährst.',
  'auth.configurationError': 'Die Anmeldung ist vorübergehend nicht verfügbar, weil die Konfiguration unvollständig ist.',
  'auth.invalidParameters': 'Die Angaben zum gewählten Tarif sind ungültig. Kehre zur Preisseite zurück und versuche es erneut.',
  'auth.offline': 'Postqron kann den Anmeldedienst nicht erreichen. Prüfe deine Verbindung und versuche es erneut.',
  'auth.retry': 'Erneut versuchen',
  'callback.loading': 'Sichere Anmeldung wird abgeschlossen…',
  'callback.title': 'Anmeldung konnte nicht abgeschlossen werden',
  'callback.description': 'Die Anbieterantwort wurde abgelehnt, ist abgelaufen oder unvollständig. Es wurde keine Sitzung erstellt.',
  'callback.retry': 'Zurück zur Anmeldung',
  'onboarding.eyebrow': 'Ein letzter Schritt',
  'onboarding.title': 'Richte deinen Arbeitsbereich ein',
  'onboarding.description': 'Bestätige die erforderlichen Dokumente und wähle deinen Arbeitsbereich.',
  'onboarding.create': 'Neuen Arbeitsbereich erstellen',
  'onboarding.select': 'Vorhandenen Arbeitsbereich verwenden',
  'onboarding.workspaceName': 'Name des Arbeitsbereichs',
  'onboarding.workspacePlaceholder': 'Mein Arbeitsbereich',
  'onboarding.workspaceChoice': 'Arbeitsbereich',
  'onboarding.submit': 'Postqron öffnen',
  'onboarding.saving': 'Arbeitsbereich wird eingerichtet…',
  'onboarding.error': 'Die Einrichtung konnte nicht abgeschlossen werden. Deine Auswahl bleibt erhalten; versuche es erneut.',
  'shell.skip': 'Zum Hauptinhalt springen',
  'shell.navigation': 'Produktnavigation',
  'shell.home': 'Start',
  'shell.workspace': 'Aktueller Arbeitsbereich',
  'shell.profile': 'Profil',
  'shell.logout': 'Abmelden',
  'shell.menu': 'Navigation öffnen',
  'shell.closeMenu': 'Navigation schließen',
  'home.eyebrow': 'Arbeitsbereich im Überblick',
  'home.welcome': 'Willkommen, {name}',
  'home.description': 'Die Produkt-Shell ist bereit. Verbundene Funktionen erscheinen hier, ohne diese Navigation zu ändern.',
  'home.getStarted': 'Verbinde zuerst einen Social-Media-Kanal oder erstelle einen Entwurf.',
  'state.loading.title': 'Arbeitsbereich wird geladen',
  'state.loading.description': 'Sichere Sitzung und Zugriff auf den Arbeitsbereich werden geprüft.',
  'state.empty.title': 'Noch keine Inhalte',
  'state.empty.description': 'Diese Funktion hat einen leeren Bereich für den ersten Eintrag.',
  'state.offline.title': 'Du scheinst offline zu sein',
  'state.offline.description': 'Stelle die Verbindung wieder her und versuche es erneut. Deine Arbeit wurde nicht verworfen.',
  'state.denied.title': 'Zugriff verweigert',
  'state.denied.description': 'Dein Konto hat keinen Zugriff auf diesen Arbeitsbereich oder diese Funktion.',
  'state.retry': 'Erneut versuchen',
  'feature.title': 'Funktionsbereich',
  'feature.description': 'Diese Route ist für die zuständige Feature-Slice reserviert.',
  'documentTitle.profile': 'Dein Profil — Postqron',
  'documentTitle.security': 'Sicherheitseinstellungen — Postqron',
  'documentTitle.providers': 'Verbundene Anbieter — Postqron',
  'documentTitle.plan': 'Tarif und Nutzung — Postqron',
  'documentTitle.workspace': 'Arbeitsbereichseinstellungen — Postqron',
  'documentTitle.privacy': 'Datenschutz und Exporte — Postqron',
  'documentTitle.verifyEmail': 'Bestätige deine E-Mail — Postqron',
  'auth.confirmation': 'Passwort bestätigen',
  'auth.registerSubmit': 'Konto erstellen',
  'auth.registering': 'Konto wird erstellt…',
  'auth.registerError': 'Dein Konto konnte nicht erstellt werden. Prüfe die Angaben und versuche es erneut.',
  'auth.signInError': 'Die Anmeldung ist fehlgeschlagen. Prüfe deine Zugangsdaten und versuche es erneut.',
  'auth.resend': 'Bestätigung erneut senden',
  'auth.resending': 'Wird erneut gesendet…',
  'auth.resendError': 'Die Bestätigungs-E-Mail konnte nicht erneut gesendet werden. Versuche es gleich noch einmal.',
  'auth.verificationTitle': 'Prüfe deinen Posteingang',
  'auth.verificationDescription': 'Wir haben einen Bestätigungslink an {email} gesendet. Bestätige die Adresse, um fortzufahren.',
  'auth.verificationOpen': 'E-Mail-Bestätigungsseite öffnen',
  'shell.nav.home': 'Start',
  'shell.nav.profile': 'Profil',
  'shell.nav.security': 'Sicherheit',
  'shell.nav.providers': 'Anbieter',
  'shell.nav.plan': 'Tarif',
  'shell.nav.workspace': 'Arbeitsbereich',
  'shell.nav.privacy': 'Datenschutz',
  'home.currentWorkspace': 'Aktueller Arbeitsbereich',
  'home.currentRole': 'Rolle: {role}',
  'home.noWorkspace': 'Kein Arbeitsbereich ausgewählt',
  'home.currentPlanLabel': 'Aktueller Tarif',
  'home.planUnknown': 'Tarif nicht verfügbar',
  'home.providerCountLabel': 'Verbundene Anbieter',
  'home.providerCountDescription': 'Prüfe, welche Zugänge und Verbindungen dieses Konto schützen.',
  'home.card.profile.eyebrow': 'Kontodetails',
  'home.card.profile.title': 'Profil aktualisieren',
  'home.card.profile.description': 'Halte Namen, Sprache und Zeitzone passend zu deiner Arbeit aktuell.',
  'home.card.security.eyebrow': 'Zugriffsschutz',
  'home.card.security.title': 'Sicherheit prüfen',
  'home.card.security.description': 'Ändere dein Passwort, prüfe Zugriffsmethoden und widerrufe Sitzungen.',
  'home.card.providers.eyebrow': 'Verbundene Identitäten',
  'home.card.providers.title': 'Anbieter verwalten',
  'home.card.providers.description': 'Verbinde oder trenne verfügbare OAuth-Anbieter, ohne die App zu verlassen.',
  'home.card.plan.eyebrow': 'Kommerzieller Status',
  'home.card.plan.title': 'Tarifnutzung ansehen',
  'home.card.plan.description': 'Prüfe aktiven Tarif, Limits und aktuelle Nutzung aus autoritativen Daten.',
  'home.card.workspace.eyebrow': 'Arbeitsbereichszugriff',
  'home.card.workspace.title': 'Arbeitsbereich verwalten',
  'home.card.workspace.description': 'Wechsle Arbeitsbereiche, prüfe Mitglieder und bestätige deine aktuelle Rolle.',
  'home.card.privacy.eyebrow': 'Datenschutzkontrollen',
  'home.card.privacy.title': 'Daten exportieren oder löschen',
  'home.card.privacy.description': 'Fordere Exporte an, prüfe den Löschstatus und verwalte die Schutzfrist.',
  'profile.eyebrow': 'Kontoprofil',
  'profile.title': 'Profil',
  'profile.description': 'Halte deinen angezeigten Namen und regionale Einstellungen aktuell.',
  'profile.displayName': 'Anzeigename',
  'profile.email': 'E-Mail-Adresse',
  'profile.locale': 'Bevorzugte Sprache',
  'profile.timezone': 'Zeitzone',
  'profile.updatedAt': 'Zuletzt aktualisiert',
  'profile.emailStatus': 'E-Mail-Bestätigung',
  'profile.verified': 'Bestätigt',
  'profile.unverified': 'Bestätigung ausstehend',
  'profile.saved': 'Dein Profil wurde aktualisiert.',
  'profile.error': 'Dein Profil konnte nicht gespeichert werden. Versuche es erneut.',
  'profile.saving': 'Profil wird gespeichert…',
  'profile.submit': 'Profil speichern',
  'security.eyebrow': 'Sicherheit',
  'security.title': 'Sicherheitseinstellungen',
  'security.description': 'Verwalte Passwort, Sitzungen und verbundene Zugriffsmethoden.',
  'security.emailStatus': 'Primäre E-Mail',
  'security.emailMissing': 'Keine E-Mail hinterlegt',
  'security.verified': 'Bestätigt',
  'security.unverified': 'Bestätigung ausstehend',
  'security.methods': 'Zugriffsmethoden',
  'security.onlyMethod': 'erforderlich, um den Kontozugriff zu behalten',
  'security.changePassword': 'Passwort ändern',
  'security.currentPassword': 'Aktuelles Passwort',
  'security.newPassword': 'Neues Passwort',
  'security.confirmPassword': 'Neues Passwort bestätigen',
  'security.changeSubmit': 'Passwort aktualisieren',
  'security.changing': 'Passwort wird aktualisiert…',
  'security.changed': 'Dein Passwort wurde aktualisiert.',
  'security.error': 'Die Sicherheitsaktion konnte nicht abgeschlossen werden. Versuche es erneut.',
  'security.sessions': 'Aktive Sitzungen',
  'security.sessionsDescription': 'Widerrufe andere aktive Sitzungen, wenn du unerwünschten Zugriff vermutest.',
  'security.revokeSubmit': 'Andere Sitzungen widerrufen',
  'security.revoking': 'Sitzungen werden widerrufen…',
  'security.revoked': 'Andere Sitzungen wurden widerrufen.',
  'providers.eyebrow': 'Verbundene Anbieter',
  'providers.title': 'Anbieter',
  'providers.description': 'Verbinde unterstützte Anmeldeanbieter und trenne die, die du nicht mehr verwendest.',
  'providers.linkNew': 'Neuen Anbieter verbinden',
  'providers.noAvailable': 'Derzeit sind keine weiteren konfigurierten Anbieter verfügbar.',
  'providers.connected': 'Verbundene Methoden',
  'providers.required': 'Erforderlich',
  'providers.disconnect': 'Trennen',
  'providers.disconnecting': 'Wird getrennt…',
  'providers.linked': 'Die Anbieter-Verknüpfung wurde in einem neuen sicheren Ablauf gestartet.',
  'providers.removed': 'Anbieter getrennt.',
  'providers.error': 'Deine Anbieter konnten nicht aktualisiert werden. Versuche es erneut.',
  'plan.eyebrow': 'Tarif',
  'plan.title': 'Tarif und Nutzung',
  'plan.description': 'Prüfe den Tarif des aktuellen Arbeitsbereichs, Limits und Verbrauch.',
  'plan.current': 'Aktuelles Abonnement',
  'plan.unknown': 'Nicht verfügbar',
  'plan.usage': 'Nutzung',
  'plan.limits': 'Limits',
  'workspace.eyebrow': 'Arbeitsbereich',
  'workspace.title': 'Arbeitsbereichseinstellungen',
  'workspace.description': 'Prüfe den ausgewählten Arbeitsbereich, verfügbare Arbeitsbereiche und aktuelle Mitglieder.',
  'workspace.current': 'Ausgewählter Arbeitsbereich',
  'workspace.all': 'Verfügbare Arbeitsbereiche',
  'workspace.members': 'Mitglieder',
  'workspace.none': 'Nicht verfügbar',
  'privacy.eyebrow': 'Datenschutz',
  'privacy.title': 'Datenschutz und Datenkontrollen',
  'privacy.description': 'Fordere Exporte an, verfolge den Löschstatus und verwalte Aktionen während der Schutzfrist.',
  'privacy.exportAccount': 'Kontoexport',
  'privacy.exportWorkspace': 'Arbeitsbereichsexport',
  'privacy.exportDescription': 'Bereite einen Datenschutzauszug mit den aktuell verfügbaren Kontodaten vor.',
  'privacy.requestExport': 'Export anfordern',
  'privacy.requesting': 'Anfrage wird gesendet…',
  'privacy.deleteAccount': 'Konto löschen',
  'privacy.deleteWorkspace': 'Arbeitsbereich löschen',
  'privacy.deleteDescription': 'Das Löschen startet eine geschützte Frist vor der endgültigen Entfernung.',
  'privacy.requestDelete': 'Löschung anfordern',
  'privacy.exportStatus': 'Exportstatus',
  'privacy.download': 'Sicheren Download abrufen',
  'privacy.downloading': 'Export wird geladen…',
  'privacy.deletionStatus': 'Löschstatus',
  'privacy.cancelDeletion': 'Löschanfrage abbrechen',
  'privacy.cancelling': 'Anfrage wird abgebrochen…',
  'privacy.statusNote': 'Export- und Löschanfragen unterliegen weiterhin Aufbewahrungs- und Eigentumsregeln.',
  'privacy.saved': 'Deine Datenschutzanfrage wurde gespeichert.',
  'privacy.error': 'Die Datenschutzanfrage konnte nicht abgeschlossen werden. Versuche es erneut.',
  'privacy.workspaceUnavailable': 'Für diese Aktion ist derzeit kein Owner-Arbeitsbereich verfügbar.',
  'privacy.confirmAccountDeletion': 'Kontolöschung anfordern? Dadurch beginnt die konfigurierte Schutzfrist.',
  'privacy.confirmWorkspaceDeletion': 'Löschung des Arbeitsbereichs "{workspace}" anfordern? Dadurch beginnt die konfigurierte Schutzfrist.',
  'verify.eyebrow': 'E-Mail-Bestätigung',
  'verify.title': 'Bestätige deine E-Mail-Adresse',
  'verify.description': 'Gib dieselbe E-Mail-Adresse ein, um einen neuen Bestätigungslink anzufordern.',
  'verify.success': 'Wenn die Adresse gültig ist, wurde die Bestätigung abgeschlossen oder erneut gesendet.',
  'verify.error': 'Die E-Mail konnte nicht bestätigt oder erneut gesendet werden. Prüfe die Angaben und versuche es erneut.',
  'verify.email': 'E-Mail-Adresse',
  'verify.resend': 'Bestätigung erneut senden',
  'verify.resending': 'Wird erneut gesendet…',
  'verify.return': 'Zurück zur Anmeldung',
}

export const APP_SHELL_CATALOGS: Readonly<
  Record<AppShellLocale, AppShellCatalog>
> = Object.freeze({ en, it, es, fr, de })

export function translateAppShell(
  locale: AppShellLocale,
  key: AppShellMessageKey,
  parameters: Readonly<Record<string, string | number>> = {},
): string {
  return APP_SHELL_CATALOGS[locale][key].replace(
    /\{([A-Za-z][A-Za-z0-9_]*)\}/gu,
    (_placeholder, name: string) => String(parameters[name] ?? `{${name}}`),
  )
}
