export const APP_SHELL_LOCALES = ['en', 'it', 'es', 'fr', 'de'] as const
export type AppShellLocale = typeof APP_SHELL_LOCALES[number]

const en = {
  'auth.eyebrow': 'Postqron workspace',
  'auth.title': 'Plan, publish, and keep every channel in view.',
  'auth.description': 'Sign in or create your account with a trusted provider. No password to remember.',
  'auth.newAccount': 'Create an account',
  'auth.existingAccount': 'Sign in',
  'auth.consentBefore': 'I accept the',
  'auth.terms': 'Terms and Conditions',
  'auth.consentAnd': 'and the',
  'auth.privacy': 'Privacy Policy',
  'auth.consentAfter': '.',
  'auth.provider.google': 'Continue with Google',
  'auth.provider.apple': 'Continue with Apple',
  'auth.provider.facebook': 'Continue with Facebook',
  'auth.provider.linkedin': 'Continue with LinkedIn',
  'auth.providerUnavailable': 'This sign-in method is not configured.',
  'auth.requiredConsent': 'Accept the required documents before continuing.',
  'auth.configurationError': 'Sign-in is temporarily unavailable because configuration is incomplete.',
  'auth.invalidParameters': 'The selected plan details are not valid. Return to pricing and try again.',
  'auth.offline': 'Postqron cannot reach the sign-in service. Check your connection and try again.',
  'auth.retry': 'Try again',
  'callback.loading': 'Completing secure sign-in…',
  'callback.title': 'We could not complete sign-in',
  'callback.description': 'The provider response was declined, expired, or incomplete. No session was created.',
  'callback.retry': 'Return to sign-in',
  'onboarding.eyebrow': 'One last step',
  'onboarding.title': 'Set up your workspace',
  'onboarding.description': 'Confirm the required documents and choose where you want to work.',
  'onboarding.create': 'Create a new workspace',
  'onboarding.select': 'Use an existing workspace',
  'onboarding.workspaceName': 'Workspace name',
  'onboarding.workspacePlaceholder': 'My workspace',
  'onboarding.workspaceChoice': 'Workspace',
  'onboarding.submit': 'Open Postqron',
  'onboarding.saving': 'Setting up your workspace…',
  'onboarding.error': 'We could not finish setup. Your choices were not lost; try again.',
  'shell.skip': 'Skip to main content',
  'shell.navigation': 'Product navigation',
  'shell.home': 'Home',
  'shell.workspace': 'Current workspace',
  'shell.profile': 'Profile',
  'shell.logout': 'Sign out',
  'shell.menu': 'Open navigation',
  'shell.closeMenu': 'Close navigation',
  'home.eyebrow': 'Workspace overview',
  'home.welcome': 'Welcome, {name}',
  'home.description': 'Your product shell is ready. Connected features appear here without changing this navigation.',
  'home.getStarted': 'Start by connecting a social channel or creating a draft.',
  'state.loading.title': 'Loading your workspace',
  'state.loading.description': 'Checking your secure session and workspace access.',
  'state.empty.title': 'Nothing here yet',
  'state.empty.description': 'This feature has an empty workspace slot ready for its first item.',
  'state.offline.title': 'You appear to be offline',
  'state.offline.description': 'Reconnect and retry. Postqron has not discarded your work.',
  'state.denied.title': 'Access denied',
  'state.denied.description': 'Your account does not have access to this workspace or feature.',
  'state.retry': 'Retry',
  'feature.title': 'Feature workspace',
  'feature.description': 'This route is reserved for its owning feature slice.',
} as const

export type AppShellMessageKey = keyof typeof en
export type AppShellCatalog = Readonly<Record<AppShellMessageKey, string>>

const it: AppShellCatalog = {
  'auth.eyebrow': 'Workspace Postqron',
  'auth.title': 'Pianifica, pubblica e tieni ogni canale sotto controllo.',
  'auth.description': 'Accedi o crea il tuo account con un provider affidabile. Nessuna password da ricordare.',
  'auth.newAccount': 'Crea un account',
  'auth.existingAccount': 'Accedi',
  'auth.consentBefore': 'Accetto i',
  'auth.terms': 'Termini e condizioni',
  'auth.consentAnd': 'e la',
  'auth.privacy': 'Privacy Policy',
  'auth.consentAfter': '.',
  'auth.provider.google': 'Continua con Google',
  'auth.provider.apple': 'Continua con Apple',
  'auth.provider.facebook': 'Continua con Facebook',
  'auth.provider.linkedin': 'Continua con LinkedIn',
  'auth.providerUnavailable': 'Questo metodo di accesso non è configurato.',
  'auth.requiredConsent': 'Accetta i documenti obbligatori prima di continuare.',
  'auth.configurationError': 'L’accesso è temporaneamente indisponibile perché la configurazione è incompleta.',
  'auth.invalidParameters': 'I dettagli del piano selezionato non sono validi. Torna ai prezzi e riprova.',
  'auth.offline': 'Postqron non riesce a raggiungere il servizio di accesso. Controlla la connessione e riprova.',
  'auth.retry': 'Riprova',
  'callback.loading': 'Completamento dell’accesso sicuro…',
  'callback.title': 'Non è stato possibile completare l’accesso',
  'callback.description': 'La risposta del provider è stata negata, è scaduta o è incompleta. Non è stata creata alcuna sessione.',
  'callback.retry': 'Torna all’accesso',
  'onboarding.eyebrow': 'Un ultimo passaggio',
  'onboarding.title': 'Configura il tuo workspace',
  'onboarding.description': 'Conferma i documenti obbligatori e scegli dove vuoi lavorare.',
  'onboarding.create': 'Crea un nuovo workspace',
  'onboarding.select': 'Usa un workspace esistente',
  'onboarding.workspaceName': 'Nome del workspace',
  'onboarding.workspacePlaceholder': 'Il mio workspace',
  'onboarding.workspaceChoice': 'Workspace',
  'onboarding.submit': 'Apri Postqron',
  'onboarding.saving': 'Configurazione del workspace…',
  'onboarding.error': 'Non è stato possibile terminare la configurazione. Le tue scelte non sono andate perse; riprova.',
  'shell.skip': 'Vai al contenuto principale',
  'shell.navigation': 'Navigazione prodotto',
  'shell.home': 'Home',
  'shell.workspace': 'Workspace corrente',
  'shell.profile': 'Profilo',
  'shell.logout': 'Esci',
  'shell.menu': 'Apri la navigazione',
  'shell.closeMenu': 'Chiudi la navigazione',
  'home.eyebrow': 'Panoramica workspace',
  'home.welcome': 'Bentornato, {name}',
  'home.description': 'La shell prodotto è pronta. Le funzionalità collegate appariranno qui senza modificare questa navigazione.',
  'home.getStarted': 'Inizia collegando un canale social o creando una bozza.',
  'state.loading.title': 'Caricamento del workspace',
  'state.loading.description': 'Verifica della sessione sicura e dell’accesso al workspace.',
  'state.empty.title': 'Ancora nessun contenuto',
  'state.empty.description': 'Questa funzionalità ha uno spazio vuoto pronto per il primo elemento.',
  'state.offline.title': 'Sembra che tu sia offline',
  'state.offline.description': 'Riconnettiti e riprova. Postqron non ha eliminato il tuo lavoro.',
  'state.denied.title': 'Accesso negato',
  'state.denied.description': 'Il tuo account non può accedere a questo workspace o funzionalità.',
  'state.retry': 'Riprova',
  'feature.title': 'Spazio funzionalità',
  'feature.description': 'Questa route è riservata alla feature che ne è proprietaria.',
}

const es: AppShellCatalog = {
  'auth.eyebrow': 'Espacio de trabajo Postqron',
  'auth.title': 'Planifica, publica y controla todos tus canales.',
  'auth.description': 'Inicia sesión o crea tu cuenta con un proveedor de confianza. Sin contraseñas que recordar.',
  'auth.newAccount': 'Crear una cuenta',
  'auth.existingAccount': 'Iniciar sesión',
  'auth.consentBefore': 'Acepto los',
  'auth.terms': 'Términos y condiciones',
  'auth.consentAnd': 'y la',
  'auth.privacy': 'Política de privacidad',
  'auth.consentAfter': '.',
  'auth.provider.google': 'Continuar con Google',
  'auth.provider.apple': 'Continuar con Apple',
  'auth.provider.facebook': 'Continuar con Facebook',
  'auth.provider.linkedin': 'Continuar con LinkedIn',
  'auth.providerUnavailable': 'Este método de acceso no está configurado.',
  'auth.requiredConsent': 'Acepta los documentos obligatorios antes de continuar.',
  'auth.configurationError': 'El acceso no está disponible temporalmente porque falta configuración.',
  'auth.invalidParameters': 'Los datos del plan seleccionado no son válidos. Vuelve a precios e inténtalo de nuevo.',
  'auth.offline': 'Postqron no puede conectar con el servicio de acceso. Comprueba tu conexión e inténtalo de nuevo.',
  'auth.retry': 'Reintentar',
  'callback.loading': 'Completando el acceso seguro…',
  'callback.title': 'No pudimos completar el acceso',
  'callback.description': 'La respuesta del proveedor fue rechazada, caducó o está incompleta. No se creó ninguna sesión.',
  'callback.retry': 'Volver al acceso',
  'onboarding.eyebrow': 'Un último paso',
  'onboarding.title': 'Configura tu espacio de trabajo',
  'onboarding.description': 'Confirma los documentos obligatorios y elige dónde quieres trabajar.',
  'onboarding.create': 'Crear un espacio nuevo',
  'onboarding.select': 'Usar un espacio existente',
  'onboarding.workspaceName': 'Nombre del espacio',
  'onboarding.workspacePlaceholder': 'Mi espacio de trabajo',
  'onboarding.workspaceChoice': 'Espacio de trabajo',
  'onboarding.submit': 'Abrir Postqron',
  'onboarding.saving': 'Configurando tu espacio…',
  'onboarding.error': 'No pudimos terminar la configuración. Tus elecciones no se han perdido; inténtalo de nuevo.',
  'shell.skip': 'Ir al contenido principal',
  'shell.navigation': 'Navegación del producto',
  'shell.home': 'Inicio',
  'shell.workspace': 'Espacio actual',
  'shell.profile': 'Perfil',
  'shell.logout': 'Cerrar sesión',
  'shell.menu': 'Abrir navegación',
  'shell.closeMenu': 'Cerrar navegación',
  'home.eyebrow': 'Resumen del espacio',
  'home.welcome': 'Te damos la bienvenida, {name}',
  'home.description': 'La estructura del producto está lista. Las funciones conectadas aparecerán aquí sin cambiar esta navegación.',
  'home.getStarted': 'Empieza conectando un canal social o creando un borrador.',
  'state.loading.title': 'Cargando tu espacio',
  'state.loading.description': 'Comprobando tu sesión segura y el acceso al espacio.',
  'state.empty.title': 'Todavía no hay nada',
  'state.empty.description': 'Esta función tiene un espacio vacío preparado para su primer elemento.',
  'state.offline.title': 'Parece que no tienes conexión',
  'state.offline.description': 'Vuelve a conectarte e inténtalo de nuevo. Postqron no ha descartado tu trabajo.',
  'state.denied.title': 'Acceso denegado',
  'state.denied.description': 'Tu cuenta no tiene acceso a este espacio o función.',
  'state.retry': 'Reintentar',
  'feature.title': 'Espacio de la función',
  'feature.description': 'Esta ruta está reservada para la feature propietaria.',
}

const fr: AppShellCatalog = {
  'auth.eyebrow': 'Espace de travail Postqron',
  'auth.title': 'Planifiez, publiez et gardez chaque canal sous contrôle.',
  'auth.description': 'Connectez-vous ou créez votre compte avec un fournisseur de confiance. Aucun mot de passe à retenir.',
  'auth.newAccount': 'Créer un compte',
  'auth.existingAccount': 'Se connecter',
  'auth.consentBefore': 'J’accepte les',
  'auth.terms': 'Conditions générales',
  'auth.consentAnd': 'et la',
  'auth.privacy': 'Politique de confidentialité',
  'auth.consentAfter': '.',
  'auth.provider.google': 'Continuer avec Google',
  'auth.provider.apple': 'Continuer avec Apple',
  'auth.provider.facebook': 'Continuer avec Facebook',
  'auth.provider.linkedin': 'Continuer avec LinkedIn',
  'auth.providerUnavailable': 'Cette méthode de connexion n’est pas configurée.',
  'auth.requiredConsent': 'Acceptez les documents obligatoires avant de continuer.',
  'auth.configurationError': 'La connexion est temporairement indisponible car la configuration est incomplète.',
  'auth.invalidParameters': 'Les informations du forfait sélectionné ne sont pas valides. Revenez aux tarifs et réessayez.',
  'auth.offline': 'Postqron ne peut pas joindre le service de connexion. Vérifiez votre connexion et réessayez.',
  'auth.retry': 'Réessayer',
  'callback.loading': 'Finalisation de la connexion sécurisée…',
  'callback.title': 'Impossible de finaliser la connexion',
  'callback.description': 'La réponse du fournisseur a été refusée, a expiré ou est incomplète. Aucune session n’a été créée.',
  'callback.retry': 'Revenir à la connexion',
  'onboarding.eyebrow': 'Une dernière étape',
  'onboarding.title': 'Configurez votre espace de travail',
  'onboarding.description': 'Confirmez les documents obligatoires et choisissez où travailler.',
  'onboarding.create': 'Créer un nouvel espace',
  'onboarding.select': 'Utiliser un espace existant',
  'onboarding.workspaceName': 'Nom de l’espace',
  'onboarding.workspacePlaceholder': 'Mon espace de travail',
  'onboarding.workspaceChoice': 'Espace de travail',
  'onboarding.submit': 'Ouvrir Postqron',
  'onboarding.saving': 'Configuration de votre espace…',
  'onboarding.error': 'La configuration n’a pas pu être terminée. Vos choix sont conservés ; réessayez.',
  'shell.skip': 'Aller au contenu principal',
  'shell.navigation': 'Navigation du produit',
  'shell.home': 'Accueil',
  'shell.workspace': 'Espace actuel',
  'shell.profile': 'Profil',
  'shell.logout': 'Se déconnecter',
  'shell.menu': 'Ouvrir la navigation',
  'shell.closeMenu': 'Fermer la navigation',
  'home.eyebrow': 'Vue d’ensemble de l’espace',
  'home.welcome': 'Bienvenue, {name}',
  'home.description': 'La structure du produit est prête. Les fonctionnalités connectées apparaîtront ici sans modifier cette navigation.',
  'home.getStarted': 'Commencez par connecter un canal social ou créer un brouillon.',
  'state.loading.title': 'Chargement de votre espace',
  'state.loading.description': 'Vérification de votre session sécurisée et de l’accès à l’espace.',
  'state.empty.title': 'Rien pour le moment',
  'state.empty.description': 'Cette fonctionnalité dispose d’un espace vide prêt pour son premier élément.',
  'state.offline.title': 'Vous semblez hors ligne',
  'state.offline.description': 'Reconnectez-vous et réessayez. Postqron n’a pas supprimé votre travail.',
  'state.denied.title': 'Accès refusé',
  'state.denied.description': 'Votre compte n’a pas accès à cet espace ou à cette fonctionnalité.',
  'state.retry': 'Réessayer',
  'feature.title': 'Espace de fonctionnalité',
  'feature.description': 'Cette route est réservée à la feature qui en est propriétaire.',
}

const de: AppShellCatalog = {
  'auth.eyebrow': 'Postqron-Arbeitsbereich',
  'auth.title': 'Plane, veröffentliche und behalte jeden Kanal im Blick.',
  'auth.description': 'Melde dich über einen vertrauenswürdigen Anbieter an oder erstelle dein Konto. Kein Passwort nötig.',
  'auth.newAccount': 'Konto erstellen',
  'auth.existingAccount': 'Anmelden',
  'auth.consentBefore': 'Ich akzeptiere die',
  'auth.terms': 'Allgemeinen Geschäftsbedingungen',
  'auth.consentAnd': 'und die',
  'auth.privacy': 'Datenschutzerklärung',
  'auth.consentAfter': '.',
  'auth.provider.google': 'Mit Google fortfahren',
  'auth.provider.apple': 'Mit Apple fortfahren',
  'auth.provider.facebook': 'Mit Facebook fortfahren',
  'auth.provider.linkedin': 'Mit LinkedIn fortfahren',
  'auth.providerUnavailable': 'Diese Anmeldemethode ist nicht konfiguriert.',
  'auth.requiredConsent': 'Akzeptiere die erforderlichen Dokumente, bevor du fortfährst.',
  'auth.configurationError': 'Die Anmeldung ist vorübergehend nicht verfügbar, weil die Konfiguration unvollständig ist.',
  'auth.invalidParameters': 'Die Angaben zum gewählten Tarif sind ungültig. Kehre zur Preisseite zurück und versuche es erneut.',
  'auth.offline': 'Postqron kann den Anmeldedienst nicht erreichen. Prüfe deine Verbindung und versuche es erneut.',
  'auth.retry': 'Erneut versuchen',
  'callback.loading': 'Sichere Anmeldung wird abgeschlossen…',
  'callback.title': 'Anmeldung konnte nicht abgeschlossen werden',
  'callback.description': 'Die Anbieterantwort wurde abgelehnt, ist abgelaufen oder unvollständig. Es wurde keine Sitzung erstellt.',
  'callback.retry': 'Zurück zur Anmeldung',
  'onboarding.eyebrow': 'Ein letzter Schritt',
  'onboarding.title': 'Richte deinen Arbeitsbereich ein',
  'onboarding.description': 'Bestätige die erforderlichen Dokumente und wähle deinen Arbeitsbereich.',
  'onboarding.create': 'Neuen Arbeitsbereich erstellen',
  'onboarding.select': 'Vorhandenen Arbeitsbereich verwenden',
  'onboarding.workspaceName': 'Name des Arbeitsbereichs',
  'onboarding.workspacePlaceholder': 'Mein Arbeitsbereich',
  'onboarding.workspaceChoice': 'Arbeitsbereich',
  'onboarding.submit': 'Postqron öffnen',
  'onboarding.saving': 'Arbeitsbereich wird eingerichtet…',
  'onboarding.error': 'Die Einrichtung konnte nicht abgeschlossen werden. Deine Auswahl bleibt erhalten; versuche es erneut.',
  'shell.skip': 'Zum Hauptinhalt springen',
  'shell.navigation': 'Produktnavigation',
  'shell.home': 'Start',
  'shell.workspace': 'Aktueller Arbeitsbereich',
  'shell.profile': 'Profil',
  'shell.logout': 'Abmelden',
  'shell.menu': 'Navigation öffnen',
  'shell.closeMenu': 'Navigation schließen',
  'home.eyebrow': 'Arbeitsbereich im Überblick',
  'home.welcome': 'Willkommen, {name}',
  'home.description': 'Die Produkt-Shell ist bereit. Verbundene Funktionen erscheinen hier, ohne diese Navigation zu ändern.',
  'home.getStarted': 'Verbinde zuerst einen Social-Media-Kanal oder erstelle einen Entwurf.',
  'state.loading.title': 'Arbeitsbereich wird geladen',
  'state.loading.description': 'Sichere Sitzung und Zugriff auf den Arbeitsbereich werden geprüft.',
  'state.empty.title': 'Noch keine Inhalte',
  'state.empty.description': 'Diese Funktion hat einen leeren Bereich für den ersten Eintrag.',
  'state.offline.title': 'Du scheinst offline zu sein',
  'state.offline.description': 'Stelle die Verbindung wieder her und versuche es erneut. Deine Arbeit wurde nicht verworfen.',
  'state.denied.title': 'Zugriff verweigert',
  'state.denied.description': 'Dein Konto hat keinen Zugriff auf diesen Arbeitsbereich oder diese Funktion.',
  'state.retry': 'Erneut versuchen',
  'feature.title': 'Funktionsbereich',
  'feature.description': 'Diese Route ist für die zuständige Feature-Slice reserviert.',
}

export const APP_SHELL_CATALOGS: Readonly<
  Record<AppShellLocale, AppShellCatalog>
> = Object.freeze({ en, it, es, fr, de })

export function translateAppShell(
  locale: AppShellLocale,
  key: AppShellMessageKey,
  parameters: Readonly<Record<string, string | number>> = {},
): string {
  return APP_SHELL_CATALOGS[locale][key].replace(
    /\{([A-Za-z][A-Za-z0-9_]*)\}/gu,
    (_placeholder, name: string) => String(parameters[name] ?? `{${name}}`),
  )
}
