const commonEditorial = {
  'social.provider.facebook_groups': 'Facebook Groups',
  'social.provider.instagram_personal': 'Instagram Personal',
  'social.provider.x': 'X',
  'social.provider.linkedin': 'LinkedIn',
  'social.provider.pinterest': 'Pinterest',
  'social.provider.tiktok': 'TikTok',
  'social.provider.google_business_profile': 'Google Business Profile',
  'social.provider.mastodon': 'Mastodon',
  'social.provider.youtube': 'YouTube',
  'social.provider.threads': 'Threads',
  'social.provider.bluesky': 'Bluesky',
} as const

const enEditorial = {
  'documentTitle.publish': 'Create a post — Postqron',
  'documentTitle.calendar': 'Publishing calendar — Postqron',
  'shell.nav.publish': 'Publish',
  'shell.nav.calendar': 'Calendar',
  'shell.newPost': 'New post',
  'social.addChannel': 'Add channel',
  'social.resource.facebook_page': 'Facebook Page',
  'social.resource.facebook_group': 'Facebook Group',
  'social.resource.instagram_professional': 'Instagram Business / Creator',
  'social.resource.instagram_personal': 'Instagram personal account',
  'social.resource.x_profile': 'X profile',
  'social.resource.linkedin_profile': 'LinkedIn profile',
  'social.resource.linkedin_page': 'LinkedIn Page',
  'social.resource.pinterest_board': 'Pinterest board',
  'social.resource.tiktok_profile': 'TikTok profile',
  'social.resource.google_business_profile_location': 'Business Profile location',
  'social.resource.mastodon_account': 'Mastodon account',
  'social.resource.youtube_channel': 'YouTube channel',
  'social.resource.threads_profile': 'Threads profile',
  'social.resource.bluesky_account': 'Bluesky account',
  'social.accountType.group': 'Group',
  'social.accountType.personal': 'Personal',
  'social.accountType.profile': 'Profile',
  'social.accountType.organization': 'Organization',
  'social.accountType.board': 'Board',
  'social.accountType.location': 'Location',
  'social.accountType.channel': 'Channel',
  'social.catalogDescription': 'The complete D2 catalog stays visible even while an adapter is being configured or is unavailable.',
  'social.catalogState.available': 'Available',
  'social.catalogState.configuring': 'Configuring',
  'social.catalogState.unavailable': 'Unavailable',
  'social.configuration.ready': 'Ready to connect.',
  'social.configuration.not_configured': 'Provider credentials are not configured.',
  'social.configuration.review_required': 'Provider review is still in progress.',
  'social.configuration.audit_required': 'The runtime audit must be completed.',
  'social.publishingMode': 'Publishing mode',
  'social.publishingMode.auto': 'Automatic publishing',
  'social.publishingMode.notification': 'Notification publishing',
  'social.publishingMode.unknown': 'Not declared',
  'social.errorProviderReview': 'This provider is still in review. No authorization was started.',
  'social.errorProviderAudit': 'This provider is configured but its runtime audit is incomplete.',
  'social.manageRestricted': 'Only an Owner on an active workspace can connect, reconnect, select, or revoke channels.',
  'social.discoveryLegend': 'Discovery input',
  'social.discoveryKindLabel': 'Discovery type',
  'social.chooseDiscoveryKind': 'Choose a discovery type',
  'social.discoveryKind.instance_origin': 'Instance origin',
  'social.discoveryKind.handle': 'Handle',
  'social.discoveryKind.did': 'DID',
  'social.discoveryKind.pds_origin': 'PDS origin',
  'social.discoveryValueLabel': 'Discovery value',
  'social.discoveryValuePlaceholder': 'https://social.example or @handle',
  'social.discoveryHelp': 'Provide only the typed identifier accepted by F5. Passwords and app-passwords are never accepted here.',
  'social.errorPopupBlocked': 'Your browser blocked the secure authorization window. Allow popups for Postqron and try again.',
  'social.errorDiscoveryRequired': 'Choose a discovery type and value before starting this provider authorization.',
  'social.errorCallbackHandoff': 'The provider completed OAuth, but the JSON callback could not be handed back to the UI securely. No channel was connected.',
  'social.errorPopupIsolation': 'The authorization window could not be isolated safely. No authorization was started.',
  'social.errorPopupClosed': 'You closed the authorization window before finishing. No channel was connected. Try again when you are ready.',
  'composer.eyebrow': 'Publish',
  'composer.title': 'Create a post',
  'composer.editTitle': 'Edit scheduled post',
  'composer.description': 'Write once, choose multiple destinations, and adapt content before publishing.',
  'composer.emptyEyebrow': 'Start here',
  'composer.emptyTitle': 'Connect a channel before publishing',
  'composer.emptyDescription': 'Add at least one available social channel, then return here to create and schedule content.',
  'composer.addChannel': 'Add a social channel',
  'composer.contentEyebrow': 'Content',
  'composer.contentTitle': 'Post content',
  'composer.textLabel': 'Text',
  'composer.textPlaceholder': 'What do you want to share?',
  'composer.linkLabel': 'Link (optional)',
  'composer.mediaEyebrow': 'Media',
  'composer.mediaTitle': 'Images and video',
  'composer.mediaDescription': 'Files are uploaded through the secure F6 authorization and inspected before scheduling.',
  'composer.upload': 'Add media',
  'composer.uploading': 'Uploading and checking…',
  'composer.mediaReady': 'Media uploaded and checked.',
  'composer.removeMedia': 'Remove',
  'composer.mediaStatus.pending': 'Checking',
  'composer.mediaStatus.ready': 'Ready',
  'composer.mediaStatus.rejected': 'Rejected',
  'composer.threadEyebrow': 'Thread',
  'composer.threadTitle': 'Thread items',
  'composer.threadDescription': 'Thread structure follows the live F6 capability rules for the selected destinations.',
  'composer.threadLegend': 'Thread content',
  'composer.threadLimits': 'Items: {minimum} minimum, {maximum} maximum. Characters per item: {characters}. Media per item: {media}.',
  'composer.threadEmpty': 'No thread items yet.',
  'composer.threadItemTitle': 'Item {count}',
  'composer.removeThreadItem': 'Remove item',
  'composer.threadTextLabel': 'Item text',
  'composer.threadTextPlaceholder': 'Write this thread item.',
  'composer.threadMediaLegend': 'Item media',
  'composer.threadMediaEmpty': 'Upload media above to attach it to a thread item.',
  'composer.addThreadItem': 'Add thread item',
  'composer.threadForbidden': 'A selected destination does not allow threads. Remove the stale thread items before publishing.',
  'composer.threadConstraintsImpossible': 'The selected destinations have incompatible thread limits: the required minimum is greater than the allowed maximum.',
  'composer.destinationsEyebrow': 'Destinations',
  'composer.destinationsTitle': 'Choose channels',
  'composer.destinationsDescription': 'Select one or more channels. Available formats and rules come from the live F6 capability catalog.',
  'composer.destinationsLegend': 'Destination selection',
  'composer.destinationRequired': 'Select at least one destination before publishing.',
  'composer.destinationUnavailable': 'No active F6 capability is available for this channel yet.',
  'composer.formatLabel': 'Format',
  'composer.format.text': 'Text',
  'composer.format.link': 'Link',
  'composer.format.image': 'Image',
  'composer.format.carousel': 'Carousel',
  'composer.format.video': 'Video',
  'composer.format.short_video': 'Short video',
  'composer.format.thread': 'Thread',
  'composer.personalizationLabel': 'Channel-specific text (optional)',
  'composer.personalizationPlaceholder': 'Leave empty to use the main text.',
  'composer.providerFieldsLegend': 'Provider metadata',
  'composer.requiredField': '(required)',
  'composer.chooseFieldValue': 'Choose a value',
  'composer.maxCharacters': 'Maximum {count} characters.',
  'composer.field.destinations': 'Destinations',
  'composer.field.text': 'Text',
  'composer.field.link': 'Link',
  'composer.field.media': 'Media',
  'composer.field.thread': 'Thread',
  'composer.validation.code.channel_id_required': 'A destination channel is missing.',
  'composer.validation.code.destination_id_duplicate': 'Each destination must appear only once.',
  'composer.validation.code.destination_id_required': 'A destination identifier is missing.',
  'composer.validation.code.destinations_required': 'Select at least one destination.',
  'composer.validation.code.media_id_duplicate': 'The same media item cannot be attached twice.',
  'composer.validation.code.media_id_required': 'A media identifier is missing.',
  'composer.validation.code.media_storage_key_required': 'Uploaded media is incomplete. Upload it again.',
  'composer.validation.code.text_required': 'Text is required for this destination.',
  'composer.validation.code.text_too_long': 'Text exceeds the allowed length.',
  'composer.validation.code.video_fast_start_required': 'The video must use fast-start streaming metadata.',
  'composer.validation.rule.max_item_characters': 'This thread item is too long.',
  'composer.validation.rule.max_media_per_item': 'This thread item has too many media attachments.',
  'composer.validation.rule.maximum_code_points': 'This value is too long.',
  'composer.validation.rule.maximum_items': 'Too many items were added.',
  'composer.validation.rule.minimum_items': 'Add more items to satisfy the minimum.',
  'composer.validation.rule.required': 'This field is required.',
  'composer.validation.rule.unique': 'This value must be unique.',
  'composer.actionsEyebrow': 'Actions',
  'composer.actionsTitle': 'Save or publish',
  'composer.saveDraft': 'Save draft',
  'composer.publishNow': 'Publish now',
  'composer.publishing': 'Queueing publication…',
  'composer.schedule': 'Schedule',
  'composer.scheduling': 'Scheduling…',
  'composer.confirmSchedule': 'Confirm schedule',
  'composer.dateTimeLabel': 'Local date and time',
  'composer.timezoneLabel': 'IANA timezone',
  'composer.offsetLabel': 'UTC offset in minutes (if ambiguous)',
  'composer.offsetHelp': 'Only needed during the repeated hour when daylight saving time ends.',
  'composer.chooseOffset': 'Choose which occurrence',
  'composer.offsetRequired': 'This local time occurs twice. Choose the intended UTC offset.',
  'composer.localTimeNonexistent': 'This local time does not exist because of a daylight-saving transition. Choose another time.',
  'composer.offsetInvalid': 'Enter a UTC offset between -1080 and 1080 minutes.',
  'composer.scheduleRequired': 'Enter a date, time, and IANA timezone.',
  'composer.validationFailed': 'Some destinations are not valid yet. Review the field-level guidance below.',
  'composer.saved': 'Draft saved.',
  'composer.saveState.idle': 'Changes waiting to autosave',
  'composer.saveState.saving': 'Saving…',
  'composer.saveState.saved': 'All changes saved',
  'composer.saveState.error': 'Autosave needs attention',
  'editorial.error.accessDenied': 'You do not have access to this workspace action.',
  'editorial.error.conflict': 'The post changed elsewhere. Reload and retry with the latest revision.',
  'editorial.error.dependency': 'A required publishing service is not ready. Your draft remains saved; retry when the dependency is available.',
  'editorial.error.invalid': 'The request is not valid. Review the highlighted fields and provider rules.',
  'editorial.error.offline': 'Postqron is unreachable. Check your connection and retry; your local edits remain on screen.',
  'editorial.error.notFound': 'This draft or scheduled post is no longer available.',
  'editorial.error.unavailable': 'The editorial service is temporarily unavailable. Retry in a moment.',
  'calendar.eyebrow': 'Publishing',
  'calendar.title': 'Calendar',
  'calendar.description': 'Review scheduled work by date, channel, status, and explicit timezone.',
  'calendar.controlsLabel': 'Calendar controls',
  'calendar.viewCalendar': 'Calendar view',
  'calendar.viewList': 'List view',
  'calendar.filterChannel': 'Channel',
  'calendar.allChannels': 'All channels',
  'calendar.filterStatus': 'Status',
  'calendar.allStatuses': 'All statuses',
  'calendar.timezone': 'Display timezone',
  'calendar.previousMonth': 'Previous month',
  'calendar.nextMonth': 'Next month',
  'calendar.emptyEyebrow': 'No posts',
  'calendar.emptyTitle': 'Nothing scheduled for this period',
  'calendar.emptyDescription': 'Create a post or change the filters to see other scheduled work.',
  'calendar.untitled': 'Untitled draft',
  'calendar.unknownChannel': 'Unavailable channel',
  'calendar.status.scheduled': 'Scheduled',
  'calendar.status.publishing': 'Publishing',
  'calendar.status.published': 'Published',
  'calendar.status.failed': 'Failed',
  'calendar.status.cancelled': 'Cancelled',
  'calendar.failureGeneric': 'Publishing failed for this destination. F7 does not expose a provider-specific cause; check the channel and retry.',
  'calendar.readOnly': 'This post is now read-only in F30. Only scheduled posts can be edited, duplicated, rescheduled, or cancelled.',
  'calendar.edit': 'Edit',
  'calendar.duplicate': 'Duplicate',
  'calendar.reschedule': 'Reschedule',
  'calendar.cancel': 'Cancel',
  'calendar.cancelConfirm': 'Cancel this scheduled post? The previous publication command will be invalidated.',
  'calendar.duplicated': 'Post duplicated.',
  'calendar.rescheduled': 'Post rescheduled.',
  'calendar.cancelled': 'Scheduled post cancelled.',
  'calendar.rescheduleEyebrow': 'New publication time',
  'calendar.rescheduleTitle': 'Reschedule post',
  'calendar.confirmReschedule': 'Confirm new time',
  'calendar.close': 'Close',
} as const

type LocalEditorialCatalog = Readonly<Record<keyof typeof enEditorial, string>>

const itEditorial: LocalEditorialCatalog = {
  ...enEditorial,
  'documentTitle.publish': 'Crea un post — Postqron',
  'documentTitle.calendar': 'Calendario editoriale — Postqron',
  'shell.nav.publish': 'Pubblica',
  'shell.nav.calendar': 'Calendario',
  'shell.newPost': 'Nuovo post',
  'social.addChannel': 'Aggiungi canale',
  'social.errorPopupIsolation': 'Non è stato possibile isolare in sicurezza la finestra di autorizzazione. Nessuna autorizzazione è stata avviata.',
  'social.errorPopupClosed': 'Hai chiuso la finestra di autorizzazione prima di completare. Nessun canale è stato collegato. Riprova quando vuoi.',
  'social.resource.facebook_page': 'Pagina Facebook',
  'social.resource.facebook_group': 'Gruppo Facebook',
  'social.resource.instagram_professional': 'Instagram Business / Creator',
  'social.resource.instagram_personal': 'Account Instagram personale',
  'social.resource.x_profile': 'Profilo X',
  'social.resource.linkedin_profile': 'Profilo LinkedIn',
  'social.resource.linkedin_page': 'Pagina LinkedIn',
  'social.resource.pinterest_board': 'Bacheca Pinterest',
  'social.resource.tiktok_profile': 'Profilo TikTok',
  'social.resource.google_business_profile_location': 'Sede del Profilo dell’attività',
  'social.resource.mastodon_account': 'Account Mastodon',
  'social.resource.youtube_channel': 'Canale YouTube',
  'social.resource.threads_profile': 'Profilo Threads',
  'social.resource.bluesky_account': 'Account Bluesky',
  'social.accountType.group': 'Gruppo',
  'social.accountType.personal': 'Personale',
  'social.accountType.profile': 'Profilo',
  'social.accountType.organization': 'Organizzazione',
  'social.accountType.board': 'Bacheca',
  'social.accountType.location': 'Sede',
  'social.accountType.channel': 'Canale',
  'social.catalogDescription': 'Il catalogo D2 completo resta visibile anche quando un adapter è in configurazione o non disponibile.',
  'social.catalogState.available': 'Disponibile',
  'social.catalogState.configuring': 'In configurazione',
  'social.catalogState.unavailable': 'Non disponibile',
  'social.configuration.ready': 'Pronto per il collegamento.',
  'social.configuration.not_configured': 'Le credenziali del provider non sono configurate.',
  'social.configuration.review_required': 'La review del provider è ancora in corso.',
  'social.configuration.audit_required': 'L’audit runtime deve essere completato.',
  'social.publishingMode': 'Modalità di pubblicazione',
  'social.publishingMode.auto': 'Pubblicazione automatica',
  'social.publishingMode.notification': 'Pubblicazione con notifica',
  'social.publishingMode.unknown': 'Non dichiarata',
  'social.errorProviderReview': 'Questo provider è ancora in review. Nessuna autorizzazione è stata avviata.',
  'social.errorProviderAudit': 'Il provider è configurato, ma l’audit runtime non è completo.',
  'social.manageRestricted': 'Solo un Owner su un workspace attivo può collegare, riconnettere, selezionare o revocare canali.',
  'social.discoveryLegend': 'Input di discovery',
  'social.discoveryKindLabel': 'Tipo di discovery',
  'social.chooseDiscoveryKind': 'Scegli un tipo di discovery',
  'social.discoveryKind.instance_origin': 'Origin dell’istanza',
  'social.discoveryKind.handle': 'Handle',
  'social.discoveryKind.did': 'DID',
  'social.discoveryKind.pds_origin': 'Origin del PDS',
  'social.discoveryValueLabel': 'Valore di discovery',
  'social.discoveryValuePlaceholder': 'https://social.example o @handle',
  'social.discoveryHelp': 'Fornisci solo l’identificatore tipizzato accettato da F5. Password e app-password non sono mai accettate qui.',
  'social.errorPopupBlocked': 'Il browser ha bloccato la finestra di autorizzazione sicura. Consenti i popup per Postqron e riprova.',
  'social.errorDiscoveryRequired': 'Scegli tipo e valore di discovery prima di avviare questa autorizzazione.',
  'social.errorCallbackHandoff': 'Il provider ha completato OAuth, ma il callback JSON non è stato restituito alla UI in modo sicuro. Nessun canale è stato collegato.',
  'composer.eyebrow': 'Pubblica',
  'composer.title': 'Crea un post',
  'composer.editTitle': 'Modifica post programmato',
  'composer.description': 'Scrivi una volta, scegli più destinazioni e adatta il contenuto prima della pubblicazione.',
  'composer.emptyEyebrow': 'Inizia qui',
  'composer.emptyTitle': 'Collega un canale prima di pubblicare',
  'composer.emptyDescription': 'Aggiungi almeno un canale social disponibile, poi torna qui per creare e programmare contenuti.',
  'composer.addChannel': 'Aggiungi un canale social',
  'composer.contentEyebrow': 'Contenuto',
  'composer.contentTitle': 'Contenuto del post',
  'composer.textLabel': 'Testo',
  'composer.textPlaceholder': 'Cosa vuoi condividere?',
  'composer.linkLabel': 'Link (facoltativo)',
  'composer.mediaEyebrow': 'Media',
  'composer.mediaTitle': 'Immagini e video',
  'composer.mediaDescription': 'I file vengono caricati con l’autorizzazione sicura F6 e controllati prima della programmazione.',
  'composer.upload': 'Aggiungi media',
  'composer.uploading': 'Caricamento e controllo…',
  'composer.mediaReady': 'Media caricato e controllato.',
  'composer.removeMedia': 'Rimuovi',
  'composer.mediaStatus.pending': 'In controllo',
  'composer.mediaStatus.ready': 'Pronto',
  'composer.mediaStatus.rejected': 'Rifiutato',
  'composer.threadEyebrow': 'Thread',
  'composer.threadTitle': 'Elementi del thread',
  'composer.threadDescription': 'La struttura del thread segue le regole capability F6 vive delle destinazioni selezionate.',
  'composer.threadLegend': 'Contenuto del thread',
  'composer.threadLimits': 'Elementi: minimo {minimum}, massimo {maximum}. Caratteri per elemento: {characters}. Media per elemento: {media}.',
  'composer.threadEmpty': 'Ancora nessun elemento nel thread.',
  'composer.threadItemTitle': 'Elemento {count}',
  'composer.removeThreadItem': 'Rimuovi elemento',
  'composer.threadTextLabel': 'Testo dell’elemento',
  'composer.threadTextPlaceholder': 'Scrivi questo elemento del thread.',
  'composer.threadMediaLegend': 'Media dell’elemento',
  'composer.threadMediaEmpty': 'Carica media sopra per associarli a un elemento del thread.',
  'composer.addThreadItem': 'Aggiungi elemento',
  'composer.threadForbidden': 'Una destinazione selezionata non consente thread. Rimuovi gli elementi obsoleti prima di pubblicare.',
  'composer.threadConstraintsImpossible': 'Le destinazioni selezionate hanno limiti thread incompatibili: il minimo richiesto supera il massimo consentito.',
  'composer.destinationsEyebrow': 'Destinazioni',
  'composer.destinationsTitle': 'Scegli i canali',
  'composer.destinationsDescription': 'Seleziona uno o più canali. Formati e regole arrivano dal catalogo capability F6.',
  'composer.destinationsLegend': 'Selezione destinazioni',
  'composer.destinationRequired': 'Seleziona almeno una destinazione prima di pubblicare.',
  'composer.destinationUnavailable': 'Non è ancora disponibile una capability F6 attiva per questo canale.',
  'composer.formatLabel': 'Formato',
  'composer.format.text': 'Testo',
  'composer.format.link': 'Link',
  'composer.format.image': 'Immagine',
  'composer.format.carousel': 'Carosello',
  'composer.format.video': 'Video',
  'composer.format.short_video': 'Video breve',
  'composer.format.thread': 'Thread',
  'composer.personalizationLabel': 'Testo specifico per il canale (facoltativo)',
  'composer.personalizationPlaceholder': 'Lascia vuoto per usare il testo principale.',
  'composer.providerFieldsLegend': 'Metadati del provider',
  'composer.requiredField': '(obbligatorio)',
  'composer.chooseFieldValue': 'Scegli un valore',
  'composer.maxCharacters': 'Massimo {count} caratteri.',
  'composer.field.destinations': 'Destinazioni',
  'composer.field.text': 'Testo',
  'composer.field.link': 'Link',
  'composer.field.media': 'Media',
  'composer.field.thread': 'Thread',
  'composer.validation.code.channel_id_required': 'Manca il canale di una destinazione.',
  'composer.validation.code.destination_id_duplicate': 'Ogni destinazione deve comparire una sola volta.',
  'composer.validation.code.destination_id_required': 'Manca l’identificatore della destinazione.',
  'composer.validation.code.destinations_required': 'Seleziona almeno una destinazione.',
  'composer.validation.code.media_id_duplicate': 'Lo stesso media non può essere associato due volte.',
  'composer.validation.code.media_id_required': 'Manca l’identificatore del media.',
  'composer.validation.code.media_storage_key_required': 'Il media caricato è incompleto. Caricalo di nuovo.',
  'composer.validation.code.text_required': 'Il testo è obbligatorio per questa destinazione.',
  'composer.validation.code.text_too_long': 'Il testo supera la lunghezza consentita.',
  'composer.validation.code.video_fast_start_required': 'Il video deve usare metadati fast-start.',
  'composer.validation.rule.max_item_characters': 'Questo elemento del thread è troppo lungo.',
  'composer.validation.rule.max_media_per_item': 'Questo elemento del thread ha troppi media.',
  'composer.validation.rule.maximum_code_points': 'Questo valore è troppo lungo.',
  'composer.validation.rule.maximum_items': 'Sono stati aggiunti troppi elementi.',
  'composer.validation.rule.minimum_items': 'Aggiungi altri elementi per raggiungere il minimo richiesto.',
  'composer.validation.rule.required': 'Questo campo è obbligatorio.',
  'composer.validation.rule.unique': 'Questo valore deve essere univoco.',
  'composer.actionsEyebrow': 'Azioni',
  'composer.actionsTitle': 'Salva o pubblica',
  'composer.saveDraft': 'Salva bozza',
  'composer.publishNow': 'Pubblica ora',
  'composer.publishing': 'Invio in pubblicazione…',
  'composer.schedule': 'Programma',
  'composer.scheduling': 'Programmazione…',
  'composer.confirmSchedule': 'Conferma programmazione',
  'composer.dateTimeLabel': 'Data e ora locali',
  'composer.timezoneLabel': 'Timezone IANA',
  'composer.offsetLabel': 'Offset UTC in minuti (se ambiguo)',
  'composer.offsetHelp': 'Serve solo nell’ora ripetuta al termine dell’ora legale.',
  'composer.chooseOffset': 'Scegli l’occorrenza',
  'composer.offsetRequired': 'Questa ora locale si ripete due volte. Scegli l’offset UTC desiderato.',
  'composer.localTimeNonexistent': 'Questa ora locale non esiste a causa del cambio dell’ora legale. Scegli un altro orario.',
  'composer.offsetInvalid': 'Inserisci un offset UTC tra -1080 e 1080 minuti.',
  'composer.scheduleRequired': 'Inserisci data, ora e timezone IANA.',
  'composer.validationFailed': 'Alcune destinazioni non sono ancora valide. Segui le indicazioni sui campi.',
  'composer.saved': 'Bozza salvata.',
  'composer.saveState.idle': 'Modifiche in attesa di autosave',
  'composer.saveState.saving': 'Salvataggio…',
  'composer.saveState.saved': 'Tutte le modifiche sono salvate',
  'composer.saveState.error': 'L’autosave richiede attenzione',
  'editorial.error.accessDenied': 'Non hai accesso a questa azione nel workspace.',
  'editorial.error.conflict': 'Il post è cambiato altrove. Ricarica e riprova con la revisione più recente.',
  'editorial.error.dependency': 'Un servizio di pubblicazione richiesto non è pronto. La bozza resta salvata; riprova quando sarà disponibile.',
  'editorial.error.invalid': 'La richiesta non è valida. Controlla i campi e le regole del provider.',
  'editorial.error.offline': 'Postqron non è raggiungibile. Controlla la connessione e riprova; le modifiche restano sullo schermo.',
  'editorial.error.notFound': 'Questa bozza o questo post programmato non è più disponibile.',
  'editorial.error.unavailable': 'Il servizio editoriale è temporaneamente non disponibile. Riprova tra poco.',
  'calendar.eyebrow': 'Pubblicazione',
  'calendar.title': 'Calendario',
  'calendar.description': 'Controlla il lavoro programmato per data, canale, stato e timezone esplicita.',
  'calendar.controlsLabel': 'Controlli del calendario',
  'calendar.viewCalendar': 'Vista calendario',
  'calendar.viewList': 'Vista elenco',
  'calendar.filterChannel': 'Canale',
  'calendar.allChannels': 'Tutti i canali',
  'calendar.filterStatus': 'Stato',
  'calendar.allStatuses': 'Tutti gli stati',
  'calendar.timezone': 'Timezone di visualizzazione',
  'calendar.previousMonth': 'Mese precedente',
  'calendar.nextMonth': 'Mese successivo',
  'calendar.emptyEyebrow': 'Nessun post',
  'calendar.emptyTitle': 'Niente di programmato in questo periodo',
  'calendar.emptyDescription': 'Crea un post o cambia i filtri per vedere altri contenuti programmati.',
  'calendar.untitled': 'Bozza senza titolo',
  'calendar.unknownChannel': 'Canale non disponibile',
  'calendar.status.scheduled': 'Programmato',
  'calendar.status.publishing': 'In pubblicazione',
  'calendar.status.published': 'Pubblicato',
  'calendar.status.failed': 'Fallito',
  'calendar.status.cancelled': 'Annullato',
  'calendar.failureGeneric': 'Pubblicazione fallita per questa destinazione. F7 non espone una causa specifica del provider: controlla il canale e riprova.',
  'calendar.readOnly': 'Questo post ora è in sola lettura in F30. Solo i post programmati possono essere modificati, duplicati, riprogrammati o annullati.',
  'calendar.edit': 'Modifica',
  'calendar.duplicate': 'Duplica',
  'calendar.reschedule': 'Riprogramma',
  'calendar.cancel': 'Annulla',
  'calendar.cancelConfirm': 'Annullare questo post programmato? Il comando di pubblicazione precedente verrà invalidato.',
  'calendar.duplicated': 'Post duplicato.',
  'calendar.rescheduled': 'Post riprogrammato.',
  'calendar.cancelled': 'Post programmato annullato.',
  'calendar.rescheduleEyebrow': 'Nuovo orario di pubblicazione',
  'calendar.rescheduleTitle': 'Riprogramma il post',
  'calendar.confirmReschedule': 'Conferma nuovo orario',
  'calendar.close': 'Chiudi',
}

const esEditorial: LocalEditorialCatalog = {
  ...enEditorial,
  'documentTitle.publish': 'Crear una publicación — Postqron',
  'documentTitle.calendar': 'Calendario editorial — Postqron',
  'shell.nav.publish': 'Publicar',
  'shell.nav.calendar': 'Calendario',
  'shell.newPost': 'Nueva publicación',
  'social.addChannel': 'Añadir canal',
  'social.errorPopupIsolation': 'No se pudo aislar de forma segura la ventana de autorización. No se inició ninguna autorización.',
  'social.errorPopupClosed': 'Cerraste la ventana de autorización antes de terminar. No se conectó ningún canal. Inténtalo de nuevo cuando quieras.',
  'social.resource.facebook_page': 'Página de Facebook',
  'social.resource.facebook_group': 'Grupo de Facebook',
  'social.resource.instagram_professional': 'Instagram Business / Creator',
  'social.resource.instagram_personal': 'Cuenta personal de Instagram',
  'social.resource.x_profile': 'Perfil de X',
  'social.resource.linkedin_profile': 'Perfil de LinkedIn',
  'social.resource.linkedin_page': 'Página de LinkedIn',
  'social.resource.pinterest_board': 'Tablero de Pinterest',
  'social.resource.tiktok_profile': 'Perfil de TikTok',
  'social.resource.google_business_profile_location': 'Ubicación del Perfil de Empresa',
  'social.resource.mastodon_account': 'Cuenta de Mastodon',
  'social.resource.youtube_channel': 'Canal de YouTube',
  'social.resource.threads_profile': 'Perfil de Threads',
  'social.resource.bluesky_account': 'Cuenta de Bluesky',
  'social.accountType.group': 'Grupo',
  'social.accountType.personal': 'Personal',
  'social.accountType.profile': 'Perfil',
  'social.accountType.organization': 'Organización',
  'social.accountType.board': 'Tablero',
  'social.accountType.location': 'Ubicación',
  'social.accountType.channel': 'Canal',
  'social.catalogDescription': 'El catálogo D2 completo sigue visible aunque un adaptador esté en configuración o no disponible.',
  'social.catalogState.available': 'Disponible',
  'social.catalogState.configuring': 'En configuración',
  'social.catalogState.unavailable': 'No disponible',
  'social.configuration.ready': 'Listo para conectar.',
  'social.configuration.not_configured': 'Las credenciales del proveedor no están configuradas.',
  'social.configuration.review_required': 'La revisión del proveedor sigue en curso.',
  'social.configuration.audit_required': 'Debe completarse la auditoría de ejecución.',
  'social.publishingMode': 'Modo de publicación',
  'social.publishingMode.auto': 'Publicación automática',
  'social.publishingMode.notification': 'Publicación por notificación',
  'social.publishingMode.unknown': 'No declarado',
  'social.errorProviderReview': 'Este proveedor sigue en revisión. No se inició ninguna autorización.',
  'social.errorProviderAudit': 'El proveedor está configurado, pero falta su auditoría de ejecución.',
  'composer.eyebrow': 'Publicar',
  'composer.title': 'Crear una publicación',
  'composer.editTitle': 'Editar publicación programada',
  'composer.description': 'Escribe una vez, elige varios destinos y adapta el contenido antes de publicar.',
  'composer.emptyEyebrow': 'Empieza aquí',
  'composer.emptyTitle': 'Conecta un canal antes de publicar',
  'composer.emptyDescription': 'Añade al menos un canal social disponible y vuelve para crear y programar contenido.',
  'composer.addChannel': 'Añadir un canal social',
  'composer.contentEyebrow': 'Contenido',
  'composer.contentTitle': 'Contenido de la publicación',
  'composer.textLabel': 'Texto',
  'composer.textPlaceholder': '¿Qué quieres compartir?',
  'composer.linkLabel': 'Enlace (opcional)',
  'composer.mediaEyebrow': 'Multimedia',
  'composer.mediaTitle': 'Imágenes y vídeo',
  'composer.mediaDescription': 'Los archivos usan la autorización segura de F6 y se inspeccionan antes de programar.',
  'composer.upload': 'Añadir archivo',
  'composer.uploading': 'Subiendo y comprobando…',
  'composer.mediaReady': 'Archivo subido y comprobado.',
  'composer.removeMedia': 'Quitar',
  'composer.mediaStatus.pending': 'Comprobando',
  'composer.mediaStatus.ready': 'Listo',
  'composer.mediaStatus.rejected': 'Rechazado',
  'composer.destinationsEyebrow': 'Destinos',
  'composer.destinationsTitle': 'Elige canales',
  'composer.destinationsDescription': 'Selecciona uno o varios canales. Los formatos y reglas proceden del catálogo F6.',
  'composer.destinationRequired': 'Selecciona al menos un destino antes de publicar.',
  'composer.destinationUnavailable': 'Aún no hay una capacidad F6 activa para este canal.',
  'composer.formatLabel': 'Formato',
  'composer.format.text': 'Texto',
  'composer.format.link': 'Enlace',
  'composer.format.image': 'Imagen',
  'composer.format.carousel': 'Carrusel',
  'composer.format.video': 'Vídeo',
  'composer.format.short_video': 'Vídeo corto',
  'composer.format.thread': 'Hilo',
  'composer.personalizationLabel': 'Texto específico del canal (opcional)',
  'composer.personalizationPlaceholder': 'Déjalo vacío para usar el texto principal.',
  'composer.providerFieldsLegend': 'Metadatos del proveedor',
  'composer.requiredField': '(obligatorio)',
  'composer.chooseFieldValue': 'Elige un valor',
  'composer.maxCharacters': 'Máximo {count} caracteres.',
  'composer.actionsEyebrow': 'Acciones',
  'composer.actionsTitle': 'Guardar o publicar',
  'composer.saveDraft': 'Guardar borrador',
  'composer.publishNow': 'Publicar ahora',
  'composer.publishing': 'Enviando a publicación…',
  'composer.schedule': 'Programar',
  'composer.scheduling': 'Programando…',
  'composer.confirmSchedule': 'Confirmar programación',
  'composer.dateTimeLabel': 'Fecha y hora locales',
  'composer.timezoneLabel': 'Zona horaria IANA',
  'composer.offsetLabel': 'Desfase UTC en minutos (si es ambiguo)',
  'composer.offsetHelp': 'Solo es necesario durante la hora repetida al terminar el horario de verano.',
  'composer.chooseOffset': 'Elige la ocurrencia',
  'composer.offsetRequired': 'Esta hora local ocurre dos veces. Elige el desfase UTC deseado.',
  'composer.localTimeNonexistent': 'Esta hora local no existe debido al cambio de horario. Elige otra hora.',
  'composer.threadForbidden': 'Un destino seleccionado no admite hilos. Elimina los elementos obsoletos antes de publicar.',
  'composer.threadConstraintsImpossible': 'Los destinos seleccionados tienen límites de hilo incompatibles: el mínimo requerido supera el máximo permitido.',
  'composer.offsetInvalid': 'Introduce un desfase UTC entre -1080 y 1080 minutos.',
  'composer.scheduleRequired': 'Introduce fecha, hora y zona horaria IANA.',
  'composer.validationFailed': 'Algunos destinos aún no son válidos. Revisa las indicaciones de cada campo.',
  'composer.saved': 'Borrador guardado.',
  'composer.saveState.idle': 'Cambios pendientes de guardado automático',
  'composer.saveState.saving': 'Guardando…',
  'composer.saveState.saved': 'Todos los cambios guardados',
  'composer.saveState.error': 'El guardado automático requiere atención',
  'editorial.error.accessDenied': 'No tienes acceso a esta acción del espacio.',
  'editorial.error.conflict': 'La publicación cambió en otro lugar. Recarga e inténtalo con la última revisión.',
  'editorial.error.dependency': 'Un servicio necesario no está listo. El borrador sigue guardado; inténtalo cuando esté disponible.',
  'editorial.error.invalid': 'La solicitud no es válida. Revisa los campos y las reglas del proveedor.',
  'editorial.error.offline': 'Postqron no está disponible. Comprueba la conexión; tus cambios siguen en pantalla.',
  'editorial.error.notFound': 'Este borrador o publicación programada ya no está disponible.',
  'editorial.error.unavailable': 'El servicio editorial no está disponible temporalmente. Inténtalo de nuevo.',
  'calendar.eyebrow': 'Publicación',
  'calendar.title': 'Calendario',
  'calendar.description': 'Revisa el trabajo programado por fecha, canal, estado y zona horaria explícita.',
  'calendar.controlsLabel': 'Controles del calendario',
  'calendar.viewCalendar': 'Vista de calendario',
  'calendar.viewList': 'Vista de lista',
  'calendar.filterChannel': 'Canal',
  'calendar.allChannels': 'Todos los canales',
  'calendar.filterStatus': 'Estado',
  'calendar.allStatuses': 'Todos los estados',
  'calendar.timezone': 'Zona horaria visible',
  'calendar.previousMonth': 'Mes anterior',
  'calendar.nextMonth': 'Mes siguiente',
  'calendar.emptyEyebrow': 'Sin publicaciones',
  'calendar.emptyTitle': 'No hay nada programado para este periodo',
  'calendar.emptyDescription': 'Crea una publicación o cambia los filtros para ver otro trabajo programado.',
  'calendar.untitled': 'Borrador sin título',
  'calendar.unknownChannel': 'Canal no disponible',
  'calendar.status.scheduled': 'Programado',
  'calendar.status.publishing': 'Publicando',
  'calendar.status.published': 'Publicado',
  'calendar.status.failed': 'Fallido',
  'calendar.status.cancelled': 'Cancelado',
  'calendar.failureGeneric': 'La publicación falló para este destino. F7 no expone una causa del proveedor; revisa el canal e inténtalo de nuevo.',
  'calendar.edit': 'Editar',
  'calendar.duplicate': 'Duplicar',
  'calendar.reschedule': 'Reprogramar',
  'calendar.cancel': 'Cancelar',
  'calendar.cancelConfirm': '¿Cancelar esta publicación programada? Se invalidará el comando anterior.',
  'calendar.duplicated': 'Publicación duplicada.',
  'calendar.rescheduled': 'Publicación reprogramada.',
  'calendar.cancelled': 'Publicación programada cancelada.',
  'calendar.rescheduleEyebrow': 'Nueva hora de publicación',
  'calendar.rescheduleTitle': 'Reprogramar publicación',
  'calendar.confirmReschedule': 'Confirmar nueva hora',
  'calendar.close': 'Cerrar',
}

const frEditorial: LocalEditorialCatalog = {
  ...enEditorial,
  'documentTitle.publish': 'Créer une publication — Postqron',
  'documentTitle.calendar': 'Calendrier éditorial — Postqron',
  'shell.nav.publish': 'Publier',
  'shell.nav.calendar': 'Calendrier',
  'shell.newPost': 'Nouvelle publication',
  'social.addChannel': 'Ajouter un canal',
  'social.errorPopupIsolation': 'La fenêtre d’autorisation n’a pas pu être isolée en toute sécurité. Aucune autorisation n’a été lancée.',
  'social.errorPopupClosed': 'Vous avez fermé la fenêtre d’autorisation avant la fin. Aucun canal n’a été connecté. Réessayez quand vous le souhaitez.',
  'social.resource.facebook_page': 'Page Facebook',
  'social.resource.facebook_group': 'Groupe Facebook',
  'social.resource.instagram_professional': 'Instagram Business / Creator',
  'social.resource.instagram_personal': 'Compte Instagram personnel',
  'social.resource.x_profile': 'Profil X',
  'social.resource.linkedin_profile': 'Profil LinkedIn',
  'social.resource.linkedin_page': 'Page LinkedIn',
  'social.resource.pinterest_board': 'Tableau Pinterest',
  'social.resource.tiktok_profile': 'Profil TikTok',
  'social.resource.google_business_profile_location': 'Établissement de la fiche d’entreprise',
  'social.resource.mastodon_account': 'Compte Mastodon',
  'social.resource.youtube_channel': 'Chaîne YouTube',
  'social.resource.threads_profile': 'Profil Threads',
  'social.resource.bluesky_account': 'Compte Bluesky',
  'social.accountType.group': 'Groupe',
  'social.accountType.personal': 'Personnel',
  'social.accountType.profile': 'Profil',
  'social.accountType.organization': 'Organisation',
  'social.accountType.board': 'Tableau',
  'social.accountType.location': 'Établissement',
  'social.accountType.channel': 'Chaîne',
  'social.catalogDescription': 'Le catalogue D2 complet reste visible même si un adaptateur est en configuration ou indisponible.',
  'social.catalogState.available': 'Disponible',
  'social.catalogState.configuring': 'En configuration',
  'social.catalogState.unavailable': 'Indisponible',
  'social.configuration.ready': 'Prêt à connecter.',
  'social.configuration.not_configured': 'Les identifiants du fournisseur ne sont pas configurés.',
  'social.configuration.review_required': 'La validation du fournisseur est en cours.',
  'social.configuration.audit_required': 'L’audit d’exécution doit être terminé.',
  'social.publishingMode': 'Mode de publication',
  'social.publishingMode.auto': 'Publication automatique',
  'social.publishingMode.notification': 'Publication par notification',
  'social.publishingMode.unknown': 'Non déclaré',
  'social.errorProviderReview': 'Ce fournisseur est encore en validation. Aucune autorisation n’a été lancée.',
  'social.errorProviderAudit': 'Le fournisseur est configuré mais son audit d’exécution est incomplet.',
  'composer.eyebrow': 'Publier',
  'composer.title': 'Créer une publication',
  'composer.editTitle': 'Modifier la publication programmée',
  'composer.description': 'Rédigez une fois, choisissez plusieurs destinations et adaptez le contenu avant publication.',
  'composer.emptyEyebrow': 'Commencez ici',
  'composer.emptyTitle': 'Connectez un canal avant de publier',
  'composer.emptyDescription': 'Ajoutez au moins un canal disponible, puis revenez créer et programmer votre contenu.',
  'composer.addChannel': 'Ajouter un canal social',
  'composer.contentEyebrow': 'Contenu',
  'composer.contentTitle': 'Contenu de la publication',
  'composer.textLabel': 'Texte',
  'composer.textPlaceholder': 'Que souhaitez-vous partager ?',
  'composer.linkLabel': 'Lien (facultatif)',
  'composer.mediaEyebrow': 'Médias',
  'composer.mediaTitle': 'Images et vidéo',
  'composer.mediaDescription': 'Les fichiers utilisent l’autorisation sécurisée F6 et sont inspectés avant programmation.',
  'composer.upload': 'Ajouter un média',
  'composer.uploading': 'Téléversement et contrôle…',
  'composer.mediaReady': 'Média téléversé et contrôlé.',
  'composer.removeMedia': 'Retirer',
  'composer.mediaStatus.pending': 'Contrôle',
  'composer.mediaStatus.ready': 'Prêt',
  'composer.mediaStatus.rejected': 'Refusé',
  'composer.destinationsEyebrow': 'Destinations',
  'composer.destinationsTitle': 'Choisir les canaux',
  'composer.destinationsDescription': 'Sélectionnez un ou plusieurs canaux. Formats et règles viennent du catalogue F6.',
  'composer.destinationRequired': 'Sélectionnez au moins une destination avant de publier.',
  'composer.destinationUnavailable': 'Aucune capacité F6 active n’est encore disponible pour ce canal.',
  'composer.formatLabel': 'Format',
  'composer.format.text': 'Texte',
  'composer.format.link': 'Lien',
  'composer.format.image': 'Image',
  'composer.format.carousel': 'Carrousel',
  'composer.format.video': 'Vidéo',
  'composer.format.short_video': 'Vidéo courte',
  'composer.format.thread': 'Fil',
  'composer.personalizationLabel': 'Texte propre au canal (facultatif)',
  'composer.personalizationPlaceholder': 'Laissez vide pour utiliser le texte principal.',
  'composer.providerFieldsLegend': 'Métadonnées du fournisseur',
  'composer.requiredField': '(obligatoire)',
  'composer.chooseFieldValue': 'Choisir une valeur',
  'composer.maxCharacters': '{count} caractères maximum.',
  'composer.actionsEyebrow': 'Actions',
  'composer.actionsTitle': 'Enregistrer ou publier',
  'composer.saveDraft': 'Enregistrer le brouillon',
  'composer.publishNow': 'Publier maintenant',
  'composer.publishing': 'Mise en publication…',
  'composer.schedule': 'Programmer',
  'composer.scheduling': 'Programmation…',
  'composer.confirmSchedule': 'Confirmer la programmation',
  'composer.dateTimeLabel': 'Date et heure locales',
  'composer.timezoneLabel': 'Fuseau IANA',
  'composer.offsetLabel': 'Décalage UTC en minutes (si ambigu)',
  'composer.offsetHelp': 'Nécessaire uniquement pendant l’heure répétée à la fin de l’heure d’été.',
  'composer.chooseOffset': 'Choisir l’occurrence',
  'composer.offsetRequired': 'Cette heure locale se produit deux fois. Choisissez le décalage UTC voulu.',
  'composer.localTimeNonexistent': 'Cette heure locale n’existe pas à cause du changement d’heure. Choisissez une autre heure.',
  'composer.threadForbidden': 'Une destination sélectionnée interdit les fils. Supprimez les éléments obsolètes avant de publier.',
  'composer.threadConstraintsImpossible': 'Les destinations sélectionnées ont des limites incompatibles : le minimum requis dépasse le maximum autorisé.',
  'composer.offsetInvalid': 'Saisissez un décalage UTC entre -1080 et 1080 minutes.',
  'composer.scheduleRequired': 'Saisissez une date, une heure et un fuseau IANA.',
  'composer.validationFailed': 'Certaines destinations ne sont pas encore valides. Consultez les indications des champs.',
  'composer.saved': 'Brouillon enregistré.',
  'composer.saveState.idle': 'Modifications en attente d’enregistrement',
  'composer.saveState.saving': 'Enregistrement…',
  'composer.saveState.saved': 'Toutes les modifications sont enregistrées',
  'composer.saveState.error': 'L’enregistrement automatique exige votre attention',
  'editorial.error.accessDenied': 'Vous n’avez pas accès à cette action dans l’espace.',
  'editorial.error.conflict': 'La publication a changé ailleurs. Rechargez et utilisez la dernière révision.',
  'editorial.error.dependency': 'Un service requis n’est pas prêt. Le brouillon reste enregistré ; réessayez plus tard.',
  'editorial.error.invalid': 'La demande n’est pas valide. Vérifiez les champs et les règles du fournisseur.',
  'editorial.error.offline': 'Postqron est inaccessible. Vérifiez la connexion ; vos modifications restent affichées.',
  'editorial.error.notFound': 'Ce brouillon ou cette publication programmée n’est plus disponible.',
  'editorial.error.unavailable': 'Le service éditorial est temporairement indisponible. Réessayez bientôt.',
  'calendar.eyebrow': 'Publication',
  'calendar.title': 'Calendrier',
  'calendar.description': 'Consultez le travail programmé par date, canal, état et fuseau explicite.',
  'calendar.controlsLabel': 'Commandes du calendrier',
  'calendar.viewCalendar': 'Vue calendrier',
  'calendar.viewList': 'Vue liste',
  'calendar.filterChannel': 'Canal',
  'calendar.allChannels': 'Tous les canaux',
  'calendar.filterStatus': 'État',
  'calendar.allStatuses': 'Tous les états',
  'calendar.timezone': 'Fuseau d’affichage',
  'calendar.previousMonth': 'Mois précédent',
  'calendar.nextMonth': 'Mois suivant',
  'calendar.emptyEyebrow': 'Aucune publication',
  'calendar.emptyTitle': 'Rien de programmé pour cette période',
  'calendar.emptyDescription': 'Créez une publication ou modifiez les filtres.',
  'calendar.untitled': 'Brouillon sans titre',
  'calendar.unknownChannel': 'Canal indisponible',
  'calendar.status.scheduled': 'Programmé',
  'calendar.status.publishing': 'Publication',
  'calendar.status.published': 'Publié',
  'calendar.status.failed': 'Échec',
  'calendar.status.cancelled': 'Annulé',
  'calendar.failureGeneric': 'La publication a échoué pour cette destination. F7 n’expose pas la cause du fournisseur ; vérifiez le canal.',
  'calendar.edit': 'Modifier',
  'calendar.duplicate': 'Dupliquer',
  'calendar.reschedule': 'Reprogrammer',
  'calendar.cancel': 'Annuler',
  'calendar.cancelConfirm': 'Annuler cette publication programmée ? La commande précédente sera invalidée.',
  'calendar.duplicated': 'Publication dupliquée.',
  'calendar.rescheduled': 'Publication reprogrammée.',
  'calendar.cancelled': 'Publication programmée annulée.',
  'calendar.rescheduleEyebrow': 'Nouvelle heure de publication',
  'calendar.rescheduleTitle': 'Reprogrammer la publication',
  'calendar.confirmReschedule': 'Confirmer la nouvelle heure',
  'calendar.close': 'Fermer',
}

const deEditorial: LocalEditorialCatalog = {
  ...enEditorial,
  'documentTitle.publish': 'Beitrag erstellen — Postqron',
  'documentTitle.calendar': 'Redaktionskalender — Postqron',
  'shell.nav.publish': 'Veröffentlichen',
  'shell.nav.calendar': 'Kalender',
  'shell.newPost': 'Neuer Beitrag',
  'social.addChannel': 'Kanal hinzufügen',
  'social.errorPopupIsolation': 'Das Autorisierungsfenster konnte nicht sicher isoliert werden. Es wurde keine Autorisierung gestartet.',
  'social.errorPopupClosed': 'Sie haben das Autorisierungsfenster vor dem Abschluss geschlossen. Es wurde kein Kanal verbunden. Versuchen Sie es erneut, wenn Sie bereit sind.',
  'social.resource.facebook_page': 'Facebook-Seite',
  'social.resource.facebook_group': 'Facebook-Gruppe',
  'social.resource.instagram_professional': 'Instagram Business / Creator',
  'social.resource.instagram_personal': 'Persönliches Instagram-Konto',
  'social.resource.x_profile': 'X-Profil',
  'social.resource.linkedin_profile': 'LinkedIn-Profil',
  'social.resource.linkedin_page': 'LinkedIn-Seite',
  'social.resource.pinterest_board': 'Pinterest-Pinnwand',
  'social.resource.tiktok_profile': 'TikTok-Profil',
  'social.resource.google_business_profile_location': 'Unternehmensprofil-Standort',
  'social.resource.mastodon_account': 'Mastodon-Konto',
  'social.resource.youtube_channel': 'YouTube-Kanal',
  'social.resource.threads_profile': 'Threads-Profil',
  'social.resource.bluesky_account': 'Bluesky-Konto',
  'social.accountType.group': 'Gruppe',
  'social.accountType.personal': 'Persönlich',
  'social.accountType.profile': 'Profil',
  'social.accountType.organization': 'Organisation',
  'social.accountType.board': 'Pinnwand',
  'social.accountType.location': 'Standort',
  'social.accountType.channel': 'Kanal',
  'social.catalogDescription': 'Der vollständige D2-Katalog bleibt sichtbar, auch wenn ein Adapter konfiguriert wird oder nicht verfügbar ist.',
  'social.catalogState.available': 'Verfügbar',
  'social.catalogState.configuring': 'In Konfiguration',
  'social.catalogState.unavailable': 'Nicht verfügbar',
  'social.configuration.ready': 'Bereit zum Verbinden.',
  'social.configuration.not_configured': 'Anbieter-Zugangsdaten sind nicht konfiguriert.',
  'social.configuration.review_required': 'Die Anbieterprüfung läuft noch.',
  'social.configuration.audit_required': 'Das Laufzeit-Audit muss abgeschlossen werden.',
  'social.publishingMode': 'Veröffentlichungsmodus',
  'social.publishingMode.auto': 'Automatische Veröffentlichung',
  'social.publishingMode.notification': 'Veröffentlichung per Benachrichtigung',
  'social.publishingMode.unknown': 'Nicht angegeben',
  'social.errorProviderReview': 'Dieser Anbieter wird noch geprüft. Es wurde keine Autorisierung gestartet.',
  'social.errorProviderAudit': 'Der Anbieter ist konfiguriert, aber sein Laufzeit-Audit ist unvollständig.',
  'composer.eyebrow': 'Veröffentlichen',
  'composer.title': 'Beitrag erstellen',
  'composer.editTitle': 'Geplanten Beitrag bearbeiten',
  'composer.description': 'Einmal schreiben, mehrere Ziele wählen und Inhalte vor der Veröffentlichung anpassen.',
  'composer.emptyEyebrow': 'Hier beginnen',
  'composer.emptyTitle': 'Verbinde vor dem Veröffentlichen einen Kanal',
  'composer.emptyDescription': 'Füge mindestens einen verfügbaren Social-Kanal hinzu und kehre dann hierher zurück.',
  'composer.addChannel': 'Social-Kanal hinzufügen',
  'composer.contentEyebrow': 'Inhalt',
  'composer.contentTitle': 'Beitragsinhalt',
  'composer.textLabel': 'Text',
  'composer.textPlaceholder': 'Was möchtest du teilen?',
  'composer.linkLabel': 'Link (optional)',
  'composer.mediaEyebrow': 'Medien',
  'composer.mediaTitle': 'Bilder und Video',
  'composer.mediaDescription': 'Dateien werden mit der sicheren F6-Autorisierung hochgeladen und vor der Planung geprüft.',
  'composer.upload': 'Medium hinzufügen',
  'composer.uploading': 'Upload und Prüfung…',
  'composer.mediaReady': 'Medium hochgeladen und geprüft.',
  'composer.removeMedia': 'Entfernen',
  'composer.mediaStatus.pending': 'Prüfung',
  'composer.mediaStatus.ready': 'Bereit',
  'composer.mediaStatus.rejected': 'Abgelehnt',
  'composer.destinationsEyebrow': 'Ziele',
  'composer.destinationsTitle': 'Kanäle auswählen',
  'composer.destinationsDescription': 'Wähle einen oder mehrere Kanäle. Formate und Regeln stammen aus dem F6-Katalog.',
  'composer.destinationRequired': 'Wähle vor der Veröffentlichung mindestens ein Ziel.',
  'composer.destinationUnavailable': 'Für diesen Kanal ist noch keine aktive F6-Fähigkeit verfügbar.',
  'composer.formatLabel': 'Format',
  'composer.format.text': 'Text',
  'composer.format.link': 'Link',
  'composer.format.image': 'Bild',
  'composer.format.carousel': 'Karussell',
  'composer.format.video': 'Video',
  'composer.format.short_video': 'Kurzvideo',
  'composer.format.thread': 'Thread',
  'composer.personalizationLabel': 'Kanalspezifischer Text (optional)',
  'composer.personalizationPlaceholder': 'Leer lassen, um den Haupttext zu verwenden.',
  'composer.providerFieldsLegend': 'Anbieter-Metadaten',
  'composer.requiredField': '(erforderlich)',
  'composer.chooseFieldValue': 'Wert auswählen',
  'composer.maxCharacters': 'Maximal {count} Zeichen.',
  'composer.actionsEyebrow': 'Aktionen',
  'composer.actionsTitle': 'Speichern oder veröffentlichen',
  'composer.saveDraft': 'Entwurf speichern',
  'composer.publishNow': 'Jetzt veröffentlichen',
  'composer.publishing': 'Veröffentlichung wird eingereiht…',
  'composer.schedule': 'Planen',
  'composer.scheduling': 'Planung…',
  'composer.confirmSchedule': 'Planung bestätigen',
  'composer.dateTimeLabel': 'Lokales Datum und Uhrzeit',
  'composer.timezoneLabel': 'IANA-Zeitzone',
  'composer.offsetLabel': 'UTC-Abweichung in Minuten (falls mehrdeutig)',
  'composer.offsetHelp': 'Nur während der wiederholten Stunde am Ende der Sommerzeit nötig.',
  'composer.chooseOffset': 'Vorkommen auswählen',
  'composer.offsetRequired': 'Diese Ortszeit tritt zweimal auf. Wähle den gewünschten UTC-Offset.',
  'composer.localTimeNonexistent': 'Diese Ortszeit existiert wegen der Zeitumstellung nicht. Wähle eine andere Uhrzeit.',
  'composer.threadForbidden': 'Ein ausgewähltes Ziel erlaubt keine Threads. Entferne veraltete Elemente vor der Veröffentlichung.',
  'composer.threadConstraintsImpossible': 'Die ausgewählten Ziele haben unvereinbare Thread-Limits: Das erforderliche Minimum liegt über dem erlaubten Maximum.',
  'composer.offsetInvalid': 'Gib eine UTC-Abweichung zwischen -1080 und 1080 Minuten ein.',
  'composer.scheduleRequired': 'Gib Datum, Uhrzeit und IANA-Zeitzone ein.',
  'composer.validationFailed': 'Einige Ziele sind noch ungültig. Beachte die Hinweise zu den Feldern.',
  'composer.saved': 'Entwurf gespeichert.',
  'composer.saveState.idle': 'Änderungen warten auf Autosave',
  'composer.saveState.saving': 'Speichern…',
  'composer.saveState.saved': 'Alle Änderungen gespeichert',
  'composer.saveState.error': 'Autosave benötigt Aufmerksamkeit',
  'editorial.error.accessDenied': 'Du hast keinen Zugriff auf diese Workspace-Aktion.',
  'editorial.error.conflict': 'Der Beitrag wurde anderswo geändert. Lade neu und nutze die neueste Revision.',
  'editorial.error.dependency': 'Ein benötigter Dienst ist nicht bereit. Der Entwurf bleibt gespeichert; versuche es später erneut.',
  'editorial.error.invalid': 'Die Anfrage ist ungültig. Prüfe Felder und Anbieterregeln.',
  'editorial.error.offline': 'Postqron ist nicht erreichbar. Prüfe die Verbindung; deine Änderungen bleiben sichtbar.',
  'editorial.error.notFound': 'Dieser Entwurf oder geplante Beitrag ist nicht mehr verfügbar.',
  'editorial.error.unavailable': 'Der Redaktionsdienst ist vorübergehend nicht verfügbar. Versuche es erneut.',
  'calendar.eyebrow': 'Veröffentlichung',
  'calendar.title': 'Kalender',
  'calendar.description': 'Prüfe geplante Arbeit nach Datum, Kanal, Status und ausdrücklicher Zeitzone.',
  'calendar.controlsLabel': 'Kalendersteuerung',
  'calendar.viewCalendar': 'Kalenderansicht',
  'calendar.viewList': 'Listenansicht',
  'calendar.filterChannel': 'Kanal',
  'calendar.allChannels': 'Alle Kanäle',
  'calendar.filterStatus': 'Status',
  'calendar.allStatuses': 'Alle Status',
  'calendar.timezone': 'Anzeigezeitzone',
  'calendar.previousMonth': 'Vorheriger Monat',
  'calendar.nextMonth': 'Nächster Monat',
  'calendar.emptyEyebrow': 'Keine Beiträge',
  'calendar.emptyTitle': 'Für diesen Zeitraum ist nichts geplant',
  'calendar.emptyDescription': 'Erstelle einen Beitrag oder ändere die Filter.',
  'calendar.untitled': 'Entwurf ohne Titel',
  'calendar.unknownChannel': 'Nicht verfügbarer Kanal',
  'calendar.status.scheduled': 'Geplant',
  'calendar.status.publishing': 'Wird veröffentlicht',
  'calendar.status.published': 'Veröffentlicht',
  'calendar.status.failed': 'Fehlgeschlagen',
  'calendar.status.cancelled': 'Abgebrochen',
  'calendar.failureGeneric': 'Die Veröffentlichung für dieses Ziel ist fehlgeschlagen. F7 liefert keine Anbieterursache; prüfe den Kanal.',
  'calendar.edit': 'Bearbeiten',
  'calendar.duplicate': 'Duplizieren',
  'calendar.reschedule': 'Neu planen',
  'calendar.cancel': 'Abbrechen',
  'calendar.cancelConfirm': 'Diesen geplanten Beitrag abbrechen? Der vorherige Befehl wird ungültig.',
  'calendar.duplicated': 'Beitrag dupliziert.',
  'calendar.rescheduled': 'Beitrag neu geplant.',
  'calendar.cancelled': 'Geplanter Beitrag abgebrochen.',
  'calendar.rescheduleEyebrow': 'Neue Veröffentlichungszeit',
  'calendar.rescheduleTitle': 'Beitrag neu planen',
  'calendar.confirmReschedule': 'Neue Zeit bestätigen',
  'calendar.close': 'Schließen',
}

export type EditorialMessageKey =
  | keyof typeof commonEditorial
  | keyof typeof enEditorial

export const EDITORIAL_CATALOGS = Object.freeze({
  de: { ...commonEditorial, ...deEditorial },
  en: { ...commonEditorial, ...enEditorial },
  es: { ...commonEditorial, ...esEditorial },
  fr: { ...commonEditorial, ...frEditorial },
  it: { ...commonEditorial, ...itEditorial },
}) satisfies Readonly<
  Record<
    'de' | 'en' | 'es' | 'fr' | 'it',
    Readonly<Record<EditorialMessageKey, string>>
  >
>
